import React, { useEffect, useRef, useState } from 'react';
import { Bell, BellOff, Camera, CheckCircle2, FileDown, Fingerprint, Loader2, QrCode, RefreshCw, ShieldCheck, Trash2, Wifi, WifiOff, X, Smartphone, ScanLine, Users, AlertTriangle } from 'lucide-react';
import { jsPDF } from 'jspdf';
import { getWebPushState, enableWebPush, disableWebPush } from '../lib/webPush';
import { listPhase1Queue, removePhase1QueueItem, type Phase1QueueItem, type Phase1Scope } from '../lib/phase1Offline';
import { flushPhase1Queue } from '../lib/phase1SyncEngine';
import { passkeyFeatureEnabled, passkeySupportedOnDevice, registerCurrentUserPasskey } from '../lib/passkey';
import { useOnlineStatus } from '../hooks/useOnlineStatus';
import Phase2FreeTools from './Phase2FreeTools';
import { getPhase5NativeCapabilities, phase5NativeAvailable, scanNativeCode, scanNativeDocument, verifyNativeDeviceOwner, type Phase5NativeCapabilities } from '../lib/phase5NativeSmart';
import { disableNativePush, enableNativePush, getNativePushState } from '../lib/nativePush';
import type { Phase5PresenceSnapshot } from '../lib/phase5Presence';
import { getPhase6SyncGuardianState } from '../lib/phase6SyncGuardian';
import { getPhase6AppShieldEnabled, setPhase6AppShieldEnabled } from './Phase6AppShield';
import Phase7SmartIntelligence from './Phase7SmartIntelligence';

interface Props { open:boolean; onClose:()=>void; scope:Phase1Scope; role:string; }

type ScanPage={id:string;url:string;name:string};

export default function Phase1SmartTools({open,onClose,scope,role}:Props){
  const online=useOnlineStatus();
  const[queueCount,setQueueCount]=useState(0);const[queueItems,setQueueItems]=useState<Phase1QueueItem[]>([]);const[syncing,setSyncing]=useState(false);const[msg,setMsg]=useState('');const[err,setErr]=useState('');
  const[push,setPush]=useState<any>(null);const[pushBusy,setPushBusy]=useState(false);
  const[nativeCap,setNativeCap]=useState<Phase5NativeCapabilities|null>(null);const[nativePush,setNativePush]=useState<any>(null);const[nativeBusy,setNativeBusy]=useState(false);const[nativeToken,setNativeToken]=useState('');const[presence,setPresence]=useState<Phase5PresenceSnapshot>({connected:0,ownConnected:false,status:'connecting'});
  const[guardian,setGuardian]=useState<any>(null);const[appShield,setAppShield]=useState(()=>getPhase6AppShieldEnabled(scope.userId));
  const[qr,setQr]=useState('');const[scanning,setScanning]=useState(false);const videoRef=useRef<HTMLVideoElement|null>(null);const scannerRef=useRef<any>(null);
  const[pages,setPages]=useState<ScanPage[]>([]);const pagesRef=useRef<ScanPage[]>([]);const[fileBusy,setFileBusy]=useState(false);
  const reloadQueue=async()=>{const items=await listPhase1Queue(scope);setQueueItems(items);setQueueCount(items.length)};
  const reloadPush=async()=>{try{setPush(await getWebPushState())}catch{setPush(null)}};
  const reloadNative=async()=>{if(!phase5NativeAvailable()){setNativeCap(null);setNativePush(null);setGuardian(null);return;}try{setNativeCap(await getPhase5NativeCapabilities())}catch{setNativeCap(null)}try{setNativePush(await getNativePushState())}catch{setNativePush(null)}try{setGuardian(await getPhase6SyncGuardianState())}catch{setGuardian(null)}};
  useEffect(()=>{if(!open)return;void reloadQueue();void reloadPush();void reloadNative();const h=()=>{void reloadQueue();void reloadNative()};const p=(event:any)=>setPresence(event?.detail||{connected:0,ownConnected:false,status:'unknown',editingByRecord:{}});window.addEventListener('edunixo_phase1_queue_changed',h);window.addEventListener('edunixo_phase6_collaboration',p);return()=>{window.removeEventListener('edunixo_phase1_queue_changed',h);window.removeEventListener('edunixo_phase6_collaboration',p)}},[open,scope.schoolId,scope.userId]);
  useEffect(()=>{pagesRef.current=pages},[pages]);
  useEffect(()=>()=>{try{scannerRef.current?.stop?.()}catch{};pagesRef.current.forEach(p=>URL.revokeObjectURL(p.url))},[]);
  if(!open)return null;
  const syncNow=async()=>{setSyncing(true);setErr('');try{const r=await flushPhase1Queue(scope);await reloadQueue();setMsg(r.failed?`${r.synced} synced; ${r.failed} item(s) need review.`:`${r.synced} offline item(s) synced. ${r.pending} pending.`)}catch(e:any){setErr(e?.message||'Sync failed.')}finally{setSyncing(false)}};
  const togglePush=async()=>{setPushBusy(true);setErr('');setMsg('');try{if(push?.subscribed){await disableWebPush();setMsg('Push notifications disabled on this device.')}else{await enableWebPush();setMsg('Free Web Push notifications enabled on this device.')}await reloadPush()}catch(e:any){setErr(e?.message||'Push setup failed.')}finally{setPushBusy(false)}};
  const toggleNativePush=async()=>{setNativeBusy(true);setErr('');setMsg('');try{if(nativeToken){await disableNativePush(nativeToken);setNativeToken('');setMsg('Native Android push registration disabled for this Classtago account.')}else{const r=await enableNativePush();setNativeToken(r.token);setMsg('Native Android FCM push registered for this device.')}await reloadNative()}catch(e:any){setErr(e?.message||'Native Android push setup failed.')}finally{setNativeBusy(false)}};
  const nativeCode=async()=>{setErr('');setQr('');try{const result=await scanNativeCode();setQr(result.rawValue||result.displayValue||'');setMsg('Native Google code scan completed on device.')}catch(e:any){if(!/cancel/i.test(String(e?.message||'')))setErr(e?.message||'Native code scanner failed.')}};
  const nativeDocument=async()=>{setErr('');setMsg('');setFileBusy(true);try{const result=await scanNativeDocument();setMsg(`ML Kit document scan complete · ${result.pageCount||0} page(s) · saved to ${result.savedTo||'device'} as ${result.fileName||'PDF'}.`)}catch(e:any){if(!/cancel/i.test(String(e?.message||'')))setErr(e?.message||'Native document scanner failed.')}finally{setFileBusy(false)}};
  const verifyDevice=async()=>{setErr('');setMsg('');try{const result=await verifyNativeDeviceOwner();if(result.verified)setMsg('Secure Android biometric/device credential verification succeeded.')}catch(e:any){setErr(e?.message||'Secure device verification failed.')}};
  const discardQueueItem=async(item:Phase1QueueItem)=>{if(!window.confirm('Remove this pending local offline action? Cloud data will not be changed.'))return;await removePhase1QueueItem(item.id);await reloadQueue();setMsg('Pending local offline action removed. Cloud data was not changed.');};
  const stopQr=()=>{try{scannerRef.current?.stop?.()}catch{};scannerRef.current=null;if(videoRef.current)videoRef.current.srcObject=null;setScanning(false)};
  const startQr=async()=>{setErr('');setQr('');
    const Detector=(window as any).BarcodeDetector;
    if(!Detector){setErr('QR scanning needs a Chromium/Android browser with BarcodeDetector support. Camera document scanning remains available.');return;}
    setScanning(true);
    try{
      const stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'}},audio:false});
      if(!videoRef.current)throw new Error('Camera preview is unavailable.');
      videoRef.current.srcObject=stream;await videoRef.current.play();
      const detector=new Detector({formats:['qr_code']});let raf=0;let stopped=false;
      const controller={stop:()=>{stopped=true;if(raf)cancelAnimationFrame(raf);stream.getTracks().forEach(t=>t.stop())}};scannerRef.current=controller;
      const scan=async()=>{if(stopped||!videoRef.current)return;try{const codes=await detector.detect(videoRef.current);const value=String(codes?.[0]?.rawValue||'');if(value){setQr(value);controller.stop();scannerRef.current=null;videoRef.current.srcObject=null;setScanning(false);return}}catch{}raf=requestAnimationFrame(scan)};
      raf=requestAnimationFrame(scan);
    }catch(e:any){stopQr();setErr(e?.message||'Camera QR scanner could not start.')}};
  const addPages=(files:FileList|null)=>{if(!files)return;const next=[...files].filter(f=>f.type.startsWith('image/')).map(f=>({id:crypto.randomUUID(),url:URL.createObjectURL(f),name:f.name}));setPages(p=>[...p,...next])};
  const exportPdf=async()=>{if(!pages.length)return;setFileBusy(true);setErr('');try{const pdf=new jsPDF({unit:'pt',format:'a4'});for(let i=0;i<pages.length;i++){if(i)pdf.addPage();const img=new Image();img.src=pages[i].url;await img.decode();const pageW=595.28,pageH=841.89,margin=24;const ratio=Math.min((pageW-margin*2)/img.naturalWidth,(pageH-margin*2)/img.naturalHeight);const w=img.naturalWidth*ratio,h=img.naturalHeight*ratio;pdf.addImage(img,'JPEG',(pageW-w)/2,(pageH-h)/2,w,h,undefined,'FAST')}pdf.save(`Classtago-Scanned-Document-${new Date().toISOString().slice(0,10)}.pdf`);setMsg('Scanned document PDF created on this device.')}catch(e:any){setErr(e?.message||'PDF could not be created.')}finally{setFileBusy(false)}};
  const registerPasskey=async()=>{setErr('');setMsg('');try{const data:any=await registerCurrentUserPasskey();setMsg(`Passkey registered${data?.friendly_name?` · ${data.friendly_name}`:''}.`)}catch(e:any){setErr(e?.message||'Passkey could not be registered.')}};
  return <div className="fixed inset-0 z-[10000] flex items-end justify-center bg-slate-950/60 p-2 backdrop-blur-sm sm:items-center sm:p-5" role="dialog" aria-modal="true"><div className="max-h-[92vh] w-full max-w-4xl overflow-y-auto rounded-[1.8rem] border border-slate-200 bg-slate-50 shadow-2xl"><header className="sticky top-0 z-10 flex items-center justify-between border-b border-slate-200 bg-white/95 p-4 backdrop-blur"><div><p className="text-[10px] font-black uppercase tracking-[.18em] text-cyan-700">Smart Technology Stack · Phase 1–7</p><h2 className="text-xl font-black text-slate-950">Offline, Native ML, Private Realtime & Predictive Automation</h2></div><button onClick={onClose} className="rounded-xl border border-slate-200 p-2"><X className="h-5 w-5"/></button></header><div className="grid gap-4 p-4 md:grid-cols-2">
    <section className="rounded-2xl border bg-white p-4"><div className="flex items-center gap-2"><div className={`rounded-xl p-2 ${online?'bg-emerald-50 text-emerald-700':'bg-amber-50 text-amber-700'}`}>{online?<Wifi className="h-5 w-5"/>:<WifiOff className="h-5 w-5"/>}</div><div><b>Secure Offline Queue</b><p className="text-xs text-slate-500">Attendance + Subject Mark List</p></div></div><div className="mt-4 rounded-xl bg-slate-50 p-3 text-sm"><b>{queueCount}</b> pending encrypted action(s)</div><button disabled={!online||syncing||queueCount===0} onClick={()=>void syncNow()} className="mt-3 inline-flex items-center gap-2 rounded-xl bg-slate-950 px-4 py-2 text-xs font-black text-white disabled:opacity-40">{syncing?<Loader2 className="h-4 w-4 animate-spin"/>:<RefreshCw className="h-4 w-4"/>}Sync Now</button>{queueItems.length>0&&<div className="mt-3 space-y-2">{queueItems.map(item=><div key={item.id} className={`rounded-xl border p-2.5 ${item.lastError?'border-amber-200 bg-amber-50':'border-slate-200 bg-white'}`}><div className="flex items-start justify-between gap-2"><div><div className="text-[10px] font-black uppercase text-slate-700">{item.kind==='attendance_save'?'Attendance':'Subject Mark Draft'}</div><div className="mt-1 text-[9px] text-slate-500">Captured {new Date(item.capturedAt).toLocaleString()} · attempts {item.attempts||0}</div>{item.lastError&&<div className="mt-1 text-[9px] font-bold text-amber-800"><AlertTriangle className="mr-1 inline h-3 w-3"/>{item.lastError}</div>}</div><button onClick={()=>void discardQueueItem(item)} className="rounded-lg border bg-white p-1.5 text-rose-600" title="Discard local pending action"><Trash2 className="h-3.5 w-3.5"/></button></div></div>)}</div>}</section>
    <section className="rounded-2xl border bg-white p-4"><div className="flex items-center gap-2"><div className="rounded-xl bg-violet-50 p-2 text-violet-700">{push?.subscribed?<Bell className="h-5 w-5"/>:<BellOff className="h-5 w-5"/>}</div><div><b>Free Push Notifications</b><p className="text-xs text-slate-500">Standard Web Push · no paid provider</p></div></div><p className="mt-3 text-xs text-slate-600">{push?.configured?'Server keys configured.':push?.supported?'One-time free VAPID key setup is pending on hosting.':'Push is not supported in this browser.'}</p><button disabled={pushBusy||!push?.supported} onClick={()=>void togglePush()} className="mt-3 inline-flex items-center gap-2 rounded-xl border border-slate-300 px-4 py-2 text-xs font-black disabled:opacity-40">{pushBusy?<Loader2 className="h-4 w-4 animate-spin"/>:<Bell className="h-4 w-4"/>}{push?.subscribed?'Disable on this device':'Enable notifications'}</button></section>
    <section className="rounded-2xl border bg-white p-4"><div className="flex items-center gap-2"><Users className="h-5 w-5 text-cyan-700"/><div><b>Private Realtime Collaboration</b><p className="text-xs text-slate-500">School-scoped Presence + concurrent-edit signals</p></div></div><div className="mt-4 rounded-xl bg-cyan-50 p-3"><div className="text-2xl font-black text-cyan-900">{presence.connected}</div><div className="text-[10px] font-bold uppercase text-cyan-700">Classtago client(s) connected to this school room</div></div><p className="mt-2 text-[9px] text-slate-500">Private Realtime channel access is restricted to active users of this school. No names, emails or student records are broadcast. Attendance/Mark List pages use low-sensitivity edit signals only; server conflict checks remain authoritative.</p></section>
    <section className="rounded-2xl border bg-white p-4"><div className="flex items-center gap-2"><Smartphone className="h-5 w-5 text-emerald-700"/><div><b>Native Android Push</b><p className="text-xs text-slate-500">Firebase Cloud Messaging · free transport</p></div></div><p className="mt-3 text-xs text-slate-600">{!nativePush?.native?'Android app only.':!nativePush?.firebaseConfigured?'Android Firebase config pending.':!nativePush?.serverConfigured?'Server FCM credentials pending.':'Native Android push pipeline ready.'}</p><button disabled={nativeBusy||!nativePush?.firebaseConfigured||!nativePush?.serverConfigured} onClick={()=>void toggleNativePush()} className="mt-3 inline-flex items-center gap-2 rounded-xl border border-slate-300 px-4 py-2 text-xs font-black disabled:opacity-40">{nativeBusy?<Loader2 className="h-4 w-4 animate-spin"/>:<Bell className="h-4 w-4"/>}{nativeToken?'Disable native push':'Enable native push'}</button></section>
    <section className="rounded-2xl border bg-white p-4 md:col-span-2"><div className="flex items-center gap-2"><QrCode className="h-5 w-5 text-cyan-700"/><div><b>QR Scanner</b><p className="text-xs text-slate-500">Camera-based on-device scan</p></div></div><div className="mt-3 overflow-hidden rounded-xl bg-black"><video ref={videoRef} className="aspect-video w-full object-cover" muted playsInline/></div><div className="mt-3 flex flex-wrap gap-2">{nativeCap?.codeScanner&&<button onClick={()=>void nativeCode()} className="inline-flex items-center gap-2 rounded-xl bg-cyan-700 px-4 py-2 text-xs font-black text-white"><ScanLine className="h-4 w-4"/>Native ML Kit Scan</button>}<button onClick={()=>void startQr()} disabled={scanning} className="rounded-xl bg-slate-950 px-4 py-2 text-xs font-black text-white disabled:opacity-40">Web Camera Fallback</button><button onClick={stopQr} disabled={!scanning} className="rounded-xl border px-4 py-2 text-xs font-black disabled:opacity-40">Stop</button></div>{qr&&<div className="mt-3 rounded-xl border border-emerald-200 bg-emerald-50 p-3 text-xs break-all"><b>Scanned:</b> {qr}</div>}</section>
    <section className="rounded-2xl border bg-white p-4 md:col-span-2"><div className="flex items-center gap-2"><Camera className="h-5 w-5 text-violet-700"/><div><b>Document Scanner</b><p className="text-xs text-slate-500">Capture multiple pages → local PDF</p></div></div>{nativeCap?.documentScanner&&<button onClick={()=>void nativeDocument()} disabled={fileBusy} className="mt-3 mr-2 inline-flex items-center gap-2 rounded-xl bg-violet-700 px-4 py-2 text-xs font-black text-white disabled:opacity-40">{fileBusy?<Loader2 className="h-4 w-4 animate-spin"/>:<ScanLine className="h-4 w-4"/>}ML Kit Auto Scan & PDF</button>}<label className="mt-3 inline-flex cursor-pointer items-center gap-2 rounded-xl border border-violet-300 bg-white px-4 py-2 text-xs font-black text-violet-800"><Camera className="h-4 w-4"/>Manual Camera Fallback<input hidden type="file" accept="image/*" capture="environment" multiple onChange={e=>{addPages(e.target.files);e.currentTarget.value=''}}/></label><div className="mt-3 grid grid-cols-2 gap-2 sm:grid-cols-4">{pages.map((p,i)=><div key={p.id} className="relative overflow-hidden rounded-xl border bg-slate-100"><img src={p.url} className="aspect-[3/4] w-full object-cover"/><span className="absolute left-2 top-2 rounded bg-black/70 px-2 py-1 text-[9px] font-black text-white">Page {i+1}</span><button onClick={()=>{URL.revokeObjectURL(p.url);setPages(x=>x.filter(y=>y.id!==p.id))}} className="absolute right-2 top-2 rounded bg-white p-1 text-rose-600"><Trash2 className="h-3.5 w-3.5"/></button></div>)}</div>{pages.length>0&&<button onClick={()=>void exportPdf()} disabled={fileBusy} className="mt-3 inline-flex items-center gap-2 rounded-xl bg-slate-950 px-4 py-2 text-xs font-black text-white">{fileBusy?<Loader2 className="h-4 w-4 animate-spin"/>:<FileDown className="h-4 w-4"/>}Create PDF</button>}</section>
    <section className="rounded-2xl border bg-white p-4 md:col-span-2"><div className="flex items-center gap-2"><Fingerprint className="h-5 w-5 text-emerald-700"/><div><b>Passkey / Biometric Login Foundation</b><p className="text-xs text-slate-500">WebAuthn · fingerprint/face/PIN on supported devices</p></div></div><div className="mt-3 rounded-xl border border-amber-200 bg-amber-50 p-3 text-xs text-amber-900">{passkeyFeatureEnabled?'Passkey enrollment is enabled for the configured production domain.':'Prepared but intentionally not enrolled yet. Enable only after the final custom domain/Relying Party ID is locked, otherwise existing passkeys can become invalid.'}</div><div className="mt-3 flex flex-wrap gap-2">{nativeCap?.deviceCredential&&<button onClick={()=>void verifyDevice()} className="inline-flex items-center gap-2 rounded-xl bg-emerald-700 px-4 py-2 text-xs font-black text-white"><ShieldCheck className="h-4 w-4"/>Verify device owner</button>}<button disabled={!passkeyFeatureEnabled||!passkeySupportedOnDevice()} onClick={()=>void registerPasskey()} className="inline-flex items-center gap-2 rounded-xl border px-4 py-2 text-xs font-black disabled:opacity-40"><Fingerprint className="h-4 w-4"/>Register passkey</button></div></section>
    <section className="rounded-2xl border bg-white p-4 md:col-span-2"><div className="flex items-center gap-2"><ShieldCheck className="h-5 w-5 text-indigo-700"/><div><b>Smart Resilience</b><p className="text-xs text-slate-500">Private collaboration · Sync Guardian · App Shield</p></div></div><div className="mt-3 grid gap-3 sm:grid-cols-2"><div className="rounded-xl bg-indigo-50 p-3"><div className="text-xs font-black text-indigo-900">Android Sync Guardian</div><p className="mt-1 text-[10px] leading-4 text-indigo-800">{guardian?.native?(guardian.enabled===false?'Disabled on this device':(guardian.workScheduled?`Reminder scheduled · ${guardian.pendingCount||0} pending action(s)`:`Active · ${guardian.pendingCount||0} pending action(s) tracked`)):'Android app only. Web auto-sync remains active while the page is open.'}</p></div><div className="rounded-xl bg-emerald-50 p-3"><div className="flex items-center justify-between gap-3"><div><div className="text-xs font-black text-emerald-900">Biometric App Shield</div><p className="mt-1 text-[10px] leading-4 text-emerald-800">Opt-in lock after 60 seconds away from the Android app.</p></div><button disabled={!nativeCap?.deviceCredential} onClick={()=>{const next=!appShield;setAppShield(next);setPhase6AppShieldEnabled(scope.userId,next)}} className="rounded-xl border border-emerald-300 bg-white px-3 py-2 text-[10px] font-black text-emerald-800 disabled:opacity-40">{appShield?'Disable':'Enable'}</button></div></div></div><p className="mt-3 text-[9px] text-slate-500">Private Realtime collaboration broadcasts no names, emails, student data or marks—only anonymous session presence and a scoped record-edit signal.</p></section>
    {String(role||'').toLowerCase()==='headmaster'&&<Phase7SmartIntelligence />}
    <Phase2FreeTools scope={scope} role={role} />
    {msg&&<div className="md:col-span-2 rounded-xl border border-emerald-200 bg-emerald-50 p-3 text-xs font-bold text-emerald-800"><CheckCircle2 className="mr-1 inline h-4 w-4"/>{msg}</div>}{err&&<div className="md:col-span-2 rounded-xl border border-rose-200 bg-rose-50 p-3 text-xs font-bold text-rose-800">{err}</div>}
  </div><footer className="border-t bg-white p-4 text-[10px] text-slate-500"><ShieldCheck className="mr-1 inline h-3.5 w-3.5"/>No mandatory paid provider. Native ML Kit, biometric verification, private Realtime collaboration, WorkManager Sync Guardian, encrypted offline sync and FCM transport are additive; existing cloud permissions remain authoritative. FCM/passkeys activate only after their final production configuration is supplied.</footer></div></div>
}
