import React,{useEffect,useMemo,useState} from 'react';
import {Download,FileSearch,HardDriveDownload,Loader2,RefreshCw,Save,ShieldCheck,Stethoscope,UsersRound} from 'lucide-react';
import type {Language,User} from '../types';
import {generateSystemExport,loadAuditLogs,loadSystemControl,runDuplicateDiagnostics,saveRolePermissions} from '../services/headmasterOperationsControlService';

type Props={lang:Language;user:User;activeFeatureId?:string|null;mode?:'system'|'audit'};type Tab='users'|'export'|'bulk'|'duplicates'|'diagnostics'|'audit'|'sensitive'|'permission'|'exceptions'|'evidence'|'retention';
const feature:Record<string,Tab>={'system-users-permissions':'users','system-backup-restore':'export','system-bulk-import-export':'bulk','system-duplicate-detection':'duplicates','system-diagnostics':'diagnostics','system-audit-trail':'audit','sensitive-action-audit':'sensitive','permission-change-audit':'permission','policy-exception-review':'exceptions','compliance-evidence-pack':'evidence','audit-retention-review':'retention'};
const roles=['headmaster','clerk','teacher','student'];const modules=['dashboard','admissions','attendance','fees','results','exams','timetable','library','certificates','communication','payroll','master_data','administration'];
export default function HeadmasterSystemAuditCloudWorkspace({activeFeatureId,mode='system'}:Props){
 const[data,setData]=useState<any>(null),[loading,setLoading]=useState(true),[busy,setBusy]=useState(''),[error,setError]=useState(''),[ok,setOk]=useState(''),[tab,setTab]=useState<Tab>(mode==='audit'?'sensitive':'users'),[diag,setDiag]=useState<any>(null),[perm,setPerm]=useState<any[]>([]);
 const load=async()=>{setLoading(true);setError('');try{const x=await loadSystemControl();setData(x);setPerm(buildPermissions(x.permissions||[]))}catch(e:any){setError(e?.message||'System Control could not be loaded.')}finally{setLoading(false)}};useEffect(()=>{void load()},[]);useEffect(()=>{if(activeFeatureId&&feature[activeFeatureId])setTab(feature[activeFeatureId]);else setTab(mode==='audit'?'sensitive':'users')},[activeFeatureId,mode]);
 const run=async(key:string,fn:()=>Promise<any>,msg='Action completed.')=>{setBusy(key);setError('');setOk('');try{const r=await fn();setDiag(r);setOk(msg);return r}catch(e:any){setError(e?.message||'Action failed.')}finally{setBusy('')}};
 const logs=useMemo(()=>data?.audit||[],[data]);const filtered=useMemo(()=>{if(tab==='permission')return logs.filter((x:any)=>/permission/i.test(`${x.action} ${x.summary}`));if(tab==='exceptions')return logs.filter((x:any)=>/(denied|reject|exception|failed|cancel)/i.test(`${x.action} ${x.summary}`));if(tab==='sensitive')return logs.filter((x:any)=>/(delete|password|publish|approve|paid|close|writeoff|permission|role|promotion|certificate|cancel)/i.test(`${x.action} ${x.summary}`));return logs},[logs,tab]);
 if(loading&&!data)return <Loader/>;return <div className="space-y-5 text-left"><Hero mode={mode} onRefresh={()=>void load()} loading={loading}/>{(error||ok)&&<Banner error={error} ok={ok}/>}<Nav mode={mode} tab={tab} setTab={setTab}/>
 {tab==='users'&&<section className="space-y-5"><Panel title="Cloud Staff Accounts"><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-xs [&_th]:bg-slate-50 [&_th]:p-3 [&_th]:text-left [&_th]:text-[10px] [&_th]:uppercase [&_th]:text-slate-400 [&_td]:border-t [&_td]:p-3"><thead><tr><th>Name</th><th>Role</th><th>Designation</th><th>Identity</th><th>Status</th></tr></thead><tbody>{(data?.staff||[]).map((s:any)=><tr key={s.id}><td><b>{s.name}</b><div className="text-[10px] text-slate-500">{s.email||s.username||'—'}</div></td><td>{s.role}</td><td>{s.designation||'—'}</td><td>{s.shalarthId||s.employeeCode||'—'}</td><td><Badge value={s.isActive?'active':'inactive'}/></td></tr>)}</tbody></table></div></Panel><Panel title="Role / Module Permissions"><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-xs [&_th]:bg-slate-50 [&_th]:p-3 [&_th]:text-left [&_th]:text-[10px] [&_th]:uppercase [&_th]:text-slate-400 [&_td]:border-t [&_td]:p-3"><thead><tr><th>Module</th>{roles.map(r=><th key={r}>{r}</th>)}</tr></thead><tbody>{modules.map(m=><tr key={m}><td className="font-black">{m.replaceAll('_',' ')}</td>{roles.map(r=>{const row=perm.find((p:any)=>p.roleName===r&&p.moduleKey===m);return <td key={r}><input type="checkbox" disabled={r==='headmaster'} checked={r==='headmaster'?true:Boolean(row?.allowed)} onChange={e=>setPerm(old=>old.map((p:any)=>p.roleName===r&&p.moduleKey===m?{...p,allowed:e.target.checked}:p))}/></td>})}</tr>)}</tbody></table></div><button disabled={!!busy} onClick={async()=>{await run('perm',()=>saveRolePermissions(perm),'Role permissions saved and audited.');await load()}} className="mt-4 inline-flex items-center justify-center gap-2 rounded-xl bg-slate-950 px-4 py-2.5 text-xs font-black text-white disabled:opacity-40"><Save className="h-4 w-4"/>Save Permissions</button></Panel></section>}
 {tab==='export'&&<Panel title="Controlled Cloud Export / Recovery"><p className="text-sm leading-6 text-slate-600">Browser restore is intentionally disabled. Generate a school-scoped portability/audit snapshot; production recovery remains a privileged database/platform operation.</p><button disabled={!!busy} onClick={async()=>{const x=await run('export',generateSystemExport,'School cloud export generated.');if(x)downloadJson(x,`edunixo-school-export-${new Date().toISOString().slice(0,10)}.json`)}} className="mt-4 inline-flex items-center justify-center gap-2 rounded-xl bg-slate-950 px-4 py-2.5 text-xs font-black text-white disabled:opacity-40"><HardDriveDownload className="h-4 w-4"/>Generate Cloud Export</button></Panel>}
 {tab==='bulk'&&<Panel title="Controlled Bulk Intake"><div className="grid gap-3 md:grid-cols-2"><Control title="Student Bulk Admission" text="Canonical owner: Clerk Admission Intake. Upload its approved Excel/CSV template there; final Student Master creation remains Headmaster-controlled."/><Control title="Academic Master Import" text="Canonical owner: Academic Setup. Class/Division/Subject masters remain in their owner module; System Admin does not maintain duplicate browser registries."/></div></Panel>}
 {tab==='duplicates'&&<Panel title="Read-only Duplicate Detection"><p className="text-sm text-slate-600">Detection never merges or deletes records. Exact-ID dependency audit is required before any repair.</p><button disabled={!!busy} onClick={()=>run('dupes',runDuplicateDiagnostics,'Duplicate diagnostic completed.')} className="mt-4 inline-flex items-center justify-center gap-2 rounded-xl bg-slate-950 px-4 py-2.5 text-xs font-black text-white disabled:opacity-40"><FileSearch className="h-4 w-4"/>Run Diagnostic</button>{diag?.candidates&&<div className="mt-5 space-y-3">{diag.candidates.map((c:any,i:number)=><div key={i} className="flex flex-col gap-3 rounded-xl border border-slate-200 p-4 sm:flex-row sm:items-center sm:justify-between"><div><b>{c.entityType} · {c.matchType}</b><div className="text-[10px] text-slate-500">{c.value}</div></div><span className="rounded-full bg-amber-100 px-3 py-1 text-[10px] font-black text-amber-700">{c.records?.length||0} records</span></div>)}{!diag.candidates.length&&<div className="p-8 text-center text-xs font-bold text-slate-400">No duplicate identifier sets found.</div>}</div>}</Panel>}
 {tab==='diagnostics'&&<Panel title="System Health"><div className="grid gap-3 md:grid-cols-2">{(data?.health||[]).map((h:any)=><div key={h.id} className="rounded-xl border p-4"><div className="flex items-center justify-between gap-3"><b className="text-xs">{h.name}</b><Badge value={h.status}/></div><p className="mt-2 text-xs leading-5 text-slate-600">{h.message}</p></div>)}</div><div className="mt-4 text-[10px] text-slate-400">Last diagnostic: {data?.healthGeneratedAt||'—'}</div></Panel>}
 {['audit','sensitive','permission','exceptions'].includes(tab)&&<Panel title={tab==='permission'?'Permission Change Audit':tab==='exceptions'?'Policy Exception Review':tab==='sensitive'?'Sensitive Action Audit':'Audit Trail Logs'}><AuditTable rows={filtered}/></Panel>}
 {tab==='evidence'&&<Panel title="Compliance Evidence Pack"><p className="text-sm leading-6 text-slate-600">Creates a current school-scoped export plus the latest audit trail view. It is evidence/export, not a restore file or a claim of statutory certification.</p><button disabled={!!busy} onClick={async()=>{setBusy('evidence');setError('');try{const [snapshot,audit]=await Promise.all([generateSystemExport(),loadAuditLogs()]);downloadJson({generatedAt:new Date().toISOString(),snapshot,audit},`edunixo-compliance-evidence-${new Date().toISOString().slice(0,10)}.json`);setOk('Compliance evidence pack generated.')}catch(e:any){setError(e?.message||'Evidence pack failed.')}finally{setBusy('')}}} className="mt-4 inline-flex items-center justify-center gap-2 rounded-xl bg-slate-950 px-4 py-2.5 text-xs font-black text-white disabled:opacity-40"><Download className="h-4 w-4"/>Generate Evidence Pack</button></Panel>}
 {tab==='retention'&&<Panel title="Audit Retention Review"><div className="rounded-2xl border bg-slate-50 p-5"><div className="text-xs font-black">Current server view</div><div className="mt-2 text-sm text-slate-700">{data?.retentionView||'Latest school-scoped audit events.'}</div><div className="mt-3 text-xs text-slate-500">Visible records: {logs.length}. Retention/deletion is not exposed to school users; audit history is append-only through operational workflows.</div></div></Panel>}
 </div>}
function buildPermissions(existing:any[]){const m=new Map(existing.map((p:any)=>[`${String(p.role_name||p.roleName)}:${String(p.module_key||p.moduleKey)}`,Boolean(p.allowed)]));return roles.flatMap(role=>modules.map(moduleKey=>({roleName:role,moduleKey,allowed:role==='headmaster'?true:Boolean(m.get(`${role}:${moduleKey}`))}))) }
function downloadJson(data:any,name:string){const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();URL.revokeObjectURL(url)}
function Hero({mode,onRefresh,loading}:{mode:string;onRefresh:()=>void;loading:boolean}){return <div className="rounded-3xl border border-slate-800 bg-slate-950 p-6 text-white"><div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><div className="flex items-center gap-2 text-xs font-black uppercase tracking-[.18em] text-cyan-200"><ShieldCheck className="h-4 w-4"/>{mode==='audit'?'Audit & Compliance':'System Administration'}</div><h1 className="mt-2 text-2xl font-black">{mode==='audit'?'Audit & Compliance Control':'System & Administration'}</h1><p className="mt-2 text-sm text-slate-300">Cloud accounts, permissions, diagnostics, export and immutable school-scoped audit evidence. No localStorage is an operational source here.</p></div><button onClick={onRefresh} className="inline-flex items-center gap-2 rounded-xl border border-white/15 bg-white/10 px-4 py-2 text-xs font-black"><RefreshCw className={`h-4 w-4 ${loading?'animate-spin':''}`}/>Refresh</button></div></div>}
function Nav({mode,tab,setTab}:{mode:string;tab:Tab;setTab:(t:Tab)=>void}){const xs=mode==='audit'?([['sensitive','Sensitive Actions'],['permission','Permission Changes'],['exceptions','Policy Exceptions'],['evidence','Evidence Pack'],['retention','Retention']] as [Tab,string][]):([['users','Users & Permissions'],['export','Backup / Export'],['bulk','Bulk Intake'],['duplicates','Duplicates'],['diagnostics','Diagnostics'],['audit','Audit Trail']] as [Tab,string][]);return <div className="flex gap-2 overflow-x-auto rounded-2xl border bg-white p-2">{xs.map(([id,label])=><button key={id} onClick={()=>setTab(id)} className={`shrink-0 rounded-xl px-4 py-2 text-xs font-black ${tab===id?'bg-slate-950 text-white':'text-slate-600 hover:bg-slate-100'}`}>{label}</button>)}</div>}
function AuditTable({rows}:{rows:any[]}){return <div className="overflow-x-auto"><table className="w-full min-w-[760px] text-xs [&_th]:bg-slate-50 [&_th]:p-3 [&_th]:text-left [&_th]:text-[10px] [&_th]:uppercase [&_th]:text-slate-400 [&_td]:border-t [&_td]:p-3"><thead><tr><th>Time</th><th>Actor</th><th>Action</th><th>Summary</th></tr></thead><tbody>{rows.slice(0,500).map((r:any)=><tr key={r.id}><td className="whitespace-nowrap">{r.created_at?new Date(r.created_at).toLocaleString('en-IN'):'—'}</td><td>{r.actor_name||'System'}</td><td className="font-mono text-[10px]">{r.action}</td><td>{r.summary||'—'}</td></tr>)}{!rows.length&&<tr><td colSpan={4} className="p-10 text-center font-bold text-slate-400">No matching audit events.</td></tr>}</tbody></table></div>}
function Panel({title,children}:{title:string;children:React.ReactNode}){return <div className="rounded-2xl border bg-white p-5 shadow-sm"><h2 className="mb-4 font-black">{title}</h2>{children}</div>}
function Control({title,text}:{title:string;text:string}){return <div className="rounded-xl border bg-slate-50 p-4"><b className="text-xs">{title}</b><p className="mt-2 text-xs leading-5 text-slate-600">{text}</p></div>}
function Badge({value}:{value:string}){const v=String(value||'').toLowerCase();const good=['active','ok'].includes(v);const warn=['warn'].includes(v);return <span className={`rounded-full px-2.5 py-1 text-[9px] font-black uppercase ${good?'bg-emerald-100 text-emerald-700':warn?'bg-amber-100 text-amber-700':'bg-slate-100 text-slate-600'}`}>{value}</span>}
function Banner({error,ok}:{error:string;ok:string}){return <div className={`rounded-2xl border p-4 text-sm font-bold ${error?'border-rose-200 bg-rose-50 text-rose-700':'border-emerald-200 bg-emerald-50 text-emerald-700'}`}>{error||ok}</div>}
function Loader(){return <div className="flex min-h-72 items-center justify-center rounded-3xl border bg-white"><Loader2 className="h-8 w-8 animate-spin"/></div>}
