import React,{useEffect,useMemo,useState} from 'react';
import { BookOpenCheck, CheckCircle2, Clock3, Loader2, RefreshCw, RotateCcw, ShieldCheck } from 'lucide-react';
import type { Language,User } from '../types';
import { loadHeadmasterResultWorkflow } from '../services/headmasterAcademicFinalizationService';

interface Props{lang:Language;user:User;activeFeatureId?:string|null}
export default function HeadmasterResultControlWorkspace({activeFeatureId}:Props){
 const [data,setData]=useState<any>(null);const[loading,setLoading]=useState(true);const[error,setError]=useState('');const[q,setQ]=useState('');
 const load=async()=>{setLoading(true);setError('');try{setData(await loadHeadmasterResultWorkflow())}catch(e:any){setError(e?.message||'Result Control could not be loaded.')}finally{setLoading(false)}};useEffect(()=>{void load()},[]);
 const needle=q.trim().toLowerCase();
 const rows=useMemo(()=>{if(!data)return[];const out:any[]=[];(data.subjectLists||[]).forEach((r:any)=>out.push({...r,kind:'Subject Mark List',name:r.subjectName,status:r.status,detail:`${r.className}${r.divisionName?` / ${r.divisionName}`:''} · ${String(r.term).replaceAll('_',' ')}`}));(data.resultBooks||[]).forEach((r:any)=>out.push({...r,kind:'Result Book',name:'Class Result Book',status:r.status,detail:`${r.className}${r.divisionName?` / ${r.divisionName}`:''} · ${String(r.term).replaceAll('_',' ')}`}));(data.progressBatches||[]).forEach((r:any)=>out.push({...r,kind:'Progress Card',name:'Progress Card Batch',status:r.status,detail:`${r.className}${r.divisionName?` / ${r.divisionName}`:''} · ${String(r.term).replaceAll('_',' ')}`}));return out.filter(r=>!needle||[r.kind,r.name,r.detail,r.teacherName,r.status].join(' ').toLowerCase().includes(needle));},[data,needle]);
 const featureFilter=(row:any)=>{switch(activeFeatureId){case'completed-result-records':return ['accepted','sent_to_progress_card','final'].includes(String(row.status));case'draft-result-records':return ['draft','building','prepared'].includes(String(row.status));case'pending-result-work':return ['submitted','complete','reviewed','prepared'].includes(String(row.status));case'returned-result-corrections':return String(row.status)==='returned';default:return true}};
 const visible=rows.filter(featureFilter); const s=data?.summary||{subjectLists:{},resultBooks:{},progressBatches:{}};
 return <div className="space-y-5 text-left"><div className="rounded-3xl border border-slate-800 bg-slate-950 p-6 text-white"><div className="flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between"><div><div className="flex items-center gap-2 text-xs font-black uppercase tracking-[.18em] text-violet-200"><ShieldCheck className="h-4 w-4"/> Headmaster Result Control</div><h1 className="mt-2 text-2xl font-black">Result Workflow Oversight</h1><p className="mt-2 max-w-3xl text-sm text-slate-300">Canonical Subject Mark Lists → Result Book → Progress Card chain. Final publication remains Headmaster-only.</p></div><button onClick={()=>void load()} className="inline-flex items-center gap-2 rounded-xl border border-white/15 bg-white/10 px-4 py-2 text-xs font-black"><RefreshCw className={`h-4 w-4 ${loading?'animate-spin':''}`}/>Refresh</button></div></div>
 <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Stat label="Submitted Mark Lists" value={s.subjectLists.submitted||0} icon={Clock3}/><Stat label="Accepted Mark Lists" value={s.subjectLists.accepted||0} icon={CheckCircle2}/><Stat label="Complete Result Books" value={(s.resultBooks.complete||0)+(s.resultBooks.sent_to_progress_card||0)} icon={BookOpenCheck}/><Stat label="Returned Corrections" value={s.subjectLists.returned||0} icon={RotateCcw}/></div>
 {error&&<div className="rounded-2xl border border-rose-200 bg-rose-50 p-4 text-sm font-bold text-rose-700">{error}</div>}
 <div className="rounded-2xl border border-slate-200 bg-white p-4"><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search class, subject, teacher or status…" className="w-full rounded-xl border border-slate-200 px-4 py-2.5 text-sm"/></div>
 {loading?<div className="flex min-h-52 items-center justify-center rounded-2xl border bg-white"><Loader2 className="h-7 w-7 animate-spin"/></div>:<div className="overflow-x-auto rounded-2xl border border-slate-200 bg-white"><table className="w-full min-w-[860px] text-left text-xs"><thead className="bg-slate-50 text-[10px] uppercase text-slate-400"><tr><th className="p-4">Stage</th><th className="p-4">Class / Term</th><th className="p-4">Subject / Record</th><th className="p-4">Teacher</th><th className="p-4">Status</th><th className="p-4">Updated</th></tr></thead><tbody className="divide-y">{visible.map((r:any)=><tr key={`${r.kind}:${r.id}`}><td className="p-4 font-black text-slate-900">{r.kind}</td><td className="p-4">{r.detail}</td><td className="p-4 font-bold">{r.name}</td><td className="p-4">{r.teacherName||'—'}</td><td className="p-4"><Badge value={r.status}/></td><td className="p-4 text-slate-500">{r.updatedAt?new Date(r.updatedAt).toLocaleString():'—'}</td></tr>)}{!visible.length&&<tr><td colSpan={6} className="p-10 text-center font-bold text-slate-400">No matching canonical result records.</td></tr>}</tbody></table></div>}
 {activeFeatureId==='result-workflow-progress'&&<div className="rounded-2xl border border-cyan-200 bg-cyan-50 p-5 text-xs leading-6 text-cyan-900"><b>Workflow rule:</b> Teacher saves and submits Subject Mark List → Class Teacher returns/accepts → Result Book becomes complete → Progress Card batch is prepared → Headmaster reviews and publishes/final-locks. Draft or incomplete data is never shown to Students.</div>}
 </div>
}
function Stat({label,value,icon:Icon}:{label:string;value:number;icon:any}){return <div className="rounded-2xl border border-slate-200 bg-white p-4"><div className="flex items-center justify-between"><div className="text-[10px] font-black uppercase text-slate-400">{label}</div><Icon className="h-4 w-4 text-slate-400"/></div><div className="mt-2 text-2xl font-black text-slate-950">{value}</div></div>}
function Badge({value}:{value:string}){const v=String(value||'').toLowerCase();const cls=['accepted','complete','sent_to_progress_card','final'].includes(v)?'bg-emerald-100 text-emerald-700':v==='returned'?'bg-rose-100 text-rose-700':'bg-amber-100 text-amber-700';return <span className={`rounded-full px-2.5 py-1 text-[9px] font-black uppercase ${cls}`}>{String(value||'—').replaceAll('_',' ')}</span>}
