import React,{useEffect,useMemo,useState} from 'react';
import { BadgeIndianRupee,BriefcaseBusiness,CheckCircle2,Clock3,FileBadge,Landmark,Loader2,Plus,RefreshCw,Save,ShieldCheck,Users,WalletCards } from 'lucide-react';
import type { Language,User } from '../types';
import { approvePayrollRun,createHrRecord,createPayrollRun,createSalaryHead,loadHeadmasterHrPayroll,markPayrollPaid,saveSalaryProfile,updateSalaryHead } from '../services/headmasterHrFinanceService';

type Props={lang:Language;user:User;activeFeatureId?:string|null};
type Tab='payroll'|'setup'|'service_book'|'increment'|'loan'|'certificate'|'reports';
const featureTab:Record<string,Tab>={'payroll-processing':'payroll','salary-structure-setup':'setup','digital-service-book':'service_book','increment-desk':'increment','loans-advances':'loan','payroll-certificates':'certificate','payroll-reports':'reports'};
const money=(n:any)=>`₹${Number(n||0).toLocaleString('en-IN',{maximumFractionDigits:2})}`;

export default function HeadmasterPayrollHRCloudWorkspace({activeFeatureId}:Props){
 const[data,setData]=useState<any>(null),[loading,setLoading]=useState(true),[busy,setBusy]=useState(''),[error,setError]=useState(''),[success,setSuccess]=useState('');
 const[tab,setTab]=useState<Tab>('payroll'),[month,setMonth]=useState(()=>new Date().toISOString().slice(0,7)),[selectedRun,setSelectedRun]=useState<string>('');
 const[headForm,setHeadForm]=useState({name:'',type:'income',defaultAmount:0}),[staffId,setStaffId]=useState(''),[profileValues,setProfileValues]=useState<Record<string,number>>({});
 const[recordForm,setRecordForm]=useState({teacherId:'',recordDate:new Date().toISOString().slice(0,10),title:'',amount:'',notes:''});
 const load=async()=>{setLoading(true);setError('');try{const x=await loadHeadmasterHrPayroll();setData(x);if(!staffId&&x.staff?.[0])setStaffId(x.staff[0].id);if(!recordForm.teacherId&&x.staff?.[0])setRecordForm(v=>({...v,teacherId:x.staff[0].id}));}catch(e:any){setError(e?.message||'HR/Payroll could not be loaded.')}finally{setLoading(false)}};
 useEffect(()=>{void load()},[]);useEffect(()=>{if(activeFeatureId&&featureTab[activeFeatureId])setTab(featureTab[activeFeatureId])},[activeFeatureId]);
 const activeStaff=(data?.staff||[]).filter((s:any)=>s.isActive),profiles=new Map((data?.profiles||[]).map((p:any)=>[p.teacherId,p]));
 useEffect(()=>{if(!data||!staffId)return;const p:any=profiles.get(staffId);const next:Record<string,number>={};(data.heads||[]).filter((h:any)=>h.isActive).forEach((h:any)=>next[h.id]=Number(p?.headValues?.[h.id]??h.defaultAmount??0));setProfileValues(next)},[staffId,data]);
 const run=async(action:string,fn:()=>Promise<any>)=>{setBusy(action);setError('');setSuccess('');try{const r=await fn();setSuccess(r?.message||'Saved successfully.');await load()}catch(e:any){setError(e?.message||'Action failed.')}finally{setBusy('')}};
 const addHead=()=>run('head',()=>createSalaryHead(headForm));const saveProfile=()=>staffId&&run(`profile:${staffId}`,()=>saveSalaryProfile(staffId,{headValues:profileValues,effectiveFrom:new Date().toISOString().slice(0,10)}));
 const createRun=()=>run('run',()=>createPayrollRun({monthKey:month}));
 const recordType:Record<Tab,string>={payroll:'remark',setup:'remark',service_book:'service_book',increment:'increment',loan:'loan',certificate:'certificate',reports:'remark'};
 const addRecord=()=>run('record',()=>createHrRecord({teacherId:recordForm.teacherId,recordType:recordType[tab],recordDate:recordForm.recordDate,title:recordForm.title,amount:recordForm.amount===''?null:Number(recordForm.amount),payload:{notes:recordForm.notes}}));
 const filteredRecords=(data?.hrRecords||[]).filter((r:any)=>r.recordType===recordType[tab]);
 const selected=(data?.runs||[]).find((r:any)=>r.id===selectedRun);
 if(loading&&!data)return <LoaderPage/>;
 return <div className="space-y-5 text-left">
  <Hero onRefresh={()=>void load()} loading={loading}/>
  <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5"><Stat label="Active Staff" value={activeStaff.length} icon={Users}/><Stat label="Pending Leave" value={data?.leaveSummary?.pending||0} icon={Clock3}/><Stat label="Payroll Runs" value={data?.runs?.length||0} icon={WalletCards}/><Stat label="Approved/Paid" value={(data?.runs||[]).filter((r:any)=>['approved','paid'].includes(r.status)).length} icon={CheckCircle2}/><Stat label="Latest Net Payroll" value={data?.runs?.[0]?money(data.runs[0].netTotal):'—'} icon={BadgeIndianRupee}/></div>
  {(error||success)&&<div className={`rounded-2xl border p-4 text-sm font-bold ${error?'border-rose-200 bg-rose-50 text-rose-700':'border-emerald-200 bg-emerald-50 text-emerald-700'}`}>{error||success}</div>}
  <Nav tab={tab} setTab={setTab}/>
  {tab==='payroll'&&<section className="space-y-4"><Panel title="Generate Monthly Payroll"><div className="flex flex-col gap-3 sm:flex-row"><input type="month" value={month} onChange={e=>setMonth(e.target.value)} className="rounded-xl border px-4 py-2.5 text-sm"/><button disabled={!!busy} onClick={createRun} className="rounded-xl bg-slate-950 px-5 py-2.5 text-xs font-black text-white">Generate Draft</button></div><p className="mt-3 text-xs text-slate-500">Active Staff Master + saved salary profiles are snapshotted into a permanent monthly payroll run. Approved months are locked.</p></Panel><RunTable runs={data?.runs||[]} busy={busy} setSelectedRun={setSelectedRun} act={(id,a)=>run(`${a}:${id}`,()=>a==='approve'?approvePayrollRun(id):markPayrollPaid(id))}/>{selected&&<RunDetail run={selected} onClose={()=>setSelectedRun('')}/>}</section>}
  {tab==='setup'&&<section className="grid gap-5 xl:grid-cols-[0.8fr_1.2fr]"><Panel title="Salary Heads"><div className="grid gap-2 sm:grid-cols-3"><input value={headForm.name} onChange={e=>setHeadForm({...headForm,name:e.target.value})} placeholder="Head name" className="rounded-xl border px-3 py-2 text-xs"/><select value={headForm.type} onChange={e=>setHeadForm({...headForm,type:e.target.value})} className="rounded-xl border px-3 py-2 text-xs"><option value="income">Income</option><option value="deduction">Deduction</option></select><div className="flex gap-2"><input type="number" min="0" value={headForm.defaultAmount} onChange={e=>setHeadForm({...headForm,defaultAmount:Number(e.target.value)})} className="min-w-0 flex-1 rounded-xl border px-3 py-2 text-xs"/><button onClick={addHead} className="rounded-xl bg-slate-950 px-3 text-white"><Plus className="h-4 w-4"/></button></div></div><div className="mt-4 divide-y rounded-xl border">{(data?.heads||[]).map((h:any)=><div key={h.id} className="flex items-center justify-between gap-3 p-3"><div><div className="text-xs font-black">{h.name}</div><div className="text-[10px] text-slate-500">{h.type} · default {money(h.defaultAmount)} {h.isSystem?'· system':''}</div></div><button onClick={()=>run(`toggle:${h.id}`,()=>updateSalaryHead(h.id,{isActive:!h.isActive}))} className={`rounded-lg px-2.5 py-1 text-[9px] font-black ${h.isActive?'bg-emerald-50 text-emerald-700':'bg-slate-100 text-slate-500'}`}>{h.isActive?'ACTIVE':'INACTIVE'}</button></div>)}</div></Panel><Panel title="Staff Salary Structure"><select value={staffId} onChange={e=>setStaffId(e.target.value)} className="w-full rounded-xl border px-3 py-2 text-sm"><option value="">Select staff</option>{activeStaff.map((s:any)=><option key={s.id} value={s.id}>{s.name} · {s.designation||'Staff'}</option>)}</select><div className="mt-4 grid gap-3 sm:grid-cols-2">{(data?.heads||[]).filter((h:any)=>h.isActive).map((h:any)=><label key={h.id} className="rounded-xl border bg-slate-50 p-3 text-xs"><span className="font-bold text-slate-700">{h.name}</span><input type="number" min="0" value={profileValues[h.id]??0} onChange={e=>setProfileValues(v=>({...v,[h.id]:Number(e.target.value)}))} className="mt-2 w-full rounded-lg border bg-white px-3 py-2"/></label>)}</div><button disabled={!staffId||!!busy} onClick={saveProfile} className="mt-4 inline-flex items-center gap-2 rounded-xl bg-indigo-600 px-4 py-2.5 text-xs font-black text-white"><Save className="h-4 w-4"/>Save Salary Structure</button></Panel></section>}
  {['service_book','increment','loan','certificate'].includes(tab)&&<section className="grid gap-5 xl:grid-cols-[0.8fr_1.2fr]"><Panel title={tabLabel(tab)}><div className="grid gap-3"><select value={recordForm.teacherId} onChange={e=>setRecordForm({...recordForm,teacherId:e.target.value})} className="rounded-xl border px-3 py-2 text-sm">{activeStaff.map((s:any)=><option key={s.id} value={s.id}>{s.name} · {s.designation||'Staff'}</option>)}</select><input type="date" value={recordForm.recordDate} onChange={e=>setRecordForm({...recordForm,recordDate:e.target.value})} className="rounded-xl border px-3 py-2 text-sm"/><input value={recordForm.title} onChange={e=>setRecordForm({...recordForm,title:e.target.value})} placeholder={recordPlaceholder(tab)} className="rounded-xl border px-3 py-2 text-sm"/>{['increment','loan'].includes(tab)&&<input type="number" min="0" value={recordForm.amount} onChange={e=>setRecordForm({...recordForm,amount:e.target.value})} placeholder="Amount" className="rounded-xl border px-3 py-2 text-sm"/>}<textarea value={recordForm.notes} onChange={e=>setRecordForm({...recordForm,notes:e.target.value})} placeholder="Notes / order / purpose" className="min-h-24 rounded-xl border px-3 py-2 text-sm"/><button disabled={!recordForm.teacherId||!recordForm.title||!!busy} onClick={addRecord} className="rounded-xl bg-slate-950 px-4 py-2.5 text-xs font-black text-white">Save Permanent HR Record</button></div></Panel><Panel title="Permanent Register"><div className="divide-y rounded-xl border">{filteredRecords.map((r:any)=><div key={r.id} className="p-4"><div className="flex justify-between gap-3"><div><div className="text-xs font-black text-slate-900">{r.title}</div><div className="mt-1 text-[10px] text-slate-500">{staffName(data,r.teacherId)} · {r.recordDate}</div></div>{r.amount!=null&&<div className="text-xs font-black">{money(r.amount)}</div>}</div>{r.payload?.notes&&<p className="mt-2 text-xs text-slate-600">{r.payload.notes}</p>}</div>)}{!filteredRecords.length&&<div className="p-8 text-center text-xs font-bold text-slate-400">No cloud records yet.</div>}</div></Panel></section>}
  {tab==='reports'&&<section className="grid gap-5 xl:grid-cols-2"><Panel title="Payroll Summary"><div className="divide-y">{(data?.runs||[]).map((r:any)=><div key={r.id} className="grid grid-cols-4 gap-2 py-3 text-xs"><b>{r.monthKey}</b><span>{r.status}</span><span>{r.staffCount} staff</span><b className="text-right">{money(r.netTotal)}</b></div>)}</div></Panel><Panel title="HR Readiness"><div className="space-y-3 text-xs"><Line label="Canonical Staff Master" value={`${activeStaff.length} active`}/><Line label="Leave workflow" value={`${data?.leaveSummary?.pending||0} pending`}/><Line label="Salary profiles configured" value={`${data?.profiles?.length||0}/${activeStaff.length}`}/><Line label="Service/Increment/Loan records" value={String(data?.hrRecords?.length||0)}/></div></Panel></section>}
 </div>
}
function Hero({onRefresh,loading}:{onRefresh:()=>void;loading:boolean}){return <div className="rounded-3xl border border-slate-800 bg-slate-950 p-6 text-white"><div className="flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between"><div><div className="flex items-center gap-2 text-xs font-black uppercase tracking-[.18em] text-cyan-200"><ShieldCheck className="h-4 w-4"/>Cloud HR & Payroll</div><h1 className="mt-2 text-2xl font-black">Staff HR, Payroll & Service Records</h1><p className="mt-2 max-w-3xl text-sm text-slate-300">Staff Master and Leave stay in their existing canonical owners. Salary structure, payroll runs, service book, increments, loans and certificates are permanent cloud records.</p></div><button onClick={onRefresh} className="inline-flex items-center gap-2 rounded-xl border border-white/15 bg-white/10 px-4 py-2 text-xs font-black"><RefreshCw className={`h-4 w-4 ${loading?'animate-spin':''}`}/>Refresh</button></div></div>}
function Nav({tab,setTab}:{tab:Tab;setTab:(v:Tab)=>void}){const xs:[Tab,string][]=[['payroll','Payroll'],['setup','Salary Setup'],['service_book','Service Book'],['increment','Increments'],['loan','Loans'],['certificate','Certificates'],['reports','Reports']];return <div className="flex gap-2 overflow-x-auto rounded-2xl border bg-white p-2">{xs.map(([id,label])=><button key={id} onClick={()=>setTab(id)} className={`shrink-0 rounded-xl px-4 py-2 text-xs font-black ${tab===id?'bg-slate-950 text-white':'text-slate-600 hover:bg-slate-100'}`}>{label}</button>)}</div>}
function Panel({title,children}:{title:string;children:React.ReactNode}){return <div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="mb-4 font-black text-slate-950">{title}</h2>{children}</div>}
function Stat({label,value,icon:Icon}:{label:string;value:any;icon:any}){return <div className="rounded-2xl border bg-white p-4"><div className="flex justify-between"><span className="text-[10px] font-black uppercase text-slate-400">{label}</span><Icon className="h-4 w-4 text-slate-400"/></div><div className="mt-2 text-xl font-black text-slate-950">{value}</div></div>}
function RunTable({runs,busy,setSelectedRun,act}:{runs:any[];busy:string;setSelectedRun:(id:string)=>void;act:(id:string,a:'approve'|'paid')=>void}){return <div className="overflow-x-auto rounded-2xl border bg-white"><table className="w-full min-w-[850px] text-xs"><thead className="bg-slate-50 text-left text-[10px] uppercase text-slate-400"><tr><th className="p-4">Month</th><th className="p-4">Staff</th><th className="p-4">Gross</th><th className="p-4">Deductions</th><th className="p-4">Net</th><th className="p-4">Status</th><th className="p-4">Action</th></tr></thead><tbody className="divide-y">{runs.map(r=><tr key={r.id}><td className="p-4 font-black">{r.monthKey}</td><td className="p-4">{r.staffCount}</td><td className="p-4">{money(r.grossTotal)}</td><td className="p-4">{money(r.deductionTotal)}</td><td className="p-4 font-black">{money(r.netTotal)}</td><td className="p-4"><Badge value={r.status}/></td><td className="p-4"><div className="flex gap-2"><button onClick={()=>setSelectedRun(r.id)} className="rounded-lg border px-3 py-1.5 text-[10px] font-black">View</button>{r.status==='draft'&&<button disabled={!!busy} onClick={()=>act(r.id,'approve')} className="rounded-lg bg-indigo-600 px-3 py-1.5 text-[10px] font-black text-white">Approve</button>}{r.status==='approved'&&<button disabled={!!busy} onClick={()=>act(r.id,'paid')} className="rounded-lg bg-emerald-600 px-3 py-1.5 text-[10px] font-black text-white">Mark Paid</button>}</div></td></tr>)}{!runs.length&&<tr><td colSpan={7} className="p-10 text-center font-bold text-slate-400">No payroll generated yet.</td></tr>}</tbody></table></div>}
function RunDetail({run,onClose}:{run:any;onClose:()=>void}){return <Panel title={`Payroll Detail · ${run.monthKey}`}><div className="mb-3 flex justify-end"><button onClick={onClose} className="text-xs font-black text-slate-500">Close</button></div><div className="overflow-x-auto"><table className="w-full min-w-[700px] text-xs"><thead className="bg-slate-50 text-left text-[10px] uppercase text-slate-400"><tr><th className="p-3">Staff</th><th className="p-3">Designation</th><th className="p-3">Gross</th><th className="p-3">Deduction</th><th className="p-3">Net</th></tr></thead><tbody className="divide-y">{run.items.map((i:any)=><tr key={i.id}><td className="p-3 font-black">{i.employeeName}</td><td className="p-3">{i.designation||'—'}</td><td className="p-3">{money(i.grossIncome)}</td><td className="p-3">{money(i.totalDeductions)}</td><td className="p-3 font-black">{money(i.netPay)}</td></tr>)}</tbody></table></div></Panel>}
function Badge({value}:{value:string}){const v=String(value||'').toLowerCase();return <span className={`rounded-full px-2.5 py-1 text-[9px] font-black uppercase ${v==='paid'||v==='approved'?'bg-emerald-100 text-emerald-700':v==='draft'?'bg-amber-100 text-amber-700':'bg-slate-100 text-slate-600'}`}>{value}</span>}
function LoaderPage(){return <div className="flex min-h-72 items-center justify-center rounded-3xl border bg-white"><Loader2 className="h-8 w-8 animate-spin"/></div>}
function staffName(data:any,id:string){return data?.staff?.find((s:any)=>s.id===id)?.name||'Staff'}
function tabLabel(tab:Tab){return tab==='service_book'?'Digital Service Book':tab==='increment'?'Increment Register':tab==='loan'?'Loans & Advances':'Payroll Certificates'}
function recordPlaceholder(tab:Tab){return tab==='service_book'?'Service order / posting / qualification entry':tab==='increment'?'Increment order':tab==='loan'?'Loan / advance sanction':'Salary / experience certificate record'}
function Line({label,value}:{label:string;value:string}){return <div className="flex items-center justify-between gap-4 rounded-xl bg-slate-50 p-3"><span className="font-bold text-slate-600">{label}</span><b className="text-slate-950">{value}</b></div>}
