import React, { useEffect, useMemo, useState } from 'react';
import { Activity, AlertTriangle, BellRing, BrainCircuit, CheckCircle2, Clock3, Gauge, Loader2, RefreshCw, ShieldCheck, Users } from 'lucide-react';
import { supabase } from '../lib/supabase';

async function headers(extra:Record<string,string>={}){
  const {data,error}=await supabase.auth.getSession();
  if(error||!data.session?.access_token)throw new Error('Your EDUNIXO session expired. Sign in again.');
  return {Authorization:`Bearer ${data.session.access_token}`,...extra};
}
async function api(path:string,init:RequestInit={}){
  const response=await fetch(path,{...init,headers:{...(await headers(init.body?{'Content-Type':'application/json'}:{})),...(init.headers||{})},cache:'no-store'});
  const payload=await response.json().catch(()=>({}));
  if(!response.ok)throw new Error(payload.error||'Smart Intelligence request failed.');
  return payload;
}

const RULES:any={
  attendance_risk:{title:'Attendance Risk Watch',detail:'30-day absence pattern → explainable student risk score',icon:Activity},
  result_readiness:{title:'Result Readiness Watch',detail:'Current assignments → mark-list readiness, missing scopes & corrections',icon:CheckCircle2},
  teacher_workload:{title:'Teacher Workload Watch',detail:'Assigned weekly periods → workload pressure signal',icon:Gauge},
};

export default function Phase7SmartIntelligence(){
  const[data,setData]=useState<any>(null);const[busy,setBusy]=useState(false);const[action,setAction]=useState('');const[error,setError]=useState('');const[msg,setMsg]=useState('');
  const load=async()=>{setBusy(true);setError('');try{setData(await api('/api/headmaster/smart-intelligence'));}catch(e:any){setError(e?.message||'Smart Intelligence could not load.')}finally{setBusy(false)}};
  useEffect(()=>{void load()},[]);
  const intel=data?.intelligence; const rules=data?.rules||[];
  const byKey=useMemo(()=>new Map(rules.map((r:any)=>[r.rule_key,r])),[rules]);
  const updateRule=async(key:string,enabled:boolean)=>{setAction(key);setError('');setMsg('');try{const current:any=byKey.get(key);await api(`/api/headmaster/smart-automation/rules/${key}`,{method:'PUT',body:JSON.stringify({enabled,cadenceMinutes:current?.cadence_minutes})});setMsg(`${RULES[key]?.title||key} ${enabled?'enabled':'disabled'}.`);await load();}catch(e:any){setError(e?.message||'Rule update failed.')}finally{setAction('')}};
  const preview=async(key:string,notify=false)=>{setAction(`${key}:${notify?'notify':'preview'}`);setError('');setMsg('');try{const result=await api(`/api/headmaster/smart-automation/rules/${key}/${notify?'notify':'preview'}`,{method:'POST'});const count=result?.result?.findings?.length||0;setMsg(notify?`${count} finding(s) evaluated; Headmaster alert created only when findings exist.`:`Preview complete · ${count} current finding(s). No notification was sent.`);await load();}catch(e:any){setError(e?.message||'Rule preview failed.')}finally{setAction('')}};
  return <section className="rounded-2xl border border-indigo-200 bg-white p-4 md:col-span-2">
    <div className="flex flex-wrap items-start justify-between gap-3"><div className="flex items-center gap-2"><div className="rounded-xl bg-indigo-50 p-2 text-indigo-700"><BrainCircuit className="h-5 w-5"/></div><div><b>Smart Automation & Predictive Intelligence</b><p className="text-xs text-slate-500">Explainable rules · proactive alerts · no paid AI dependency</p></div></div><button disabled={busy} onClick={()=>void load()} className="inline-flex items-center gap-2 rounded-xl border px-3 py-2 text-[10px] font-black disabled:opacity-40"><RefreshCw className={`h-3.5 w-3.5 ${busy?'animate-spin':''}`}/>Refresh intelligence</button></div>
    {busy&&!data?<div className="mt-4 flex items-center gap-2 text-xs text-slate-500"><Loader2 className="h-4 w-4 animate-spin"/>Calculating current school signals…</div>:intel&&<>
      <div className="mt-4 grid gap-3 sm:grid-cols-4"><div className="rounded-xl bg-rose-50 p-3"><div className="text-2xl font-black text-rose-900">{intel.attendance?.highRiskCount||0}</div><div className="text-[9px] font-black uppercase text-rose-700">High attendance risk</div></div><div className="rounded-xl bg-emerald-50 p-3"><div className="text-2xl font-black text-emerald-900">{intel.results?.readinessPercent??100}%</div><div className="text-[9px] font-black uppercase text-emerald-700">Result readiness</div></div><div className="rounded-xl bg-amber-50 p-3"><div className="text-2xl font-black text-amber-900">{intel.workload?.highPressureCount||0}</div><div className="text-[9px] font-black uppercase text-amber-700">High workload pressure</div></div><div className="rounded-xl bg-slate-100 p-3"><div className="text-2xl font-black text-slate-900">{intel.anomalies?.length||0}</div><div className="text-[9px] font-black uppercase text-slate-600">Operational anomalies</div></div></div>
      <div className="mt-4 grid gap-3 lg:grid-cols-3">{Object.entries(RULES).map(([key,meta]:any)=>{const rule:any=byKey.get(key);const Icon=meta.icon;return <div key={key} className="rounded-xl border border-slate-200 p-3"><div className="flex items-start justify-between gap-3"><div className="flex gap-2"><Icon className="mt-0.5 h-4 w-4 text-indigo-700"/><div><div className="text-xs font-black text-slate-900">{meta.title}</div><div className="mt-1 text-[9px] leading-4 text-slate-500">{meta.detail}</div></div></div><button disabled={!!action} onClick={()=>void updateRule(key,!rule?.enabled)} className={`rounded-full px-2.5 py-1 text-[9px] font-black ${rule?.enabled?'bg-emerald-100 text-emerald-800':'bg-slate-100 text-slate-600'}`}>{rule?.enabled?'ON':'OFF'}</button></div><div className="mt-3 flex flex-wrap gap-2"><button disabled={!!action} onClick={()=>void preview(key,false)} className="rounded-lg border px-2.5 py-1.5 text-[9px] font-black">Preview</button><button disabled={!!action} onClick={()=>void preview(key,true)} className="inline-flex items-center gap-1 rounded-lg border border-indigo-200 bg-indigo-50 px-2.5 py-1.5 text-[9px] font-black text-indigo-800"><BellRing className="h-3 w-3"/>Alert now</button></div><div className="mt-2 flex items-center gap-1 text-[8px] text-slate-400"><Clock3 className="h-3 w-3"/>Auto cadence {Math.round(Number(rule?.cadence_minutes||1440)/60)}h · default OFF</div></div>})}</div>
      {intel.anomalies?.length>0&&<div className="mt-4 rounded-xl border border-amber-200 bg-amber-50 p-3"><div className="flex items-center gap-2 text-xs font-black text-amber-900"><AlertTriangle className="h-4 w-4"/>Current explainable anomalies</div><div className="mt-2 grid gap-1">{intel.anomalies.slice(0,6).map((a:any,i:number)=><div key={`${a.kind}-${i}`} className="text-[10px] text-amber-900">• {a.label}</div>)}</div></div>}
      {(data?.runs||[]).length>0&&<div className="mt-4 rounded-xl border border-slate-200 p-3"><div className="text-[10px] font-black text-slate-800">Automation audit · recent runs</div><div className="mt-2 grid gap-1">{data.runs.slice(0,5).map((run:any)=><div key={run.id} className="flex flex-wrap items-center justify-between gap-2 rounded-lg bg-slate-50 px-2.5 py-2 text-[9px] text-slate-600"><span>{String(run.trigger_kind||'run').replaceAll('_',' ')} · {new Date(run.started_at).toLocaleString()}</span><span className="font-black text-slate-800">{run.status} · {run.findings_count||0} finding(s) · {run.notifications_created||0} alert(s)</span></div>)}</div></div>}
      <div className="mt-4 grid gap-3 sm:grid-cols-2"><div className="rounded-xl bg-slate-50 p-3"><div className="flex items-center gap-1 text-[10px] font-black text-slate-800"><Users className="h-3.5 w-3.5"/>Top attendance-risk signals</div>{(intel.attendance?.riskStudents||[]).slice(0,4).length?<div className="mt-2 space-y-1">{intel.attendance.riskStudents.slice(0,4).map((x:any)=><div key={x.studentId} className="flex justify-between text-[9px]"><span>{x.studentName} · {x.absentDays}/{x.markedDays} absent</span><b>{x.riskScore}/100</b></div>)}</div>:<p className="mt-2 text-[9px] text-slate-500">Not enough marked attendance data yet. Minimum 5 marked days are required before a risk score appears.</p>}</div><div className="rounded-xl bg-slate-50 p-3"><div className="flex items-center gap-1 text-[10px] font-black text-slate-800"><Gauge className="h-3.5 w-3.5"/>Highest teacher workload signals</div>{(intel.workload?.teachers||[]).slice(0,4).length?<div className="mt-2 space-y-1">{intel.workload.teachers.slice(0,4).map((x:any)=><div key={x.teacherId} className="flex justify-between text-[9px]"><span>{x.teacherName} · {x.weeklyPeriods} periods/week</span><b>{x.pressureScore}/100</b></div>)}</div>:<p className="mt-2 text-[9px] text-slate-500">No active teacher workload assignments are available.</p>}</div></div>
    </>}
    {msg&&<div className="mt-3 rounded-xl border border-emerald-200 bg-emerald-50 p-2.5 text-[10px] font-bold text-emerald-800"><CheckCircle2 className="mr-1 inline h-3.5 w-3.5"/>{msg}</div>}{error&&<div className="mt-3 rounded-xl border border-rose-200 bg-rose-50 p-2.5 text-[10px] font-bold text-rose-800">{error}</div>}
    <p className="mt-3 text-[9px] leading-4 text-slate-500"><ShieldCheck className="mr-1 inline h-3 w-3"/>Scores are deterministic and explainable. Attendance risk needs at least 5 marked days; Result Readiness does not create missing-result alerts until a result cycle has actually started. Automation rules are opt-in and can only create Headmaster notifications—they cannot publish results, change marks, alter attendance, or modify Student/Staff records.</p>
  </section>;
}
