/* ============================================================
   50 PREMIUM Progress Card Designs
   Each design is fully premium with:
   - Elegant typography
   - Gold foil accents
   - Ornate borders / corner ornaments
   - Medal / badge elements
   - Ribbon banners
   - Decorative dividers
   ============================================================ */

export type HeaderStyle = 'gradient' | 'solid' | 'minimal' | 'ribbon' | 'ornate';
export type BorderStyle = 'gold_foil' | 'double_gold' | 'navy_silver' | 'ornate' | 'elegant_thin' | 'none';
export type Decoration = 'circles' | 'triangles' | 'ribbons' | 'stars' | 'waves' | 'flourish' | 'none';
export type LayoutStyle = 'classic' | 'modern' | 'compact' | 'spacious' | 'royal';
export type FontTitle = 'Playfair Display' | 'Cormorant Garamond' | 'Cinzel' | 'Great Vibes' | 'Merriweather';
export type FontBody = 'Inter' | 'Lato' | 'Poppins' | 'Roboto' | 'Open Sans';

export interface ProgressCardDesign {
  id: string;
  name: string;
  tier: 'premium' | 'royal' | 'elite';

  // Colors
  primaryColor: string;
  secondaryColor: string;
  accentColor: string;
  goldColor: string;
  backgroundColor: string;
  textColor: string;

  // Premium visual elements
  headerStyle: HeaderStyle;
  borderStyle: BorderStyle;
  decoration: Decoration;
  layout: LayoutStyle;
  fontTitle: FontTitle;
  fontBody: FontBody;

  // Premium toggles
  hasCornerOrnaments: boolean;
  hasMedalBadge: boolean;
  hasGoldFoil: boolean;
  hasRibbonBanner: boolean;
  hasElegantDivider: boolean;
  hasWatermark: boolean;
  hasEmbossedTitle: boolean;
  hasSparkleAccent: boolean;
}

export const DESIGNS: ProgressCardDesign[] = [
  // ═══════════ ROYAL NAVY FAMILY (10) ═══════════
  { id: 'd01', name: 'Royal Navy Gold', tier: 'royal', primaryColor: '#06163f', secondaryColor: '#0b3d86', accentColor: '#eab308', goldColor: '#fbbf24', backgroundColor: '#f8fbff', textColor: '#0f172a', headerStyle: 'ornate', borderStyle: 'double_gold', decoration: 'flourish', layout: 'royal', fontTitle: 'Playfair Display', fontBody: 'Merriweather', hasCornerOrnaments: true, hasMedalBadge: true, hasGoldFoil: true, hasRibbonBanner: true, hasElegantDivider: true, hasWatermark: false, hasEmbossedTitle: true, hasSparkleAccent: true },
  { id: 'd02', name: 'Imperial Navy', tier: 'royal', primaryColor: '#0a1e3f', secondaryColor: '#1e3a8a', accentColor: '#fcd34d', goldColor: '#fbbf24', backgroundColor: '#fefce8', textColor: '#0f172a', headerStyle: 'ornate', borderStyle: 'gold_foil', decoration: 'stars', layout: 'royal', fontTitle: 'Cinzel', fontBody: 'Lato', hasCornerOrnaments: true, hasMedalBadge: true, hasGoldFoil: true, hasRibbonBanner: true, hasElegantDivider: true, hasWatermark: true, hasEmbossedTitle: true, hasSparkleAccent: false },
  { id: 'd03', name: 'Navy Heritage', tier: 'premium', primaryColor: '#0f172a', secondaryColor: '#1e40af', accentColor: '#facc15', goldColor: '#eab308', backgroundColor: '#f1f5f9', textColor: '#0f172a', headerStyle: 'gradient', borderStyle: 'double_gold', decoration: 'circles', layout: 'classic', fontTitle: 'Merriweather', fontBody: 'Inter', hasCornerOrnaments: true, hasMedalBadge: true, hasGoldFoil: true, hasRibbonBanner: false, hasElegantDivider: true, hasWatermark: false, hasEmbossedTitle: false, hasSparkleAccent: false },
  { id: 'd04', name: 'Deep Sapphire', tier: 'premium', primaryColor: '#020617', secondaryColor: '#0c4a6e', accentColor: '#38bdf8', goldColor: '#fbbf24', backgroundColor: '#f0f9ff', textColor: '#082f49', headerStyle: 'gradient', borderStyle: 'navy_silver', decoration: 'waves', layout: 'modern', fontTitle: 'Cormorant Garamond', fontBody: 'Poppins', hasCornerOrnaments: true, hasMedalBadge: false, hasGoldFoil: false, hasRibbonBanner: true, hasElegantDivider: true, hasWatermark: false, hasEmbossedTitle: true, hasSparkleAccent: true },
  { id: 'd05', name: 'Ocean Sovereign', tier: 'royal', primaryColor: '#075985', secondaryColor: '#0891b2', accentColor: '#facc15', goldColor: '#fbbf24', backgroundColor: '#f0fdfa', textColor: '#083344', headerStyle: 'ornate', borderStyle: 'gold_foil', decoration: 'flourish', layout: 'royal', fontTitle: 'Playfair Display', fontBody: 'Merriweather', hasCornerOrnaments: true, hasMedalBadge: true, hasGoldFoil: true, hasRibbonBanner: true, hasElegantDivider: true, hasWatermark: false, hasEmbossedTitle: true, hasSparkleAccent: true },
  { id: 'd06', name: 'Blue Monarch', tier: 'premium', primaryColor: '#1e3a8a', secondaryColor: '#3b82f6', accentColor: '#fbbf24', goldColor: '#eab308', backgroundColor: '#eff6ff', textColor: '#1e3a8a', headerStyle: 'ribbon', borderStyle: 'gold_foil', decoration: 'ribbons', layout: 'classic', fontTitle: 'Merriweather', fontBody: 'Poppins', hasCornerOrnaments: false, hasMedalBadge: true, hasGoldFoil: true, hasRibbonBanner: true, hasElegantDivider: true, hasWatermark: false, hasEmbossedTitle: false, hasSparkleAccent: false },
  { id: 'd07', name: 'Sapphire Wave', tier: 'premium', primaryColor: '#0284c7', secondaryColor: '#0ea5e9', accentColor: '#fef08a', goldColor: '#fbbf24', backgroundColor: '#f0f9ff', textColor: '#0c4a6e', headerStyle: 'gradient', borderStyle: 'elegant_thin', decoration: 'waves', layout: 'modern', fontTitle: 'Cormorant Garamond', fontBody: 'Poppins', hasCornerOrnaments: true, hasMedalBadge: false, hasGoldFoil: false, hasRibbonBanner: false, hasElegantDivider: true, hasWatermark: false, hasEmbossedTitle: false, hasSparkleAccent: true },
  { id: 'd08', name: 'Platinum Navy', tier: 'elite', primaryColor: '#0a1e3f', secondaryColor: '#1e40af', accentColor: '#fde047', goldColor: '#fbbf24', backgroundColor: '#fefce8', textColor: '#0f172a', headerStyle: 'ornate', borderStyle: 'double_gold', decoration: 'stars', layout: 'royal', fontTitle: 'Cinzel', fontBody: 'Lato', hasCornerOrnaments: true, hasMedalBadge: true, hasGoldFoil: true, hasRibbonBanner: true, hasElegantDivider: true, hasWatermark: true, hasEmbossedTitle: true, hasSparkleAccent: true },
  { id: 'd09', name: 'Stellar Blue', tier: 'premium', primaryColor: '#1e293b', secondaryColor: '#334155', accentColor: '#94a3b8', goldColor: '#fbbf24', backgroundColor: '#ffffff', textColor: '#0f172a', headerStyle: 'minimal', borderStyle: 'elegant_thin', decoration: 'none', layout: 'compact', fontTitle: 'Inter', fontBody: 'Inter', hasCornerOrnaments: false, hasMedalBadge: false, hasGoldFoil: false, hasRibbonBanner: false, hasElegantDivider: true, hasWatermark: false, hasEmbossedTitle: false, hasSparkleAccent: false },
  { id: 'd10', name: 'Cosmic Indigo', tier: 'premium', primaryColor: '#312e81', secondaryColor: '#4338ca', accentColor: '#a5b4fc', goldColor: '#fbbf24', backgroundColor: '#eef2ff', textColor: '#1e1b4b', headerStyle: 'gradient', borderStyle: 'navy_silver', decoration: 'stars', layout: 'modern', fontTitle: 'Cormorant Garamond', fontBody: 'Poppins', hasCornerOrnaments: true, hasMedalBadge: true, hasGoldFoil: false, hasRibbonBanner: true, hasElegantDivider: true, hasWatermark: false, hasEmbossedTitle: true, hasSparkleAccent: true },

  // ═══════════ ROYAL GOLD FAMILY (10) ═══════════
  { id: 'd11', name: 'Golden Sovereign', tier: 'royal', primaryColor: '#4c1d0e', secondaryColor: '#7c2d12', accentColor: '#fbbf24', goldColor: '#fde047', backgroundColor: '#fffbeb', textColor: '#431407', headerStyle: 'ornate', borderStyle: 'double_gold', decoration: 'flourish', layout: 'royal', fontTitle: 'Playfair Display', fontBody: 'Merriweather', hasCornerOrnaments: true, hasMedalBadge: true, hasGoldFoil: true, hasRibbonBanner: true, hasElegantDivider: true, hasWatermark: false, hasEmbossedTitle: true, hasSparkleAccent: true },
  { id: 'd12', name: 'Maroon Dynasty', tier: 'royal', primaryColor: '#7f1d1d', secondaryColor: '#991b1b', accentColor: '#fcd34d', goldColor: '#fbbf24', backgroundColor: '#fef2f2', textColor: '#450a0a', headerStyle: 'ornate', borderStyle: 'gold_foil', decoration: 'ribbons', layout: 'royal', fontTitle: 'Cinzel', fontBody: 'Lora', hasCornerOrnaments: true, hasMedalBadge: true, hasGoldFoil: true, hasRibbonBanner: true, hasElegantDivider: true, hasWatermark: true, hasEmbossedTitle: true, hasSparkleAccent: false },
  { id: 'd13', name: 'Amber Luxury', tier: 'premium', primaryColor: '#b45309', secondaryColor: '#d97706', accentColor: '#fde68a', goldColor: '#fbbf24', backgroundColor: '#fffbeb', textColor: '#451a03', headerStyle: 'gradient', borderStyle: 'double_gold', decoration: 'circles', layout: 'classic', fontTitle: 'Cormorant Garamond', fontBody: 'Poppins', hasCornerOrnaments: true, hasMedalBadge: true, hasGoldFoil: true, hasRibbonBanner: false, hasElegantDivider: true, hasWatermark: false, hasEmbossedTitle: true, hasSparkleAccent: true },
  { id: 'd14', name: 'Bronze Emperor', tier: 'elite', primaryColor: '#451a03', secondaryColor: '#78350f', accentColor: '#f59e0b', goldColor: '#fbbf24', backgroundColor: '#fef3c7', textColor: '#451a03', headerStyle: 'ornate', borderStyle: 'double_gold', decoration: 'stars', layout: 'royal', fontTitle: 'Cinzel', fontBody: 'Lora', hasCornerOrnaments: true, hasMedalBadge: true, hasGoldFoil: true, hasRibbonBanner: true, hasElegantDivider: true, hasWatermark: true, hasEmbossedTitle: true, hasSparkleAccent: true },
  { id: 'd15', name: 'Imperial Gold', tier: 'royal', primaryColor: '#78350f', secondaryColor: '#a16207', accentColor: '#fef08a', goldColor: '#fde047', backgroundColor: '#fefce8', textColor: '#422006', headerStyle: 'ornate', borderStyle: 'gold_foil', decoration: 'flourish', layout: 'royal', fontTitle: 'Playfair Display', fontBody: 'Merriweather', hasCornerOrnaments: true, hasMedalBadge: true, hasGoldFoil: true, hasRibbonBanner: true, hasElegantDivider: true, hasWatermark: false, hasEmbossedTitle: true, hasSparkleAccent: true },
  { id: 'd16', name: 'Sunburst Gold', tier: 'premium', primaryColor: '#ca8a04', secondaryColor: '#facc15', accentColor: '#fb923c', goldColor: '#fbbf24', backgroundColor: '#fefce8', textColor: '#422006', headerStyle: 'gradient', borderStyle: 'double_gold', decoration: 'stars', layout: 'classic', fontTitle: 'Cormorant Garamond', fontBody: 'Poppins', hasCornerOrnaments: true, hasMedalBadge: true, hasGoldFoil: true, hasRibbonBanner: false, hasElegantDivider: true, hasWatermark: false, hasEmbossedTitle: false, hasSparkleAccent: true },
  { id: 'd17', name: 'Antique Bronze', tier: 'premium', primaryColor: '#713f12', secondaryColor: '#a16207', accentColor: '#eab308', goldColor: '#fbbf24', backgroundColor: '#fef9c3', textColor: '#422006', headerStyle: 'ribbon', borderStyle: 'ornate', decoration: 'flourish', layout: 'classic', fontTitle: 'Merriweather', fontBody: 'Lora', hasCornerOrnaments: true, hasMedalBadge: true, hasGoldFoil: true, hasRibbonBanner: true, hasElegantDivider: true, hasWatermark: false, hasEmbossedTitle: false, hasSparkleAccent: false },
  { id: 'd18', name: 'Honey Premium', tier: 'premium', primaryColor: '#a16207', secondaryColor: '#ca8a04', accentColor: '#fef3c7', goldColor: '#fbbf24', backgroundColor: '#fffbeb', textColor: '#422006', headerStyle: 'gradient', borderStyle: 'gold_foil', decoration: 'circles', layout: 'modern', fontTitle: 'Cormorant Garamond', fontBody: 'Poppins', hasCornerOrnaments: true, hasMedalBadge: true, hasGoldFoil: true, hasRibbonBanner: false, hasElegantDivider: true, hasWatermark: false, hasEmbossedTitle: false, hasSparkleAccent: true },
  { id: 'd19', name: 'Vintage Sepia', tier: 'premium', primaryColor: '#57534e', secondaryColor: '#78716c', accentColor: '#eab308', goldColor: '#fbbf24', backgroundColor: '#fafaf9', textColor: '#1c1917', headerStyle: 'minimal', borderStyle: 'ornate', decoration: 'none', layout: 'classic', fontTitle: 'Playfair Display', fontBody: 'Lora', hasCornerOrnaments: true, hasMedalBadge: false, hasGoldFoil: false, hasRibbonBanner: false, hasElegantDivider: true, hasWatermark: false, hasEmbossedTitle: true, hasSparkleAccent: false },
  { id: 'd20', name: 'Gold Rush', tier: 'elite', primaryColor: '#854d0e', secondaryColor: '#ca8a04', accentColor: '#fef08a', goldColor: '#fde047', backgroundColor: '#fefce8', textColor: '#422006', headerStyle: 'ornate', borderStyle: 'double_gold', decoration: 'stars', layout: 'royal', fontTitle: 'Cinzel', fontBody: 'Lora', hasCornerOrnaments: true, hasMedalBadge: true, hasGoldFoil: true, hasRibbonBanner: true, hasElegantDivider: true, hasWatermark: true, hasEmbossedTitle: true, hasSparkleAccent: true },

  // ═══════════ EMERALD / GREEN FAMILY (10) ═══════════
  { id: 'd21', name: 'Emerald Crown', tier: 'royal', primaryColor: '#064e3b', secondaryColor: '#047857', accentColor: '#fbbf24', goldColor: '#fde047', backgroundColor: '#ecfdf5', textColor: '#064e3b', headerStyle: 'ornate', borderStyle: 'double_gold', decoration: 'flourish', layout: 'royal', fontTitle: 'Playfair Display', fontBody: 'Merriweather', hasCornerOrnaments: true, hasMedalBadge: true, hasGoldFoil: true, hasRibbonBanner: true, hasElegantDivider: true, hasWatermark: false, hasEmbossedTitle: true, hasSparkleAccent: true },
  { id: 'd22', name: 'Forest Majesty', tier: 'royal', primaryColor: '#14532d', secondaryColor: '#166534', accentColor: '#facc15', goldColor: '#fbbf24', backgroundColor: '#f0fdf4', textColor: '#14532d', headerStyle: 'ornate', borderStyle: 'gold_foil', decoration: 'stars', layout: 'royal', fontTitle: 'Cinzel', fontBody: 'Lora', hasCornerOrnaments: true, hasMedalBadge: true, hasGoldFoil: true, hasRibbonBanner: true, hasElegantDivider: true, hasWatermark: true, hasEmbossedTitle: true, hasSparkleAccent: false },
  { id: 'd23', name: 'Mint Sovereign', tier: 'premium', primaryColor: '#059669', secondaryColor: '#10b981', accentColor: '#a7f3d0', goldColor: '#fbbf24', backgroundColor: '#ecfdf5', textColor: '#064e3b', headerStyle: 'gradient', borderStyle: 'double_gold', decoration: 'waves', layout: 'modern', fontTitle: 'Cormorant Garamond', fontBody: 'Poppins', hasCornerOrnaments: true, hasMedalBadge: false, hasGoldFoil: false, hasRibbonBanner: true, hasElegantDivider: true, hasWatermark: false, hasEmbossedTitle: false, hasSparkleAccent: true },
  { id: 'd24', name: 'Olive Heritage', tier: 'premium', primaryColor: '#365314', secondaryColor: '#4d7c0f', accentColor: '#fde047', goldColor: '#fbbf24', backgroundColor: '#f7fee7', textColor: '#1a2e05', headerStyle: 'ribbon', borderStyle: 'ornate', decoration: 'flourish', layout: 'classic', fontTitle: 'Merriweather', fontBody: 'Lora', hasCornerOrnaments: true, hasMedalBadge: true, hasGoldFoil: true, hasRibbonBanner: true, hasElegantDivider: true, hasWatermark: false, hasEmbossedTitle: false, hasSparkleAccent: false },
  { id: 'd25', name: 'Teal Royalty', tier: 'royal', primaryColor: '#0f766e', secondaryColor: '#14b8a6', accentColor: '#5eead4', goldColor: '#fbbf24', backgroundColor: '#f0fdfa', textColor: '#134e4a', headerStyle: 'ornate', borderStyle: 'gold_foil', decoration: 'circles', layout: 'royal', fontTitle: 'Playfair Display', fontBody: 'Lato', hasCornerOrnaments: true, hasMedalBadge: true, hasGoldFoil: true, hasRibbonBanner: true, hasElegantDivider: true, hasWatermark: false, hasEmbossedTitle: true, hasSparkleAccent: true },
  { id: 'd26', name: 'Jade Palace', tier: 'elite', primaryColor: '#065f46', secondaryColor: '#059669', accentColor: '#fbbf24', goldColor: '#fde047', backgroundColor: '#ecfdf5', textColor: '#064e3b', headerStyle: 'ornate', borderStyle: 'double_gold', decoration: 'stars', layout: 'royal', fontTitle: 'Cinzel', fontBody: 'Merriweather', hasCornerOrnaments: true, hasMedalBadge: true, hasGoldFoil: true, hasRibbonBanner: true, hasElegantDivider: true, hasWatermark: true, hasEmbossedTitle: true, hasSparkleAccent: true },
  { id: 'd27', name: 'Lime Prestige', tier: 'premium', primaryColor: '#65a30d', secondaryColor: '#84cc16', accentColor: '#fef08a', goldColor: '#fbbf24', backgroundColor: '#f7fee7', textColor: '#1a2e05', headerStyle: 'gradient', borderStyle: 'double_gold', decoration: 'triangles', layout: 'modern', fontTitle: 'Cormorant Garamond', fontBody: 'Poppins', hasCornerOrnaments: true, hasMedalBadge: false, hasGoldFoil: false, hasRibbonBanner: false, hasElegantDivider: true, hasWatermark: false, hasEmbossedTitle: false, hasSparkleAccent: true },
  { id: 'd28', name: 'Dark Verdant', tier: 'premium', primaryColor: '#052e16', secondaryColor: '#14532d', accentColor: '#4ade80', goldColor: '#fbbf24', backgroundColor: '#f0fdf4', textColor: '#052e16', headerStyle: 'solid', borderStyle: 'navy_silver', decoration: 'none', layout: 'spacious', fontTitle: 'Inter', fontBody: 'Inter', hasCornerOrnaments: true, hasMedalBadge: false, hasGoldFoil: false, hasRibbonBanner: false, hasElegantDivider: true, hasWatermark: false, hasEmbossedTitle: false, hasSparkleAccent: false },
  { id: 'd29', name: 'Sage Elegance', tier: 'premium', primaryColor: '#4d7c0f', secondaryColor: '#65a30d', accentColor: '#fef3c7', goldColor: '#fbbf24', backgroundColor: '#f7fee7', textColor: '#1a2e05', headerStyle: 'minimal', borderStyle: 'ornate', decoration: 'flourish', layout: 'compact', fontTitle: 'Playfair Display', fontBody: 'Lora', hasCornerOrnaments: true, hasMedalBadge: false, hasGoldFoil: false, hasRibbonBanner: false, hasElegantDivider: true, hasWatermark: false, hasEmbossedTitle: false, hasSparkleAccent: false },
  { id: 'd30', name: 'Pine Dynasty', tier: 'royal', primaryColor: '#166534', secondaryColor: '#15803d', accentColor: '#fcd34d', goldColor: '#fbbf24', backgroundColor: '#f0fdf4', textColor: '#14532d', headerStyle: 'ornate', borderStyle: 'double_gold', decoration: 'circles', layout: 'royal', fontTitle: 'Cinzel', fontBody: 'Merriweather', hasCornerOrnaments: true, hasMedalBadge: true, hasGoldFoil: true, hasRibbonBanner: true, hasElegantDivider: true, hasWatermark: false, hasEmbossedTitle: true, hasSparkleAccent: true },

  // ═══════════ MAROON / CRIMSON FAMILY (10) ═══════════
  { id: 'd31', name: 'Crimson Majesty', tier: 'royal', primaryColor: '#7f1d1d', secondaryColor: '#991b1b', accentColor: '#fcd34d', goldColor: '#fde047', backgroundColor: '#fef2f2', textColor: '#450a0a', headerStyle: 'ornate', borderStyle: 'double_gold', decoration: 'flourish', layout: 'royal', fontTitle: 'Playfair Display', fontBody: 'Merriweather', hasCornerOrnaments: true, hasMedalBadge: true, hasGoldFoil: true, hasRibbonBanner: true, hasElegantDivider: true, hasWatermark: false, hasEmbossedTitle: true, hasSparkleAccent: true },
  { id: 'd32', name: 'Ruby Sovereign', tier: 'royal', primaryColor: '#b91c1c', secondaryColor: '#dc2626', accentColor: '#fef08a', goldColor: '#fbbf24', backgroundColor: '#fef2f2', textColor: '#450a0a', headerStyle: 'ornate', borderStyle: 'gold_foil', decoration: 'stars', layout: 'royal', fontTitle: 'Cinzel', fontBody: 'Lora', hasCornerOrnaments: true, hasMedalBadge: true, hasGoldFoil: true, hasRibbonBanner: true, hasElegantDivider: true, hasWatermark: true, hasEmbossedTitle: true, hasSparkleAccent: false },
  { id: 'd33', name: 'Crimson Rose', tier: 'premium', primaryColor: '#881337', secondaryColor: '#be123c', accentColor: '#fcd34d', goldColor: '#fbbf24', backgroundColor: '#fff1f2', textColor: '#4c0519', headerStyle: 'ribbon', borderStyle: 'gold_foil', decoration: 'flourish', layout: 'classic', fontTitle: 'Merriweather', fontBody: 'Poppins', hasCornerOrnaments: true, hasMedalBadge: true, hasGoldFoil: true, hasRibbonBanner: true, hasElegantDivider: true, hasWatermark: false, hasEmbossedTitle: false, hasSparkleAccent: false },
  { id: 'd34', name: 'Rose Gold', tier: 'premium', primaryColor: '#9f1239', secondaryColor: '#e11d48', accentColor: '#fbcfe8', goldColor: '#fbbf24', backgroundColor: '#fff1f2', textColor: '#4c0519', headerStyle: 'gradient', borderStyle: 'elegant_thin', decoration: 'circles', layout: 'modern', fontTitle: 'Cormorant Garamond', fontBody: 'Poppins', hasCornerOrnaments: true, hasMedalBadge: false, hasGoldFoil: false, hasRibbonBanner: true, hasElegantDivider: true, hasWatermark: false, hasEmbossedTitle: false, hasSparkleAccent: true },
  { id: 'd35', name: 'Burgundy Royal', tier: 'elite', primaryColor: '#4c0519', secondaryColor: '#7f1d1d', accentColor: '#eab308', goldColor: '#fbbf24', backgroundColor: '#fef2f2', textColor: '#1c1917', headerStyle: 'ornate', borderStyle: 'double_gold', decoration: 'stars', layout: 'royal', fontTitle: 'Cinzel', fontBody: 'Lora', hasCornerOrnaments: true, hasMedalBadge: true, hasGoldFoil: true, hasRibbonBanner: true, hasElegantDivider: true, hasWatermark: true, hasEmbossedTitle: true, hasSparkleAccent: true },
  { id: 'd36', name: 'Rust Emperor', tier: 'premium', primaryColor: '#9a3412', secondaryColor: '#c2410c', accentColor: '#fed7aa', goldColor: '#fbbf24', backgroundColor: '#fff7ed', textColor: '#431407', headerStyle: 'gradient', borderStyle: 'double_gold', decoration: 'triangles', layout: 'modern', fontTitle: 'Cormorant Garamond', fontBody: 'Poppins', hasCornerOrnaments: true, hasMedalBadge: true, hasGoldFoil: false, hasRibbonBanner: false, hasElegantDivider: true, hasWatermark: false, hasEmbossedTitle: false, hasSparkleAccent: true },
  { id: 'd37', name: 'Terracotta Heritage', tier: 'premium', primaryColor: '#7c2d12', secondaryColor: '#9a3412', accentColor: '#fbbf24', goldColor: '#fde047', backgroundColor: '#fff7ed', textColor: '#431407', headerStyle: 'ribbon', borderStyle: 'ornate', decoration: 'flourish', layout: 'classic', fontTitle: 'Merriweather', fontBody: 'Lora', hasCornerOrnaments: true, hasMedalBadge: true, hasGoldFoil: true, hasRibbonBanner: true, hasElegantDivider: true, hasWatermark: false, hasEmbossedTitle: false, hasSparkleAccent: false },
  { id: 'd38', name: 'Cherry Bloom', tier: 'premium', primaryColor: '#be185d', secondaryColor: '#db2777', accentColor: '#fbcfe8', goldColor: '#fbbf24', backgroundColor: '#fdf2f8', textColor: '#500724', headerStyle: 'gradient', borderStyle: 'elegant_thin', decoration: 'circles', layout: 'modern', fontTitle: 'Cormorant Garamond', fontBody: 'Poppins', hasCornerOrnaments: true, hasMedalBadge: false, hasGoldFoil: false, hasRibbonBanner: false, hasElegantDivider: true, hasWatermark: false, hasEmbossedTitle: false, hasSparkleAccent: true },
  { id: 'd39', name: 'Wine Palace', tier: 'royal', primaryColor: '#581c87', secondaryColor: '#7e22ce', accentColor: '#fcd34d', goldColor: '#fbbf24', backgroundColor: '#faf5ff', textColor: '#3b0764', headerStyle: 'ornate', borderStyle: 'double_gold', decoration: 'stars', layout: 'royal', fontTitle: 'Playfair Display', fontBody: 'Merriweather', hasCornerOrnaments: true, hasMedalBadge: true, hasGoldFoil: true, hasRibbonBanner: true, hasElegantDivider: true, hasWatermark: false, hasEmbossedTitle: true, hasSparkleAccent: true },
  { id: 'd40', name: 'Sunset Coral', tier: 'premium', primaryColor: '#c2410c', secondaryColor: '#ea580c', accentColor: '#fef08a', goldColor: '#fbbf24', backgroundColor: '#fff7ed', textColor: '#431407', headerStyle: 'gradient', borderStyle: 'double_gold', decoration: 'waves', layout: 'modern', fontTitle: 'Cormorant Garamond', fontBody: 'Lato', hasCornerOrnaments: true, hasMedalBadge: false, hasGoldFoil: false, hasRibbonBanner: true, hasElegantDivider: true, hasWatermark: false, hasEmbossedTitle: false, hasSparkleAccent: true },

  // ═══════════ PURPLE / MODERN ELITE FAMILY (10) ═══════════
  { id: 'd41', name: 'Royal Purple Elite', tier: 'royal', primaryColor: '#581c87', secondaryColor: '#7e22ce', accentColor: '#fbbf24', goldColor: '#fde047', backgroundColor: '#faf5ff', textColor: '#3b0764', headerStyle: 'ornate', borderStyle: 'double_gold', decoration: 'stars', layout: 'royal', fontTitle: 'Playfair Display', fontBody: 'Merriweather', hasCornerOrnaments: true, hasMedalBadge: true, hasGoldFoil: true, hasRibbonBanner: true, hasElegantDivider: true, hasWatermark: false, hasEmbossedTitle: true, hasSparkleAccent: true },
  { id: 'd42', name: 'Lavender Prestige', tier: 'premium', primaryColor: '#6b21a8', secondaryColor: '#a855f7', accentColor: '#e9d5ff', goldColor: '#fbbf24', backgroundColor: '#faf5ff', textColor: '#3b0764', headerStyle: 'gradient', borderStyle: 'elegant_thin', decoration: 'circles', layout: 'modern', fontTitle: 'Cormorant Garamond', fontBody: 'Poppins', hasCornerOrnaments: true, hasMedalBadge: false, hasGoldFoil: false, hasRibbonBanner: false, hasElegantDivider: true, hasWatermark: false, hasEmbossedTitle: false, hasSparkleAccent: true },
  { id: 'd43', name: 'Deep Violet Crown', tier: 'royal', primaryColor: '#3b0764', secondaryColor: '#6b21a8', accentColor: '#fcd34d', goldColor: '#fbbf24', backgroundColor: '#faf5ff', textColor: '#1e1b4b', headerStyle: 'ornate', borderStyle: 'gold_foil', decoration: 'flourish', layout: 'royal', fontTitle: 'Cinzel', fontBody: 'Lora', hasCornerOrnaments: true, hasMedalBadge: true, hasGoldFoil: true, hasRibbonBanner: true, hasElegantDivider: true, hasWatermark: true, hasEmbossedTitle: true, hasSparkleAccent: false },
  { id: 'd44', name: 'Slate Professional', tier: 'premium', primaryColor: '#1e293b', secondaryColor: '#334155', accentColor: '#64748b', goldColor: '#fbbf24', backgroundColor: '#f8fafc', textColor: '#0f172a', headerStyle: 'minimal', borderStyle: 'elegant_thin', decoration: 'none', layout: 'compact', fontTitle: 'Inter', fontBody: 'Inter', hasCornerOrnaments: false, hasMedalBadge: false, hasGoldFoil: false, hasRibbonBanner: false, hasElegantDivider: true, hasWatermark: false, hasEmbossedTitle: false, hasSparkleAccent: false },
  { id: 'd45', name: 'Charcoal Elite', tier: 'premium', primaryColor: '#18181b', secondaryColor: '#3f3f46', accentColor: '#facc15', goldColor: '#fbbf24', backgroundColor: '#fafafa', textColor: '#18181b', headerStyle: 'minimal', borderStyle: 'elegant_thin', decoration: 'triangles', layout: 'modern', fontTitle: 'Inter', fontBody: 'Inter', hasCornerOrnaments: true, hasMedalBadge: false, hasGoldFoil: false, hasRibbonBanner: false, hasElegantDivider: true, hasWatermark: false, hasEmbossedTitle: false, hasSparkleAccent: false },
  { id: 'd46', name: 'Teal Purple Fusion', tier: 'premium', primaryColor: '#0f766e', secondaryColor: '#581c87', accentColor: '#fcd34d', goldColor: '#fbbf24', backgroundColor: '#f5f3ff', textColor: '#3b0764', headerStyle: 'gradient', borderStyle: 'double_gold', decoration: 'circles', layout: 'classic', fontTitle: 'Playfair Display', fontBody: 'Merriweather', hasCornerOrnaments: true, hasMedalBadge: true, hasGoldFoil: false, hasRibbonBanner: true, hasElegantDivider: true, hasWatermark: false, hasEmbossedTitle: false, hasSparkleAccent: true },
  { id: 'd47', name: 'Indigo Sovereign', tier: 'royal', primaryColor: '#312e81', secondaryColor: '#4338ca', accentColor: '#a5b4fc', goldColor: '#fbbf24', backgroundColor: '#eef2ff', textColor: '#1e1b4b', headerStyle: 'ornate', borderStyle: 'navy_silver', decoration: 'stars', layout: 'royal', fontTitle: 'Cinzel', fontBody: 'Poppins', hasCornerOrnaments: true, hasMedalBadge: true, hasGoldFoil: true, hasRibbonBanner: true, hasElegantDivider: true, hasWatermark: false, hasEmbossedTitle: true, hasSparkleAccent: true },
  { id: 'd48', name: 'Plum Dynasty', tier: 'royal', primaryColor: '#701a75', secondaryColor: '#a21caf', accentColor: '#fbcfe8', goldColor: '#fbbf24', backgroundColor: '#fdf4ff', textColor: '#4a044e', headerStyle: 'ornate', borderStyle: 'gold_foil', decoration: 'ribbons', layout: 'royal', fontTitle: 'Playfair Display', fontBody: 'Merriweather', hasCornerOrnaments: true, hasMedalBadge: true, hasGoldFoil: true, hasRibbonBanner: true, hasElegantDivider: true, hasWatermark: true, hasEmbossedTitle: true, hasSparkleAccent: true },
  { id: 'd49', name: 'Black Gold Elite', tier: 'elite', primaryColor: '#0a0a0a', secondaryColor: '#1c1917', accentColor: '#eab308', goldColor: '#fde047', backgroundColor: '#fafaf9', textColor: '#0a0a0a', headerStyle: 'ornate', borderStyle: 'double_gold', decoration: 'stars', layout: 'royal', fontTitle: 'Cinzel', fontBody: 'Lora', hasCornerOrnaments: true, hasMedalBadge: true, hasGoldFoil: true, hasRibbonBanner: true, hasElegantDivider: true, hasWatermark: true, hasEmbossedTitle: true, hasSparkleAccent: true },
  { id: 'd50', name: 'Pastel Prestige', tier: 'premium', primaryColor: '#7c3aed', secondaryColor: '#ec4899', accentColor: '#06b6d4', goldColor: '#fbbf24', backgroundColor: '#faf5ff', textColor: '#1e1b4b', headerStyle: 'gradient', borderStyle: 'elegant_thin', decoration: 'circles', layout: 'modern', fontTitle: 'Cormorant Garamond', fontBody: 'Poppins', hasCornerOrnaments: true, hasMedalBadge: false, hasGoldFoil: false, hasRibbonBanner: true, hasElegantDivider: true, hasWatermark: false, hasEmbossedTitle: false, hasSparkleAccent: true },
];

export const DESIGN_COUNT = DESIGNS.length;
