import React, { useEffect, useMemo, useState } from 'react';
import { CheckCircle2, Cloud, Eye, Printer, RefreshCw, X, History } from 'lucide-react';
import { supabase } from '../../lib/supabase';
import { calculateComputed } from './resultTemplateConfig';
import { loadReadOnlyList, loadSubjectListById } from './teacherResultService';
import { printSectionById } from '../../utils/printSection';

const missing=(e:any)=>/does not exist|schema cache|could not find|relation .* does not exist/i.test(String(e?.message||''));
const termLabel=(t:string)=>t==='first_term'?'First Term':'Second Term';

export default function ClerkResultCloudPrintInbox(){
  const [rows,setRows]=useState<any[]>([]);const[busy,setBusy]=useState(false);const[error,setError]=useState('');
  const [classes,setClasses]=useState<Map<string,string>>(new Map());const[divisions,setDivisions]=useState<Map<string,string>>(new Map());const[schoolName,setSchoolName]=useState('School');
  const [preview,setPreview]=useState<any>(null);
  const [statusFilter,setStatusFilter]=useState<'ready'|'printed'|'all'>('ready');
  const load=async()=>{setBusy(true);try{let query:any=supabase.from('edunixo_result_print_queue').select('*').in('status',['ready','printed']).order('created_at',{ascending:false}).limit(200);const r=await query;if(r.error){if(missing(r.error)){setRows([]);setError('Teacher Result cloud print queue is not installed yet.');return}throw r.error}const qrows=r.data||[];setRows(qrows);setError('');const sid=String(qrows[0]?.school_id||'');if(sid){const [school,cls,div]=await Promise.all([supabase.from('schools').select('school_name').eq('id',sid).maybeSingle(),supabase.from('school_classes').select('id,class_name').eq('school_id',sid),supabase.from('school_divisions').select('id,division_name').eq('school_id',sid)]);if(!school.error&&school.data)setSchoolName((school.data as any).school_name||'School');if(!cls.error)setClasses(new Map((cls.data||[]).map((x:any)=>[String(x.id),String(x.class_name)])));if(!div.error)setDivisions(new Map((div.data||[]).map((x:any)=>[String(x.id),String(x.division_name)])));}}catch(e:any){setError(e?.message||'Cloud result print queue unavailable.')}finally{setBusy(false)}};
  useEffect(()=>{void load()},[]);
  const markPrinted=async(id:string)=>{setBusy(true);try{const session=await supabase.auth.getSession();const token=session.data.session?.access_token;if(session.error||!token)throw session.error||new Error('Secure Clerk session was not found.');const response=await fetch(`/api/clerk/result-print-queue/${encodeURIComponent(id)}/printed`,{method:'POST',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:JSON.stringify({})});const payload=await response.json().catch(()=>({}));if(!response.ok)throw new Error(payload.error||'Unable to update print status securely.');setPreview(null);await load()}catch(e:any){setError(e?.message||'Unable to update print status.')}finally{setBusy(false)}};
  const openPreview=async(item:any)=>{setBusy(true);setError('');try{if(item.item_type==='subject_mark_list'){const list=await loadSubjectListById(item.source_id);if(!list)throw new Error('Subject Mark List source is unavailable.');const detail=await loadReadOnlyList(list);setPreview({type:'subject',item,list,...detail});}else{const rb=await supabase.from('edunixo_result_books').select('*').eq('id',item.source_id).maybeSingle();if(rb.error)throw rb.error;if(!rb.data)throw new Error('Result Book source is unavailable.');setPreview({type:'book',item,book:rb.data});}}catch(e:any){setError(e?.message||'Print preview could not be prepared.')}finally{setBusy(false)}};
  const visibleRows=useMemo(()=>rows.filter((r:any)=>statusFilter==='all'||r.status===statusFilter),[rows,statusFilter]);
  const classLabel=(r:any)=>classes.get(String(r.class_id))||r.class_id;const divisionLabel=(r:any)=>r.division_id?(divisions.get(String(r.division_id))||r.division_id):'—';
  const bookColumns=preview?.type==='book'&&Array.isArray(preview.book.column_schema)?preview.book.column_schema:[];
  const bookRows=preview?.type==='book'?Object.entries(preview.book.consolidated||{}):[];
  const subjectRows=preview?.type==='subject'?preview.roster||[]:[];
  const subjectTemplate=preview?.type==='subject'?preview.template:null;
  const printableTitle=preview?.type==='subject'?`${preview.list.subjectName} · ${termLabel(preview.list.term)} Subject Mark List`:`${preview?classLabel(preview.item):''} · ${preview?termLabel(preview.item.term):''} Result Book`;
  return <>
    <style>{`@media print{body *{visibility:hidden!important}.r4-cloud-print-preview,.r4-cloud-print-preview *{visibility:visible!important}.r4-cloud-print-preview{position:absolute!important;left:0;top:0;width:100%;background:#fff!important;box-shadow:none!important;border:0!important}.r4-print-actions{display:none!important}@page{size:A4 landscape;margin:8mm}}`}</style>
    <section className="rounded-2xl border border-cyan-200 bg-cyan-50/40 p-4 shadow-sm">
      <div className="flex flex-wrap items-start justify-between gap-3"><div className="flex gap-3"><div className="rounded-xl bg-slate-950 p-2 text-white"><Cloud className="h-4 w-4"/></div><div><h4 className="text-sm font-black text-slate-900">Result Print Center</h4><p className="text-[11px] text-slate-600">Accepted Subject Mark Lists and completed Result Books are handled in one print workspace. Printed items remain available in history; there is no duplicate Completed Result Books feature.</p></div></div><button onClick={()=>void load()} disabled={busy} className="inline-flex items-center gap-1 rounded-lg border border-cyan-200 bg-white px-3 py-2 text-[10px] font-black text-cyan-800"><RefreshCw className="h-3 w-3"/>Refresh</button></div>
      <div className="mt-3 flex flex-wrap gap-2">{([['ready','Ready to Print'],['printed','Printed History'],['all','All']] as const).map(([key,label])=><button key={key} onClick={()=>setStatusFilter(key)} className={`inline-flex items-center gap-1 rounded-full px-3 py-1.5 text-[10px] font-black ${statusFilter===key?'bg-slate-950 text-white':'border border-slate-200 bg-white text-slate-600'}`}>{key==='printed'?<History className="h-3 w-3"/>:null}{label}</button>)}</div>
      {error&&<div className="mt-3 rounded-lg border border-amber-200 bg-amber-50 p-2 text-[10px] font-bold text-amber-800">{error}</div>}
      {visibleRows.length>0?<div className="mt-3 overflow-x-auto rounded-xl border border-cyan-100 bg-white"><table className="w-full min-w-[820px] text-[11px]"><thead className="bg-slate-950 text-white"><tr><th className="p-2 text-left">Type</th><th className="p-2 text-left">Class / Division</th><th className="p-2 text-left">Subject</th><th className="p-2">Term</th><th className="p-2">Received</th><th className="p-2">Actions</th></tr></thead><tbody>{visibleRows.map(r=><tr key={r.id} className="border-t"><td className="p-2 font-black">{r.item_type==='subject_mark_list'?'Subject Mark List':'Result Book'}</td><td className="p-2">{classLabel(r)} / {divisionLabel(r)}</td><td className="p-2">{r.subject_name||'Class Result Book'}</td><td className="p-2 text-center">{termLabel(r.term)}</td><td className="p-2 text-center">{String(r.created_at||'').slice(0,16).replace('T',' ')}</td><td className="p-2"><div className="flex justify-center gap-1.5"><button onClick={()=>void openPreview(r)} disabled={busy} className="inline-flex items-center gap-1 rounded-lg border border-slate-300 bg-white px-2.5 py-1.5 font-black"><Eye className="h-3 w-3"/>Preview / Print</button>{r.status==='ready'?<button onClick={()=>void markPrinted(r.id)} disabled={busy} className="inline-flex items-center gap-1 rounded-lg bg-emerald-600 px-2.5 py-1.5 font-black text-white"><CheckCircle2 className="h-3 w-3"/>Mark Printed</button>:<span className="inline-flex items-center gap-1 rounded-lg bg-slate-100 px-2.5 py-1.5 font-black text-slate-600"><CheckCircle2 className="h-3 w-3"/>Printed</span>}</div></td></tr>)}</tbody></table></div>:!error&&<div className="mt-3 flex items-center gap-2 rounded-xl border border-dashed border-cyan-200 p-4 text-[11px] text-slate-600"><CheckCircle2 className="h-4 w-4 text-emerald-600"/>No Result print items in this view.</div>}
    </section>
    {preview&&<div className="fixed inset-0 z-[9999] overflow-auto bg-slate-950/70 p-3 md:p-6"><section id="clerk-result-cloud-preview-print" className="r4-cloud-print-preview mx-auto min-w-[980px] max-w-[1500px] rounded-2xl bg-white p-5 shadow-2xl"><div className="r4-print-actions mb-4 flex items-center justify-between gap-3 border-b pb-3"><div><h3 className="font-black text-slate-950">{printableTitle}</h3><p className="text-[10px] text-slate-500">Official Clerk print copy received through the approved Subject Teacher → Class Teacher workflow.</p></div><div className="flex gap-2"><button type="button" onClick={()=>printSectionById('clerk-result-cloud-preview-print', printableTitle)} className="inline-flex items-center gap-1 rounded-lg bg-slate-950 px-3 py-2 text-xs font-black text-white"><Printer className="h-3.5 w-3.5"/>Print</button><button onClick={()=>setPreview(null)} className="rounded-lg border p-2"><X className="h-4 w-4"/></button></div></div><div className="mb-4 text-center"><h1 className="text-lg font-black uppercase">{schoolName}</h1><h2 className="text-sm font-black">{printableTitle}</h2><p className="text-[10px]">Class {classLabel(preview.item)} · Division {divisionLabel(preview.item)}</p></div>
      {preview.type==='subject'&&subjectTemplate&&<div className="overflow-visible"><table className="w-full border-collapse text-[9px]"><thead><tr className="bg-slate-100"><th className="border p-1">Roll</th><th className="border p-1">GR</th><th className="border p-1 text-left">Student</th>{subjectTemplate.heads.map((h:any)=><th key={h.key} className="border p-1">{h.label}{h.maxMarks!=null?<span className="block text-[8px] font-normal">Max {h.maxMarks}</span>:null}</th>)}</tr></thead><tbody>{subjectRows.map((s:any,i:number)=>{const r=preview.rows.find((x:any)=>x.studentId===s.id)||{marks:{},computed:{}};const computed={...r.computed,...calculateComputed(subjectTemplate,r.marks)};return <tr key={s.id}><td className="border p-1 text-center">{s.rollNumber||i+1}</td><td className="border p-1 text-center">{s.grNumber||'—'}</td><td className="border p-1 font-semibold">{s.name}</td>{subjectTemplate.heads.map((h:any)=><td key={h.key} className="border p-1 text-center">{h.kind==='calculated'?(computed[h.key]??'—'):(r.marks[h.key]??'—')}</td>)}</tr>})}</tbody></table></div>}
      {preview.type==='book'&&<div><table className="w-full border-collapse text-[8px]"><thead><tr className="bg-slate-950 text-white"><th className="border border-slate-600 p-1 text-left">Student</th><th className="border border-slate-600 p-1">Roll</th><th className="border border-slate-600 p-1">GR</th>{bookColumns.map((c:any)=><th key={c.key} className="border border-slate-600 p-1">{c.subjectName}<span className="block font-normal">{c.label}</span></th>)}</tr></thead><tbody>{bookRows.map(([id,row]:any)=><tr key={id}><td className="border p-1 font-semibold">{row.studentName||id}</td><td className="border p-1 text-center">{row.rollNumber||'—'}</td><td className="border p-1 text-center">{row.grNumber||'—'}</td>{bookColumns.map((c:any)=><td key={c.key} className="border p-1 text-center">{row[c.key]!==''&&row[c.key]!=null?String(row[c.key]):'—'}</td>)}</tr>)}</tbody></table></div>}
      <div className="mt-4 flex justify-between border-t pt-6 text-[9px]"><span>Class Teacher Signature</span><span>Clerk / Record Copy</span><span>Headmaster Signature</span></div></section></div>}
  </>;
}
