import React, { useCallback, useEffect, useMemo, useState } from 'react';
import { BellRing, CheckCircle2, Clock3, FileText, LogOut, PackageCheck, RefreshCw, ShieldCheck, UserRound, UsersRound } from 'lucide-react';
import type { User } from '../../types';
import { supabase } from '../../lib/supabase';
import { getNativeBellStatus, isNativeBellPlatform, openNativeBellNotificationSettings, requestNativeExactAlarmAccess, syncNativeBellSchedule } from '../../lib/bellAlarmNative';

const authToken=async()=>{const {data:{session}}=await supabase.auth.getSession();if(!session?.access_token)throw new Error('Peon session expired. Please log in again.');return session.access_token;};
async function api(path:string,init:RequestInit={}){const token=await authToken();const r=await fetch(path,{...init,headers:{...(init.body?{'Content-Type':'application/json'}:{}),...(init.headers||{}),Authorization:`Bearer ${token}`},cache:'no-store'});const b=await r.json().catch(()=>({}));if(!r.ok)throw new Error(b.error||'Operation failed.');return b;}
const fmt=(v:any)=>{if(!v)return '—';try{return new Date(v).toLocaleString();}catch{return String(v)}};

type Props={user:User; activeModuleId?:string|null; activeFeatureId?:string|null; onNavigate?:(moduleId:string,featureId?:string)=>void};
export default function PeonPortalWorkspace({user,activeModuleId='pn-home',onNavigate}:Props){
 const [snapshot,setSnapshot]=useState<any>(null),[bell,setBell]=useState<any>(null),[leaves,setLeaves]=useState<any[]>([]),[busy,setBusy]=useState(true),[message,setMessage]=useState('');
 const [visitor,setVisitor]=useState({visitorName:'',purpose:'',contactNumber:'',organization:'',metWith:''}); const [leave,setLeave]=useState({startDate:'',endDate:'',leaveType:'Casual Leave',reason:''}); const [nativeStatus,setNativeStatus]=useState<any>(null);
 const load=useCallback(async()=>{setBusy(true);setMessage('');try{const tasks=[api('/api/peon/operations/snapshot'),api('/api/peon/bell-schedule'),api('/api/leave-management/applications')];const [s,b,l]=await Promise.all(tasks);setSnapshot(s);setBell(b);setLeaves(l.applications||[]);if(isNativeBellPlatform()){const status=await getNativeBellStatus();setNativeStatus(status);if(status.exactAlarmAllowed){const synced=await syncNativeBellSchedule(b.schedule||[]);setNativeStatus((cur:any)=>({...cur,scheduledCount:synced.scheduled}));}}else setNativeStatus({native:false});}catch(e:any){setMessage(e.message||'Peon workspace could not be loaded.');}finally{setBusy(false);}},[]);
 useEffect(()=>{void load();const refresh=()=>{if(document.visibilityState==='visible')void load();};document.addEventListener('visibilitychange',refresh);const timer=window.setInterval(()=>{if(document.visibilityState==='visible')void load();},5*60*1000);return()=>{document.removeEventListener('visibilitychange',refresh);window.clearInterval(timer);};},[load]);
 const todayEvents=bell?.todayEvents||[]; const nextBell=useMemo(()=>{const now=new Date();return (bell?.schedule||[]).map((e:any)=>({...e,dt:new Date(Number(e.epochMs)||new Date(`${e.localDate}T${e.time}:00`).getTime())})).filter((e:any)=>e.dt.getTime()>now.getTime()).sort((a:any,b:any)=>a.dt.getTime()-b.dt.getTime())[0]||null;},[bell]);
 const action=async(path:string,body?:any)=>{setMessage('');try{await api(path,{method:'POST',body:body?JSON.stringify(body):undefined});setMessage('Saved successfully.');await load();}catch(e:any){setMessage(e.message||'Action failed.');}};
 const submitVisitor=async(e:React.FormEvent)=>{e.preventDefault();await action('/api/peon/visitors',visitor);setVisitor({visitorName:'',purpose:'',contactNumber:'',organization:'',metWith:''});};
 const submitLeave=async(e:React.FormEvent)=>{e.preventDefault();if(!leave.reason.trim()){setMessage('Leave reason is required.');return;}await action('/api/leave-management/applications',{application:{...leave,applicantName:user.name||'Peon'}});setLeave({startDate:'',endDate:'',leaveType:'Casual Leave',reason:''});};
 const module=activeModuleId||'pn-home';
 if(busy&&!snapshot)return <div className="rounded-3xl border border-slate-200 bg-white p-8 text-sm font-semibold text-slate-500">Loading Peon Operations…</div>;
 const cards=<div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-5">{[
   ['Next Bell',nextBell?`${nextBell.time} · ${nextBell.label}`:'No upcoming bell',BellRing],['Visitors Inside',snapshot?.summary?.visitorsInside||0,UsersRound],['Students Out',snapshot?.summary?.studentsOut||0,UserRound],['Staff Out',snapshot?.summary?.staffOut||0,ShieldCheck],['Pending Delivery',snapshot?.summary?.pendingDispatch||0,PackageCheck]
 ].map(([label,value,Icon]:any)=><div key={label} className="rounded-2xl border border-slate-200 bg-white p-4"><Icon className="h-5 w-5 text-blue-600"/><div className="mt-3 text-[10px] font-black uppercase tracking-wider text-slate-400">{label}</div><div className="mt-1 text-sm font-black text-slate-900">{value}</div></div>)}</div>;
 const notice=message?<div className="rounded-2xl border border-blue-200 bg-blue-50 p-3 text-xs font-semibold text-blue-800">{message}</div>:null;
 if(module==='pn-bell-timing')return <div className="space-y-5 text-left">{cards}<section className="rounded-3xl border border-slate-200 bg-white p-5"><div className="flex items-start justify-between gap-3"><div><div className="text-[10px] font-black uppercase tracking-[.2em] text-blue-600">Mandatory Bell Service</div><h2 className="mt-1 text-xl font-black text-slate-900">Bell Timing & Alarm</h2><p className="mt-1 text-xs text-slate-500">Source: <b>{bell?.source==='manual'?'Headmaster Manual Schedule':'School Timetable'}</b>. Peon cannot edit or disable this schedule.</p></div><button type="button" onClick={()=>void load()} className="rounded-xl border border-slate-200 p-2"><RefreshCw className="h-4 w-4"/></button></div>
   <div className="mt-5 rounded-2xl bg-slate-950 p-5 text-white"><div className="text-xs font-bold text-slate-400">Next Bell</div><div className="mt-1 text-2xl font-black">{nextBell?`${nextBell.time} · ${nextBell.label}`:'No upcoming bell'}</div></div>
   <div className="mt-5"><h3 className="text-sm font-black text-slate-900">Today's Bell Schedule</h3><div className="mt-2 divide-y divide-slate-100 rounded-2xl border border-slate-200">{todayEvents.map((e:any)=><div key={e.id} className="flex items-center justify-between px-4 py-3"><span className="text-sm font-bold text-slate-800">{e.label}</span><span className="font-mono text-sm font-black text-blue-700">{e.time}</span></div>)}{!todayEvents.length&&<div className="p-4 text-xs text-slate-500">No bells scheduled today.</div>}</div></div>
   {bell?.leaveSuppression?.activeToday&&<div className="mt-5 rounded-2xl border border-emerald-200 bg-emerald-50 p-4"><div className="font-black text-emerald-900">Bell Alarm Paused — Approved Leave</div><p className="mt-1 text-xs text-emerald-800">Your approved leave is active today. EDUNIXO has removed bell alarms for your leave session. Alarms resume automatically after the approved leave period.</p></div>}
   <div className="mt-5 rounded-2xl border border-amber-200 bg-amber-50 p-4"><div className="font-black text-amber-900">Android Bell Device Readiness</div>{nativeStatus?.native?<div className="mt-2 space-y-2 text-xs text-amber-900"><div>Exact alarm access: <b>{nativeStatus.exactAlarmAllowed?'Ready':'Required'}</b></div><div>Notification visibility: <b>{nativeStatus.notificationsAllowed?'Ready':'System permission required'}</b></div><div>Scheduled local alarms: <b>{nativeStatus.scheduledCount||0}</b></div>{!nativeStatus.exactAlarmAllowed&&<button type="button" onClick={async()=>{await requestNativeExactAlarmAccess();setMessage('Android exact-alarm settings opened. Enable EDUNIXO and return to refresh.');}} className="rounded-xl bg-amber-900 px-3 py-2 font-bold text-white">Complete Mandatory Alarm Setup</button>}{!nativeStatus.notificationsAllowed&&<button type="button" onClick={()=>void openNativeBellNotificationSettings()} className="ml-2 rounded-xl border border-amber-400 bg-white px-3 py-2 font-bold">Open Notification Settings</button>}</div>:<p className="mt-2 text-xs text-amber-800">Native bell alarms activate in the installed Android app. Web preview displays the authoritative schedule only.</p>}</div>
  </section>{notice}</div>;
 if(module==='pn-gate-visitor')return <div className="space-y-5 text-left">{cards}<div className="grid gap-5 lg:grid-cols-2"><form onSubmit={submitVisitor} className="space-y-3 rounded-3xl border border-slate-200 bg-white p-5"><h2 className="font-black text-slate-900">Visitor Check-in</h2><input required placeholder="Visitor name" value={visitor.visitorName} onChange={e=>setVisitor({...visitor,visitorName:e.target.value})} className="w-full rounded-xl border border-slate-200 px-3 py-2.5"/><input placeholder="Contact number" value={visitor.contactNumber} onChange={e=>setVisitor({...visitor,contactNumber:e.target.value})} className="w-full rounded-xl border border-slate-200 px-3 py-2.5"/><input placeholder="Organization" value={visitor.organization} onChange={e=>setVisitor({...visitor,organization:e.target.value})} className="w-full rounded-xl border border-slate-200 px-3 py-2.5"/><input placeholder="Person to meet" value={visitor.metWith} onChange={e=>setVisitor({...visitor,metWith:e.target.value})} className="w-full rounded-xl border border-slate-200 px-3 py-2.5"/><textarea required placeholder="Purpose" value={visitor.purpose} onChange={e=>setVisitor({...visitor,purpose:e.target.value})} className="w-full rounded-xl border border-slate-200 px-3 py-2.5"/><button className="rounded-xl bg-blue-600 px-4 py-2.5 text-xs font-black text-white">Check In Visitor</button></form>
 <div className="rounded-3xl border border-slate-200 bg-white p-5"><h2 className="font-black text-slate-900">Visitors Currently Inside</h2><div className="mt-3 space-y-2">{(snapshot?.visitors||[]).filter((v:any)=>!v.outTime).map((v:any)=><div key={v.id} className="flex items-center justify-between gap-3 rounded-xl bg-slate-50 p-3"><div><b className="text-sm">{v.visitorName}</b><div className="text-xs text-slate-500">{v.purpose} · In {v.inTime||'—'}</div></div><button type="button" onClick={()=>void action(`/api/peon/visitors/${v.id}/signout`)} className="rounded-lg border border-slate-300 bg-white px-3 py-2 text-xs font-bold">Check Out</button></div>)}{!(snapshot?.visitors||[]).some((v:any)=>!v.outTime)&&<p className="text-xs text-slate-500">No visitor is currently inside.</p>}</div></div></div>
 <div className="grid gap-5 lg:grid-cols-2"><GateList title="Approved Student Passes" rows={(snapshot?.studentPasses||[]).filter((p:any)=>p.status==='out')} nameKey="studentName" onReturn={(id)=>action(`/api/peon/student-passes/${id}/return`)}/><GateList title="Approved Staff Passes" rows={(snapshot?.staffPasses||[]).filter((p:any)=>p.status==='out')} nameKey="staffName" onReturn={(id)=>action(`/api/peon/staff-passes/${id}/return`)}/></div>{notice}</div>;
 if(module==='pn-dispatch')return <div className="space-y-5 text-left">{cards}<section className="rounded-3xl border border-slate-200 bg-white p-5"><h2 className="font-black text-slate-900">Outgoing Dispatch & Delivery</h2><p className="mt-1 text-xs text-slate-500">Clerk owns the Dispatch Register. You may only update physical delivery status.</p><div className="mt-4 space-y-2">{(snapshot?.dispatches||[]).map((d:any)=><div key={d.id} className="rounded-2xl border border-slate-200 p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><b className="text-sm text-slate-900">{d.dispatchNo} · {d.subject}</b><div className="text-xs text-slate-500">To: {d.partyName} · {d.deliveryMode||'Delivery'} · {d.dispatchDate}</div><div className="mt-1 text-[11px] font-bold uppercase text-blue-700">{d.status}</div></div><div className="flex flex-wrap gap-2">{['collected','delivered','returned'].map(st=><button key={st} type="button" onClick={()=>void action(`/api/peon/dispatch/${d.id}/status`,{status:st})} className="rounded-lg border border-slate-200 px-3 py-2 text-xs font-bold capitalize">{st}</button>)}</div></div></div>)}{!(snapshot?.dispatches||[]).length&&<p className="text-xs text-slate-500">No outgoing dispatch records.</p>}</div></section>{notice}</div>;
 if(module==='pn-leave')return <div className="space-y-5 text-left">{cards}<div className="grid gap-5 lg:grid-cols-2"><form onSubmit={submitLeave} className="space-y-3 rounded-3xl border border-slate-200 bg-white p-5"><h2 className="font-black text-slate-900">My Leave Application</h2><div className="grid grid-cols-2 gap-2"><input required type="date" value={leave.startDate} onChange={e=>setLeave({...leave,startDate:e.target.value})} className="rounded-xl border border-slate-200 px-3 py-2.5"/><input required type="date" value={leave.endDate} onChange={e=>setLeave({...leave,endDate:e.target.value})} className="rounded-xl border border-slate-200 px-3 py-2.5"/></div><select value={leave.leaveType} onChange={e=>setLeave({...leave,leaveType:e.target.value})} className="w-full rounded-xl border border-slate-200 px-3 py-2.5"><option>Casual Leave</option><option>Medical Leave</option><option>Earned Leave</option><option>Other</option></select><textarea required placeholder="Reason" value={leave.reason} onChange={e=>setLeave({...leave,reason:e.target.value})} className="w-full rounded-xl border border-slate-200 px-3 py-2.5"/><button className="rounded-xl bg-blue-600 px-4 py-2.5 text-xs font-black text-white">Send to Headmaster</button></form><div className="rounded-3xl border border-slate-200 bg-white p-5"><h2 className="font-black text-slate-900">Leave History</h2><div className="mt-3 space-y-2">{leaves.map((l:any)=><div key={l.id} className="rounded-xl bg-slate-50 p-3"><div className="flex justify-between gap-2"><b className="text-xs">{l.leaveType}</b><span className="text-[11px] font-black text-blue-700">{l.status}</span></div><div className="text-xs text-slate-500">{l.startDate} → {l.endDate}</div>{l.status==='Pending'&&<button type="button" onClick={()=>void action(`/api/leave-management/applications/${l.id}/cancel`)} className="mt-2 text-xs font-bold text-rose-600">Cancel Pending Leave</button>}</div>)}</div></div></div>{notice}</div>;
 if(module==='pn-notices')return <div className="space-y-5 text-left">{cards}<section className="rounded-3xl border border-slate-200 bg-white p-5"><h2 className="font-black text-slate-900">Notices & Instructions</h2><div className="mt-4 space-y-2">{(snapshot?.notifications||[]).map((n:any)=><div key={n.id} className={`rounded-2xl border p-4 ${n.isRead?'border-slate-200 bg-white':'border-blue-200 bg-blue-50'}`}><div className="flex justify-between gap-3"><div><b className="text-sm">{n.title}</b><p className="mt-1 text-xs text-slate-600">{n.body}</p><div className="mt-2 text-[10px] text-slate-400">{fmt(n.createdAt)}</div></div>{!n.isRead&&<button type="button" onClick={()=>void action(`/api/peon/notifications/${n.id}/read`)} className="h-fit rounded-lg border border-blue-200 bg-white px-3 py-2 text-xs font-bold text-blue-700">Mark Read</button>}</div></div>)}{!(snapshot?.notifications||[]).length&&<p className="text-xs text-slate-500">No notices yet.</p>}</div></section>{notice}</div>;
 return <div className="space-y-5 text-left"><section className="rounded-3xl bg-slate-950 p-6 text-white"><div className="text-[10px] font-black uppercase tracking-[.2em] text-cyan-300">Peon Operations</div><h2 className="mt-1 text-2xl font-black">Welcome, {user.name||'Staff'}</h2><p className="mt-2 text-xs text-slate-300">Operational access only. Academic, result, fee and administrative approval data remain restricted.</p></section>{cards}<div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{[['pn-bell-timing','Bell Timing & Alarm',BellRing],['pn-gate-visitor','Gate & Visitor Desk',UsersRound],['pn-dispatch','Dispatch & Delivery',PackageCheck],['pn-leave','My Leave',Clock3],['pn-notices','Notices & Instructions',FileText],['pn-profile','Profile & Security',ShieldCheck]].map(([id,label,Icon]:any)=><button key={id} type="button" onClick={()=>onNavigate?.(id)} className="flex items-center gap-3 rounded-2xl border border-slate-200 bg-white p-4 text-left"><Icon className="h-5 w-5 text-blue-600"/><b className="text-sm text-slate-800">{label}</b></button>)}</div>{notice}</div>;
}
function GateList({title,rows,nameKey,onReturn}:{title:string;rows:any[];nameKey:string;onReturn:(id:string)=>void}){return <section className="rounded-3xl border border-slate-200 bg-white p-5"><h3 className="font-black text-slate-900">{title}</h3><div className="mt-3 space-y-2">{rows.map(p=><div key={p.id} className="flex items-center justify-between gap-3 rounded-xl bg-slate-50 p-3"><div><b className="text-sm">{p[nameKey]}</b><div className="text-xs text-slate-500">{p.passNo} · {p.reason}</div></div><button type="button" onClick={()=>onReturn(p.id)} className="rounded-lg bg-emerald-600 px-3 py-2 text-xs font-bold text-white">Mark Returned</button></div>)}{!rows.length&&<p className="text-xs text-slate-500">No approved person currently out.</p>}</div></section>}
