import React,{useEffect,useMemo,useState} from 'react';
import { AlertTriangle, BrainCircuit, CheckCircle2, FileImage, FileSpreadsheet, FileText, Loader2, LockKeyhole, RefreshCw, Send, ShieldCheck, Sparkles, UploadCloud, X } from 'lucide-react';
import * as XLSX from 'xlsx';
import { supabase } from '../lib/supabase';

type UploadKind='sheet'|'pdf'|'image';
type DocumentRole='mark_list'|'result_book'|'progress_card'|'board_rules';
type PreparedFile={name:string;mimeType:string;size:number;kind:UploadKind;documentRole:DocumentRole;extractedText?:string;base64?:string};
type Proposal={
  country:string;state:string;board:string;curriculum:string;mediums:string[];classes:string[];detectedSubjects:string[];
  examStructure:string[];markComponents:string[];gradingRules:string[];passRules:string[];promotionRules:string[];
  markListColumns:string[];resultBookSections:string[];progressCardSections:string[];signatures:string[];attendanceFields:string[];
  warnings:string[];evidence:string[];confidence:number;summary:string;
};
type PackRow={id:string;name:string;category:string;active:boolean;definition:any;updated_at?:string;created_at?:string};
type ResultSystemStatus={configured:boolean;importAllowed:boolean;source:string;activeSystemName?:string|null;activePackId?:string|null;signals?:{masterTemplateCount?:number;templateMappingCount?:number;subjectListCount?:number;resultBookCount?:number}};
type AcademicCoreFamily={id:string;familyCode:string;familyName:string;requiresJurisdiction:boolean;sortOrder:number};
type AcademicCoreJurisdiction={id:string;code:string;name:string;type:string;sortOrder:number};
type AcademicCoreBoard={id:string;familyId:string;familyCode:string;familyName:string;jurisdictionId?:string|null;jurisdictionCode?:string|null;jurisdictionName?:string|null;boardCode:string;boardName:string;authorityName?:string|null;rulesVerified:boolean;rulesReady:boolean;rulesetId?:string|null;rulesetVersion?:string|null;publishedTemplateCount:number;sortOrder:number};
type AcademicCoreOptions={families:AcademicCoreFamily[];jurisdictions:AcademicCoreJurisdiction[];boards:AcademicCoreBoard[];currentProfile?:{board_id?:string|null;ruleset_id?:string|null;configuration_status?:string|null;is_locked?:boolean}|null};

const MAX_FILES=8;
const MAX_TOTAL_BYTES=7_500_000;
const SUPPORTED=new Set(['application/pdf','image/jpeg','image/png','application/vnd.openxmlformats-officedocument.spreadsheetml.sheet','application/vnd.ms-excel']);
const emptyProposal:Proposal={country:'India',state:'',board:'',curriculum:'',mediums:[],classes:[],detectedSubjects:[],examStructure:[],markComponents:[],gradingRules:[],passRules:[],promotionRules:[],markListColumns:[],resultBookSections:[],progressCardSections:[],signatures:[],attendanceFields:[],warnings:[],evidence:[],confidence:0,summary:''};
const DOCUMENTS:{role:DocumentRole;title:string;button:string;recommended:string;description:string;icon:React.ComponentType<{className?:string}>}[]=[
  {role:'mark_list',title:'Mark List / Marks Register',button:'Upload Mark List',recommended:'Best: Excel · Also PDF/JPG/PNG',description:'Subjects, exam columns, maximum marks, totals, grades and spreadsheet formulas.',icon:FileSpreadsheet},
  {role:'result_book',title:'Result Book / Consolidated Sheet',button:'Upload Result Book',recommended:'Best: Excel · Also PDF/JPG/PNG',description:'Class-level consolidation, annual totals, result status and promotion-related columns.',icon:FileSpreadsheet},
  {role:'progress_card',title:'Progress Card / Report Card',button:'Upload Progress Card',recommended:'Best: PDF/JPG/PNG · Excel also accepted',description:'Printed report layout, student details, academic sections, attendance, remarks and signatures.',icon:FileImage},
  {role:'board_rules',title:'Board Rules / Grading Circular',button:'Upload Board Rules',recommended:'Best: PDF · Also JPG/PNG/Excel',description:'Official grading, pass, promotion, examination or assessment rules used for verification.',icon:FileText}
];

async function authJson<T=any>(path:string,init:RequestInit={}):Promise<T>{
  const session=await supabase.auth.getSession();
  const token=session.data.session?.access_token;
  if(session.error||!token)throw session.error||new Error('Authenticated Clerk session not found.');
  const response=await fetch(path,{...init,headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`,...(init.headers||{})},cache:'no-store'});
  const payload=await response.json().catch(()=>({}));
  if(!response.ok)throw new Error(payload?.error||`Request failed (${response.status}).`);
  return payload as T;
}

const fileToBase64=(file:File)=>new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>{const raw=String(reader.result||'');resolve(raw.includes(',')?raw.slice(raw.indexOf(',')+1):raw)};reader.onerror=()=>reject(reader.error||new Error('File could not be read.'));reader.readAsDataURL(file)});

async function prepareExcel(file:File,documentRole:DocumentRole):Promise<PreparedFile>{
  const buffer=await file.arrayBuffer();
  const workbook=XLSX.read(buffer,{type:'array',cellDates:false,cellFormula:true});
  const blocks:string[]=[];
  for(const sheetName of workbook.SheetNames.slice(0,8)){
    const sheet=workbook.Sheets[sheetName];
    const rows=XLSX.utils.sheet_to_json<any[]>(sheet,{header:1,defval:'',raw:false}).slice(0,120);
    const text=rows.map(row=>row.slice(0,40).map(v=>String(v??'').trim()).join(' | ')).filter(Boolean).join('\n');
    blocks.push(`SHEET: ${sheetName}\n${text}`);
  }
  return {name:file.name,mimeType:file.type||'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',size:file.size,kind:'sheet',documentRole,extractedText:blocks.join('\n\n').slice(0,220000),base64:await fileToBase64(file)};
}

async function prepareFile(file:File,documentRole:DocumentRole):Promise<PreparedFile>{
  const lower=file.name.toLowerCase();
  if(lower.endsWith('.xlsx')||lower.endsWith('.xls'))return prepareExcel(file,documentRole);
  const kind:UploadKind=file.type==='application/pdf'||lower.endsWith('.pdf')?'pdf':'image';
  return {name:file.name,mimeType:file.type||(kind==='pdf'?'application/pdf':lower.endsWith('.png')?'image/png':'image/jpeg'),size:file.size,kind,documentRole,base64:await fileToBase64(file)};
}

const csv=(value:string)=>value.split(/[,\n]/).map(x=>x.trim()).filter(Boolean);
const join=(value:any)=>Array.isArray(value)?value.join(', '):'';
const statusLabel=(row:PackRow)=>{const s=String(row?.definition?.status||(row.active?'approved':'pending_headmaster'));return s==='approved'&&!row.active?'approved (inactive)':s.replaceAll('_',' ')};
const roleLabel=(role?:string)=>DOCUMENTS.find(x=>x.role===role)?.title||'Source document';

export default function CurriculumResultImportStudio(){
  const[files,setFiles]=useState<PreparedFile[]>([]);const[busy,setBusy]=useState('');const[error,setError]=useState('');const[msg,setMsg]=useState('');
  const[proposal,setProposal]=useState<Proposal|null>(null);const[clerkNotes,setClerkNotes]=useState('');const[reuseSourcePackId,setReuseSourcePackId]=useState('');const[packs,setPacks]=useState<PackRow[]>([]);const[loadingPacks,setLoadingPacks]=useState(false);
  const[systemStatus,setSystemStatus]=useState<ResultSystemStatus|null>(null);const[statusLoading,setStatusLoading]=useState(true);const[statusError,setStatusError]=useState('');
  const[coreOptions,setCoreOptions]=useState<AcademicCoreOptions|null>(null);const[coreLoading,setCoreLoading]=useState(true);const[coreError,setCoreError]=useState('');
  const[selectedFamilyId,setSelectedFamilyId]=useState('');const[selectedJurisdictionId,setSelectedJurisdictionId]=useState('');const[platformBoardId,setPlatformBoardId]=useState('');
  const loadStatus=async()=>{setStatusLoading(true);setStatusError('');try{const p=await authJson<ResultSystemStatus>('/api/admin/result-system-status');setSystemStatus(p)}catch(e:any){setSystemStatus(null);setStatusError(e?.message||'Result System status could not be verified.')}finally{setStatusLoading(false)}};
  const loadPacks=async()=>{setLoadingPacks(true);try{const p=await authJson<any>('/api/admin/result-curriculum-packs');setPacks(Array.isArray(p?.packs)?p.packs:[])}catch(e:any){setError(e?.message||'Curriculum packs could not be loaded.')}finally{setLoadingPacks(false)}};
  const loadCore=async()=>{setCoreLoading(true);setCoreError('');try{const p=await authJson<AcademicCoreOptions>('/api/admin/academic-core/options');setCoreOptions(p);const currentBoardId=String(p?.currentProfile?.board_id||'');if(currentBoardId){const board=(p.boards||[]).find(x=>x.id===currentBoardId);if(board){setSelectedFamilyId(board.familyId);setSelectedJurisdictionId(board.jurisdictionId||'');setPlatformBoardId(board.id)}}}catch(e:any){setCoreOptions(null);setCoreError(e?.message||'Platform Academic Core options could not be loaded.')}finally{setCoreLoading(false)}};
  useEffect(()=>{void loadStatus();void loadPacks();void loadCore()},[]);
  const totalBytes=useMemo(()=>files.reduce((n,f)=>n+f.size,0),[files]);
  const selectedFamily=useMemo(()=>coreOptions?.families.find(x=>x.id===selectedFamilyId)||null,[coreOptions,selectedFamilyId]);
  const availableBoards=useMemo(()=>{const rows=(coreOptions?.boards||[]).filter(x=>x.familyId===selectedFamilyId);return selectedFamily?.requiresJurisdiction?rows.filter(x=>x.jurisdictionId===selectedJurisdictionId):rows},[coreOptions,selectedFamilyId,selectedJurisdictionId,selectedFamily]);
  const selectedBoard=useMemo(()=>coreOptions?.boards.find(x=>x.id===platformBoardId)||null,[coreOptions,platformBoardId]);
  const profileLocked=Boolean(coreOptions?.currentProfile?.is_locked);
  useEffect(()=>{if(profileLocked)return;if(!selectedFamilyId){setPlatformBoardId('');setSelectedJurisdictionId('');return}if(selectedFamily?.requiresJurisdiction){if(!selectedJurisdictionId){setPlatformBoardId('');return}if(availableBoards.length===1)setPlatformBoardId(availableBoards[0].id);else if(!availableBoards.some(x=>x.id===platformBoardId))setPlatformBoardId('')}else{setSelectedJurisdictionId('');if(availableBoards.length===1)setPlatformBoardId(availableBoards[0].id);else if(!availableBoards.some(x=>x.id===platformBoardId))setPlatformBoardId('')}},[selectedFamilyId,selectedJurisdictionId,availableBoards,selectedFamily,profileLocked]);
  const onFiles=async(documentRole:DocumentRole,list:FileList|null)=>{if(!list)return;setError('');setMsg('');try{const selected=[...Array.from(list)];if(files.length+selected.length>MAX_FILES)throw new Error(`Upload up to ${MAX_FILES} files across all four document sections.`);const unsupported=selected.find(f=>!SUPPORTED.has(f.type)&&!/[.](xlsx|xls|pdf|jpg|jpeg|png)$/i.test(f.name));if(unsupported)throw new Error(`${unsupported.name}: only Excel, PDF, JPG and PNG are supported.`);if(totalBytes+selected.reduce((n,f)=>n+f.size,0)>MAX_TOTAL_BYTES)throw new Error('Keep the combined upload below 7.5 MB for one analysis. Large scans can be split into separate pages.');setBusy(`files:${documentRole}`);const prepared:PreparedFile[]=[];for(const file of selected)prepared.push(await prepareFile(file,documentRole));setFiles(prev=>[...prev,...prepared]);if(!reuseSourcePackId)setProposal(null);else setMsg('Replacement evidence added to the returned draft. Unreplaced source-document sections will be retained for Headmaster verification.')}catch(e:any){setError(e?.message||'Files could not be prepared.')}finally{setBusy('')}};
  const analyze=async()=>{if(!files.length)return;if(!platformBoardId){setError('Select Curriculum / Board first.');return}setBusy('analyze');setError('');setMsg('');try{const payload=await authJson<any>('/api/clerk/result-curriculum-import/analyze',{method:'POST',body:JSON.stringify({files,platformBoardId})});setProposal({...emptyProposal,...(payload?.proposal||{})});setMsg('AI draft prepared inside the locked Board/State scope. Verify every academic rule before sending it to the Headmaster.')}catch(e:any){setError(e?.message||'Result system analysis failed.')}finally{setBusy('')}};
  const change=(key:keyof Proposal,value:any)=>setProposal(prev=>prev?{...prev,[key]:value}:prev);
  const submit=async()=>{if(!proposal)return;setBusy('submit');setError('');setMsg('');try{if(!platformBoardId)throw new Error('Select Curriculum / Board first.');if(!proposal.board.trim()&&!proposal.curriculum.trim())throw new Error('Board / Curriculum name is required before Headmaster review.');await authJson('/api/clerk/result-curriculum-packs',{method:'POST',body:JSON.stringify({proposal,clerkNotes,files,reuseSourcePackId,platformBoardId})});setMsg('Curriculum Result Pack sent to Headmaster for final verification.');setProposal(null);setFiles([]);setClerkNotes('');setReuseSourcePackId('');await loadPacks();await loadStatus();await loadCore()}catch(e:any){setError(e?.message||'Curriculum pack could not be submitted.')}finally{setBusy('')}};

  if(statusLoading)return <div className="grid min-h-56 place-items-center rounded-2xl border border-slate-200 bg-white"><div className="text-center"><Loader2 className="mx-auto h-7 w-7 animate-spin text-cyan-700"/><div className="mt-3 text-xs font-black text-slate-600">Checking school Result System…</div></div></div>;
  if(statusError||!systemStatus)return <div className="rounded-2xl border border-amber-200 bg-amber-50 p-5 text-left"><div className="flex items-start gap-3"><LockKeyhole className="mt-0.5 h-5 w-5 text-amber-700"/><div className="min-w-0 flex-1"><h2 className="font-black text-amber-950">Import is locked until Result System status is verified</h2><p className="mt-1 text-xs leading-5 text-amber-900">{statusError||'Secure status verification is unavailable.'} Classtago fails closed so an existing school Result System cannot be replaced accidentally.</p><button type="button" onClick={()=>void loadStatus()} className="mt-3 inline-flex min-h-10 items-center gap-2 rounded-xl bg-amber-900 px-4 text-xs font-black text-white"><RefreshCw className="h-4 w-4"/>Retry verification</button></div></div></div>;
  if(systemStatus.configured)return <div className="space-y-4 text-left"><section className="rounded-3xl border border-emerald-200 bg-emerald-50 p-6"><div className="flex items-start gap-4"><div className="grid h-12 w-12 shrink-0 place-items-center rounded-2xl bg-emerald-700 text-white"><ShieldCheck className="h-6 w-6"/></div><div><div className="text-[10px] font-black uppercase tracking-[.18em] text-emerald-700">Result System protected</div><h1 className="mt-1 text-2xl font-black text-slate-950">This school already has an active Result System</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-slate-700">{systemStatus.activeSystemName||'The current school Result workflow'} remains the canonical system. <b>Import Existing Result System is only for a new or unconfigured school</b>, so no upload or curriculum-activation controls are shown here.</p><div className="mt-4 rounded-xl border border-emerald-200 bg-white p-3 text-xs font-bold text-emerald-900">Continue using Master Mark List, Master Result Book and Master Progress Card. Any future curriculum change must use a separate protected Result System Migration workflow and must not rewrite historical results.</div></div></div></section></div>;

  return <div className="space-y-5 text-left">
    <section className="rounded-3xl border border-slate-800 bg-slate-950 p-6 text-white shadow-xl">
      <div className="flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between"><div><div className="flex items-center gap-2 text-[10px] font-black uppercase tracking-[.2em] text-cyan-300"><Sparkles className="h-4 w-4"/>Dynamic Result Engine · New School Onboarding</div><h1 className="mt-2 text-2xl font-black">Import Existing Result System</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-slate-300">This school has no operational Result System yet. Upload each source under its correct document type; Classtago prepares a proposed curriculum schema, Clerk verifies it and Headmaster gives final approval.</p></div><div className="rounded-2xl border border-white/10 bg-white/5 px-4 py-3 text-xs"><div className="font-black text-emerald-300">Onboarding-only protection</div><div className="mt-1 text-slate-300">Once a Result System becomes active, this import feature is removed from the normal Clerk workflow.</div></div></div>
    </section>

    {error&&<div className="rounded-2xl border border-rose-200 bg-rose-50 p-4 text-sm font-bold text-rose-700">{error}</div>}
    {msg&&<div className="rounded-2xl border border-emerald-200 bg-emerald-50 p-4 text-sm font-bold text-emerald-800">{msg}</div>}

    <section className="rounded-2xl border border-indigo-200 bg-white p-5 shadow-sm">
      <div className="flex flex-wrap items-start justify-between gap-3"><div><div className="text-[10px] font-black uppercase tracking-[.18em] text-indigo-700">Step 1 · Platform Academic Core</div><h2 className="mt-1 font-black text-slate-950">Select Curriculum / Board</h2><p className="mt-1 max-w-3xl text-xs leading-5 text-slate-500">This selection is locked before AI analysis. State Board opens the India State/UT selector; another curriculum cannot leak into this school's rules.</p></div>{profileLocked&&<span className="rounded-full bg-emerald-100 px-3 py-1 text-[10px] font-black text-emerald-800">School Academic Profile Locked</span>}</div>
      {coreLoading?<div className="mt-4 flex items-center gap-2 rounded-xl bg-slate-50 p-4 text-xs font-bold text-slate-600"><Loader2 className="h-4 w-4 animate-spin"/>Loading India board registry…</div>:coreError||!coreOptions?<div className="mt-4 rounded-xl border border-amber-200 bg-amber-50 p-4 text-xs font-bold text-amber-900">{coreError||'Academic Core options are unavailable.'}<button type="button" onClick={()=>void loadCore()} className="ml-3 rounded-lg border border-amber-300 bg-white px-3 py-2">Retry</button></div>:<>
        <div className="mt-4 grid gap-3 md:grid-cols-2 xl:grid-cols-3">
          <label className="text-xs font-black text-slate-700">Curriculum / Board Family<select disabled={profileLocked} value={selectedFamilyId} onChange={e=>{setSelectedFamilyId(e.target.value);setSelectedJurisdictionId('');setPlatformBoardId('');setProposal(null)}} className="mt-1 min-h-11 w-full rounded-xl border border-slate-300 bg-white px-3 text-sm font-semibold disabled:bg-slate-100"><option value="">Select curriculum</option>{coreOptions.families.map(row=><option key={row.id} value={row.id}>{row.familyName}</option>)}</select></label>
          {selectedFamily?.requiresJurisdiction&&<label className="text-xs font-black text-slate-700">State / Union Territory<select disabled={profileLocked} value={selectedJurisdictionId} onChange={e=>{setSelectedJurisdictionId(e.target.value);setPlatformBoardId('');setProposal(null)}} className="mt-1 min-h-11 w-full rounded-xl border border-slate-300 bg-white px-3 text-sm font-semibold disabled:bg-slate-100"><option value="">Select State / UT</option>{coreOptions.jurisdictions.map(row=><option key={row.id} value={row.id}>{row.name}</option>)}</select></label>}
          {selectedFamilyId&&(!selectedFamily?.requiresJurisdiction||selectedJurisdictionId)&&<label className="text-xs font-black text-slate-700">Applicable Board<select disabled={profileLocked} value={platformBoardId} onChange={e=>{setPlatformBoardId(e.target.value);setProposal(null)}} className="mt-1 min-h-11 w-full rounded-xl border border-slate-300 bg-white px-3 text-sm font-semibold disabled:bg-slate-100"><option value="">Select board</option>{availableBoards.map(row=><option key={row.id} value={row.id}>{row.boardName}</option>)}</select></label>}
        </div>
        {selectedFamilyId&&availableBoards.length===0&&(!selectedFamily?.requiresJurisdiction||selectedJurisdictionId)&&<div className="mt-4 rounded-xl border border-amber-200 bg-amber-50 p-3 text-xs font-bold text-amber-900">No board route is registered for this selection yet. Super Admin must add/activate it in Academic Core.</div>}
        {selectedBoard&&<div className={`mt-4 rounded-xl border p-4 ${selectedBoard.rulesReady?'border-emerald-200 bg-emerald-50':'border-amber-200 bg-amber-50'}`}><div className="flex flex-wrap items-center justify-between gap-2"><div><div className="text-xs font-black text-slate-950">{selectedBoard.boardName}</div><div className="mt-1 text-[10px] text-slate-600">{selectedBoard.jurisdictionName||'National / International'} · {selectedBoard.boardCode}{selectedBoard.rulesetVersion?` · Rules ${selectedBoard.rulesetVersion}`:''}</div></div><span className={`rounded-full px-3 py-1 text-[10px] font-black ${selectedBoard.rulesReady?'bg-emerald-700 text-white':'bg-amber-700 text-white'}`}>{selectedBoard.rulesReady?'Verified Rules Ready':'Rules Verification Pending'}</span></div><p className="mt-2 text-[11px] leading-5 text-slate-700">{selectedBoard.rulesReady?'Headmaster can activate this curriculum after source verification.':'Clerk may prepare the school sample pack, but Headmaster activation remains blocked until Super Admin publishes the verified Board Rules Pack.'}</p></div>}
      </>}
    </section>

    <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm">
      <div><h2 className="font-black text-slate-950">2. Upload source documents by type</h2><p className="mt-1 text-xs text-slate-500">All four are useful, but not mandatory. Upload what the school actually has. Accepted: Excel, PDF, JPG and PNG · up to {MAX_FILES} files · 7.5 MB combined.</p></div>
      {reuseSourcePackId&&<div className="mt-4 rounded-xl border border-cyan-200 bg-cyan-50 p-3 text-xs font-bold text-cyan-900">This is a returned draft. Original private source documents are retained. Uploading a replacement in one section replaces that document role while other retained evidence remains available to Headmaster.</div>}
      <div className="mt-5 grid gap-4 lg:grid-cols-2">{DOCUMENTS.map(doc=>{const DocIcon=doc.icon;const selected=files.map((f,index)=>({f,index})).filter(x=>x.f.documentRole===doc.role);return <article key={doc.role} className="rounded-2xl border border-slate-200 bg-slate-50/70 p-4"><div className="flex items-start gap-3"><div className="grid h-11 w-11 shrink-0 place-items-center rounded-xl bg-white text-cyan-800 shadow-sm"><DocIcon className="h-5 w-5"/></div><div className="min-w-0 flex-1"><h3 className="text-sm font-black text-slate-950">{doc.title}</h3><p className="mt-1 text-[10px] font-bold text-cyan-800">{doc.recommended}</p><p className="mt-1 text-[11px] leading-5 text-slate-500">{doc.description}</p></div></div><label className="mt-4 inline-flex min-h-11 cursor-pointer items-center gap-2 rounded-xl bg-cyan-700 px-4 py-2.5 text-xs font-black text-white"><UploadCloud className="h-4 w-4"/>{busy===`files:${doc.role}`?'Preparing…':doc.button}<input type="file" multiple accept=".xlsx,.xls,.pdf,.jpg,.jpeg,.png" className="hidden" disabled={!!busy} onChange={e=>{void onFiles(doc.role,e.target.files);e.currentTarget.value=''}}/></label><div className="mt-3 space-y-2">{selected.map(({f,index})=><div key={`${f.name}:${index}`} className="flex items-center gap-2 rounded-xl border border-slate-200 bg-white p-2.5"><div className="grid h-8 w-8 shrink-0 place-items-center rounded-lg bg-slate-100 text-slate-700">{f.kind==='sheet'?<FileSpreadsheet className="h-4 w-4"/>:f.kind==='pdf'?<FileText className="h-4 w-4"/>:<FileImage className="h-4 w-4"/>}</div><div className="min-w-0 flex-1"><div className="truncate text-[11px] font-black text-slate-900">{f.name}</div><div className="text-[9px] text-slate-500">{(f.size/1024/1024).toFixed(2)} MB</div></div><button type="button" onClick={()=>{setFiles(v=>v.filter((_,x)=>x!==index));if(!reuseSourcePackId)setProposal(null)}} className="grid h-8 w-8 place-items-center rounded-lg border text-slate-500" aria-label={`Remove ${f.name}`}><X className="h-3.5 w-3.5"/></button></div>)}{!selected.length&&<div className="rounded-xl border border-dashed border-slate-300 bg-white/70 px-3 py-3 text-[10px] text-slate-400">No {doc.title} selected yet.</div>}</div></article>})}</div>
      <div className="mt-5 flex flex-wrap items-center justify-between gap-3 rounded-xl border border-slate-200 bg-slate-50 p-4"><div><div className="text-[10px] font-black uppercase tracking-wide text-slate-500">Combined prepared size</div><div className="mt-1 text-sm font-black text-slate-900">{(totalBytes/1024/1024).toFixed(2)} MB · {files.length}/{MAX_FILES} files</div></div><button type="button" disabled={!files.length||!platformBoardId||!!busy} onClick={()=>void analyze()} className="inline-flex min-h-11 items-center gap-2 rounded-xl bg-violet-700 px-5 py-2.5 text-xs font-black text-white disabled:opacity-40">{busy==='analyze'?<Loader2 className="h-4 w-4 animate-spin"/>:<BrainCircuit className="h-4 w-4"/>}{busy==='analyze'?'Analysing Result System…':'Analyse Complete Result System'}</button></div>
    </section>

    {proposal&&<section className="space-y-4 rounded-2xl border border-violet-200 bg-white p-5 shadow-sm">
      <div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="font-black text-slate-950">3. Verify detected curriculum rules</h2><p className="mt-1 text-xs text-slate-500">AI is a drafting assistant only. Marks, pass and promotion rules require human verification.</p></div><span className="rounded-full bg-violet-50 px-3 py-1 text-[10px] font-black text-violet-700">Confidence {Math.round(Number(proposal.confidence||0)*100)}%</span></div>
      <div className="grid gap-3 md:grid-cols-2 xl:grid-cols-4"><LockedField label="Country" value={proposal.country}/><LockedField label="State / Region" value={proposal.state||'Not applicable'}/><LockedField label="Board" value={proposal.board}/><LockedField label="Curriculum / Scheme" value={proposal.curriculum}/></div>
      <div className="grid gap-3 md:grid-cols-2"><ListField label="Mediums" value={join(proposal.mediums)} onChange={v=>change('mediums',csv(v))}/><ListField label="Classes / Standards" value={join(proposal.classes)} onChange={v=>change('classes',csv(v))}/><ListField label="Exam / Term Structure" value={join(proposal.examStructure)} onChange={v=>change('examStructure',csv(v))}/><ListField label="Marks Components" value={join(proposal.markComponents)} onChange={v=>change('markComponents',csv(v))}/><ListField label="Grading Rules" value={join(proposal.gradingRules)} onChange={v=>change('gradingRules',csv(v))}/><ListField label="Pass Rules" value={join(proposal.passRules)} onChange={v=>change('passRules',csv(v))}/><ListField label="Promotion Rules" value={join(proposal.promotionRules)} onChange={v=>change('promotionRules',csv(v))}/><ListField label="Detected Subjects" value={join(proposal.detectedSubjects)} onChange={v=>change('detectedSubjects',csv(v))}/><ListField label="Attendance Fields" value={join(proposal.attendanceFields)} onChange={v=>change('attendanceFields',csv(v))}/><ListField label="Required Signatures" value={join(proposal.signatures)} onChange={v=>change('signatures',csv(v))}/></div>
      <div className="grid gap-3 lg:grid-cols-3"><PreviewCard title="Master Mark List" items={proposal.markListColumns}/><PreviewCard title="Master Result Book" items={proposal.resultBookSections}/><PreviewCard title="Progress Card" items={proposal.progressCardSections}/></div>
      {!!proposal.warnings?.length&&<div className="rounded-xl border border-amber-200 bg-amber-50 p-4"><div className="flex items-center gap-2 text-xs font-black text-amber-900"><AlertTriangle className="h-4 w-4"/>Must verify</div><ul className="mt-2 list-disc space-y-1 pl-5 text-xs text-amber-900">{proposal.warnings.map((x,i)=><li key={i}>{x}</li>)}</ul></div>}{!!proposal.evidence?.length&&<div className="rounded-xl border border-slate-200 bg-slate-50 p-4"><div className="text-xs font-black text-slate-900">Detected evidence</div><ul className="mt-2 list-disc space-y-1 pl-5 text-xs text-slate-700">{proposal.evidence.map((x,i)=><li key={i}>{x}</li>)}</ul></div>}
      <label className="block text-xs font-black text-slate-700">Clerk verification notes<textarea value={clerkNotes} onChange={e=>setClerkNotes(e.target.value)} placeholder="Mention the circular/page/Excel sheet used to verify marks, grading and promotion rules…" className="mt-1 min-h-24 w-full rounded-xl border border-slate-300 p-3 text-sm font-normal"/></label>
      <div className="flex flex-wrap items-center justify-between gap-3 rounded-xl border border-cyan-200 bg-cyan-50 p-4"><div className="max-w-2xl text-xs leading-5 text-cyan-950"><b>Approval rule:</b> Headmaster approval activates this pack only because this school currently has no operational Result System. Once activated, normal onboarding import is locked.</div><button disabled={!!busy} onClick={()=>void submit()} className="inline-flex min-h-11 items-center gap-2 rounded-xl bg-slate-950 px-5 py-2.5 text-xs font-black text-white disabled:opacity-40">{busy==='submit'?<Loader2 className="h-4 w-4 animate-spin"/>:<Send className="h-4 w-4"/>}{busy==='submit'?'Sending…':'Send to Headmaster'}</button></div>
    </section>}

    <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm">
      <div className="flex items-center justify-between gap-3"><div><h2 className="font-black text-slate-950">Curriculum Pack History</h2><p className="mt-1 text-xs text-slate-500">School-scoped onboarding proposals and approvals. Original source files remain private for Headmaster verification.</p></div><button onClick={()=>void loadPacks()} disabled={loadingPacks} className="inline-flex min-h-10 items-center gap-2 rounded-xl border px-3 text-xs font-black"><RefreshCw className={`h-4 w-4 ${loadingPacks?'animate-spin':''}`}/>Refresh</button></div>
      <div className="mt-4 overflow-x-auto rounded-xl border"><table className="w-full min-w-[900px] text-xs"><thead className="bg-slate-50 text-[10px] uppercase text-slate-500"><tr><th className="p-3 text-left">Curriculum</th><th className="p-3 text-left">Board / State</th><th className="p-3 text-left">Status</th><th className="p-3 text-left">Source Types</th><th className="p-3 text-left">Headmaster Note</th><th className="p-3 text-left">Updated</th><th className="p-3 text-left">Action</th></tr></thead><tbody className="divide-y">{packs.map(row=><tr key={row.id}><td className="p-3 font-black">{row.name}</td><td className="p-3">{row.definition?.proposal?.board||'—'}{row.definition?.proposal?.state?` · ${row.definition.proposal.state}`:''}</td><td className="p-3"><span className={`rounded-full px-2.5 py-1 text-[9px] font-black uppercase ${row.active?'bg-emerald-100 text-emerald-700':String(row.definition?.status)==='returned'?'bg-rose-100 text-rose-700':'bg-amber-100 text-amber-800'}`}>{statusLabel(row)}</span></td><td className="max-w-[260px] p-3 text-slate-600">{Array.isArray(row.definition?.sourceFiles)&&row.definition.sourceFiles.length?Array.from(new Set(row.definition.sourceFiles.map((f:any)=>roleLabel(f.documentRole)))).join(' · '):'—'}</td><td className="max-w-[260px] p-3 text-slate-600">{row.definition?.approval?.note||'—'}</td><td className="p-3 text-slate-500">{row.updated_at?new Date(row.updated_at).toLocaleString():'—'}</td><td className="p-3">{String(row.definition?.status)==='returned'?<button type="button" onClick={()=>{setProposal({...emptyProposal,...(row.definition?.proposal||{})});setClerkNotes(row.definition?.clerkNotes||'');setFiles([]);setReuseSourcePackId(row.id);if(row.definition?.academicCoreSelection?.id){setSelectedFamilyId(String(row.definition.academicCoreSelection.familyId||''));setSelectedJurisdictionId(String(row.definition.academicCoreSelection.jurisdictionId||''));setPlatformBoardId(String(row.definition.academicCoreSelection.id||''))}setMsg('Returned pack reopened as an editable draft. Original private source documents will be reused unless you upload replacements in a matching document section.');window.scrollTo({top:0,behavior:'smooth'})}} className="rounded-lg border border-rose-200 bg-rose-50 px-3 py-2 text-[10px] font-black text-rose-700">Reopen Draft</button>:<span className="text-[10px] text-slate-400">—</span>}</td></tr>)}{!packs.length&&!loadingPacks&&<tr><td colSpan={7} className="p-8 text-center text-slate-400">No imported curriculum pack yet.</td></tr>}</tbody></table></div>
    </section>
  </div>;
}

function LockedField({label,value}:{label:string;value:string}){return <label className="text-xs font-black text-slate-700">{label}<input readOnly value={value||''} className="mt-1 w-full rounded-xl border border-slate-200 bg-slate-100 px-3 py-2.5 text-sm font-bold text-slate-700"/></label>}
function Field({label,value,onChange}:{label:string;value:string;onChange:(v:string)=>void}){return <label className="text-xs font-black text-slate-700">{label}<input value={value||''} onChange={e=>onChange(e.target.value)} className="mt-1 w-full rounded-xl border border-slate-300 px-3 py-2.5 text-sm font-normal"/></label>}
function ListField({label,value,onChange}:{label:string;value:string;onChange:(v:string)=>void}){return <label className="text-xs font-black text-slate-700">{label}<textarea value={value||''} onChange={e=>onChange(e.target.value)} className="mt-1 min-h-20 w-full rounded-xl border border-slate-300 p-3 text-sm font-normal" placeholder="Comma separated"/></label>}
function PreviewCard({title,items}:{title:string;items:string[]}){return <div className="rounded-xl border border-slate-200 bg-slate-50 p-4"><div className="flex items-center gap-2 text-xs font-black text-slate-900"><CheckCircle2 className="h-4 w-4 text-emerald-600"/>{title}</div><div className="mt-3 space-y-1 text-xs text-slate-600">{(items||[]).slice(0,16).map((x,i)=><div key={i} className="rounded-lg bg-white px-2.5 py-2">{x}</div>)}{!items?.length&&<div className="text-slate-400">No structure detected yet.</div>}</div></div>}
