import React, { useEffect, useMemo, useState } from 'react';
import { CalendarDays, Clock, FileCheck2, FileText, Loader2, Edit2, Plus, RefreshCw, ShieldCheck, XCircle } from 'lucide-react';
import type { Language, User } from '../types';
import HeadmasterQuestionPaperReview from './HeadmasterQuestionPaperReview';
import { requestActionConfirm } from '../lib/actionConfirm';
import {
  loadHeadmasterExamSchedule,
  saveHeadmasterExamSchedule,
  setHeadmasterExamScheduleStatus,
  type ExamScheduleRow
} from '../services/headmasterAcademicFinalizationService';

interface Props { lang: Language; user: User; activeFeatureId?: string | null; }
const examOptions = [
  ['first_unit_test','First Unit Test'],['first_term_examination','First Term Examination'],
  ['second_unit_test','Second Unit Test'],['second_term_examination','Second Term Examination']
] as const;
const emptyForm = { academicYearId:'', examKey:'first_unit_test', examName:'First Unit Test', term:'first_term', classId:'', divisionId:'', subjectId:'', examDate:'', startTime:'', endTime:'', durationMinutes:'', totalMarks:'', room:'', instructions:'' };

export default function HeadmasterExamControlWorkspace({ lang, user, activeFeatureId }: Props) {
  const initial = activeFeatureId === 'question-paper-review' ? 'papers' : 'schedule';
  const [tab,setTab]=useState<'schedule'|'papers'>(initial);
  const [data,setData]=useState<any>({rows:[],academicYears:[],classes:[],divisions:[],subjects:[]});
  const [loading,setLoading]=useState(true); const [error,setError]=useState(''); const [busy,setBusy]=useState('');
  const [editing,setEditing]=useState<ExamScheduleRow|null>(null); const [form,setForm]=useState<any>(emptyForm);

  useEffect(()=>{ if(activeFeatureId==='question-paper-review')setTab('papers'); else if(activeFeatureId==='exam-schedule-control')setTab('schedule'); },[activeFeatureId]);
  const load=async()=>{setLoading(true);setError('');try{const schedule=await loadHeadmasterExamSchedule();setData(schedule);if(!form.academicYearId){const active=(schedule.academicYears||[]).find((r:any)=>r.isActive)||schedule.academicYears?.[0];if(active)setForm((v:any)=>({...v,academicYearId:active.id}));}}catch(e:any){setError(e?.message||'Exam Control could not be loaded.');}finally{setLoading(false)}};
  useEffect(()=>{void load()},[]);

  const classes=useMemo(()=>data.classes.filter((r:any)=>!form.academicYearId||!r.academicYearId||String(r.academicYearId)===form.academicYearId),[data.classes,form.academicYearId]);
  const divisions=useMemo(()=>data.divisions.filter((r:any)=>!form.classId||String(r.classId||'')===form.classId),[data.divisions,form.classId]);
  const reset=()=>{setEditing(null);setForm((v:any)=>({...emptyForm,academicYearId:v.academicYearId||data.academicYears?.find((r:any)=>r.isActive)?.id||''}));};
  const edit=(row:ExamScheduleRow)=>{setEditing(row);setForm({academicYearId:row.academicYearId,examKey:row.examKey,examName:row.examName,term:row.term||'',classId:row.classId,divisionId:row.divisionId||'',subjectId:row.subjectId,examDate:row.examDate,startTime:row.startTime||'',endTime:row.endTime||'',durationMinutes:row.durationMinutes??'',totalMarks:row.totalMarks??'',room:row.room||'',instructions:row.instructions||''});setTab('schedule');};
  const save=async()=>{setBusy('save');setError('');try{if(!form.academicYearId||!form.classId||!form.subjectId||!form.examDate)throw new Error('Academic Year, Class, Subject and Exam Date are required.');await saveHeadmasterExamSchedule({...form,divisionId:form.divisionId||null,durationMinutes:form.durationMinutes===''?null:Number(form.durationMinutes),totalMarks:form.totalMarks===''?null:Number(form.totalMarks)},editing?.id);reset();await load();}catch(e:any){setError(e?.message||'Exam Schedule could not be saved.');}finally{setBusy('')}};
  const status=async(row:ExamScheduleRow,action:'publish'|'cancel'|'draft')=>{const ok=await requestActionConfirm({title:`${action==='publish'?'Publish':action==='cancel'?'Cancel':'Move to Draft'} exam entry?`,message:`${row.examName} · ${row.className} · ${row.subjectName} · ${row.examDate}`,confirmLabel:action==='publish'?'Publish':action==='cancel'?'Cancel Entry':'Move to Draft',tone:action==='cancel'?'danger':'warning'});if(!ok)return;setBusy(row.id);try{await setHeadmasterExamScheduleStatus(row.id,action);await load();}catch(e:any){setError(e?.message||'Exam status could not be changed.');}finally{setBusy('')}};
  const counts={draft:data.rows.filter((r:any)=>r.status==='draft').length,published:data.rows.filter((r:any)=>r.status==='published').length};
  return <div className="space-y-5 text-left">
    <div className="rounded-3xl border border-slate-800 bg-slate-950 p-6 text-white shadow-xl"><div className="flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between"><div><div className="flex items-center gap-2 text-xs font-black uppercase tracking-[.18em] text-cyan-200"><ShieldCheck className="h-4 w-4"/> Headmaster Final Authority</div><h1 className="mt-2 text-2xl font-black">Exam & Question Paper Control</h1><p className="mt-2 max-w-3xl text-sm text-slate-300">Official Exam Schedule and Teacher paper review from one cloud workspace. Combined Subject Groups are configured separately in Academic Setup; Subject Teachers own their section marks and chapters.</p></div><button onClick={()=>void load()} className="inline-flex items-center gap-2 rounded-xl border border-white/15 bg-white/10 px-4 py-2 text-xs font-black"><RefreshCw className={`h-4 w-4 ${loading?'animate-spin':''}`}/>Refresh</button></div></div>
    <div className="grid gap-3 sm:grid-cols-2"><Stat label="Draft Exam Rows" value={counts.draft}/><Stat label="Published Exam Rows" value={counts.published}/></div>
    <div className="flex flex-wrap gap-2 rounded-2xl border border-slate-200 bg-white p-2">{([['schedule','Exam Schedule'],['papers','Teacher Question Papers']] as const).map(([key,label])=><button key={key} onClick={()=>setTab(key)} className={`rounded-xl px-4 py-2.5 text-xs font-black ${tab===key?'bg-slate-950 text-white':'text-slate-600 hover:bg-slate-50'}`}>{label}</button>)}</div>
    {error&&<div className="rounded-2xl border border-rose-200 bg-rose-50 p-4 text-sm font-bold text-rose-700">{error}</div>}
    {loading?<div className="flex min-h-52 items-center justify-center rounded-2xl border bg-white"><Loader2 className="h-7 w-7 animate-spin"/></div>:tab==='papers'?<HeadmasterQuestionPaperReview lang={lang} user={user}/>:<div className="space-y-5">
      <div className="grid gap-5 xl:grid-cols-[390px_1fr]"><div className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-center justify-between"><h3 className="font-black text-slate-900">{editing?'Edit Exam Row':'Add Exam Row'}</h3>{editing&&<button onClick={reset} className="text-xs font-black text-slate-500">Cancel edit</button>}</div><div className="mt-4 grid gap-3">
        <Select label="Academic Year" value={form.academicYearId} onChange={(v)=>setForm((x:any)=>({...x,academicYearId:v,classId:'',divisionId:''}))} options={data.academicYears}/>
        <label className="text-xs font-bold text-slate-600">Examination<select value={form.examKey} onChange={e=>{const found=examOptions.find(x=>x[0]===e.target.value);setForm((x:any)=>({...x,examKey:e.target.value,examName:found?.[1]||e.target.value,term:e.target.value.startsWith('second_')?'second_term':'first_term'}));}} className="mt-1 w-full rounded-xl border border-slate-200 px-3 py-2.5">{examOptions.map(([k,l])=><option key={k} value={k}>{l}</option>)}</select></label>
        <Select label="Class" value={form.classId} onChange={(v)=>setForm((x:any)=>({...x,classId:v,divisionId:''}))} options={classes}/><Select label="Division (optional)" value={form.divisionId} onChange={(v)=>setForm((x:any)=>({...x,divisionId:v}))} options={[{id:'',name:'All / Class-wide'},...divisions]}/><Select label="Subject" value={form.subjectId} onChange={(v)=>setForm((x:any)=>({...x,subjectId:v}))} options={data.subjects}/>
        <label className="text-xs font-bold text-slate-600">Exam Date<input type="date" value={form.examDate} onChange={e=>setForm((x:any)=>({...x,examDate:e.target.value}))} className="mt-1 w-full rounded-xl border border-slate-200 px-3 py-2.5"/></label>
        <div className="grid grid-cols-2 gap-2"><Field label="Start" type="time" value={form.startTime} onChange={(v)=>setForm((x:any)=>({...x,startTime:v}))}/><Field label="End" type="time" value={form.endTime} onChange={(v)=>setForm((x:any)=>({...x,endTime:v}))}/></div><div className="grid grid-cols-2 gap-2"><Field label="Duration (min)" type="number" value={form.durationMinutes} onChange={(v)=>setForm((x:any)=>({...x,durationMinutes:v}))}/><Field label="Total Marks" type="number" value={form.totalMarks} onChange={(v)=>setForm((x:any)=>({...x,totalMarks:v}))}/></div><Field label="Room" value={form.room} onChange={(v)=>setForm((x:any)=>({...x,room:v}))}/><label className="text-xs font-bold text-slate-600">Instructions<textarea rows={3} value={form.instructions} onChange={e=>setForm((x:any)=>({...x,instructions:e.target.value}))} className="mt-1 w-full rounded-xl border border-slate-200 px-3 py-2.5"/></label><button onClick={()=>void save()} disabled={busy==='save'} className="inline-flex items-center justify-center gap-2 rounded-xl bg-cyan-600 px-4 py-3 text-xs font-black text-white disabled:opacity-50"><Plus className="h-4 w-4"/>{busy==='save'?'Saving…':editing?'Save Changes':'Add Draft Row'}</button>
      </div></div><div className="space-y-3">{data.rows.length?data.rows.map((row:ExamScheduleRow)=><div key={row.id} className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><div className="flex flex-col gap-4 xl:flex-row xl:items-center xl:justify-between"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><Badge value={row.status}/><span className="text-[10px] font-black uppercase text-slate-400">{row.examName}</span></div><div className="mt-2 font-black text-slate-900">{row.className}{row.divisionName?` / ${row.divisionName}`:''} · {row.subjectName}</div><div className="mt-1 flex flex-wrap gap-3 text-xs text-slate-500"><span className="inline-flex items-center gap-1"><CalendarDays className="h-3.5 w-3.5"/>{row.examDate}</span><span className="inline-flex items-center gap-1"><Clock className="h-3.5 w-3.5"/>{row.startTime||'—'}{row.endTime?` – ${row.endTime}`:''}</span>{row.totalMarks!=null&&<span>{row.totalMarks} marks</span>}</div></div><div className="flex flex-wrap gap-2"><button onClick={()=>edit(row)} disabled={row.status==='published'} className="inline-flex items-center gap-1 rounded-lg border px-3 py-2 text-[10px] font-black disabled:opacity-40"><Edit2 className="h-3.5 w-3.5"/>Edit</button>{row.status!=='published'&&<button onClick={()=>void status(row,'publish')} className="inline-flex items-center gap-1 rounded-lg bg-emerald-600 px-3 py-2 text-[10px] font-black text-white"><FileCheck2 className="h-3.5 w-3.5"/>Publish</button>}{row.status==='published'&&<button onClick={()=>void status(row,'cancel')} className="inline-flex items-center gap-1 rounded-lg bg-rose-600 px-3 py-2 text-[10px] font-black text-white"><XCircle className="h-3.5 w-3.5"/>Cancel</button>}{row.status==='cancelled'&&<button onClick={()=>void status(row,'draft')} className="rounded-lg border px-3 py-2 text-[10px] font-black">Restore Draft</button>}</div></div></div>):<Empty text="No official Exam Schedule rows yet. Add the first draft from the form."/>}</div></div></div>}
  </div>;
}
function Stat({label,value}:{label:string;value:number|string}){return <div className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><div className="text-[10px] font-black uppercase tracking-wider text-slate-400">{label}</div><div className="mt-1 text-2xl font-black text-slate-950">{value}</div></div>}
function Badge({value}:{value:string}){const v=String(value||'').toLowerCase();const cls=v.includes('final')||v==='published'||v==='approved'?'bg-emerald-100 text-emerald-700':v==='cancelled'||v==='returned'?'bg-rose-100 text-rose-700':'bg-amber-100 text-amber-700';return <span className={`rounded-full px-2.5 py-1 text-[9px] font-black uppercase ${cls}`}>{String(value||'—').replaceAll('_',' ')}</span>}
function Empty({text}:{text:string}){return <div className="rounded-2xl border border-dashed border-slate-300 bg-white p-10 text-center text-sm font-bold text-slate-500">{text}</div>}
function Select({label,value,onChange,options}:{label:string;value:string;onChange:(v:string)=>void;options:any[]}){return <label className="text-xs font-bold text-slate-600">{label}<select value={value} onChange={e=>onChange(e.target.value)} className="mt-1 w-full rounded-xl border border-slate-200 px-3 py-2.5"><option value="">Select…</option>{options.map((o:any)=><option key={o.id} value={o.id}>{o.name}</option>)}</select></label>}
function Field({label,value,onChange,type='text'}:{label:string;value:any;onChange:(v:string)=>void;type?:string}){return <label className="text-xs font-bold text-slate-600">{label}<input type={type} value={value} onChange={e=>onChange(e.target.value)} className="mt-1 w-full rounded-xl border border-slate-200 px-3 py-2.5"/></label>}
