import React,{useEffect,useMemo,useState} from 'react';
import { CheckCircle2, CloudCog, RefreshCw, Save, ShieldCheck } from 'lucide-react';
import { supabase } from '../../lib/supabase';
import { fallbackTemplateKey } from './resultTemplateConfig';
import type { ResultTemplateKey } from './types';

const options:Array<{key:ResultTemplateKey;label:string}>=[
  {key:'class_1_8_regular',label:'Class 1–8 Regular Subject'},
  {key:'class_1_8_hindi_marathi',label:'Class 1–8 Hindi/Marathi Language'},
  {key:'class_9_10_single',label:'Class 9–10 Single Subject'},
  {key:'class_9_10_dual_paper',label:'Class 9–10 Dual Paper Subject'},
  {key:'class_9_10_dual_language',label:'Class 9–10 Dual Language'},
  {key:'grade_subject',label:'Grade Subject'},
];
const missing=(e:any)=>/does not exist|schema cache|could not find|relation .* does not exist/i.test(String(e?.message||''));

export default function ClerkResultTemplateMappingPanel(){
  const[schoolId,setSchoolId]=useState('');const[yearId,setYearId]=useState('');const[classes,setClasses]=useState<any[]>([]);const[subjects,setSubjects]=useState<any[]>([]);const[subjectMappings,setSubjectMappings]=useState<any[]>([]);const[mappings,setMappings]=useState<any[]>([]);const[classId,setClassId]=useState('');const[subjectId,setSubjectId]=useState('');const[templateKey,setTemplateKey]=useState<ResultTemplateKey>('class_1_8_regular');const[busy,setBusy]=useState(false);const[error,setError]=useState('');const[msg,setMsg]=useState('');
  const load=async()=>{setBusy(true);setError('');try{const auth=await supabase.auth.getUser();const uid=auth.data.user?.id;if(!uid)throw new Error('Clerk login session not found.');const m=await supabase.from('user_school_memberships').select('school_id,role_in_school').eq('user_id',uid).eq('is_active',true).maybeSingle();if(m.error)throw m.error;const sid=String((m.data as any)?.school_id||'');if(!sid)throw new Error('Active school membership not found.');setSchoolId(sid);const [years,cls,subs,schoolMaps,maps]=await Promise.all([supabase.from('school_academic_years').select('id,year_code,is_active').eq('school_id',sid).order('sort_order'),supabase.from('school_classes').select('id,class_name,class_numeric,is_active').eq('school_id',sid).neq('is_active',false).order('sort_order'),supabase.from('subjects').select('id,subject_name,subject_code,is_active').eq('school_id',sid).neq('is_active',false).order('subject_name'),supabase.from('school_subject_mappings').select('class_id,subject_id').eq('school_id',sid),supabase.from('edunixo_result_template_mappings').select('*').eq('school_id',sid).eq('active',true).order('created_at',{ascending:false})]);if(years.error)throw years.error;if(cls.error)throw cls.error;if(subs.error)throw subs.error;if(schoolMaps.error)throw schoolMaps.error;if(maps.error){if(missing(maps.error)){setError('R4 Result cloud tables are not installed yet. Mapping can be configured after the included SQL is run.');setMappings([])}else throw maps.error}else setMappings(maps.data||[]);const yrs=years.data||[];const c=cls.data||[];const s=subs.data||[];setYearId(String((yrs.find((x:any)=>x.is_active)||yrs[0])?.id||''));setClasses(c);setSubjects(s);setSubjectMappings(schoolMaps.data||[]);setClassId(v=>v||String(c[0]?.id||''));setSubjectId(v=>v||String(s[0]?.id||''));}catch(e:any){setError(e?.message||'Template mapping could not be loaded.')}finally{setBusy(false)}};
  useEffect(()=>{void load()},[]);
  const selectedClass=classes.find(x=>String(x.id)===classId);
  const mappedIds=new Set(subjectMappings.filter(x=>String(x.class_id)===classId).map(x=>String(x.subject_id)));
  const visibleSubjects=mappedIds.size?subjects.filter(s=>mappedIds.has(String(s.id))):subjects;
  const selectedSubject=subjects.find(x=>String(x.id)===subjectId);
  useEffect(()=>{if(classId&&visibleSubjects.length&&!visibleSubjects.some(s=>String(s.id)===subjectId))setSubjectId(String(visibleSubjects[0].id));},[classId,visibleSubjects.map(s=>s.id).join('|')]);
  const existing=useMemo(()=>mappings.find(x=>String(x.class_id)===classId&&String(x.subject_id)===subjectId&&(!x.academic_year_id||String(x.academic_year_id)===yearId)),[mappings,classId,subjectId,yearId]);
  useEffect(()=>{if(existing?.template_key)setTemplateKey(existing.template_key as ResultTemplateKey);else if(selectedClass&&selectedSubject)setTemplateKey(fallbackTemplateKey(selectedClass.class_name,selectedSubject.subject_name));},[existing?.id,classId,subjectId]);
  const save=async()=>{if(!schoolId||!classId||!subjectId)return;setBusy(true);setError('');setMsg('');try{let q:any=supabase.from('edunixo_result_template_mappings').select('id').eq('school_id',schoolId).eq('class_id',classId).eq('subject_id',subjectId);if(yearId)q=q.eq('academic_year_id',yearId);else q=q.is('academic_year_id',null);q=q.is('division_id',null);const found=await q.maybeSingle();if(found.error&&!missing(found.error))throw found.error;const payload={school_id:schoolId,academic_year_id:yearId||null,class_id:classId,division_id:null,subject_id:subjectId,template_key:templateKey,active:true,updated_at:new Date().toISOString()};const r=found.data?.id?await supabase.from('edunixo_result_template_mappings').update(payload).eq('id',found.data.id):await supabase.from('edunixo_result_template_mappings').insert(payload);if(r.error)throw r.error;setMsg(`${selectedClass?.class_name||'Class'} · ${selectedSubject?.subject_name||'Subject'} mapped to ${options.find(x=>x.key===templateKey)?.label}.`);await load()}catch(e:any){setError(e?.message||'Mapping could not be saved.')}finally{setBusy(false)}};
  return <section className="rounded-2xl border border-indigo-200 bg-indigo-50/40 p-5 text-left shadow-sm"><div className="flex flex-wrap items-start justify-between gap-3"><div className="flex gap-3"><div className="rounded-xl bg-slate-950 p-2 text-white"><CloudCog className="h-4 w-4"/></div><div><h4 className="text-sm font-black text-slate-900">Teacher Mark List Template Routing</h4><p className="mt-1 max-w-3xl text-[11px] leading-5 text-slate-600">Clerk decides which Master Mark List applies to each Class + Subject. Teachers never choose a template. This cloud mapping is the source of truth for Subject Marks List generation.</p></div></div><button onClick={()=>void load()} disabled={busy} className="inline-flex items-center gap-1 rounded-lg border bg-white px-3 py-2 text-[10px] font-black"><RefreshCw className="h-3 w-3"/>Refresh</button></div><div className="mt-4 grid gap-3 md:grid-cols-[1fr_1.4fr_1.5fr_auto]"><label className="text-[10px] font-black uppercase tracking-wide text-slate-600">Class<select value={classId} onChange={e=>setClassId(e.target.value)} className="mt-1 w-full rounded-xl border bg-white px-3 py-2.5 text-xs normal-case">{classes.map(c=><option key={c.id} value={c.id}>{c.class_name}</option>)}</select></label><label className="text-[10px] font-black uppercase tracking-wide text-slate-600">Subject<select value={subjectId} onChange={e=>setSubjectId(e.target.value)} className="mt-1 w-full rounded-xl border bg-white px-3 py-2.5 text-xs normal-case">{visibleSubjects.map(s=><option key={s.id} value={s.id}>{s.subject_name}{s.subject_code?` (${s.subject_code})`:''}</option>)}</select></label><label className="text-[10px] font-black uppercase tracking-wide text-slate-600">Master Template<select value={templateKey} onChange={e=>setTemplateKey(e.target.value as ResultTemplateKey)} className="mt-1 w-full rounded-xl border bg-white px-3 py-2.5 text-xs normal-case">{options.map(o=><option key={o.key} value={o.key}>{o.label}</option>)}</select></label><div className="flex items-end"><button onClick={()=>void save()} disabled={busy||!classId||!subjectId} className="inline-flex w-full items-center justify-center gap-1 rounded-xl bg-indigo-700 px-4 py-2.5 text-xs font-black text-white disabled:opacity-40"><Save className="h-3.5 w-3.5"/>Save Mapping</button></div></div>{existing&&<div className="mt-3 inline-flex items-center gap-1 rounded-full bg-emerald-100 px-3 py-1 text-[10px] font-black text-emerald-800"><ShieldCheck className="h-3 w-3"/>Current cloud mapping: {options.find(x=>x.key===existing.template_key)?.label||existing.template_key}</div>}{msg&&<div className="mt-3 flex items-center gap-2 rounded-lg border border-emerald-200 bg-emerald-50 p-2 text-[10px] font-bold text-emerald-800"><CheckCircle2 className="h-3.5 w-3.5"/>{msg}</div>}{error&&<div className="mt-3 rounded-lg border border-amber-200 bg-amber-50 p-2 text-[10px] font-bold text-amber-800">{error}</div>}</section>;
}
