import React, { useEffect, useMemo, useState } from 'react';
import { BellRing, CalendarDays, Clock3, Plus, RefreshCw, Save, Trash2 } from 'lucide-react';
import { supabase } from '../lib/supabase';
import type { User } from '../types';

type BellEvent = { id: string; label: string; time: string; kind: string; enabled?: boolean };
type BellTiming = { mode: 'timetable'|'manual'; revision: number; updatedAt?: string|null; manualSchedule: { name: string; effectiveFrom?: string|null; effectiveTo?: string|null; days: string[]; events: BellEvent[] } };
const days = ['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'];

export default function BellTimingManager({ user }: { user: User }) {
  const [timing,setTiming]=useState<BellTiming|null>(null); const [periods,setPeriods]=useState<BellEvent[]>([]); const [busy,setBusy]=useState(true); const [saving,setSaving]=useState(false); const [message,setMessage]=useState('');
  const token=async()=>{const {data:{session}}=await supabase.auth.getSession();if(!session?.access_token)throw new Error('Headmaster session expired.');return session.access_token;};
  const load=async()=>{setBusy(true);setMessage('');try{const t=await token();const r=await fetch('/api/headmaster/bell-timing',{headers:{Authorization:`Bearer ${t}`},cache:'no-store'});const b=await r.json();if(!r.ok)throw new Error(b.error||'Bell Timing could not be loaded.');setTiming(b.bellTiming);setPeriods(b.timetableEvents||[]);}catch(e:any){setMessage(e.message||'Bell Timing could not be loaded.');}finally{setBusy(false);}};
  useEffect(()=>{void load();},[]);
  const update=(patch:Partial<BellTiming>)=>setTiming(cur=>cur?{...cur,...patch}:cur);
  const updateManual=(patch:any)=>setTiming(cur=>cur?{...cur,manualSchedule:{...cur.manualSchedule,...patch}}:cur);
  const save=async()=>{if(!timing)return;setSaving(true);setMessage('');try{const t=await token();const r=await fetch('/api/headmaster/bell-timing',{method:'PUT',headers:{Authorization:`Bearer ${t}`,'Content-Type':'application/json'},body:JSON.stringify({bellTiming:timing})});const b=await r.json();if(!r.ok)throw new Error(b.error||'Bell schedule could not be saved.');setTiming(b.bellTiming);setMessage('Bell schedule saved. Peon Android devices will sync the new revision automatically.');}catch(e:any){setMessage(e.message||'Bell schedule could not be saved.');}finally{setSaving(false);}};
  const sorted=useMemo(()=>[...(timing?.manualSchedule.events||[])].sort((a,b)=>a.time.localeCompare(b.time)),[timing]);
  if(busy)return <div className="rounded-2xl border border-slate-200 bg-white p-8 text-sm font-semibold text-slate-500">Loading Bell Timing…</div>;
  if(!timing)return <div className="rounded-2xl border border-rose-200 bg-rose-50 p-5 text-sm text-rose-700">{message||'Bell Timing unavailable.'}</div>;
  return <div className="space-y-5 text-left">
    <section className="overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-sm"><div className="bg-slate-950 px-6 py-6 text-white"><div className="flex items-center gap-3"><BellRing className="h-6 w-6 text-amber-300"/><div><div className="text-[10px] font-black uppercase tracking-[.2em] text-amber-300">School Operations</div><h2 className="text-xl font-black">Bell Timing & Alarm Control</h2><p className="mt-1 text-xs text-slate-300">Headmaster is the only schedule authority. Peon app has no alarm OFF switch.</p></div></div></div>
      <div className="grid gap-3 p-5 sm:grid-cols-2"><button type="button" onClick={()=>update({mode:'timetable'})} className={`rounded-2xl border p-4 text-left ${timing.mode==='timetable'?'border-blue-500 bg-blue-50':'border-slate-200'}`}><b>Use Timetable Period Timings</b><p className="mt-1 text-xs text-slate-500">Fetches active Academic Setup periods automatically.</p></button><button type="button" onClick={()=>update({mode:'manual'})} className={`rounded-2xl border p-4 text-left ${timing.mode==='manual'?'border-violet-500 bg-violet-50':'border-slate-200'}`}><b>Manual Bell Schedule</b><p className="mt-1 text-xs text-slate-500">Independent schedule for exam days, special timing or other operations.</p></button></div>
    </section>
    {timing.mode==='timetable'?<section className="rounded-3xl border border-slate-200 bg-white p-5"><div className="mb-4 flex items-center justify-between"><div><h3 className="font-black text-slate-900">Published Period Bell Source</h3><p className="text-xs text-slate-500">Read-only here; edit period timings in Academic Setup.</p></div><button type="button" onClick={()=>void load()} className="rounded-xl border border-slate-200 p-2"><RefreshCw className="h-4 w-4"/></button></div><div className="grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{periods.map(e=><div key={e.id} className="rounded-xl bg-slate-50 p-3"><div className="text-xs font-black text-slate-800">{e.time}</div><div className="text-xs text-slate-600">{e.label}</div></div>)}{!periods.length&&<p className="text-sm text-amber-700">No active period timings found. Complete Academic Setup first.</p>}</div></section>:
    <section className="space-y-4 rounded-3xl border border-slate-200 bg-white p-5"><div className="grid gap-3 sm:grid-cols-3"><label className="sm:col-span-1 text-xs font-bold text-slate-600">Schedule Name<input value={timing.manualSchedule.name} onChange={e=>updateManual({name:e.target.value})} className="mt-1 w-full rounded-xl border border-slate-200 px-3 py-2.5"/></label><label className="text-xs font-bold text-slate-600">Effective From<input type="date" value={timing.manualSchedule.effectiveFrom||''} onChange={e=>updateManual({effectiveFrom:e.target.value||null})} className="mt-1 w-full rounded-xl border border-slate-200 px-3 py-2.5"/></label><label className="text-xs font-bold text-slate-600">Effective To<input type="date" value={timing.manualSchedule.effectiveTo||''} onChange={e=>updateManual({effectiveTo:e.target.value||null})} className="mt-1 w-full rounded-xl border border-slate-200 px-3 py-2.5"/></label></div>
      <div><div className="mb-2 text-xs font-black text-slate-700">Working Days</div><div className="flex flex-wrap gap-2">{days.map(d=><label key={d} className="flex items-center gap-2 rounded-xl border border-slate-200 px-3 py-2 text-xs font-semibold"><input type="checkbox" checked={timing.manualSchedule.days.includes(d)} onChange={e=>updateManual({days:e.target.checked?[...timing.manualSchedule.days,d]:timing.manualSchedule.days.filter(x=>x!==d)})}/>{d}</label>)}</div></div>
      <div className="space-y-2"><div className="flex items-center justify-between"><h3 className="font-black text-slate-900">Manual Bell Events</h3><button type="button" onClick={()=>updateManual({events:[...timing.manualSchedule.events,{id:`manual-${Date.now()}`,label:'New Bell',time:'08:00',kind:'custom',enabled:true}]})} className="inline-flex items-center gap-1 rounded-xl bg-slate-900 px-3 py-2 text-xs font-bold text-white"><Plus className="h-4 w-4"/>Add Bell</button></div>{sorted.map(e=><div key={e.id} className="grid gap-2 rounded-2xl border border-slate-200 p-3 sm:grid-cols-[120px_1fr_140px_44px]"><input type="time" value={e.time} onChange={x=>updateManual({events:timing.manualSchedule.events.map(r=>r.id===e.id?{...r,time:x.target.value}:r)})} className="rounded-xl border border-slate-200 px-3 py-2"/><input value={e.label} onChange={x=>updateManual({events:timing.manualSchedule.events.map(r=>r.id===e.id?{...r,label:x.target.value}:r)})} className="rounded-xl border border-slate-200 px-3 py-2"/><select value={e.kind} onChange={x=>updateManual({events:timing.manualSchedule.events.map(r=>r.id===e.id?{...r,kind:x.target.value}:r)})} className="rounded-xl border border-slate-200 px-3 py-2"><option value="assembly">Assembly</option><option value="period">Period</option><option value="break">Break</option><option value="closing">Closing</option><option value="custom">Custom</option></select><button type="button" onClick={()=>updateManual({events:timing.manualSchedule.events.filter(r=>r.id!==e.id)})} className="rounded-xl border border-rose-200 text-rose-600"><Trash2 className="mx-auto h-4 w-4"/></button></div>)}</div>
    </section>}
    {message&&<div className="rounded-2xl border border-blue-200 bg-blue-50 p-3 text-xs font-semibold text-blue-800">{message}</div>}
    <button type="button" disabled={saving} onClick={()=>void save()} className="inline-flex items-center gap-2 rounded-2xl bg-blue-600 px-5 py-3 text-sm font-black text-white disabled:opacity-60"><Save className="h-4 w-4"/>{saving?'Saving…':'Save & Publish Bell Schedule'}</button>
  </div>;
}
