import React,{useEffect,useMemo,useState} from 'react';
import { ArrowRightLeft,BadgeIndianRupee,Banknote,BookOpenCheck,CheckCircle2,Landmark,Loader2,Plus,RefreshCw,ShieldCheck,WalletCards } from 'lucide-react';
import type { Language,User } from '../types';
import { actFinanceVoucher,closeFinancialYear,createFinanceAccount,createFinanceVoucher,loadHeadmasterFinance,syncFeeReceiptsToFinance } from '../services/headmasterHrFinanceService';

type Props={lang:Language;user:User;activeFeatureId?:string|null};
type Tab='overview'|'vouchers'|'accounts'|'ledger'|'cashbank'|'reconcile'|'statements'|'yearclose'|'audit';
const featureTab:Record<string,Tab>={'accounting-overview':'overview','voucher-review':'vouchers','chart-of-accounts':'accounts','account-ledger-books':'ledger','cash-bank-registers':'cashbank','bank-reconciliation-review':'reconcile','financial-statements':'statements','finance-year-close':'yearclose','audit-safety-logs':'audit'};
const money=(n:any)=>`₹${Number(n||0).toLocaleString('en-IN',{maximumFractionDigits:2})}`;
export default function HeadmasterFinanceCloudWorkspace({activeFeatureId}:Props){
 const[data,setData]=useState<any>(null),[loading,setLoading]=useState(true),[busy,setBusy]=useState(''),[error,setError]=useState(''),[success,setSuccess]=useState(''),[tab,setTab]=useState<Tab>('overview');
 const[accountForm,setAccountForm]=useState({code:'',name:'',group:'expense',openingBalance:0});const[voucher,setVoucher]=useState({type:'payment',date:new Date().toISOString().slice(0,10),debitAccountId:'',creditAccountId:'',amount:0,narration:'',referenceNo:''});
 const load=async()=>{setLoading(true);setError('');try{const x=await loadHeadmasterFinance();setData(x);if(!voucher.debitAccountId&&x.accounts?.[0])setVoucher(v=>({...v,debitAccountId:x.accounts[0].id,creditAccountId:x.accounts[1]?.id||''}));}catch(e:any){setError(e?.message||'Finance workspace could not be loaded.')}finally{setLoading(false)}};
 useEffect(()=>{void load()},[]);useEffect(()=>{if(activeFeatureId&&featureTab[activeFeatureId])setTab(featureTab[activeFeatureId])},[activeFeatureId]);
 const run=async(key:string,fn:()=>Promise<any>)=>{setBusy(key);setError('');setSuccess('');try{const r=await fn();setSuccess(r?.created!=null?`${r.created} fee receipt voucher(s) synchronized${r.cancelled?` · ${r.cancelled} cancelled source voucher(s) reversed`:''}.`:'Action completed successfully.');await load()}catch(e:any){setError(e?.message||'Action failed.')}finally{setBusy('')}};
 const approved=(data?.vouchers||[]).filter((v:any)=>v.status==='approved'),cashBankIds=new Set((data?.accounts||[]).filter((a:any)=>['CASH','BANK'].includes(a.code)).map((a:any)=>a.id));
 const cashBank=approved.filter((v:any)=>cashBankIds.has(v.debitAccountId)||cashBankIds.has(v.creditAccountId));
 if(loading&&!data)return <LoaderPage/>;
 return <div className="space-y-5 text-left"><Hero onRefresh={()=>void load()} loading={loading} onSync={()=>run('sync',syncFeeReceiptsToFinance)} busy={busy}/><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5"><Stat label="Approved Vouchers" value={data?.summary?.approvedVouchers||0} icon={CheckCircle2}/><Stat label="Draft Vouchers" value={data?.summary?.draftVouchers||0} icon={WalletCards}/><Stat label="Income" value={money(data?.summary?.income)} icon={Banknote}/><Stat label="Expense" value={money(data?.summary?.expense)} icon={BadgeIndianRupee}/><Stat label="Surplus" value={money(data?.summary?.surplus)} icon={Landmark}/></div>{(error||success)&&<div className={`rounded-2xl border p-4 text-sm font-bold ${error?'border-rose-200 bg-rose-50 text-rose-700':'border-emerald-200 bg-emerald-50 text-emerald-700'}`}>{error||success}</div>}<Nav tab={tab} setTab={setTab}/>
 {tab==='overview'&&<div className="grid gap-5 xl:grid-cols-2"><Panel title="Financial Position"><div className="space-y-3">{(data?.accounts||[]).filter((a:any)=>a.isActive).map((a:any)=><Line key={a.id} label={`${a.code} · ${a.name}`} value={money(a.balance)}/>)}</div></Panel><Panel title="Recent Vouchers"><VoucherMini rows={(data?.vouchers||[]).slice(0,10)}/></Panel></div>}
 {tab==='vouchers'&&<section className="space-y-5"><Panel title="Create Double-entry Voucher"><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-4"><select value={voucher.type} onChange={e=>setVoucher({...voucher,type:e.target.value})} className="rounded-xl border px-3 py-2 text-xs"><option value="payment">Payment</option><option value="receipt">Receipt</option><option value="journal">Journal</option><option value="contra">Contra</option></select><input type="date" value={voucher.date} onChange={e=>setVoucher({...voucher,date:e.target.value})} className="rounded-xl border px-3 py-2 text-xs"/><select value={voucher.debitAccountId} onChange={e=>setVoucher({...voucher,debitAccountId:e.target.value})} className="rounded-xl border px-3 py-2 text-xs"><option value="">Debit Account</option>{(data?.accounts||[]).filter((a:any)=>a.isActive).map((a:any)=><option key={a.id} value={a.id}>Dr · {a.code} · {a.name}</option>)}</select><select value={voucher.creditAccountId} onChange={e=>setVoucher({...voucher,creditAccountId:e.target.value})} className="rounded-xl border px-3 py-2 text-xs"><option value="">Credit Account</option>{(data?.accounts||[]).filter((a:any)=>a.isActive).map((a:any)=><option key={a.id} value={a.id}>Cr · {a.code} · {a.name}</option>)}</select><input type="number" min="0" value={voucher.amount} onChange={e=>setVoucher({...voucher,amount:Number(e.target.value)})} placeholder="Amount" className="rounded-xl border px-3 py-2 text-xs"/><input value={voucher.referenceNo} onChange={e=>setVoucher({...voucher,referenceNo:e.target.value})} placeholder="Reference No." className="rounded-xl border px-3 py-2 text-xs"/><input value={voucher.narration} onChange={e=>setVoucher({...voucher,narration:e.target.value})} placeholder="Narration" className="rounded-xl border px-3 py-2 text-xs md:col-span-2"/><button disabled={!!busy} onClick={()=>run('voucher',()=>createFinanceVoucher(voucher))} className="rounded-xl bg-slate-950 px-4 py-2.5 text-xs font-black text-white">Save Draft Voucher</button></div></Panel><VoucherTable rows={data?.vouchers||[]} busy={busy} act={(id,action,extra={})=>run(`${action}:${id}`,()=>actFinanceVoucher(id,{action,...extra}))}/></section>}
 {tab==='accounts'&&<section className="grid gap-5 xl:grid-cols-[0.8fr_1.2fr]"><Panel title="Add Ledger Account"><div className="grid gap-3"><input value={accountForm.code} onChange={e=>setAccountForm({...accountForm,code:e.target.value.toUpperCase()})} placeholder="Code" className="rounded-xl border px-3 py-2 text-sm"/><input value={accountForm.name} onChange={e=>setAccountForm({...accountForm,name:e.target.value})} placeholder="Account name" className="rounded-xl border px-3 py-2 text-sm"/><select value={accountForm.group} onChange={e=>setAccountForm({...accountForm,group:e.target.value})} className="rounded-xl border px-3 py-2 text-sm">{['asset','liability','income','expense','equity'].map(x=><option key={x} value={x}>{x}</option>)}</select><input type="number" value={accountForm.openingBalance} onChange={e=>setAccountForm({...accountForm,openingBalance:Number(e.target.value)})} className="rounded-xl border px-3 py-2 text-sm"/><button onClick={()=>run('account',()=>createFinanceAccount(accountForm))} className="rounded-xl bg-slate-950 px-4 py-2.5 text-xs font-black text-white">Add Account</button></div></Panel><Panel title="Chart of Accounts"><div className="divide-y rounded-xl border">{(data?.accounts||[]).map((a:any)=><div key={a.id} className="grid grid-cols-[1fr_auto] gap-3 p-3"><div><b className="text-xs">{a.code} · {a.name}</b><div className="mt-1 text-[10px] uppercase text-slate-400">{a.group}{a.isSystem?' · system':''}</div></div><b className="text-xs">{money(a.balance)}</b></div>)}</div></Panel></section>}
 {tab==='ledger'&&<Panel title="Account Ledger Books"><div className="space-y-4">{(data?.accounts||[]).map((a:any)=><details key={a.id} className="rounded-xl border p-3"><summary className="cursor-pointer text-xs font-black">{a.code} · {a.name} · {money(a.balance)}</summary><div className="mt-3"><VoucherMini rows={(data?.vouchers||[]).filter((v:any)=>v.debitAccountId===a.id||v.creditAccountId===a.id)}/></div></details>)}</div></Panel>}
 {tab==='cashbank'&&<Panel title="Cash / Bank Registers"><VoucherMini rows={cashBank}/></Panel>}
 {tab==='reconcile'&&<Panel title="Bank Reconciliation"><div className="space-y-3">{approved.filter((v:any)=>cashBankIds.has(v.debitAccountId)||cashBankIds.has(v.creditAccountId)).map((v:any)=><div key={v.id} className="flex flex-col gap-3 rounded-xl border p-3 sm:flex-row sm:items-center sm:justify-between"><div><b className="text-xs">{v.voucherNo} · {money(v.amount)}</b><div className="mt-1 text-[10px] text-slate-500">{v.date} · {v.debitAccountName} / {v.creditAccountName}</div></div><button disabled={!!busy||!!v.bankReconciledAt} onClick={()=>run(`reconcile:${v.id}`,()=>actFinanceVoucher(v.id,{action:'reconcile',date:new Date().toISOString().slice(0,10)}))} className="rounded-lg bg-indigo-600 px-3 py-2 text-[10px] font-black text-white disabled:opacity-40">{v.bankReconciledAt?`Reconciled ${v.bankReconciledAt}`:'Mark Reconciled'}</button></div>)}</div></Panel>}
 {tab==='statements'&&<div className="grid gap-5 xl:grid-cols-2"><Panel title="Income Statement"><Line label="Total Income" value={money(data?.summary?.income)}/><Line label="Total Expense" value={money(data?.summary?.expense)}/><Line label="Surplus / (Deficit)" value={money(data?.summary?.surplus)}/></Panel><Panel title="Balance Snapshot">{(data?.accounts||[]).filter((a:any)=>['asset','liability','equity'].includes(a.group)).map((a:any)=><Line key={a.id} label={`${a.code} · ${a.name}`} value={money(a.balance)}/>)}</Panel></div>}
 {tab==='yearclose'&&<Panel title="Financial Year Close"><div className="space-y-3">{(data?.financialYears||[]).map((fy:any)=><div key={fy.id} className="flex flex-col gap-3 rounded-xl border p-4 sm:flex-row sm:items-center sm:justify-between"><div><b className="text-sm">{fy.name}</b><div className="mt-1 text-[10px] text-slate-500">{fy.startDate} → {fy.endDate}</div></div><div className="flex items-center gap-3"><Badge value={fy.status}/>{fy.status==='open'&&<button disabled={!!busy} onClick={()=>run(`close:${fy.id}`,()=>closeFinancialYear(fy.id))} className="rounded-lg bg-rose-600 px-3 py-2 text-[10px] font-black text-white">Close Year</button>}</div></div>)}</div><p className="mt-4 text-xs text-slate-500">Financial Year close is blocked while Draft vouchers exist.</p></Panel>}
 {tab==='audit'&&<Panel title="Audit & Safety Register"><p className="mb-4 text-xs text-slate-500">Permanent voucher states and source links. Server actions also write the school Audit Log.</p><VoucherMini rows={data?.vouchers||[]}/></Panel>}
 </div>}
function Hero({onRefresh,loading,onSync,busy}:{onRefresh:()=>void;loading:boolean;onSync:()=>void;busy:string}){return <div className="rounded-3xl border border-slate-800 bg-slate-950 p-6 text-white"><div className="flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between"><div><div className="flex items-center gap-2 text-xs font-black uppercase tracking-[.18em] text-amber-200"><ShieldCheck className="h-4 w-4"/>Cloud Accounting</div><h1 className="mt-2 text-2xl font-black">Accounting & Finance</h1><p className="mt-2 max-w-3xl text-sm text-slate-300">Permanent double-entry accounts, vouchers, ledgers, bank reconciliation, financial statements and controlled year close.</p></div><div className="flex gap-2"><button disabled={!!busy} onClick={onSync} className="rounded-xl border border-white/15 bg-white/10 px-4 py-2 text-xs font-black">Sync Fee Receipts</button><button onClick={onRefresh} className="inline-flex items-center gap-2 rounded-xl border border-white/15 bg-white/10 px-4 py-2 text-xs font-black"><RefreshCw className={`h-4 w-4 ${loading?'animate-spin':''}`}/>Refresh</button></div></div></div>}
function Nav({tab,setTab}:{tab:Tab;setTab:(x:Tab)=>void}){const xs:[Tab,string][]=[['overview','Overview'],['vouchers','Vouchers'],['accounts','Accounts'],['ledger','Ledgers'],['cashbank','Cash / Bank'],['reconcile','Reconciliation'],['statements','Statements'],['yearclose','Year Close'],['audit','Audit']];return <div className="flex gap-2 overflow-x-auto rounded-2xl border bg-white p-2">{xs.map(([id,label])=><button key={id} onClick={()=>setTab(id)} className={`shrink-0 rounded-xl px-4 py-2 text-xs font-black ${tab===id?'bg-slate-950 text-white':'text-slate-600 hover:bg-slate-100'}`}>{label}</button>)}</div>}
function Panel({title,children}:{title:string;children:React.ReactNode}){return <div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="mb-4 font-black text-slate-950">{title}</h2>{children}</div>}
function Stat({label,value,icon:Icon}:{label:string;value:any;icon:any}){return <div className="rounded-2xl border bg-white p-4"><div className="flex justify-between"><span className="text-[10px] font-black uppercase text-slate-400">{label}</span><Icon className="h-4 w-4 text-slate-400"/></div><div className="mt-2 text-xl font-black text-slate-950">{value}</div></div>}
function Line({label,value}:{label:string;value:string}){return <div className="flex items-center justify-between gap-3 rounded-xl bg-slate-50 p-3 text-xs"><span className="font-bold text-slate-600">{label}</span><b>{value}</b></div>}
function VoucherMini({rows}:{rows:any[]}){return <div className="divide-y rounded-xl border">{rows.map(v=><div key={v.id} className="grid gap-1 p-3 text-xs sm:grid-cols-[0.8fr_1fr_auto]"><div><b>{v.voucherNo}</b><div className="text-[10px] text-slate-400">{v.date}</div></div><div>{v.debitAccountName} / {v.creditAccountName}<div className="text-[10px] text-slate-500">{v.narration||v.referenceNo||'—'}</div></div><div className="text-right"><b>{money(v.amount)}</b><div className="mt-1"><Badge value={v.status}/></div></div></div>)}{!rows.length&&<div className="p-8 text-center text-xs font-bold text-slate-400">No records.</div>}</div>}
function VoucherTable({rows,busy,act}:{rows:any[];busy:string;act:(id:string,action:string,extra?:any)=>void}){return <div className="overflow-x-auto rounded-2xl border bg-white"><table className="w-full min-w-[980px] text-xs"><thead className="bg-slate-50 text-left text-[10px] uppercase text-slate-400"><tr><th className="p-4">Voucher</th><th className="p-4">Date</th><th className="p-4">Debit</th><th className="p-4">Credit</th><th className="p-4">Amount</th><th className="p-4">Status</th><th className="p-4">Action</th></tr></thead><tbody className="divide-y">{rows.map(v=><tr key={v.id}><td className="p-4 font-black">{v.voucherNo}<div className="text-[9px] font-normal text-slate-400">{v.type}</div></td><td className="p-4">{v.date}</td><td className="p-4">{v.debitAccountName}</td><td className="p-4">{v.creditAccountName}</td><td className="p-4 font-black">{money(v.amount)}</td><td className="p-4"><Badge value={v.status}/></td><td className="p-4"><div className="flex gap-2">{v.status==='draft'&&<><button disabled={!!busy} onClick={()=>act(v.id,'approve')} className="rounded-lg bg-emerald-600 px-3 py-1.5 text-[10px] font-black text-white">Approve</button><button disabled={!!busy} onClick={()=>act(v.id,'reject',{reason:'Rejected by Headmaster'})} className="rounded-lg bg-rose-50 px-3 py-1.5 text-[10px] font-black text-rose-700">Reject</button></>}{v.status==='approved'&&<button disabled={!!busy} onClick={()=>{const reason=window.prompt('Cancellation reason');if(reason)act(v.id,'cancel',{reason})}} className="rounded-lg border px-3 py-1.5 text-[10px] font-black">Cancel</button>}</div></td></tr>)}{!rows.length&&<tr><td colSpan={7} className="p-10 text-center font-bold text-slate-400">No vouchers yet.</td></tr>}</tbody></table></div>}
function Badge({value}:{value:string}){const v=String(value||'').toLowerCase();return <span className={`rounded-full px-2.5 py-1 text-[9px] font-black uppercase ${v==='approved'||v==='open'?'bg-emerald-100 text-emerald-700':v==='draft'?'bg-amber-100 text-amber-700':v==='rejected'||v==='cancelled'||v==='closed'?'bg-rose-100 text-rose-700':'bg-slate-100 text-slate-600'}`}>{value}</span>}
function LoaderPage(){return <div className="flex min-h-72 items-center justify-center rounded-3xl border bg-white"><Loader2 className="h-8 w-8 animate-spin"/></div>}
