/** Classtago R33.23 — Clerk cloud Communication Drafts & Office Dispatch. */
import React,{useEffect,useState} from 'react';
import {AlertTriangle,FileClock,FileText,MessageSquarePlus,Plus,RefreshCw,Send,ShieldCheck} from 'lucide-react';
import {Language,User as UserType} from '../types';
import {supabase} from '../lib/supabase';
import SmsGatewayControlPanel from './SmsGatewayControlPanel';

type Props={lang:Language;user:UserType;onRefreshData?:()=>void;activeFeatureId?:string|null;focusedMode?:boolean;focusedTitle?:string};
type Snapshot={drafts:any[];templates:any[];dispatches:any[]};
async function tok(){const{data:{session}}=await supabase.auth.getSession();if(!session?.access_token)throw new Error('Secure Clerk session unavailable.');return session.access_token;}
async function api(url:string,init:RequestInit={}){const r=await fetch(url,{...init,headers:{...(init.body?{'Content-Type':'application/json'}:{}),Authorization:`Bearer ${await tok()}`},cache:'no-store'});const p=await r.json().catch(()=>({}));if(!r.ok)throw new Error(p.error||'Communication request failed.');return p;}
export default function ClerkCommunicationOffice({lang,user,onRefreshData,activeFeatureId='cl-notice-drafts'}:Props){void lang;void user;const[data,setData]=useState<Snapshot|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState('');const[draft,setDraft]=useState({title:'',content:'',category:'General',targetRoles:['student','parent'] as string[]});const[template,setTemplate]=useState({name:'',channel:'Notice',category:'General',subject:'',body:'',targetRoles:['student','parent'] as string[]});const[dispatch,setDispatch]=useState({direction:'outgoing',dispatchDate:new Date().toISOString().slice(0,10),documentType:'Letter',subject:'',partyName:'',referenceNo:'',deliveryMode:'Hand',status:'dispatched',notes:''});
 const load=async()=>{setLoading(true);setError('');try{setData(await api('/api/clerk/communication-office/snapshot'));}catch(e:any){setError(e.message||'Communication Office could not be loaded.');}finally{setLoading(false);}};useEffect(()=>{void load();},[]);
 const toggleRole=(key:'draft'|'template',role:string)=>{if(key==='draft')setDraft(v=>({...v,targetRoles:v.targetRoles.includes(role)?v.targetRoles.filter(x=>x!==role):[...v.targetRoles,role]}));else setTemplate(v=>({...v,targetRoles:v.targetRoles.includes(role)?v.targetRoles.filter(x=>x!==role):[...v.targetRoles,role]}));};
 const submitDraft=async()=>{setError('');try{await api('/api/clerk/communication-drafts',{method:'POST',body:JSON.stringify({draft:{title:draft.title,content:draft.content,category:draft.category,targetRoles:draft.targetRoles}})});setDraft(v=>({...v,title:'',content:''}));await load();onRefreshData?.();}catch(e:any){setError(e.message||'Notice draft could not be sent.');}};
 const addTemplate=async()=>{setError('');try{await api('/api/clerk/communication-office/templates',{method:'POST',body:JSON.stringify(template)});setTemplate(v=>({...v,name:'',subject:'',body:''}));await load();}catch(e:any){setError(e.message||'Template could not be saved.');}};
 const addDispatch=async()=>{setError('');try{await api('/api/clerk/communication-office/dispatch',{method:'POST',body:JSON.stringify(dispatch)});setDispatch(v=>({...v,subject:'',partyName:'',referenceNo:'',notes:''}));await load();}catch(e:any){setError(e.message||'Dispatch could not be saved.');}};
 const Header=({title,sub,icon}:{title:string;sub:string;icon:React.ReactNode})=><div className="rounded-3xl bg-gradient-to-br from-slate-950 via-cyan-950 to-slate-950 p-5 text-white shadow-xl"><div className="flex items-start justify-between"><div><div className="text-[10px] font-black uppercase tracking-[.2em] text-cyan-300">Clerk · Communication Office</div><h2 className="mt-1 text-xl font-black">{title}</h2><p className="mt-1 max-w-3xl text-xs text-slate-300">{sub}</p></div><div className="rounded-2xl bg-white/10 p-3">{icon}</div></div></div>;
 const roles=['student','parent','teacher','clerk','peon'];const RolePicker=({which}:{which:'draft'|'template'})=>{const selected=which==='draft'?draft.targetRoles:template.targetRoles;return <div className="flex flex-wrap gap-2">{roles.map(r=><button type="button" key={r} onClick={()=>toggleRole(which,r)} className={`rounded-full border px-3 py-1.5 text-[10px] font-black uppercase ${selected.includes(r)?'border-cyan-500 bg-cyan-50 text-cyan-700':'bg-white text-slate-500'}`}>{r}</button>)}</div>};
 if(loading&&!data)return <div className="rounded-2xl border bg-white p-10 text-center"><RefreshCw className="mx-auto h-5 w-5 animate-spin"/></div>;if(error&&!data)return <div className="rounded-2xl border border-rose-200 bg-rose-50 p-5 text-sm font-bold text-rose-700"><AlertTriangle className="mr-2 inline h-5 w-5"/>{error}</div>;
 const NoticeDrafts=()=> <div className="space-y-5"><Header title="Notice / Circular Drafts" sub="Clerk prepares; Headmaster approves/publishes. Approval now creates real in-app notifications for the selected school roles." icon={<MessageSquarePlus className="h-5 w-5"/>}/>{error&&<div className="rounded-xl bg-rose-50 p-3 text-xs font-bold text-rose-700">{error}</div>}<div className="rounded-2xl border bg-white p-5"><div className="grid gap-3 md:grid-cols-2"><input value={draft.title} onChange={e=>setDraft(v=>({...v,title:e.target.value}))} className="rounded-xl border px-3 py-2.5" placeholder="Notice title"/><select value={draft.category} onChange={e=>setDraft(v=>({...v,category:e.target.value}))} className="rounded-xl border px-3 py-2.5">{['General','Academic','Examination','Holiday','Office','Emergency'].map(x=><option key={x}>{x}</option>)}</select><textarea value={draft.content} onChange={e=>setDraft(v=>({...v,content:e.target.value}))} className="md:col-span-2 min-h-36 rounded-xl border px-3 py-2.5" placeholder="Notice / circular content"/><div className="md:col-span-2"><div className="mb-2 text-[10px] font-black uppercase text-slate-400">Target roles</div><RolePicker which="draft"/></div></div><button onClick={()=>void submitDraft()} className="mt-4 rounded-xl bg-cyan-700 px-4 py-3 text-xs font-black text-white"><Send className="mr-2 inline h-4 w-4"/>Send for Headmaster Approval</button></div><div className="rounded-2xl border bg-white p-4"><div className="mb-3 font-black">Recent Drafts</div>{(data?.drafts||[]).slice(0,40).map(r=><div key={r.id} className="border-t py-3 text-xs"><b>{r.draft?.title||'Notice'}</b><span className={`float-right rounded-full px-2 py-1 text-[9px] font-black uppercase ${r.status==='approve'?'bg-emerald-100 text-emerald-700':r.status==='reject'?'bg-rose-100 text-rose-700':'bg-amber-100 text-amber-700'}`}>{r.status}</span><div className="mt-1 text-slate-500">{r.draft?.category||'General'} · {(r.draft?.targetRoles||[]).join(', ')||'No audience'}</div></div>)}</div></div>;
 const Templates=()=> <div className="space-y-5"><Header title="Message Templates" sub="Reusable Clerk templates are permanent cloud records shared across devices." icon={<FileText className="h-5 w-5"/>}/>{error&&<div className="rounded-xl bg-rose-50 p-3 text-xs font-bold text-rose-700">{error}</div>}<div className="rounded-2xl border bg-white p-5"><div className="grid gap-3 md:grid-cols-2"><input value={template.name} onChange={e=>setTemplate(v=>({...v,name:e.target.value}))} className="rounded-xl border px-3 py-2.5" placeholder="Template name"/><select value={template.channel} onChange={e=>setTemplate(v=>({...v,channel:e.target.value}))} className="rounded-xl border px-3 py-2.5">{['Notice','WhatsApp','Email','In-App'].map(x=><option key={x}>{x}</option>)}</select><input value={template.subject} onChange={e=>setTemplate(v=>({...v,subject:e.target.value}))} className="md:col-span-2 rounded-xl border px-3 py-2.5" placeholder="Subject (optional)"/><textarea value={template.body} onChange={e=>setTemplate(v=>({...v,body:e.target.value}))} className="md:col-span-2 min-h-28 rounded-xl border px-3 py-2.5" placeholder="Message body"/><div className="md:col-span-2"><RolePicker which="template"/></div></div><button onClick={()=>void addTemplate()} className="mt-4 rounded-xl bg-cyan-700 px-4 py-2.5 text-xs font-black text-white"><Plus className="mr-2 inline h-4 w-4"/>Save Template</button></div><div className="grid gap-3 md:grid-cols-2">{(data?.templates||[]).map(t=><div key={t.id} className="rounded-2xl border bg-white p-4"><div className="flex justify-between"><b>{t.name}</b><span className="text-[9px] font-black uppercase text-cyan-700">{t.channel}</span></div><div className="mt-2 text-xs text-slate-600">{t.body}</div><div className="mt-2 text-[10px] text-slate-400">{(t.targetRoles||[]).join(', ')||'No default audience'}</div></div>)}</div></div>;
 const History=()=> <div className="space-y-5"><Header title="Communication History" sub="Headmaster decision history for Clerk-prepared school notices. Published items are auditable cloud events." icon={<FileClock className="h-5 w-5"/>}/><div className="overflow-x-auto rounded-2xl border bg-white"><table className="w-full text-left text-xs"><thead className="bg-slate-50"><tr><th className="p-3">Created</th><th className="p-3">Title</th><th className="p-3">Audience</th><th className="p-3">Status</th><th className="p-3">Decision Note</th></tr></thead><tbody>{(data?.drafts||[]).map(r=><tr key={r.id} className="border-t"><td className="p-3">{String(r.createdAt||'').slice(0,16).replace('T',' ')}</td><td className="p-3 font-black">{r.draft?.title||'Notice'}</td><td className="p-3">{(r.draft?.targetRoles||[]).join(', ')||'—'}</td><td className="p-3 font-black uppercase">{r.status}</td><td className="p-3">{r.decisionNote||'—'}</td></tr>)}</tbody></table></div></div>;
 const Dispatch=()=> <div className="space-y-5"><Header title="Office Dispatch Records" sub="Incoming/outgoing office dispatch is now a permanent cloud register with server-issued dispatch numbers." icon={<ShieldCheck className="h-5 w-5"/>}/>{error&&<div className="rounded-xl bg-rose-50 p-3 text-xs font-bold text-rose-700">{error}</div>}<div className="rounded-2xl border bg-white p-5"><div className="grid gap-3 md:grid-cols-4"><select value={dispatch.direction} onChange={e=>setDispatch(v=>({...v,direction:e.target.value}))} className="rounded-xl border px-3 py-2.5"><option value="outgoing">Outgoing</option><option value="incoming">Incoming</option></select><input type="date" value={dispatch.dispatchDate} onChange={e=>setDispatch(v=>({...v,dispatchDate:e.target.value}))} className="rounded-xl border px-3 py-2.5"/><input value={dispatch.documentType} onChange={e=>setDispatch(v=>({...v,documentType:e.target.value}))} className="rounded-xl border px-3 py-2.5" placeholder="Document type"/><input value={dispatch.partyName} onChange={e=>setDispatch(v=>({...v,partyName:e.target.value}))} className="rounded-xl border px-3 py-2.5" placeholder="Recipient / Sender"/><input value={dispatch.subject} onChange={e=>setDispatch(v=>({...v,subject:e.target.value}))} className="md:col-span-2 rounded-xl border px-3 py-2.5" placeholder="Subject"/><input value={dispatch.referenceNo} onChange={e=>setDispatch(v=>({...v,referenceNo:e.target.value}))} className="rounded-xl border px-3 py-2.5" placeholder="Reference No"/><input value={dispatch.deliveryMode} onChange={e=>setDispatch(v=>({...v,deliveryMode:e.target.value}))} className="rounded-xl border px-3 py-2.5" placeholder="Delivery mode"/><input value={dispatch.notes} onChange={e=>setDispatch(v=>({...v,notes:e.target.value}))} className="md:col-span-3 rounded-xl border px-3 py-2.5" placeholder="Notes"/><button onClick={()=>void addDispatch()} className="rounded-xl bg-cyan-700 px-4 py-2.5 text-xs font-black text-white"><Plus className="mr-2 inline h-4 w-4"/>Record Dispatch</button></div></div><div className="overflow-x-auto rounded-2xl border bg-white"><table className="w-full text-left text-xs"><thead className="bg-slate-50"><tr><th className="p-3">Dispatch No</th><th className="p-3">Date</th><th className="p-3">Direction</th><th className="p-3">Subject</th><th className="p-3">Party</th><th className="p-3">Reference</th><th className="p-3">Status</th></tr></thead><tbody>{(data?.dispatches||[]).map(r=><tr key={r.id} className="border-t"><td className="p-3 font-mono font-bold">{r.dispatchNo}</td><td className="p-3">{r.dispatchDate}</td><td className="p-3 font-black uppercase">{r.direction}</td><td className="p-3">{r.subject}</td><td className="p-3">{r.partyName}</td><td className="p-3">{r.referenceNo||'—'}</td><td className="p-3 font-black">{r.status}</td></tr>)}</tbody></table></div></div>;
 if(activeFeatureId==='cl-sms-gateway')return <SmsGatewayControlPanel lang={lang} user={user}/>;if(activeFeatureId==='cl-communication-templates')return <Templates/>;if(activeFeatureId==='cl-communication-history')return <History/>;if(activeFeatureId==='cl-office-dispatch')return <Dispatch/>;return <NoticeDrafts/>;
}
