import { useEffect, useMemo, useState } from 'react';
import { CheckCircle2, RefreshCw, Save, Sparkles } from 'lucide-react';
import type { StudyMaterial, TeacherAssignment, YearPlanMonthCell, YearPlanSubjectDraft } from '../types/domain';
import { generateYearPlanSubject, listAcademicRecords, prepareHomeworkTextbookSource, saveAcademicRecord } from '../services/teacherAcademicService';
import { SmartPrintDialog } from './SmartPrintDialog';
import { resolveAcademicTextPresentation } from '../utils/languagePresentation';

const MONTHS = ['June','July','August','September','October','November','December','January','February','March','April'] as const;

type SubjectRow = { key:string; subjectId:string; subjectName:string; assignment:TeacherAssignment; divisions:string[]; textbooks:StudyMaterial[] };
type ClassGroup = { key:string; className:string; academicYear:string; assignments:TeacherAssignment[]; subjects:SubjectRow[] };
type DraftState = YearPlanSubjectDraft & { recordId?:string; savedStatus?:string };

const blankMonths = ():YearPlanMonthCell[] => MONTHS.map(month=>({month,content:'',kind:'teaching'}));
const hasPlanContent = (draft?:DraftState) => Boolean(draft?.months?.some(cell=>String(cell.content||'').trim()));
const planText = (subject:string,months:YearPlanMonthCell[]) => [`${subject} — Year Plan`,...months.map(cell=>`${cell.month}: ${String(cell.content||'').trim()||'—'}`)].join('\n');

export function YearPlanBuilder({ assignments, materials }:{assignments:TeacherAssignment[];materials:StudyMaterial[]}) {
  const classGroups=useMemo<ClassGroup[]>(()=>{
    const groups=new Map<string,TeacherAssignment[]>();
    for(const assignment of assignments){const key=`${assignment.academicYear}::${assignment.className}`;groups.set(key,[...(groups.get(key)||[]),assignment]);}
    return [...groups.entries()].map(([key,rows])=>{
      const subjects=new Map<string,TeacherAssignment[]>();
      for(const row of rows){const sk=row.subjectId||row.subjectName;subjects.set(sk,[...(subjects.get(sk)||[]),row]);}
      const subjectRows:SubjectRow[]=[...subjects.entries()].map(([subjectKey,subjectAssignments])=>{
        const representative=subjectAssignments[0];
        const textbooks=materials.filter(material=>material.category==='textbook'&&material.extractionStatus==='ready'&&material.className===representative.className&&material.subjectId===representative.subjectId);
        return {key:`${key}::${subjectKey}`,subjectId:representative.subjectId,subjectName:representative.subjectName,assignment:representative,divisions:[...new Set(subjectAssignments.map(item=>item.division).filter(Boolean))],textbooks};
      });
      return {key,className:rows[0]?.className||'',academicYear:rows[0]?.academicYear||'',assignments:rows,subjects:subjectRows};
    }).sort((a,b)=>a.className.localeCompare(b.className,undefined,{numeric:true}));
  },[assignments,materials]);

  const [classKey,setClassKey]=useState('');
  const [drafts,setDrafts]=useState<Record<string,DraftState>>({});
  const [busySubject,setBusySubject]=useState('');
  const [busyAll,setBusyAll]=useState(false);
  const [saveBusy,setSaveBusy]=useState(false);
  const [error,setError]=useState('');
  const [message,setMessage]=useState('');
  const group=useMemo(()=>classGroups.find(item=>item.key===classKey)||classGroups[0]||null,[classGroups,classKey]);
  const schoolName=group?.assignments[0]?.schoolName||'EDUNIXO School';
  const teacherName=group?.assignments[0]?.teacherName||'Teacher';

  useEffect(()=>{if(classGroups.length&&(!classKey||!classGroups.some(item=>item.key===classKey)))setClassKey(classGroups[0].key);},[classGroups,classKey]);
  useEffect(()=>{let cancelled=false;void listAcademicRecords('year-plan').then(records=>{if(cancelled)return;const next:Record<string,DraftState>={};for(const record of records){const meta:any=record.metadata||{},yearPlan:any=meta.yearPlan||{},rowKey=String(yearPlan.rowKey||'');if(!rowKey||next[rowKey])continue;const months=MONTHS.map(month=>{const saved=Array.isArray(yearPlan.months)?yearPlan.months.find((cell:any)=>String(cell?.month)===month):null;const rawKind=String(saved?.kind||'teaching');const kind=(['teaching','revision','exam','practice','holiday'].includes(rawKind)?rawKind:'teaching') as YearPlanMonthCell['kind'];return {month,content:String(saved?.content||''),kind};});next[rowKey]={assignmentId:record.assignmentId,subjectId:String(yearPlan.subjectId||''),subjectName:String(yearPlan.subjectName||record.subjectName||''),className:String(yearPlan.className||record.className||''),academicYear:String(yearPlan.academicYear||''),months,warnings:[],generationMethod:String(yearPlan.generationMethod||'saved'),recordId:record.id,savedStatus:record.status};}setDrafts(current=>({...next,...current}));}).catch(()=>undefined);return()=>{cancelled=true};},[]);
  useEffect(()=>{if(!group)return;const ids=[...new Set(group.subjects.flatMap(subject=>subject.textbooks.map(book=>book.id)))];if(ids.length)void prepareHomeworkTextbookSource(ids).catch(()=>undefined);},[group?.key,group?.subjects.map(row=>row.textbooks.map(book=>book.id).join(',')).join('|')]);

  const ensureDraft=(subject:SubjectRow):DraftState=>drafts[subject.key]||{assignmentId:subject.assignment.id,subjectId:subject.subjectId,subjectName:subject.subjectName,className:group?.className||subject.assignment.className,academicYear:group?.academicYear||subject.assignment.academicYear,months:blankMonths(),warnings:[],generationMethod:'manual'};
  const updateCell=(subject:SubjectRow,month:string,value:string)=>{const draft=ensureDraft(subject);setDrafts(current=>({...current,[subject.key]:{...draft,months:draft.months.map(cell=>cell.month===month?{...cell,content:value}:cell),savedStatus:undefined}}));setMessage('');};
  const generateOne=async(subject:SubjectRow)=>{if(!subject.textbooks.length)throw new Error(`${subject.subjectName}: Textbook is not AI-ready yet.`);setBusySubject(subject.key);try{const generated=await generateYearPlanSubject({assignmentId:subject.assignment.id,materialIds:subject.textbooks.map(book=>book.id)});const previous=drafts[subject.key];setDrafts(current=>({...current,[subject.key]:{...generated,recordId:previous?.recordId,savedStatus:undefined}}));return generated;}finally{setBusySubject('');}};
  const generateAll=async()=>{if(!group)return;setError('');setMessage('');setBusyAll(true);const failed:string[]=[];try{for(const subject of group.subjects){try{await generateOne(subject);}catch(e){failed.push(`${subject.subjectName}: ${e instanceof Error?e.message:'generation failed'}`);}}if(failed.length)setError(failed.join(' • '));else setMessage('AI Year Plan generated for all assigned subjects in this class. Review/edit the table, then Save Draft or Finalize.');}finally{setBusyAll(false);setBusySubject('');}};
  const saveAll=async(finalize:boolean)=>{if(!group)return;setError('');setMessage('');setSaveBusy(true);try{let savedCount=0;for(const subject of group.subjects){const draft=ensureDraft(subject);if(!hasPlanContent(draft))continue;const id=await saveAcademicRecord({id:draft.recordId,kind:'year-plan',assignmentId:subject.assignment.id,title:`${group.className} Year Plan — ${subject.subjectName}`,status:finalize?'planned':'draft',content:planText(subject.subjectName,draft.months),metadata:{yearPlan:{version:'R33.8',rowKey:subject.key,classPlanKey:group.key,academicYear:group.academicYear,className:group.className,subjectId:subject.subjectId,subjectName:subject.subjectName,divisions:subject.divisions,months:draft.months,generationMethod:draft.generationMethod,finalized:finalize},scopeSnapshot:{className:group.className,division:subject.divisions.join(', '),subjectName:subject.subjectName,academicYear:group.academicYear}}});savedCount++;setDrafts(current=>({...current,[subject.key]:{...draft,recordId:id,savedStatus:finalize?'planned':'draft'}}));}if(!savedCount)throw new Error('Generate or enter at least one Year Plan row before saving.');setMessage(finalize?`Year Plan finalized for ${savedCount} assigned subject(s).`:`Year Plan draft saved for ${savedCount} assigned subject(s).`);}catch(e){setError(e instanceof Error?e.message:'Year Plan could not be saved.');}finally{setSaveBusy(false);}};

  if(!classGroups.length)return <section className="workspace"><header className="page-head"><div><h2>AI Year Plan</h2><p>Class-wise master Year Plan for your assigned subjects.</p></div></header><div className="alert warning">No assigned Class / Subject scope is available.</div></section>;

  return <section className="workspace">
    <header className="page-head"><div><h2>AI Year Plan</h2><p>One class-wise master table: assigned subjects in rows and June–April in columns, based on each subject Textbook.</p></div><span className="pill">Textbook AI · Master Table</span></header>
    <div className="card screen-only"><div className="form-grid two"><label className="field"><span>Class Year Plan</span><select value={group?.key||''} onChange={e=>{setClassKey(e.target.value);setError('');setMessage('');}}>{classGroups.map(item=><option key={item.key} value={item.key}>{item.className} · {item.academicYear}</option>)}</select></label><div className="field"><span>Assigned Subjects</span><div className="rounded-xl border border-slate-200 bg-slate-50 px-3 py-3 text-xs font-bold text-slate-700">{group?.subjects.map(subject=>subject.subjectName).join(' · ')||'—'}</div></div></div><div className="mt-3 rounded-xl border border-cyan-100 bg-cyan-50 p-3 text-[11px] leading-5 text-cyan-950"><b>Master Year Plan rule:</b> one table per class. If the same Subject is assigned in more than one Division, it appears only once in this base Year Plan. Each row uses only that Class + Subject Textbook.</div>{error&&<div className="alert danger mt-3">{error}</div>}{message&&<div className="alert success mt-3"><CheckCircle2 className="mr-2 inline h-4 w-4"/>{message}</div>}<div className="actions mt-4"><button type="button" className="btn primary" disabled={busyAll||saveBusy} onClick={()=>void generateAll()}>{busyAll?<><RefreshCw className="h-4 w-4 animate-spin"/>Generating Year Plan…</>:<><Sparkles className="h-4 w-4"/>Generate AI Year Plan</>}</button><button type="button" className="btn ghost" disabled={busyAll||saveBusy} onClick={()=>void saveAll(false)}><Save className="h-4 w-4"/>Save Draft</button><button type="button" className="btn primary" disabled={busyAll||saveBusy} onClick={()=>void saveAll(true)}><CheckCircle2 className="h-4 w-4"/>Finalize Year Plan</button><SmartPrintDialog targetId="academic-output-year-plan" title={`${group?.className||''} Yearly Planning`} defaultPaper="A3" defaultOrientation="landscape" moduleName="year-plan"/></div></div>
    <div id="academic-output-year-plan" className="card print-root year-plan-print-root"><div className="year-plan-document-head"><div className="year-plan-school">{schoolName}</div><div className="year-plan-main-title"><span>Yearly Planning</span><span dir="rtl">سالانہ منصوبہ بندی</span></div><div className="year-plan-meta"><span><b>Academic Year:</b> {group?.academicYear||'—'}</span><span><b>Class:</b> {group?.className||'—'}</span><span><b>Teacher:</b> {teacherName}</span></div></div><div className="year-plan-table-scroll"><table className="year-plan-table"><thead><tr><th className="year-plan-subject-head">Assigned Subject</th>{MONTHS.map(month=><th key={month}>{month}</th>)}</tr></thead><tbody>{group?.subjects.map((subject,rowIndex)=>{const draft=ensureDraft(subject);return <tr key={subject.key} className={rowIndex%2===0?'year-plan-row-a':'year-plan-row-b'}><th className="year-plan-subject-cell"><div>{subject.subjectName}</div><small className="screen-only">{subject.divisions.length?`Divisions: ${subject.divisions.join(', ')}`:''}</small><button type="button" className="screen-only year-plan-regenerate" disabled={busyAll||saveBusy||busySubject===subject.key||!subject.textbooks.length} onClick={()=>void generateOne(subject).catch(e=>setError(e instanceof Error?e.message:'Generation failed.'))}>{busySubject===subject.key?'Generating…':subject.textbooks.length?'Regenerate subject':'Textbook not ready'}</button></th>{MONTHS.map(month=>{const cell=draft.months.find(item=>item.month===month)||{month,content:'',kind:'teaching' as const};const presentation=resolveAcademicTextPresentation({languageHint:subject.assignment.medium||subject.textbooks[0]?.medium||'',text:cell.content});return <td key={month} data-kind={cell.kind}><textarea className={`screen-only year-plan-cell-editor ${presentation.className}`} dir={presentation.dir} lang={presentation.languageCode==='auto'?undefined:presentation.languageCode} value={cell.content} onChange={e=>updateCell(subject,month,e.target.value)} placeholder="Chapter / Unit / Page / Revision…"/><div className={`print-only year-plan-cell-print ${presentation.className}`} dir={presentation.dir} lang={presentation.languageCode==='auto'?undefined:presentation.languageCode}>{cell.content||'—'}</div></td>})}</tr>})}</tbody></table></div><div className="print-only year-plan-signatures"><span>Subject Teacher Signature: __________________</span><span>Headmaster Signature: __________________</span></div></div>
  </section>;
}
