import { Language } from '../types';

export type AdmissionWorkflowCopy = {
  studentStep: string; guardianStep: string; addressStep: string; documentsStep: string; reviewStep: string;
  continue: string; back: string; saveDraftNote: string; draftRestored: string;
  birthPlace: string; guardianRelation: string; father: string; mother: string; guardian: string;
  alternateMobile: string; occupation: string; addressLine: string; city: string; district: string; state: string; pinCode: string;
  previousSchool: string; previousClass: string; medium: string; requiredDocuments: string; optional: string;
  chooseFile: string; remove: string; reviewBeforeSubmit: string; applicationNotAdmission: string;
  trackApplication: string; trackHelp: string; referenceCode: string; checkStatus: string; currentStatus: string; noRecord: string;
  uploadDocuments: string; uploadingDocuments: string; documentUploadFailed: string; duplicateApplication: string; prospectus: string;
  statusNew: string; statusUnderReview: string; statusDocumentsRequested: string; statusVerified: string;
  statusWaitlisted: string; statusApproved: string; statusRejected: string; statusWithdrawn: string;
};

const en: AdmissionWorkflowCopy = {
  studentStep:'Student', guardianStep:'Parent / Guardian', addressStep:'Address & School', documentsStep:'Documents', reviewStep:'Review',
  continue:'Continue', back:'Back', saveDraftNote:'Your unfinished form is saved only on this device.', draftRestored:'Your saved form has been restored.',
  birthPlace:'Place of birth', guardianRelation:'Relationship to student', father:'Father', mother:'Mother', guardian:'Guardian',
  alternateMobile:'Alternate mobile', occupation:'Occupation', addressLine:'Full residential address', city:'City / Town', district:'District', state:'State', pinCode:'PIN code',
  previousSchool:'Previous school', previousClass:'Previous class', medium:'Medium of instruction', requiredDocuments:'Required documents', optional:'Optional',
  chooseFile:'Choose file', remove:'Remove', reviewBeforeSubmit:'Review every detail before final submission.', applicationNotAdmission:'Submission creates an application for school review. It does not confirm admission or create a student login.',
  trackApplication:'Track application', trackHelp:'Enter the application reference and guardian mobile number.', referenceCode:'Application reference', checkStatus:'Check status', currentStatus:'Current status', noRecord:'No matching application was found.',
  uploadDocuments:'Upload documents', uploadingDocuments:'Uploading documents…', prospectus:'Download Prospectus', documentUploadFailed:'Application was received, but one or more documents could not be uploaded. Keep the reference and contact the school.', duplicateApplication:'A matching application already exists. Use the displayed reference to track it.',
  statusNew:'Submitted', statusUnderReview:'Under review', statusDocumentsRequested:'Documents requested', statusVerified:'Documents verified', statusWaitlisted:'Waitlisted', statusApproved:'Approved', statusRejected:'Rejected', statusWithdrawn:'Withdrawn'
};

const copies: Record<string, Partial<AdmissionWorkflowCopy>> = {
  hi:{studentStep:'विद्यार्थी',guardianStep:'माता-पिता / अभिभावक',addressStep:'पता और पिछला स्कूल',documentsStep:'दस्तावेज़',reviewStep:'समीक्षा',continue:'आगे बढ़ें',back:'वापस',saveDraftNote:'अधूरा फॉर्म केवल इसी डिवाइस पर सुरक्षित रहता है।',draftRestored:'आपका सुरक्षित फॉर्म पुनः प्राप्त हो गया है।',birthPlace:'जन्म स्थान',guardianRelation:'विद्यार्थी से संबंध',father:'पिता',mother:'माता',guardian:'अभिभावक',alternateMobile:'वैकल्पिक मोबाइल',occupation:'व्यवसाय',addressLine:'पूरा निवास पता',city:'शहर / कस्बा',district:'ज़िला',state:'राज्य',pinCode:'पिन कोड',previousSchool:'पिछला स्कूल',previousClass:'पिछली कक्षा',medium:'शिक्षण माध्यम',requiredDocuments:'आवश्यक दस्तावेज़',optional:'वैकल्पिक',chooseFile:'फ़ाइल चुनें',remove:'हटाएँ',reviewBeforeSubmit:'अंतिम जमा करने से पहले सभी विवरण जाँचें।',applicationNotAdmission:'आवेदन स्कूल की समीक्षा के लिए है। इससे प्रवेश की पुष्टि या छात्र लॉगिन नहीं बनता।',trackApplication:'आवेदन की स्थिति देखें',trackHelp:'आवेदन संदर्भ और अभिभावक मोबाइल नंबर दर्ज करें।',referenceCode:'आवेदन संदर्भ',checkStatus:'स्थिति जाँचें',currentStatus:'वर्तमान स्थिति',noRecord:'मेल खाता आवेदन नहीं मिला।',uploadDocuments:'दस्तावेज़ अपलोड करें',uploadingDocuments:'दस्तावेज़ अपलोड हो रहे हैं…',prospectus:'प्रॉस्पेक्टस डाउनलोड करें',documentUploadFailed:'आवेदन प्राप्त हुआ, लेकिन कुछ दस्तावेज़ अपलोड नहीं हुए। संदर्भ सुरक्षित रखें और स्कूल से संपर्क करें।',duplicateApplication:'इसी जानकारी का आवेदन पहले से मौजूद है। दिए गए संदर्भ से स्थिति देखें।',statusNew:'जमा हुआ',statusUnderReview:'समीक्षा में',statusDocumentsRequested:'दस्तावेज़ माँगे गए',statusVerified:'दस्तावेज़ सत्यापित',statusWaitlisted:'प्रतीक्षा सूची',statusApproved:'स्वीकृत',statusRejected:'अस्वीकृत',statusWithdrawn:'वापस लिया गया'},
  ur:{studentStep:'طالب علم',guardianStep:'والدین / سرپرست',addressStep:'پتہ اور سابقہ اسکول',documentsStep:'دستاویزات',reviewStep:'جائزہ',continue:'آگے بڑھیں',back:'واپس',saveDraftNote:'نامکمل فارم صرف اسی ڈیوائس پر محفوظ رہتا ہے۔',draftRestored:'آپ کا محفوظ فارم بحال کر دیا گیا ہے۔',birthPlace:'جائے پیدائش',guardianRelation:'طالب علم سے رشتہ',father:'والد',mother:'والدہ',guardian:'سرپرست',alternateMobile:'متبادل موبائل',occupation:'پیشہ',addressLine:'مکمل رہائشی پتہ',city:'شہر / قصبہ',district:'ضلع',state:'ریاست',pinCode:'پن کوڈ',previousSchool:'سابقہ اسکول',previousClass:'پچھلی جماعت',medium:'ذریعۂ تعلیم',requiredDocuments:'ضروری دستاویزات',optional:'اختیاری',chooseFile:'فائل منتخب کریں',remove:'ہٹائیں',reviewBeforeSubmit:'حتمی جمع کرنے سے پہلے تمام معلومات دیکھ لیں۔',applicationNotAdmission:'درخواست صرف اسکول کے جائزے کے لیے ہے۔ اس سے داخلہ منظور یا طالب علم لاگ اِن نہیں بنتا۔',trackApplication:'درخواست کی حالت دیکھیں',trackHelp:'درخواست ریفرنس اور سرپرست کا موبائل نمبر درج کریں۔',referenceCode:'درخواست ریفرنس',checkStatus:'حالت دیکھیں',currentStatus:'موجودہ حالت',noRecord:'کوئی مماثل درخواست نہیں ملی۔',uploadDocuments:'دستاویزات اپ لوڈ کریں',uploadingDocuments:'دستاویزات اپ لوڈ ہو رہی ہیں…',prospectus:'پراسپیکٹس ڈاؤن لوڈ کریں',documentUploadFailed:'درخواست موصول ہوئی، مگر کچھ دستاویزات اپ لوڈ نہ ہو سکیں۔ ریفرنس محفوظ رکھیں اور اسکول سے رابطہ کریں۔',duplicateApplication:'اسی معلومات کے ساتھ درخواست پہلے سے موجود ہے۔ دکھائے گئے ریفرنس سے حالت دیکھیں۔',statusNew:'جمع شدہ',statusUnderReview:'زیرِ جائزہ',statusDocumentsRequested:'دستاویزات مطلوب',statusVerified:'دستاویزات تصدیق شدہ',statusWaitlisted:'انتظار فہرست',statusApproved:'منظور',statusRejected:'مسترد',statusWithdrawn:'واپس لی گئی'},
  mr:{studentStep:'विद्यार्थी',guardianStep:'पालक / संरक्षक',addressStep:'पत्ता व मागील शाळा',documentsStep:'कागदपत्रे',reviewStep:'पुनरावलोकन',continue:'पुढे',back:'मागे',saveDraftNote:'अपूर्ण फॉर्म फक्त या उपकरणावर जतन होतो.',draftRestored:'जतन केलेला फॉर्म पुन्हा मिळाला.',birthPlace:'जन्मस्थान',guardianRelation:'विद्यार्थ्याशी नाते',father:'वडील',mother:'आई',guardian:'पालक',alternateMobile:'पर्यायी मोबाइल',occupation:'व्यवसाय',addressLine:'पूर्ण निवासी पत्ता',city:'शहर / गाव',district:'जिल्हा',state:'राज्य',pinCode:'पिन कोड',previousSchool:'मागील शाळा',previousClass:'मागील इयत्ता',medium:'शिक्षण माध्यम',requiredDocuments:'आवश्यक कागदपत्रे',optional:'ऐच्छिक',chooseFile:'फाइल निवडा',remove:'काढा',reviewBeforeSubmit:'अंतिम सादरीकरणापूर्वी सर्व तपशील तपासा.',applicationNotAdmission:'हा अर्ज शाळेच्या परीक्षणासाठी आहे. यामुळे प्रवेश निश्चित किंवा विद्यार्थी लॉगिन तयार होत नाही.',trackApplication:'अर्ज स्थिती पाहा',trackHelp:'अर्ज संदर्भ आणि पालकांचा मोबाइल क्रमांक द्या.',referenceCode:'अर्ज संदर्भ',checkStatus:'स्थिती तपासा',currentStatus:'सध्याची स्थिती',noRecord:'जुळणारा अर्ज सापडला नाही.',uploadDocuments:'कागदपत्रे अपलोड करा',uploadingDocuments:'कागदपत्रे अपलोड होत आहेत…',prospectus:'माहितीपत्रक डाउनलोड करा',documentUploadFailed:'अर्ज प्राप्त झाला, पण काही कागदपत्रे अपलोड झाली नाहीत. संदर्भ जतन करा व शाळेशी संपर्क साधा.',duplicateApplication:'याच माहितीचा अर्ज आधीच आहे. दिलेल्या संदर्भाने स्थिती पाहा.',statusNew:'सादर',statusUnderReview:'तपासणीत',statusDocumentsRequested:'कागदपत्रे मागविली',statusVerified:'कागदपत्रे पडताळली',statusWaitlisted:'प्रतीक्षा यादी',statusApproved:'मंजूर',statusRejected:'नामंजूर',statusWithdrawn:'मागे घेतला'},
  bn:{studentStep:'শিক্ষার্থী',guardianStep:'অভিভাবক',addressStep:'ঠিকানা ও পূর্ববর্তী বিদ্যালয়',documentsStep:'নথি',reviewStep:'পর্যালোচনা',continue:'পরবর্তী',back:'পিছনে',birthPlace:'জন্মস্থান',guardianRelation:'শিক্ষার্থীর সঙ্গে সম্পর্ক',father:'পিতা',mother:'মাতা',guardian:'অভিভাবক',alternateMobile:'বিকল্প মোবাইল',occupation:'পেশা',addressLine:'সম্পূর্ণ ঠিকানা',city:'শহর / নগর',district:'জেলা',state:'রাজ্য',pinCode:'পিন কোড',previousSchool:'পূর্ববর্তী বিদ্যালয়',previousClass:'পূর্ববর্তী শ্রেণি',medium:'শিক্ষার মাধ্যম',requiredDocuments:'প্রয়োজনীয় নথি',optional:'ঐচ্ছিক',chooseFile:'ফাইল বাছুন',remove:'সরান',trackApplication:'আবেদন অনুসরণ করুন',referenceCode:'আবেদন রেফারেন্স',checkStatus:'অবস্থা দেখুন',currentStatus:'বর্তমান অবস্থা',statusNew:'জমা হয়েছে',statusUnderReview:'পর্যালোচনাধীন',statusApproved:'অনুমোদিত',statusRejected:'প্রত্যাখ্যাত'},
  gu:{studentStep:'વિદ્યાર્થી',guardianStep:'વાલી / સંરક્ષક',addressStep:'સરનામું અને અગાઉની શાળા',documentsStep:'દસ્તાવેજો',reviewStep:'સમીક્ષા',continue:'આગળ',back:'પાછળ',birthPlace:'જન્મ સ્થળ',guardianRelation:'વિદ્યાર્થી સાથેનો સંબંધ',father:'પિતા',mother:'માતા',guardian:'સંરક્ષક',alternateMobile:'વૈકલ્પિક મોબાઇલ',occupation:'વ્યવસાય',addressLine:'પૂર્ણ રહેણાંક સરનામું',city:'શહેર / ગામ',district:'જિલ્લો',state:'રાજ્ય',pinCode:'પિન કોડ',previousSchool:'અગાઉની શાળા',previousClass:'અગાઉનો ધોરણ',medium:'શિક્ષણ માધ્યમ',requiredDocuments:'જરૂરી દસ્તાવેજો',optional:'વૈકલ્પિક',chooseFile:'ફાઇલ પસંદ કરો',remove:'દૂર કરો',trackApplication:'અરજીની સ્થિતિ જુઓ',referenceCode:'અરજી સંદર્ભ',checkStatus:'સ્થિતિ તપાસો',currentStatus:'વર્તમાન સ્થિતિ',statusNew:'સબમિટ',statusUnderReview:'સમીક્ષામાં',statusApproved:'મંજૂર',statusRejected:'નામંજૂર'},
  ta:{studentStep:'மாணவர்',guardianStep:'பெற்றோர் / பாதுகாவலர்',addressStep:'முகவரி மற்றும் முந்தைய பள்ளி',documentsStep:'ஆவணங்கள்',reviewStep:'மதிப்பாய்வு',continue:'தொடரவும்',back:'பின்செல்',birthPlace:'பிறந்த இடம்',guardianRelation:'மாணவருடனான உறவு',father:'தந்தை',mother:'தாய்',guardian:'பாதுகாவலர்',alternateMobile:'மாற்று கைபேசி',occupation:'தொழில்',addressLine:'முழு முகவரி',city:'நகரம் / ஊர்',district:'மாவட்டம்',state:'மாநிலம்',pinCode:'அஞ்சல் குறியீடு',previousSchool:'முந்தைய பள்ளி',previousClass:'முந்தைய வகுப்பு',medium:'பயிற்று மொழி',requiredDocuments:'தேவையான ஆவணங்கள்',optional:'விருப்பம்',chooseFile:'கோப்பை தேர்வு செய்க',remove:'நீக்கு',trackApplication:'விண்ணப்ப நிலை',referenceCode:'விண்ணப்ப குறிப்பு',checkStatus:'நிலையை பார்க்க',currentStatus:'தற்போதைய நிலை',statusNew:'சமர்ப்பிக்கப்பட்டது',statusUnderReview:'பரிசீலனையில்',statusApproved:'அனுமதிக்கப்பட்டது',statusRejected:'நிராகரிக்கப்பட்டது'},
  te:{studentStep:'విద్యార్థి',guardianStep:'తల్లిదండ్రులు / సంరక్షకుడు',addressStep:'చిరునామా మరియు పూర్వ పాఠశాల',documentsStep:'పత్రాలు',reviewStep:'సమీక్ష',continue:'కొనసాగించండి',back:'వెనుకకు',birthPlace:'జన్మ స్థలం',guardianRelation:'విద్యార్థితో సంబంధం',father:'తండ్రి',mother:'తల్లి',guardian:'సంరక్షకుడు',alternateMobile:'ప్రత్యామ్నాయ మొబైల్',occupation:'వృత్తి',addressLine:'పూర్తి చిరునామా',city:'నగరం / పట్టణం',district:'జిల్లా',state:'రాష్ట్రం',pinCode:'పిన్ కోడ్',previousSchool:'పూర్వ పాఠశాల',previousClass:'పూర్వ తరగతి',medium:'బోధనా మాధ్యమం',requiredDocuments:'అవసరమైన పత్రాలు',optional:'ఐచ్ఛికం',chooseFile:'ఫైల్ ఎంచుకోండి',remove:'తొలగించండి',trackApplication:'దరఖాస్తు స్థితి',referenceCode:'దరఖాస్తు సూచన',checkStatus:'స్థితి చూడండి',currentStatus:'ప్రస్తుత స్థితి',statusNew:'సమర్పించబడింది',statusUnderReview:'సమీక్షలో',statusApproved:'ఆమోదించబడింది',statusRejected:'తిరస్కరించబడింది'},
  kn:{studentStep:'ವಿದ್ಯಾರ್ಥಿ',guardianStep:'ಪೋಷಕರು / ಸಂರಕ್ಷಕರು',addressStep:'ವಿಳಾಸ ಮತ್ತು ಹಿಂದಿನ ಶಾಲೆ',documentsStep:'ದಾಖಲೆಗಳು',reviewStep:'ಪರಿಶೀಲನೆ',continue:'ಮುಂದುವರಿಸಿ',back:'ಹಿಂದೆ',birthPlace:'ಜನ್ಮ ಸ್ಥಳ',guardianRelation:'ವಿದ್ಯಾರ್ಥಿಯೊಂದಿಗೆ ಸಂಬಂಧ',father:'ತಂದೆ',mother:'ತಾಯಿ',guardian:'ಸಂರಕ್ಷಕ',alternateMobile:'ಪರ್ಯಾಯ ಮೊಬೈಲ್',occupation:'ವೃತ್ತಿ',addressLine:'ಪೂರ್ಣ ವಿಳಾಸ',city:'ನಗರ / ಪಟ್ಟಣ',district:'ಜಿಲ್ಲೆ',state:'ರಾಜ್ಯ',pinCode:'ಪಿನ್ ಕೋಡ್',previousSchool:'ಹಿಂದಿನ ಶಾಲೆ',previousClass:'ಹಿಂದಿನ ತರಗತಿ',medium:'ಬೋಧನಾ ಮಾಧ್ಯಮ',requiredDocuments:'ಅಗತ್ಯ ದಾಖಲೆಗಳು',optional:'ಐಚ್ಛಿಕ',chooseFile:'ಫೈಲ್ ಆಯ್ಕೆ',remove:'ತೆಗೆದುಹಾಕಿ',trackApplication:'ಅರ್ಜಿಯ ಸ್ಥಿತಿ',referenceCode:'ಅರ್ಜಿಯ ಉಲ್ಲೇಖ',checkStatus:'ಸ್ಥಿತಿ ಪರಿಶೀಲಿಸಿ',currentStatus:'ಪ್ರಸ್ತುತ ಸ್ಥಿತಿ',statusNew:'ಸಲ್ಲಿಸಲಾಗಿದೆ',statusUnderReview:'ಪರಿಶೀಲನೆಯಲ್ಲಿದೆ',statusApproved:'ಅನುಮೋದಿಸಲಾಗಿದೆ',statusRejected:'ನಿರಾಕರಿಸಲಾಗಿದೆ'},
  ml:{studentStep:'വിദ്യാർത്ഥി',guardianStep:'രക്ഷിതാവ്',addressStep:'വിലാസവും മുൻ സ്കൂളും',documentsStep:'രേഖകൾ',reviewStep:'പരിശോധന',continue:'തുടരുക',back:'പിന്നോട്ട്',birthPlace:'ജനനസ്ഥലം',guardianRelation:'വിദ്യാർത്ഥിയുമായുള്ള ബന്ധം',father:'പിതാവ്',mother:'മാതാവ്',guardian:'രക്ഷിതാവ്',alternateMobile:'മറ്റൊരു മൊബൈൽ',occupation:'തൊഴിൽ',addressLine:'പൂർണ്ണ വിലാസം',city:'നഗരം / പട്ടണം',district:'ജില്ല',state:'സംസ്ഥാനം',pinCode:'പിൻ കോഡ്',previousSchool:'മുൻ സ്കൂൾ',previousClass:'മുൻ ക്ലാസ്',medium:'പഠനമാധ്യമം',requiredDocuments:'ആവശ്യ രേഖകൾ',optional:'ഐച്ഛികം',chooseFile:'ഫയൽ തിരഞ്ഞെടുക്കുക',remove:'നീക്കുക',trackApplication:'അപേക്ഷ നില',referenceCode:'അപേക്ഷ റഫറൻസ്',checkStatus:'നില പരിശോധിക്കുക',currentStatus:'നിലവിലെ നില',statusNew:'സമർപ്പിച്ചു',statusUnderReview:'പരിശോധനയിൽ',statusApproved:'അംഗീകരിച്ചു',statusRejected:'നിരസിച്ചു'},
  pa:{studentStep:'ਵਿਦਿਆਰਥੀ',guardianStep:'ਮਾਤਾ-ਪਿਤਾ / ਸਰਪ੍ਰਸਤ',addressStep:'ਪਤਾ ਅਤੇ ਪਿਛਲਾ ਸਕੂਲ',documentsStep:'ਦਸਤਾਵੇਜ਼',reviewStep:'ਸਮੀਖਿਆ',continue:'ਅੱਗੇ',back:'ਵਾਪਸ',birthPlace:'ਜਨਮ ਸਥਾਨ',guardianRelation:'ਵਿਦਿਆਰਥੀ ਨਾਲ ਰਿਸ਼ਤਾ',father:'ਪਿਤਾ',mother:'ਮਾਤਾ',guardian:'ਸਰਪ੍ਰਸਤ',alternateMobile:'ਵਿਕਲਪਿਕ ਮੋਬਾਈਲ',occupation:'ਪੇਸ਼ਾ',addressLine:'ਪੂਰਾ ਪਤਾ',city:'ਸ਼ਹਿਰ / ਕਸਬਾ',district:'ਜ਼ਿਲ੍ਹਾ',state:'ਰਾਜ',pinCode:'ਪਿਨ ਕੋਡ',previousSchool:'ਪਿਛਲਾ ਸਕੂਲ',previousClass:'ਪਿਛਲੀ ਜਮਾਤ',medium:'ਸਿੱਖਿਆ ਮਾਧਿਅਮ',requiredDocuments:'ਲੋੜੀਂਦੇ ਦਸਤਾਵੇਜ਼',optional:'ਵਿਕਲਪਿਕ',chooseFile:'ਫਾਈਲ ਚੁਣੋ',remove:'ਹਟਾਓ',trackApplication:'ਅਰਜ਼ੀ ਦੀ ਸਥਿਤੀ',referenceCode:'ਅਰਜ਼ੀ ਹਵਾਲਾ',checkStatus:'ਸਥਿਤੀ ਵੇਖੋ',currentStatus:'ਮੌਜੂਦਾ ਸਥਿਤੀ',statusNew:'ਜਮ੍ਹਾਂ',statusUnderReview:'ਸਮੀਖਿਆ ਵਿੱਚ',statusApproved:'ਮਨਜ਼ੂਰ',statusRejected:'ਰੱਦ'},
  as:{studentStep:'শিক্ষাৰ্থী',guardianStep:'অভিভাৱক',addressStep:'ঠিকনা আৰু পূৰ্বৰ বিদ্যালয়',documentsStep:'নথি',reviewStep:'পৰ্যালোচনা',continue:'আগবাঢ়ক',back:'পিছলৈ',requiredDocuments:'প্ৰয়োজনীয় নথি',chooseFile:'ফাইল বাছক',trackApplication:'আবেদনৰ স্থিতি',referenceCode:'আবেদন ৰেফাৰেন্স',checkStatus:'স্থিতি চাওক'},
  brx:{studentStep:'फरायसा',guardianStep:'बिमा-बिफा / अभिभावक',addressStep:'थं आरो आगोलनि स्कुल',documentsStep:'लाइजोम',reviewStep:'नायफिन',continue:'सिगां',back:'उनाव',requiredDocuments:'गोनांथि लाइजोम',chooseFile:'फाइल सायख',trackApplication:'आबेदननि थासारि',referenceCode:'आबेदन रेफारेन्स',checkStatus:'थासारि नाय'},
  doi:{studentStep:'विद्यार्थी',guardianStep:'माता-पिता / अभिभावक',addressStep:'पता ते पिछला स्कूल',documentsStep:'दस्तावेज',reviewStep:'समीक्षा',continue:'अग्गें',back:'पिच्छें',requiredDocuments:'लोड़चदे दस्तावेज',chooseFile:'फाइल चुनो',trackApplication:'दरखास्त स्थिति',referenceCode:'दरखास्त संदर्भ',checkStatus:'स्थिति जांचो'},
  ks:{studentStep:'طالب علم',guardianStep:'والدین / سرپرست',addressStep:'پتہ تہٕ پٔتِم اسکول',documentsStep:'دستاویزات',reviewStep:'جائزہ',continue:'برٛونہہ',back:'واپس',requiredDocuments:'ضروری دستاویزات',chooseFile:'فائل ژارُن',trackApplication:'درخواست حالت',referenceCode:'درخواست ریفرنس',checkStatus:'حالت وچھو'},
  kok:{studentStep:'विद्यार्थी',guardianStep:'पालक',addressStep:'पत्तो आनी आदली शाळा',documentsStep:'कागदपत्रां',reviewStep:'पळोवणी',continue:'फुडें',back:'फाटीं',requiredDocuments:'गरजेची कागदपत्रां',chooseFile:'फायल निवडात',trackApplication:'अर्ज स्थिती',referenceCode:'अर्ज संदर्भ',checkStatus:'स्थिती पळयात'},
  mai:{studentStep:'विद्यार्थी',guardianStep:'अभिभावक',addressStep:'पता आ पिछला विद्यालय',documentsStep:'कागजात',reviewStep:'समीक्षा',continue:'आगाँ',back:'पाछाँ',requiredDocuments:'आवश्यक कागजात',chooseFile:'फाइल चुनू',trackApplication:'आवेदन स्थिति',referenceCode:'आवेदन संदर्भ',checkStatus:'स्थिति देखू'},
  mni:{studentStep:'ꯃꯍꯩꯔꯣꯏ',guardianStep:'ꯃꯄꯥ-ꯃꯃꯥ / ꯂꯣꯏꯅꯕ',addressStep:'ꯂꯩꯐꯝ ꯑꯃꯁꯨꯡ ꯃꯃꯥꯡꯒꯤ ꯁ꯭ꯀꯨꯜ',documentsStep:'ꯆꯦꯔꯣꯜ',reviewStep:'ꯌꯦꯡꯁꯤꯟꯕ',continue:'ꯃꯈꯥ ꯆꯠꯊꯧ',back:'ꯍꯟꯅꯥ',requiredDocuments:'ꯃꯊꯧ ꯇꯥꯕ ꯆꯦꯔꯣꯜ',chooseFile:'ꯐꯥꯏꯜ ꯈꯜꯂꯧ',trackApplication:'ꯑꯦꯄ꯭ꯂꯤꯀꯦꯁꯟ ꯐꯤꯕꯝ',referenceCode:'ꯔꯦꯐꯔꯦꯟꯁ',checkStatus:'ꯐꯤꯕꯝ ꯌꯦꯡꯉꯨ'},
  ne:{studentStep:'विद्यार्थी',guardianStep:'अभिभावक',addressStep:'ठेगाना र अघिल्लो विद्यालय',documentsStep:'कागजात',reviewStep:'समीक्षा',continue:'अगाडि',back:'पछाडि',requiredDocuments:'आवश्यक कागजात',chooseFile:'फाइल छान्नुहोस्',trackApplication:'आवेदन स्थिति',referenceCode:'आवेदन सन्दर्भ',checkStatus:'स्थिति हेर्नुहोस्'},
  or:{studentStep:'ଛାତ୍ର',guardianStep:'ଅଭିଭାବକ',addressStep:'ଠିକଣା ଏବଂ ପୂର୍ବ ବିଦ୍ୟାଳୟ',documentsStep:'ଦଲିଲ',reviewStep:'ସମୀକ୍ଷା',continue:'ଆଗକୁ',back:'ପଛକୁ',requiredDocuments:'ଆବଶ୍ୟକ ଦଲିଲ',chooseFile:'ଫାଇଲ ବାଛନ୍ତୁ',trackApplication:'ଆବେଦନ ସ୍ଥିତି',referenceCode:'ଆବେଦନ ସନ୍ଦର୍ଭ',checkStatus:'ସ୍ଥିତି ଦେଖନ୍ତୁ'},
  sa:{studentStep:'विद्यार्थी',guardianStep:'अभिभावकः',addressStep:'निवासः पूर्वविद्यालयश्च',documentsStep:'पत्राणि',reviewStep:'पुनरवलोकनम्',continue:'अग्रे',back:'पृष्ठतः',requiredDocuments:'आवश्यकपत्राणि',chooseFile:'सञ्चिकां चिनुत',trackApplication:'आवेदनस्थितिः',referenceCode:'आवेदनसन्दर्भः',checkStatus:'स्थितिं पश्यतु'},
  sat:{studentStep:'ᱯᱟᱹᱴᱷᱩᱣᱟᱹ',guardianStep:'ᱜᱚᱜᱚ-ᱵᱟᱵᱟ / ᱦᱟᱹᱨᱤᱭᱟᱹᱨ',addressStep:'ᱴᱷᱟᱶ ᱟᱨ ᱢᱟᱲᱟᱝ ᱤᱥᱠᱩᱞ',documentsStep:'ᱫᱚᱞᱤᱞ',reviewStep:'ᱧᱮᱞ ᱫᱚᱦᱲᱟ',continue:'ᱞᱟᱦᱟ',back:'ᱛᱟᱭᱚᱢ',requiredDocuments:'ᱞᱟᱹᱠᱛᱤ ᱫᱚᱞᱤᱞ',chooseFile:'ᱨᱮᱫ ᱵᱟᱪᱷᱟᱣ',trackApplication:'ᱟᱨᱫᱟᱥ ᱫᱚᱥᱟ',referenceCode:'ᱟᱨᱫᱟᱥ ᱨᱮᱯᱷᱟᱨᱮᱱᱥ',checkStatus:'ᱫᱚᱥᱟ ᱧᱮᱞ'},
  sd:{studentStep:'شاگرد',guardianStep:'والدين / سنڀاليندڙ',addressStep:'پتو ۽ اڳوڻو اسڪول',documentsStep:'دستاويز',reviewStep:'جائزو',continue:'اڳتي',back:'واپس',requiredDocuments:'گهربل دستاويز',chooseFile:'فائل چونڊيو',trackApplication:'درخواست جي حالت',referenceCode:'درخواست حوالو',checkStatus:'حالت ڏسو'}
};


// Complete the admission-specific workflow vocabulary for every active public
// language. Campaign-authored titles, descriptions and document labels remain
// editable per language in Website Studio.
const supplements: Record<string, Partial<AdmissionWorkflowCopy>> = {
  bn:{saveDraftNote:'অসম্পূর্ণ ফর্মটি শুধু এই ডিভাইসে সংরক্ষিত থাকে।',draftRestored:'আপনার সংরক্ষিত ফর্মটি পুনরুদ্ধার করা হয়েছে।',reviewBeforeSubmit:'চূড়ান্তভাবে জমা দেওয়ার আগে সব তথ্য যাচাই করুন।',applicationNotAdmission:'এটি বিদ্যালয়ের পর্যালোচনার জন্য একটি আবেদন। এতে ভর্তি নিশ্চিত বা শিক্ষার্থীর লগইন তৈরি হয় না।',trackHelp:'আবেদনের রেফারেন্স ও অভিভাবকের মোবাইল নম্বর লিখুন।',noRecord:'মিল থাকা কোনো আবেদন পাওয়া যায়নি।',uploadDocuments:'নথি আপলোড করুন',uploadingDocuments:'নথি আপলোড হচ্ছে…',prospectus:'প্রসপেক্টাস ডাউনলোড করুন',documentUploadFailed:'আবেদন গ্রহণ করা হয়েছে, কিন্তু এক বা একাধিক নথি আপলোড হয়নি। রেফারেন্সটি রাখুন এবং বিদ্যালয়ের সঙ্গে যোগাযোগ করুন।',duplicateApplication:'একই তথ্যের একটি আবেদন আগে থেকেই আছে। দেখানো রেফারেন্স দিয়ে অবস্থা দেখুন।',statusDocumentsRequested:'নথি চাওয়া হয়েছে',statusVerified:'নথি যাচাই হয়েছে',statusWaitlisted:'অপেক্ষমাণ তালিকায়',statusWithdrawn:'প্রত্যাহার করা হয়েছে'},
  gu:{saveDraftNote:'અધૂરું ફોર્મ ફક્ત આ ઉપકરણમાં જ સાચવાય છે.',draftRestored:'તમારું સાચવેલું ફોર્મ પુનઃસ્થાપિત થયું છે.',reviewBeforeSubmit:'અંતિમ સબમિશન પહેલાં બધી વિગતો તપાસો.',applicationNotAdmission:'આ અરજી શાળાની સમીક્ષા માટે છે. તે પ્રવેશની પુષ્ટિ કે વિદ્યાર્થી લોગિન બનાવતી નથી.',trackHelp:'અરજી સંદર્ભ અને વાલીનો મોબાઇલ નંબર દાખલ કરો.',noRecord:'મેળ ખાતી અરજી મળી નથી.',uploadDocuments:'દસ્તાવેજો અપલોડ કરો',uploadingDocuments:'દસ્તાવેજો અપલોડ થઈ રહ્યા છે…',prospectus:'પ્રોસ્પેક્ટસ ડાઉનલોડ કરો',documentUploadFailed:'અરજી મળી ગઈ છે, પરંતુ એક અથવા વધુ દસ્તાવેજો અપલોડ થયા નથી. સંદર્ભ સાચવો અને શાળાનો સંપર્ક કરો.',duplicateApplication:'આ જ માહિતીની અરજી પહેલેથી છે. દર્શાવેલા સંદર્ભથી સ્થિતિ જુઓ.',statusDocumentsRequested:'દસ્તાવેજો માંગવામાં આવ્યા',statusVerified:'દસ્તાવેજો ચકાસાયા',statusWaitlisted:'પ્રતીક્ષા યાદીમાં',statusWithdrawn:'પાછી ખેંચાઈ'},
  ta:{saveDraftNote:'முடிக்காத படிவம் இந்த சாதனத்தில் மட்டும் சேமிக்கப்படும்.',draftRestored:'சேமித்த படிவம் மீட்டெடுக்கப்பட்டது.',reviewBeforeSubmit:'இறுதியாக சமர்ப்பிக்கும் முன் அனைத்து விவரங்களையும் சரிபார்க்கவும்.',applicationNotAdmission:'இது பள்ளி பரிசீலனைக்கான விண்ணப்பம் மட்டுமே. இது சேர்க்கையை உறுதிப்படுத்தவோ மாணவர் உள்நுழைவை உருவாக்கவோ செய்யாது.',trackHelp:'விண்ணப்பக் குறிப்பு மற்றும் பாதுகாவலரின் கைபேசி எண்ணை உள்ளிடவும்.',noRecord:'பொருந்தும் விண்ணப்பம் கிடைக்கவில்லை.',uploadDocuments:'ஆவணங்களை பதிவேற்றவும்',uploadingDocuments:'ஆவணங்கள் பதிவேற்றப்படுகின்றன…',prospectus:'விளக்கப்புத்தகத்தைப் பதிவிறக்கவும்',documentUploadFailed:'விண்ணப்பம் பெறப்பட்டது; ஆனால் சில ஆவணங்கள் பதிவேற்றப்படவில்லை. குறிப்பை பாதுகாத்து பள்ளியை தொடர்புகொள்ளவும்.',duplicateApplication:'இதே தகவலுடன் விண்ணப்பம் ஏற்கனவே உள்ளது. காட்டப்பட்ட குறிப்பால் நிலையை பார்க்கவும்.',statusDocumentsRequested:'ஆவணங்கள் கோரப்பட்டுள்ளன',statusVerified:'ஆவணங்கள் சரிபார்க்கப்பட்டன',statusWaitlisted:'காத்திருப்பு பட்டியல்',statusWithdrawn:'திரும்பப் பெறப்பட்டது'},
  te:{saveDraftNote:'పూర్తి కాని ఫారం ఈ పరికరంలో మాత్రమే సేవ్ అవుతుంది.',draftRestored:'సేవ్ చేసిన ఫారం తిరిగి పొందబడింది.',reviewBeforeSubmit:'చివరిగా సమర్పించే ముందు అన్ని వివరాలు పరిశీలించండి.',applicationNotAdmission:'ఇది పాఠశాల సమీక్ష కోసం మాత్రమే దరఖాస్తు. ఇది ప్రవేశాన్ని నిర్ధారించదు లేదా విద్యార్థి లాగిన్‌ను సృష్టించదు.',trackHelp:'దరఖాస్తు సూచన మరియు సంరక్షకుడి మొబైల్ నంబర్ నమోదు చేయండి.',noRecord:'సరిపోలే దరఖాస్తు కనబడలేదు.',uploadDocuments:'పత్రాలను అప్‌లోడ్ చేయండి',uploadingDocuments:'పత్రాలు అప్‌లోడ్ అవుతున్నాయి…',prospectus:'ప్రాస్పెక్టస్ డౌన్‌లోడ్ చేయండి',documentUploadFailed:'దరఖాస్తు అందింది, కానీ కొన్ని పత్రాలు అప్‌లోడ్ కాలేదు. సూచనను భద్రపరచి పాఠశాలను సంప్రదించండి.',duplicateApplication:'ఇదే సమాచారంతో దరఖాస్తు ఇప్పటికే ఉంది. చూపిన సూచనతో స్థితి చూడండి.',statusDocumentsRequested:'పత్రాలు కోరబడ్డాయి',statusVerified:'పత్రాలు ధృవీకరించబడ్డాయి',statusWaitlisted:'వేచి జాబితాలో',statusWithdrawn:'ఉపసంహరించబడింది'},
  kn:{saveDraftNote:'ಪೂರ್ಣಗೊಳ್ಳದ ನಮೂನೆ ಈ ಸಾಧನದಲ್ಲೇ ಉಳಿಯುತ್ತದೆ.',draftRestored:'ಉಳಿಸಿದ ನಮೂನೆಯನ್ನು ಮರುಸ್ಥಾಪಿಸಲಾಗಿದೆ.',reviewBeforeSubmit:'ಅಂತಿಮ ಸಲ್ಲಿಕೆಗೆ ಮೊದಲು ಎಲ್ಲಾ ವಿವರಗಳನ್ನು ಪರಿಶೀಲಿಸಿ.',applicationNotAdmission:'ಇದು ಶಾಲೆಯ ಪರಿಶೀಲನೆಗಾಗಿ ಅರ್ಜಿ ಮಾತ್ರ. ಇದು ಪ್ರವೇಶವನ್ನು ದೃಢಪಡಿಸುವುದಿಲ್ಲ ಅಥವಾ ವಿದ್ಯಾರ್ಥಿ ಲಾಗಿನ್ ರಚಿಸುವುದಿಲ್ಲ.',trackHelp:'ಅರ್ಜಿಯ ಉಲ್ಲೇಖ ಮತ್ತು ಪೋಷಕರ ಮೊಬೈಲ್ ಸಂಖ್ಯೆಯನ್ನು ನಮೂದಿಸಿ.',noRecord:'ಹೊಂದುವ ಅರ್ಜಿ ಕಂಡುಬಂದಿಲ್ಲ.',uploadDocuments:'ದಾಖಲೆಗಳನ್ನು ಅಪ್‌ಲೋಡ್ ಮಾಡಿ',uploadingDocuments:'ದಾಖಲೆಗಳು ಅಪ್‌ಲೋಡ್ ಆಗುತ್ತಿವೆ…',prospectus:'ಪ್ರಾಸ್ಪೆಕ್ಟಸ್ ಡೌನ್‌ಲೋಡ್ ಮಾಡಿ',documentUploadFailed:'ಅರ್ಜಿಯನ್ನು ಸ್ವೀಕರಿಸಲಾಗಿದೆ, ಆದರೆ ಕೆಲವು ದಾಖಲೆಗಳು ಅಪ್‌ಲೋಡ್ ಆಗಲಿಲ್ಲ. ಉಲ್ಲೇಖವನ್ನು ಉಳಿಸಿ ಶಾಲೆಯನ್ನು ಸಂಪರ್ಕಿಸಿ.',duplicateApplication:'ಇದೇ ಮಾಹಿತಿಯ ಅರ್ಜಿ ಈಗಾಗಲೇ ಇದೆ. ತೋರಿಸಿದ ಉಲ್ಲೇಖದಿಂದ ಸ್ಥಿತಿ ನೋಡಿ.',statusDocumentsRequested:'ದಾಖಲೆಗಳನ್ನು ಕೇಳಲಾಗಿದೆ',statusVerified:'ದಾಖಲೆಗಳನ್ನು ಪರಿಶೀಲಿಸಲಾಗಿದೆ',statusWaitlisted:'ನಿರೀಕ್ಷಾ ಪಟ್ಟಿಯಲ್ಲಿ',statusWithdrawn:'ಹಿಂಪಡೆಯಲಾಗಿದೆ'},
  ml:{saveDraftNote:'പൂർത്തിയാക്കാത്ത ഫോം ഈ ഉപകരണത്തിൽ മാത്രം സൂക്ഷിക്കും.',draftRestored:'സൂക്ഷിച്ച ഫോം തിരിച്ചെടുത്തു.',reviewBeforeSubmit:'അന്തിമമായി സമർപ്പിക്കുന്നതിന് മുമ്പ് എല്ലാ വിവരങ്ങളും പരിശോധിക്കുക.',applicationNotAdmission:'ഇത് സ്കൂൾ പരിശോധനയ്ക്കുള്ള അപേക്ഷ മാത്രമാണ്. ഇതിലൂടെ പ്രവേശനം ഉറപ്പാകുകയോ വിദ്യാർത്ഥി ലോഗിൻ സൃഷ്ടിക്കപ്പെടുകയോ ഇല്ല.',trackHelp:'അപേക്ഷ റഫറൻസും രക്ഷിതാവിന്റെ മൊബൈൽ നമ്പറും നൽകുക.',noRecord:'പൊരുത്തപ്പെടുന്ന അപേക്ഷ കണ്ടെത്തിയില്ല.',uploadDocuments:'രേഖകൾ അപ്‌ലോഡ് ചെയ്യുക',uploadingDocuments:'രേഖകൾ അപ്‌ലോഡ് ചെയ്യുന്നു…',prospectus:'പ്രോസ്പെക്ടസ് ഡൗൺലോഡ് ചെയ്യുക',documentUploadFailed:'അപേക്ഷ ലഭിച്ചു, പക്ഷേ ചില രേഖകൾ അപ്‌ലോഡ് ആയില്ല. റഫറൻസ് സൂക്ഷിച്ച് സ്കൂളുമായി ബന്ധപ്പെടുക.',duplicateApplication:'ഇതേ വിവരങ്ങളുള്ള അപേക്ഷ ഇതിനകം ഉണ്ട്. കാണിച്ച റഫറൻസ് ഉപയോഗിച്ച് നില പരിശോധിക്കുക.',statusDocumentsRequested:'രേഖകൾ ആവശ്യപ്പെട്ടു',statusVerified:'രേഖകൾ പരിശോധിച്ചു',statusWaitlisted:'കാത്തിരിപ്പ് പട്ടികയിൽ',statusWithdrawn:'പിൻവലിച്ചു'},
  pa:{saveDraftNote:'ਅਧੂਰਾ ਫਾਰਮ ਸਿਰਫ਼ ਇਸ ਡਿਵਾਈਸ ਉੱਤੇ ਸੰਭਾਲਿਆ ਜਾਂਦਾ ਹੈ।',draftRestored:'ਤੁਹਾਡਾ ਸੰਭਾਲਿਆ ਫਾਰਮ ਮੁੜ ਪ੍ਰਾਪਤ ਹੋ ਗਿਆ ਹੈ।',reviewBeforeSubmit:'ਅੰਤਿਮ ਜਮ੍ਹਾਂ ਕਰਨ ਤੋਂ ਪਹਿਲਾਂ ਸਾਰੀ ਜਾਣਕਾਰੀ ਜਾਂਚੋ।',applicationNotAdmission:'ਇਹ ਸਕੂਲ ਦੀ ਸਮੀਖਿਆ ਲਈ ਅਰਜ਼ੀ ਹੈ। ਇਸ ਨਾਲ ਦਾਖਲਾ ਪੱਕਾ ਜਾਂ ਵਿਦਿਆਰਥੀ ਲਾਗਇਨ ਨਹੀਂ ਬਣਦਾ।',trackHelp:'ਅਰਜ਼ੀ ਹਵਾਲਾ ਅਤੇ ਸਰਪ੍ਰਸਤ ਦਾ ਮੋਬਾਈਲ ਨੰਬਰ ਭਰੋ।',noRecord:'ਮਿਲਦੀ ਅਰਜ਼ੀ ਨਹੀਂ ਮਿਲੀ।',uploadDocuments:'ਦਸਤਾਵੇਜ਼ ਅਪਲੋਡ ਕਰੋ',uploadingDocuments:'ਦਸਤਾਵੇਜ਼ ਅਪਲੋਡ ਹੋ ਰਹੇ ਹਨ…',prospectus:'ਪ੍ਰੋਸਪੈਕਟਸ ਡਾਊਨਲੋਡ ਕਰੋ',documentUploadFailed:'ਅਰਜ਼ੀ ਮਿਲ ਗਈ ਹੈ ਪਰ ਕੁਝ ਦਸਤਾਵੇਜ਼ ਅਪਲੋਡ ਨਹੀਂ ਹੋਏ। ਹਵਾਲਾ ਸੰਭਾਲੋ ਅਤੇ ਸਕੂਲ ਨਾਲ ਸੰਪਰਕ ਕਰੋ।',duplicateApplication:'ਇਸੇ ਜਾਣਕਾਰੀ ਨਾਲ ਅਰਜ਼ੀ ਪਹਿਲਾਂ ਹੀ ਹੈ। ਦਿਖਾਏ ਹਵਾਲੇ ਨਾਲ ਸਥਿਤੀ ਵੇਖੋ।',statusDocumentsRequested:'ਦਸਤਾਵੇਜ਼ ਮੰਗੇ ਗਏ',statusVerified:'ਦਸਤਾਵੇਜ਼ ਤਸਦੀਕ ਹੋਏ',statusWaitlisted:'ਉਡੀਕ ਸੂਚੀ ਵਿੱਚ',statusWithdrawn:'ਵਾਪਸ ਲਈ ਗਈ'},

  as:{saveDraftNote:'অসম্পূৰ্ণ প্ৰ-পত্ৰখন কেৱল এই ডিভাইচত সংৰক্ষিত থাকে।',draftRestored:'আপোনাৰ সংৰক্ষিত প্ৰ-পত্ৰখন পুনৰুদ্ধাৰ কৰা হৈছে।',birthPlace:'জন্মস্থান',guardianRelation:'শিক্ষাৰ্থীৰ সৈতে সম্পৰ্ক',father:'পিতৃ',mother:'মাতৃ',guardian:'অভিভাৱক',alternateMobile:'বিকল্প ম’বাইল',occupation:'পেচা',addressLine:'সম্পূৰ্ণ বাসগৃহৰ ঠিকনা',city:'চহৰ / নগৰ',district:'জিলা',state:'ৰাজ্য',pinCode:'পিন কোড',previousSchool:'পূৰ্বৰ বিদ্যালয়',previousClass:'পূৰ্বৰ শ্ৰেণী',medium:'শিক্ষাৰ মাধ্যম',optional:'ঐচ্ছিক',remove:'আঁতৰাওক',reviewBeforeSubmit:'চূড়ান্তভাৱে জমা দিয়াৰ আগতে সকলো তথ্য পৰীক্ষা কৰক।',applicationNotAdmission:'এইটো বিদ্যালয়ৰ পৰ্যালোচনাৰ বাবে আবেদন। ইয়াৰ দ্বাৰা নামভৰ্তি নিশ্চিত বা শিক্ষাৰ্থী লগইন সৃষ্টি নহয়।',trackHelp:'আবেদন ৰেফাৰেন্স আৰু অভিভাৱকৰ ম’বাইল নম্বৰ লিখক।',currentStatus:'বৰ্তমান স্থিতি',noRecord:'মিল থকা আবেদন পোৱা নগ’ল।',uploadDocuments:'নথি আপলোড কৰক',uploadingDocuments:'নথি আপলোড হৈ আছে…',prospectus:'প্ৰস্পেক্টাছ ডাউনলোড কৰক',documentUploadFailed:'আবেদন লাভ কৰা হৈছে, কিন্তু কিছুমান নথি আপলোড নহ’ল। ৰেফাৰেন্স ৰাখি বিদ্যালয়ৰ সৈতে যোগাযোগ কৰক।',duplicateApplication:'একেই তথ্যৰ আবেদন ইতিমধ্যে আছে। দেখুওৱা ৰেফাৰেন্সেৰে স্থিতি চাওক।',statusNew:'জমা হৈছে',statusUnderReview:'পৰ্যালোচনাধীন',statusDocumentsRequested:'নথি বিচৰা হৈছে',statusVerified:'নথি পৰীক্ষিত',statusWaitlisted:'অপেক্ষমাণ তালিকাত',statusApproved:'অনুমোদিত',statusRejected:'নাকচ',statusWithdrawn:'প্ৰত্যাহাৰ কৰা হৈছে'},
  brx:{saveDraftNote:'आबुं जाया फर्मआ बे डिभाइसआवल’ थानाय जायो।',draftRestored:'नोंथांनि थानाय फर्मखौ फिन मोनबाय।',birthPlace:'जोनोम जायगा',guardianRelation:'फरायसाजों सोमोन्दो',father:'बिफा',mother:'बिमा',guardian:'अभिभावक',alternateMobile:'गुबुन मोबाइल',occupation:'खामानि',addressLine:'आबुं थं',city:'सहर / टाउन',district:'जिल्ला',state:'राज्य',pinCode:'पिन कड',previousSchool:'आगोलनि स्कुल',previousClass:'आगोलनि थाखो',medium:'फरायनायनि राव',optional:'गोनांथि नङै',remove:'बोखार',reviewBeforeSubmit:'जोबथा होनायनि सिगां गासै फोरमायथिहोग्राखौ नायफिन।',applicationNotAdmission:'बेयो स्कुलनि नायबिजिरनायनि थाखाय आबेदनल’। बेनि जों दाखिला रोखा जानाय एबा फरायसा लगिन सोरजि जाया।',trackHelp:'आबेदन रेफारेन्स आरो अभिभावकनि मोबाइल नम्बर हाबहो।',currentStatus:'दानि थासारि',noRecord:'गोरोबनाय आबेदन मोनाखै।',uploadDocuments:'लाइजोम अपलड खालाम',uploadingDocuments:'लाइजोम अपलड जागासिनो…',prospectus:'प्रस्पेक्टास डाउनलड खालाम',documentUploadFailed:'आबेदन मोनबाय, नाथाय माखासे लाइजोम अपलड जाया। रेफारेन्सखौ दोन आरो स्कुलजों सोमोन्दो खालाम।',duplicateApplication:'बे फोरमायथिजों आबेदन सिगाङावनो दं। दिन्थिनाय रेफारेन्सजों थासारि नाय।',statusNew:'होबाय',statusUnderReview:'नायबिजिरनायाव',statusDocumentsRequested:'लाइजोम नायगिरबाय',statusVerified:'लाइजोम नायजाबाय',statusWaitlisted:'नेथारि फारिलाइयाव',statusApproved:'गनायजाबाय',statusRejected:'नागारबाय',statusWithdrawn:'फिन लाबोबाय'},
  doi:{saveDraftNote:'अधूरा फार्म सिर्फ इस डिवाइस पर सहेजेआ जंदा ऐ।',draftRestored:'तुंदा सहेजेआ फार्म बहाल होई गेआ ऐ।',birthPlace:'जन्म थाह्र',guardianRelation:'विद्यार्थी कन्नै रिश्ता',father:'पिता',mother:'माता',guardian:'अभिभावक',alternateMobile:'दूआ मोबाइल',occupation:'पेशा',addressLine:'पूरा रिहायशी पता',city:'शैहर / कस्बा',district:'जिला',state:'राज्य',pinCode:'पिन कोड',previousSchool:'पिछला स्कूल',previousClass:'पिछली जमात',medium:'पढ़ाई दा माध्यम',optional:'वैकल्पिक',remove:'हटाओ',reviewBeforeSubmit:'आखरी जमा करने थमां पैह्लें सारी जानकारी जांचो।',applicationNotAdmission:'एह स्कूल दी समीक्षा आस्तै दरखास्त ऐ। इस कन्नै दाखला पक्का जां विद्यार्थी लॉगिन नेईं बनदा।',trackHelp:'दरखास्त संदर्भ ते अभिभावक दा मोबाइल नंबर भरो।',currentStatus:'मौजूदा स्थिति',noRecord:'मेल खांदी दरखास्त नेईं मिली।',uploadDocuments:'दस्तावेज अपलोड करो',uploadingDocuments:'दस्तावेज अपलोड होआ करदे न…',prospectus:'प्रॉस्पेक्टस डाउनलोड करो',documentUploadFailed:'दरखास्त मिली गेई, पर किश दस्तावेज अपलोड नेईं होए। संदर्भ संभालो ते स्कूल कन्नै संपर्क करो।',duplicateApplication:'इक्को जानकारी दी दरखास्त पैह्लें मौजूद ऐ। दित्ते संदर्भ कन्नै स्थिति दिक्खो।',statusNew:'जमा',statusUnderReview:'समीक्षा च',statusDocumentsRequested:'दस्तावेज मंगे गे',statusVerified:'दस्तावेज जांचे गे',statusWaitlisted:'इंतजार सूची च',statusApproved:'मंजूर',statusRejected:'नामंजूर',statusWithdrawn:'वापस लैता'},
  ks:{saveDraftNote:'نامُکمل فارم چھُ صرف یتھ ڈیوائس پٮ۪ٹھ محفوظ روزان۔',draftRestored:'تُہند محفوظ فارم آو واپس بحال کرنہٕ۔',birthPlace:'جائے پیدائش',guardianRelation:'طالب علمس سۭتۍ رشتہٕ',father:'مول',mother:'ماجہ',guardian:'سرپرست',alternateMobile:'متبادل موبائل',occupation:'پیشہٕ',addressLine:'مکمل رہائشی پتہٕ',city:'شہر / قصبہٕ',district:'ضلع',state:'ریاست',pinCode:'پن کوڈ',previousSchool:'پٔتِم اسکول',previousClass:'پٔتِم جماعت',medium:'تعلیمُک ذریعہ',optional:'اختیاری',remove:'ہٹٲو',reviewBeforeSubmit:'آخری جمع کرنہٕ برونہہ تمام معلومات وچھو۔',applicationNotAdmission:'یہ چھُ صرف اسکول جائزہٕ خٲطرٕ درخواست۔ امہٕ سۭتۍ داخلہٕ پکا یا طالب علم لاگ اِن نہٕ بنان۔',trackHelp:'درخواست ریفرنس تہٕ سرپرست موبائل نمبر درج کٔریو۔',currentStatus:'موجودہ حالت',noRecord:'کاںہہ مماثل درخواست نہٕ لب۔',uploadDocuments:'دستاویزات اپ لوڈ کٔریو',uploadingDocuments:'دستاویزات اپ لوڈ گژھان چھِ…',prospectus:'پراسپیکٹس ڈاؤن لوڈ کٔریو',documentUploadFailed:'درخواست موصول گٔیہ، مگر کینہہ دستاویز اپ لوڈ نہٕ گٔیہ۔ ریفرنس محفوظ تھاویو تہٕ اسکولس سۭتۍ رابطہٕ کٔریو۔',duplicateApplication:'یہ معلومات والی درخواست پہلے موجود چھِ۔ دکھاونہٕ آمت ریفرنس سۭتۍ حالت وچھو۔',statusNew:'جمع شدہ',statusUnderReview:'زیر جائزہٕ',statusDocumentsRequested:'دستاویزات مطلوب',statusVerified:'دستاویزات تصدیق شدہ',statusWaitlisted:'انتظار فہرستس منز',statusApproved:'منظور',statusRejected:'مسترد',statusWithdrawn:'واپس گژھمت'},
  kok:{saveDraftNote:'अपुरो फॉर्म फकत ह्याच उपकरणाचेर जतन जाता.',draftRestored:'तुमचो जतन केल्लो फॉर्म परत मेळ्ळा.',birthPlace:'जल्म थळ',guardianRelation:'विद्यार्थ्याशी नातें',father:'बापूय',mother:'आवय',guardian:'पालक',alternateMobile:'पर्यायी मोबायल',occupation:'वेवसाय',addressLine:'पुराय रावपाचो पत्तो',city:'शार / गांव',district:'जिल्लो',state:'राज्य',pinCode:'पिन कोड',previousSchool:'आदली शाळा',previousClass:'आदली इयत्ता',medium:'शिक्षण माध्यम',optional:'ऐच्छिक',remove:'काडात',reviewBeforeSubmit:'निमाणें सादर करचे पयलीं सगळे तपशील तपासात.',applicationNotAdmission:'हो अर्ज शाळेच्या तपासणी खातीर आसा. हाका लागून प्रवेश पक्को वा विद्यार्थी लॉगिन तयार जायना.',trackHelp:'अर्ज संदर्भ आनी पालकाचो मोबायल क्रमांक घालात.',currentStatus:'सद्याची स्थिती',noRecord:'जुळपी अर्ज मेळ्ळो ना.',uploadDocuments:'कागदपत्रां अपलोड करात',uploadingDocuments:'कागदपत्रां अपलोड जातात…',prospectus:'माहितीपत्रक डाउनलोड करात',documentUploadFailed:'अर्ज मेळ्ळा, पण कांय कागदपत्रां अपलोड जालीं ना. संदर्भ जतन करात आनी शाळेक संपर्क करात.',duplicateApplication:'ह्याच माहितीचो अर्ज पयलींच आसा. दाखयल्ल्या संदर्भान स्थिती पळयात.',statusNew:'सादर',statusUnderReview:'तपासणीत',statusDocumentsRequested:'कागदपत्रां मागयलीं',statusVerified:'कागदपत्रां तपासलीं',statusWaitlisted:'प्रतीक्षा वळेर',statusApproved:'मंजूर',statusRejected:'नामंजूर',statusWithdrawn:'फाटीं घेतलो'},
  mai:{saveDraftNote:'अधूरा फॉर्म केवल एहि उपकरण पर सुरक्षित रहैत अछि।',draftRestored:'अहाँक सुरक्षित फॉर्म फेर सँ प्राप्त भेल।',birthPlace:'जन्म स्थान',guardianRelation:'विद्यार्थीसँ संबंध',father:'पिता',mother:'माता',guardian:'अभिभावक',alternateMobile:'वैकल्पिक मोबाइल',occupation:'पेशा',addressLine:'पूरा आवासीय पता',city:'शहर / नगर',district:'जिला',state:'राज्य',pinCode:'पिन कोड',previousSchool:'पिछला विद्यालय',previousClass:'पिछली कक्षा',medium:'शिक्षण माध्यम',optional:'वैकल्पिक',remove:'हटाउ',reviewBeforeSubmit:'अंतिम रूप सँ जमा करबाक पहिने सभ विवरण जाँचू।',applicationNotAdmission:'ई विद्यालयक समीक्षा लेल आवेदन अछि। एहि सँ प्रवेश पक्का वा विद्यार्थी लॉगिन नहि बनैत अछि।',trackHelp:'आवेदन संदर्भ आ अभिभावकक मोबाइल नंबर भरू।',currentStatus:'वर्तमान स्थिति',noRecord:'मिलैत आवेदन नहि भेटल।',uploadDocuments:'कागजात अपलोड करू',uploadingDocuments:'कागजात अपलोड भऽ रहल अछि…',prospectus:'प्रॉस्पेक्टस डाउनलोड करू',documentUploadFailed:'आवेदन प्राप्त भेल, मुदा किछु कागजात अपलोड नहि भेल। संदर्भ सुरक्षित राखू आ विद्यालय सँ संपर्क करू।',duplicateApplication:'एहि जानकारीक आवेदन पहिने सँ अछि। देखाओल संदर्भ सँ स्थिति देखू।',statusNew:'जमा',statusUnderReview:'समीक्षाधीन',statusDocumentsRequested:'कागजात माँगल गेल',statusVerified:'कागजात सत्यापित',statusWaitlisted:'प्रतीक्षा सूची',statusApproved:'स्वीकृत',statusRejected:'अस्वीकृत',statusWithdrawn:'वापस लेल गेल'},
  mni:{saveDraftNote:'ꯃꯄꯨꯡ ꯐꯥꯅꯥ ꯂꯣꯏꯗ꯭ꯔꯤꯕ ꯐꯣꯔꯝ ꯑꯁꯤ ꯗꯤꯚꯥꯏꯁ ꯑꯁꯤꯗꯈꯛꯇꯗ ꯁꯦꯚ ꯇꯧꯏ꯫',draftRestored:'ꯁꯦꯚ ꯇꯧꯔꯝꯕ ꯐꯣꯔꯝ ꯑꯗꯨ ꯍꯟꯅꯥ ꯐꯪꯂꯦ꯫',birthPlace:'ꯄꯣꯛꯐꯝ',guardianRelation:'ꯃꯍꯩꯔꯣꯏꯒ ꯂꯣꯏꯅꯕ ꯃꯔꯤ',father:'ꯃꯄꯥ',mother:'ꯃꯃꯥ',guardian:'ꯂꯣꯏꯅꯕ',alternateMobile:'ꯑꯇꯣꯞꯄ ꯃꯣꯕꯥꯏꯜ',occupation:'ꯁꯤꯟꯐꯝ',addressLine:'ꯃꯄꯨꯡ ꯐꯥꯕ ꯂꯩꯐꯝ',city:'ꯁꯍꯔ / ꯇꯥꯎꯟ',district:'ꯗꯤꯁꯇ꯭ꯔꯤꯛ',state:'ꯁ꯭ꯇꯦꯠ',pinCode:'ꯄꯤꯟ ꯀꯣꯗ',previousSchool:'ꯃꯃꯥꯡꯒꯤ ꯁ꯭ꯀꯨꯜ',previousClass:'ꯃꯃꯥꯡꯒꯤ ꯀ꯭ꯂꯥꯁ',medium:'ꯇꯝꯕꯤꯕꯒꯤ ꯂꯣꯟ',optional:'ꯑꯄꯥꯝꯕ',remove:'ꯂꯧꯊꯣꯛꯎ',reviewBeforeSubmit:'ꯑꯔꯣꯏꯕ ꯁꯕꯃꯤꯠ ꯇꯧꯗ꯭ꯔꯤꯉꯩ ꯃꯃꯥꯡꯗ ꯃꯄꯨꯡ ꯐꯥꯅꯥ ꯌꯦꯡꯁꯤꯜꯂꯨ꯫',applicationNotAdmission:'ꯃꯁꯤ ꯁ꯭ꯀꯨꯜꯅ ꯌꯦꯡꯁꯤꯟꯅꯕꯒꯤ ꯑꯦꯄ꯭ꯂꯤꯀꯦꯁꯟꯅꯤ꯫ ꯑꯦꯗꯃꯤꯁꯟ ꯀꯟꯐꯥꯔꯝ ꯅꯠꯇ꯭ꯔꯒ ꯂꯣꯒꯤꯟ ꯁꯦꯝꯗꯦ꯫',trackHelp:'ꯑꯦꯄ꯭ꯂꯤꯀꯦꯁꯟ ꯔꯦꯐꯔꯦꯟꯁ ꯑꯃꯁꯨꯡ ꯃꯣꯕꯥꯏꯜ ꯅꯝꯕꯔ ꯄꯤꯌꯨ꯫',currentStatus:'ꯍꯧꯖꯤꯛꯀꯤ ꯐꯤꯕꯝ',noRecord:'ꯃꯥꯟꯅꯕ ꯑꯦꯄ꯭ꯂꯤꯀꯦꯁꯟ ꯐꯪꯗꯦ꯫',uploadDocuments:'ꯆꯦꯔꯣꯜ ꯑꯄꯂꯣꯗ ꯇꯧꯎ',uploadingDocuments:'ꯆꯦꯔꯣꯜ ꯑꯄꯂꯣꯗ ꯇꯧꯔꯤ…',prospectus:'ꯄ꯭ꯔꯣꯁꯄꯦꯛꯇꯁ ꯗꯥꯎꯟꯂꯣꯗ ꯇꯧꯎ',documentUploadFailed:'ꯑꯦꯄ꯭ꯂꯤꯀꯦꯁꯟ ꯐꯪꯂꯦ, ꯑꯗꯨꯕꯨ ꯆꯦꯔꯣꯜ ꯈꯔ ꯑꯄꯂꯣꯗ ꯇꯧꯗꯦ꯫ ꯔꯦꯐꯔꯦꯟꯁ ꯊꯝꯃꯨ ꯑꯃꯁꯨꯡ ꯁ꯭ꯀꯨꯜꯒ ꯄꯥꯎ ꯐꯥꯎꯅꯧ꯫',duplicateApplication:'ꯃꯥꯟꯅꯕ ꯃꯔꯣꯜꯒꯤ ꯑꯦꯄ꯭ꯂꯤꯀꯦꯁꯟ ꯍꯥꯟꯅꯅ ꯂꯩꯔꯦ꯫ ꯔꯦꯐꯔꯦꯟꯁ ꯑꯗꯨꯅ ꯐꯤꯕꯝ ꯌꯦꯡꯉꯨ꯫',statusNew:'ꯁꯕꯃꯤꯠ ꯇꯧꯔꯦ',statusUnderReview:'ꯌꯦꯡꯁꯤꯟꯅꯔꯤ',statusDocumentsRequested:'ꯆꯦꯔꯣꯜ ꯍꯥꯏꯔꯦ',statusVerified:'ꯆꯦꯔꯣꯜ ꯌꯦꯡꯂꯦ',statusWaitlisted:'ꯉꯥꯏꯔꯤꯕ ꯂꯤꯁꯇ',statusApproved:'ꯑꯌꯥꯕ ꯄꯤꯔꯦ',statusRejected:'ꯌꯥꯗꯦ',statusWithdrawn:'ꯍꯟꯗꯣꯛꯂꯦ'},
  ne:{saveDraftNote:'अधुरो फाराम यही उपकरणमा मात्र सुरक्षित रहन्छ।',draftRestored:'तपाईंको सुरक्षित फाराम पुनःस्थापित भयो।',birthPlace:'जन्मस्थान',guardianRelation:'विद्यार्थीसँगको सम्बन्ध',father:'बुबा',mother:'आमा',guardian:'अभिभावक',alternateMobile:'वैकल्पिक मोबाइल',occupation:'पेशा',addressLine:'पूरा आवासीय ठेगाना',city:'सहर / नगर',district:'जिल्ला',state:'प्रदेश / राज्य',pinCode:'पिन कोड',previousSchool:'अघिल्लो विद्यालय',previousClass:'अघिल्लो कक्षा',medium:'शिक्षण माध्यम',optional:'वैकल्पिक',remove:'हटाउनुहोस्',reviewBeforeSubmit:'अन्तिम रूपमा बुझाउनु अघि सबै विवरण जाँच्नुहोस्।',applicationNotAdmission:'यो विद्यालयको समीक्षाका लागि आवेदन हो। यसले भर्ना पुष्टि वा विद्यार्थी लगइन सिर्जना गर्दैन।',trackHelp:'आवेदन सन्दर्भ र अभिभावकको मोबाइल नम्बर दिनुहोस्।',currentStatus:'हालको स्थिति',noRecord:'मिल्दो आवेदन भेटिएन।',uploadDocuments:'कागजात अपलोड गर्नुहोस्',uploadingDocuments:'कागजात अपलोड हुँदैछन्…',prospectus:'प्रोस्पेक्टस डाउनलोड गर्नुहोस्',documentUploadFailed:'आवेदन प्राप्त भयो तर केही कागजात अपलोड भएनन्। सन्दर्भ सुरक्षित राखी विद्यालयलाई सम्पर्क गर्नुहोस्।',duplicateApplication:'यही जानकारीको आवेदन पहिले नै छ। देखाइएको सन्दर्भबाट स्थिति हेर्नुहोस्।',statusNew:'बुझाइएको',statusUnderReview:'समीक्षामा',statusDocumentsRequested:'कागजात मागिएको',statusVerified:'कागजात प्रमाणित',statusWaitlisted:'प्रतीक्षा सूचीमा',statusApproved:'स्वीकृत',statusRejected:'अस्वीकृत',statusWithdrawn:'फिर्ता लिइएको'},
  or:{saveDraftNote:'ଅସମ୍ପୂର୍ଣ୍ଣ ଫର୍ମ କେବଳ ଏହି ଡିଭାଇସରେ ସଞ୍ଚିତ ରହେ।',draftRestored:'ଆପଣଙ୍କ ସଞ୍ଚିତ ଫର୍ମ ପୁନରୁଦ୍ଧାର ହୋଇଛି।',birthPlace:'ଜନ୍ମ ସ୍ଥାନ',guardianRelation:'ଛାତ୍ର ସହିତ ସମ୍ପର୍କ',father:'ପିତା',mother:'ମାତା',guardian:'ଅଭିଭାବକ',alternateMobile:'ବିକଳ୍ପ ମୋବାଇଲ',occupation:'ବୃତ୍ତି',addressLine:'ସମ୍ପୂର୍ଣ୍ଣ ବାସସ୍ଥାନ ଠିକଣା',city:'ସହର / ନଗର',district:'ଜିଲ୍ଲା',state:'ରାଜ୍ୟ',pinCode:'ପିନ କୋଡ୍',previousSchool:'ପୂର୍ବ ବିଦ୍ୟାଳୟ',previousClass:'ପୂର୍ବ ଶ୍ରେଣୀ',medium:'ଶିକ୍ଷା ମାଧ୍ୟମ',optional:'ଇଚ୍ଛାଧୀନ',remove:'ହଟାନ୍ତୁ',reviewBeforeSubmit:'ଶେଷ ଦାଖଲ ପୂର୍ବରୁ ସମସ୍ତ ବିବରଣୀ ଯାଞ୍ଚ କରନ୍ତୁ।',applicationNotAdmission:'ଏହା ବିଦ୍ୟାଳୟ ସମୀକ୍ଷା ପାଇଁ ଆବେଦନ। ଏଥିରେ ଭର୍ତ୍ତି ନିଶ୍ଚିତ କିମ୍ବା ଛାତ୍ର ଲଗଇନ୍ ସୃଷ୍ଟି ହୁଏ ନାହିଁ।',trackHelp:'ଆବେଦନ ସନ୍ଦର୍ଭ ଏବଂ ଅଭିଭାବକଙ୍କ ମୋବାଇଲ ନମ୍ବର ଦିଅନ୍ତୁ।',currentStatus:'ବର୍ତ୍ତମାନ ସ୍ଥିତି',noRecord:'ମେଳ ଥିବା ଆବେଦନ ମିଳିଲା ନାହିଁ।',uploadDocuments:'ଦଲିଲ ଅପଲୋଡ୍ କରନ୍ତୁ',uploadingDocuments:'ଦଲିଲ ଅପଲୋଡ୍ ହେଉଛି…',prospectus:'ପ୍ରସ୍ପେକ୍ଟସ୍ ଡାଉନଲୋଡ୍ କରନ୍ତୁ',documentUploadFailed:'ଆବେଦନ ମିଳିଛି, କିନ୍ତୁ କିଛି ଦଲିଲ ଅପଲୋଡ୍ ହୋଇନି। ସନ୍ଦର୍ଭ ରଖି ବିଦ୍ୟାଳୟ ସହ ଯୋଗାଯୋଗ କରନ୍ତୁ।',duplicateApplication:'ଏହି ତଥ୍ୟର ଆବେଦନ ପୂର୍ବରୁ ଅଛି। ଦେଖାଯାଇଥିବା ସନ୍ଦର୍ଭରେ ସ୍ଥିତି ଦେଖନ୍ତୁ।',statusNew:'ଦାଖଲ',statusUnderReview:'ସମୀକ୍ଷାରେ',statusDocumentsRequested:'ଦଲିଲ ମାଗାଯାଇଛି',statusVerified:'ଦଲିଲ ଯାଞ୍ଚିତ',statusWaitlisted:'ପ୍ରତୀକ୍ଷା ତାଲିକାରେ',statusApproved:'ଅନୁମୋଦିତ',statusRejected:'ପ୍ରତ୍ୟାଖ୍ୟାନ',statusWithdrawn:'ପ୍ରତ୍ୟାହୃତ'},
  sa:{saveDraftNote:'अपूर्णं प्रपत्रं केवलम् अस्मिन् उपकरणे रक्ष्यते।',draftRestored:'भवतः रक्षितं प्रपत्रं पुनः प्राप्तम्।',birthPlace:'जन्मस्थानम्',guardianRelation:'विद्यार्थिना सह सम्बन्धः',father:'पिता',mother:'माता',guardian:'अभिभावकः',alternateMobile:'वैकल्पिकदूरभाषः',occupation:'व्यवसायः',addressLine:'सम्पूर्णः निवासपत्ता',city:'नगरम्',district:'जनपदः',state:'राज्यम्',pinCode:'पिन-सङ्केतः',previousSchool:'पूर्वविद्यालयः',previousClass:'पूर्वकक्षा',medium:'शिक्षणमाध्यमम्',optional:'वैकल्पिकम्',remove:'अपसारयतु',reviewBeforeSubmit:'अन्तिमसमर्पणात् पूर्वं सर्वाणि विवरणानि परीक्षताम्।',applicationNotAdmission:'इदं विद्यालयस्य समीक्षार्थम् आवेदनम्। अनेन प्रवेशः निश्चितः न भवति, छात्र-प्रवेशसङ्केतः अपि न निर्मीयते।',trackHelp:'आवेदनसन्दर्भं अभिभावकस्य दूरभाषसङ्ख्यां च लिखतु।',currentStatus:'वर्तमानस्थितिः',noRecord:'अनुरूपम् आवेदनं न प्राप्तम्।',uploadDocuments:'पत्राणि आरोपयतु',uploadingDocuments:'पत्राणि आरोप्यन्ते…',prospectus:'विवरणपत्रं अवतारयतु',documentUploadFailed:'आवेदनं प्राप्तम्, किन्तु कानिचन पत्राणि न आरोपितानि। सन्दर्भं रक्षतु विद्यालयेन सह सम्पर्कं करोतु।',duplicateApplication:'समानविवरणयुक्तम् आवेदनं पूर्वमेव अस्ति। दर्शितसन्दर्भेण स्थितिं पश्यतु।',statusNew:'समर्पितम्',statusUnderReview:'समीक्षायाम्',statusDocumentsRequested:'पत्राणि याचितानि',statusVerified:'पत्राणि सत्यापितानि',statusWaitlisted:'प्रतीक्षासूच्याम्',statusApproved:'अनुमोदितम्',statusRejected:'अस्वीकृतम्',statusWithdrawn:'प्रतिहृतम्'},
  sat:{saveDraftNote:'ᱵᱟᱝ ᱯᱩᱨᱟᱹᱣ ᱯᱷᱚᱨᱢ ᱱᱚᱶᱟ ᱰᱤᱵᱷᱟᱭᱤᱥ ᱨᱮ ᱮᱥᱠᱟᱨ ᱥᱟᱧᱪᱟᱣᱜ-ᱟ।',draftRestored:'ᱥᱟᱧᱪᱟᱣ ᱯᱷᱚᱨᱢ ᱫᱚᱦᱲᱟ ᱧᱟᱢ ᱮᱱᱟ।',birthPlace:'ᱡᱟᱱᱟᱢ ᱴᱷᱟᱶ',guardianRelation:'ᱯᱟᱹᱴᱷᱩᱣᱟᱹ ᱥᱟᱶ ᱥᱟᱹᱜᱟᱹᱭ',father:'ᱵᱟᱵᱟ',mother:'ᱜᱚᱜᱚ',guardian:'ᱦᱟᱹᱨᱤᱭᱟᱹᱨ',alternateMobile:'ᱮᱴᱟᱜ ᱢᱳᱵᱟᱭᱤᱞ',occupation:'ᱠᱟᱹᱢᱤ',addressLine:'ᱯᱩᱨᱟᱹ ᱚᱲᱟᱜ ᱴᱷᱟᱶ',city:'ᱥᱚᱦᱚᱨ / ᱴᱟᱣᱩᱱ',district:'ᱡᱤᱞᱟᱹ',state:'ᱯᱚᱱᱚᱛ',pinCode:'ᱯᱤᱱ ᱠᱳᱰ',previousSchool:'ᱢᱟᱲᱟᱝ ᱤᱥᱠᱩᱞ',previousClass:'ᱢᱟᱲᱟᱝ ᱪᱟᱱᱚᱪ',medium:'ᱯᱟᱹᱲᱦᱟᱹᱣ ᱯᱟᱹᱨᱥᱤ',optional:'ᱟᱯᱟᱱ ᱠᱩᱥᱤ',remove:'ᱚᱪᱚᱜ',reviewBeforeSubmit:'ᱢᱩᱪᱟᱹᱫ ᱡᱚᱢᱟ ᱢᱟᱲᱟᱝ ᱡᱚᱛᱚ ᱵᱤᱵᱨᱚᱬ ᱧᱮᱞ ᱢᱮ।',applicationNotAdmission:'ᱱᱚᱶᱟ ᱤᱥᱠᱩᱞ ᱧᱮᱞ ᱫᱚᱦᱲᱟ ᱞᱟᱹᱜᱤᱫ ᱟᱨᱫᱟᱥ। ᱱᱚᱶᱟᱛᱮ ᱵᱷᱚᱨᱛᱤ ᱯᱟᱠᱟ ᱵᱟᱝ ᱟᱨ ᱞᱚᱜᱤᱱ ᱵᱟᱝ ᱵᱮᱱᱟᱣᱜ-ᱟ।',trackHelp:'ᱟᱨᱫᱟᱥ ᱨᱮᱯᱷᱟᱨᱮᱱᱥ ᱟᱨ ᱢᱳᱵᱟᱭᱤᱞ ᱮᱢ ᱢᱮ।',currentStatus:'ᱱᱤᱛᱚᱜ ᱫᱚᱥᱟ',noRecord:'ᱢᱮᱞ ᱟᱨᱫᱟᱥ ᱵᱟᱝ ᱧᱟᱢ ᱮᱱᱟ।',uploadDocuments:'ᱫᱚᱞᱤᱞ ᱟᱯᱞᱳᱰ ᱢᱮ',uploadingDocuments:'ᱫᱚᱞᱤᱞ ᱟᱯᱞᱳᱰᱚᱜ ᱠᱟᱱᱟ…',prospectus:'ᱯᱨᱚᱥᱯᱮᱠᱴᱟᱥ ᱰᱟᱣᱩᱱᱞᱳᱰ ᱢᱮ',documentUploadFailed:'ᱟᱨᱫᱟᱥ ᱧᱟᱢ ᱮᱱᱟ, ᱢᱮᱱᱠᱷᱟᱱ ᱠᱟᱹᱪ ᱫᱚᱞᱤᱞ ᱵᱟᱝ ᱟᱯᱞᱳᱰ ᱮᱱᱟ। ᱨᱮᱯᱷᱟᱨᱮᱱᱥ ᱫᱚᱦᱚ ᱢᱮ ᱟᱨ ᱤᱥᱠᱩᱞ ᱥᱟᱶ ᱡᱚᱯᱚᱲᱟᱣ ᱢᱮ।',duplicateApplication:'ᱱᱚᱶᱟ ᱵᱤᱵᱨᱚᱬ ᱨᱮᱭᱟᱜ ᱟᱨᱫᱟᱥ ᱢᱟᱲᱟᱝ ᱠᱷᱚᱱ ᱢᱮᱱᱟᱜ-ᱟ। ᱫᱮᱠᱷᱟᱣ ᱨᱮᱯᱷᱟᱨᱮᱱᱥ ᱛᱮ ᱫᱚᱥᱟ ᱧᱮᱞ ᱢᱮ।',statusNew:'ᱡᱚᱢᱟ',statusUnderReview:'ᱧᱮᱞ ᱫᱚᱦᱲᱟ ᱨᱮ',statusDocumentsRequested:'ᱫᱚᱞᱤᱞ ᱠᱷᱚᱡ ᱮᱱᱟ',statusVerified:'ᱫᱚᱞᱤᱞ ᱧᱮᱞ ᱮᱱᱟ',statusWaitlisted:'ᱛᱟᱺᱜᱤ ᱥᱩᱪᱤ ᱨᱮ',statusApproved:'ᱢᱟᱱᱟᱣ',statusRejected:'ᱵᱟᱹᱰᱨᱟᱹ',statusWithdrawn:'ᱨᱩᱣᱟᱹᱲ'},
  sd:{saveDraftNote:'نامڪمل فارم صرف هن ڊوائيس تي محفوظ رهندو آهي۔',draftRestored:'توهان جو محفوظ فارم بحال ٿي ويو آهي۔',birthPlace:'ڄمڻ جي جاءِ',guardianRelation:'شاگرد سان تعلق',father:'پيءُ',mother:'ماءُ',guardian:'سنڀاليندڙ',alternateMobile:'متبادل موبائل',occupation:'پيشو',addressLine:'مڪمل رهائشي پتو',city:'شهر / ڳوٺ',district:'ضلعو',state:'رياست',pinCode:'پن ڪوڊ',previousSchool:'اڳوڻو اسڪول',previousClass:'اڳوڻو ڪلاس',medium:'تعليم جو ذريعو',optional:'اختياري',remove:'هٽايو',reviewBeforeSubmit:'آخري جمع ڪرائڻ کان اڳ سڀ تفصيل ڏسو۔',applicationNotAdmission:'هي اسڪول جي جائزي لاءِ درخواست آهي۔ ان سان داخلا پڪي يا شاگرد لاگ اِن نٿو ٺهي۔',trackHelp:'درخواست حوالو ۽ سنڀاليندڙ جو موبائل نمبر داخل ڪريو۔',currentStatus:'موجوده حالت',noRecord:'ڪابه ملندڙ درخواست نه ملي۔',uploadDocuments:'دستاويز اپلوڊ ڪريو',uploadingDocuments:'دستاويز اپلوڊ ٿي رهيا آهن…',prospectus:'پراسپيڪٽس ڊائونلوڊ ڪريو',documentUploadFailed:'درخواست ملي وئي، پر ڪجهه دستاويز اپلوڊ نه ٿيا۔ حوالو محفوظ رکو ۽ اسڪول سان رابطو ڪريو۔',duplicateApplication:'ساڳي معلومات سان درخواست اڳ ۾ موجود آهي۔ ڏيکاريل حوالي سان حالت ڏسو۔',statusNew:'جمع ٿيل',statusUnderReview:'جائزي هيٺ',statusDocumentsRequested:'دستاويز گهريا ويا',statusVerified:'دستاويز تصديق ٿيل',statusWaitlisted:'انتظار فهرست ۾',statusApproved:'منظور',statusRejected:'رد',statusWithdrawn:'واپس ورتل'}
};

const aliases: Record<string,string> = {asm:'as',ben:'bn',bod:'brx',dgo:'doi',guj:'gu',kan:'kn',kas:'ks',mar:'mr',mal:'ml',nep:'ne',ori:'or',od:'or',pan:'pa',pun:'pa',san:'sa',snd:'sd',tam:'ta',tel:'te',urd:'ur',hin:'hi',eng:'en'};

export function getAdmissionWorkflowCopy(language: Language): AdmissionWorkflowCopy {
  const raw = String(language || 'en').toLowerCase().replace('_','-').split('-')[0];
  const code = aliases[raw] || raw;
  return { ...en, ...(copies[code] || {}), ...(supplements[code] || {}) };
}

export function admissionStatusLabel(status: string, copy: AdmissionWorkflowCopy): string {
  const map: Record<string,string> = {
    new: copy.statusNew, under_review: copy.statusUnderReview, documents_requested: copy.statusDocumentsRequested,
    verified: copy.statusVerified, waitlisted: copy.statusWaitlisted, approved: copy.statusApproved,
    rejected: copy.statusRejected, withdrawn: copy.statusWithdrawn
  };
  return map[status] || status.replaceAll('_',' ');
}
