export type ProcessRole='headmaster'|'clerk'|'teacher'|'student'|'parent'|'super_admin';
export type ProcessTier='live'|'guided';
export type ProcessCategory='Admissions & Student Journey'|'Academic Setup & Staffing'|'Daily School Operations'|'Teaching & AI'|'Exams & Results'|'Communication & School Services'|'Platform & Documents';

export type ProcessControl='text'|'textarea'|'number'|'date'|'time'|'datetime'|'select'|'multiselect'|'choice'|'radio'|'checkbox'|'file'|'password'|'status'|'read';
export type ProcessInteraction='form'|'selection'|'review'|'view';
export type ProcessField={label:string;value:string;control?:ProcessControl};
export type ProcessStep={
  id:string;
  role:ProcessRole;
  moduleKeyword:string;
  screen:string;
  title:string;
  task:string;
  autoFields:ProcessField[];
  actionLabel:string;
  effect:string[];
  interaction?:ProcessInteraction;
};
export type DemoProcess={
  id:string;
  number:number;
  title:string;
  short:string;
  description:string;
  category:ProcessCategory;
  tier:ProcessTier;
  importance:'hero'|'high'|'standard';
  steps:ProcessStep[];
};

const F=(label:string,value:string,control?:ProcessControl):ProcessField=>({label,value,control});

export const DEMO_PROCESSES:DemoProcess[]=[
  {
    id:'admission',number:1,title:'Admission → Student & Parent Account',short:'Admission',category:'Admissions & Student Journey',tier:'live',importance:'hero',
    description:'Actual Classtago controlled chain: Clerk intake → Headmaster approval/confirmation → Student Master + GR → Class Teacher notification → Student signup approval → Parent link approval.',
    steps:[
      {id:'clerk-student',role:'clerk',moduleKeyword:'New Student Admission',screen:'New Student Admission · 1. Student',title:'Enter student demographics',task:'Actual Clerk Admission Desk ke Student Demographics controls ka guided sample.',interaction:'form',autoFields:[F('G.R. Number','{grNo}','text'),F('Admission Number','{admissionNo}','text'),F('Full Student Name','{applicant}','text'),F('Date of Birth','2014-06-18','date'),F('Gender','Female','radio'),F('Religion','Other / School record','select'),F('Mother Tongue','{medium}','select')],actionLabel:'Next: Parents & Contact Info',effect:['Student demographic section is complete.','No Student Master or login is created at this stage.']},
      {id:'clerk-parents',role:'clerk',moduleKeyword:'New Student Admission',screen:'New Student Admission · 2. Parents',title:'Enter parent and contact details',task:'Text fields sirf wahi type honge jahan actual form me input hai; occupations dropdown se select honge.',interaction:'form',autoFields:[F("Father's Name",'{applicantParent}','text'),F("Mother's Name",'Sample Parent','text'),F("Father's Occupation",'Service','select'),F('Primary Mobile','{mobile}','text'),F('Emergency Contact','{mobile}','text'),F('Parent Email','parent.demo@example.test','text')],actionLabel:'Next: Address & School History',effect:['Guardian/contact information is attached to the same admission draft.']},
      {id:'clerk-history',role:'clerk',moduleKeyword:'New Student Admission',screen:'New Student Admission · 3. History',title:'Complete address and school history',task:'Actual textarea, checkbox aur previous-class selection pattern use hoga.',interaction:'form',autoFields:[F('Present Address','Demo locality, {school}','textarea'),F('Permanent Address same as Present','Yes','checkbox'),F('Village / Town','Demo City','text'),F('District','{jurisdiction}','text'),F('Previous School','Sunrise Primary School','text'),F('Previous Class','Class VII','select'),F('Previous Board','{board}','text')],actionLabel:'Next: Verification & Setup',effect:['Address and previous-school history are ready for final verification.']},
      {id:'clerk-verify',role:'clerk',moduleKeyword:'New Student Admission',screen:'New Student Admission · 4. Verify',title:'Medical, documents and office setup',task:'Actual select/file/textarea controls ka representative guided fill; fake typing nahi.',interaction:'form',autoFields:[F('Physical Disability','None reported','select'),F('Blood Group','B+','select'),F('Target Class','{class}','select'),F('Division','A','select'),F('Medium','{medium}','select'),F('Leaving Certificate','LC_demo.pdf','file'),F('Aadhaar Card','Aadhaar_demo.pdf','file'),F('Passport Photo','student_photo.webp','file'),F('Admission Type','Regular','select'),F('Clerical Remarks','Documents verified for Headmaster review.','textarea')],actionLabel:'Review Intake',effect:['Required documents and office allocation are prepared.','The application still exists only as an admission intake.']},
      {id:'clerk-send',role:'clerk',moduleKeyword:'New Student Admission',screen:'Admission Desk · Final Review',title:'Send verified intake to Headmaster',task:'Data already filled hai; yahan koi typing nahi. User final handoff khud karega.',interaction:'review',autoFields:[F('Student','{applicant}','read'),F('Proposed GR','{grNo}','read'),F('Class / Division','{class}','read'),F('Required Documents','Complete','status'),F('Handoff','Ready for Headmaster','status')],actionLabel:'Save Intake & Send to Headmaster',effect:['Canonical admission application is saved in cloud workflow.','Headmaster receives the same intake in Admissions Review & Confirmation.','No permanent Student Master or login has been created yet.']},
      {id:'hm-verification',role:'headmaster',moduleKeyword:'Admissions Review & Confirmation',screen:'Admissions Review & Confirmation · Final Verification',title:'Review submitted admission',task:'Clerk ke submitted details already visible hain; sirf review sequence highlight hoga.',interaction:'review',autoFields:[F('Applicant','{applicant}','read'),F('Reference','{admissionNo}','read'),F('Proposed GR','{grNo}','read'),F('Requested Class','{class}','read'),F('Document Status','Verified','status'),F('Current Status','Under Review','status')],actionLabel:'Continue to Headmaster Decision',effect:['Headmaster has reviewed the verified intake.','Approval is still a separate decision.']},
      {id:'hm-approval',role:'headmaster',moduleKeyword:'Admissions Review & Confirmation',screen:'Admissions Review & Confirmation · Headmaster Decision',title:'Approve admission application',task:'Approval page par koi data entry nahi; user khud Approve karega.',interaction:'review',autoFields:[F('Applicant','{applicant}','read'),F('Application Status','Verified','status'),F('Decision Note','Optional for approval','read'),F('Next Gate','GR & Allocation','status')],actionLabel:'Approve Application',effect:['Application becomes Approved.','GR & academic allocation are unlocked.','Student Master is still NOT created until final confirmation.']},
      {id:'hm-allocation',role:'headmaster',moduleKeyword:'Admissions Review & Confirmation',screen:'Admissions Review & Confirmation · GR & Allocation',title:'Confirm GR and academic placement',task:'Actual screen ke mixed controls: GR input, date, class/division dropdown aur optional roll number.',interaction:'form',autoFields:[F('GR Number','{grNo}','text'),F('Admission Date','2026-06-15','date'),F('Class','{class}','select'),F('Division','A','select'),F('Roll Number','18','number')],actionLabel:'Continue to Confirm Admission',effect:['GR and placement are ready.','Headmaster must still perform final Confirm Admission action.']},
      {id:'hm-confirm',role:'headmaster',moduleKeyword:'Admissions Review & Confirmation',screen:'Admissions Review & Confirmation · Confirm Admission',title:'Create the permanent Student Master record',task:'Readiness checks pehle se visible; user final confirmation khud karega.',interaction:'review',autoFields:[F('Headmaster Approval','Complete','status'),F('GR Number','{grNo}','read'),F('Class','{class}','read'),F('Admission Date','15 Jun 2026','read'),F('Student Master','Ready to create','status')],actionLabel:'Confirm Admission & Create Student Record',effect:['Exactly one permanent Student Master record is created.','The confirmed GR becomes eligible for Student Portal registration.','Canonical Class Teacher receives “New Admission in Your Class” notification.']},
      {id:'teacher-receive',role:'teacher',moduleKeyword:'My Students',screen:'My Students · New Admission Notification',title:'Class Teacher receives the new student',task:'Informational role view: Student Master already exists; Teacher does not recreate or re-admit the student.',interaction:'view',autoFields:[F('Notification','New Admission in Your Class','status'),F('Student','{applicant}','read'),F('GR Number','{grNo}','read'),F('Class / Division','{class}','read'),F('Portal Status','Not Signed Up','status')],actionLabel:'Open Student in My Students',effect:['The new student is visible in the Class Teacher roster.','Student Portal signup remains a separate GR-based workflow.']},
      {id:'student-signup',role:'student',moduleKeyword:'My Home',screen:'School Login · Student Portal Signup',title:'Student registers with confirmed GR',task:'Actual Student signup form: GR + optional parent mobile + password fields. Student creates the request, not the Clerk.',interaction:'form',autoFields:[F('Admission G.R. Number','{grNo}','text'),F('Parent Mobile Number','{mobile}','text'),F('Set Password','••••••••','password'),F('Confirm Password','••••••••','password')],actionLabel:'Sign Up and Await Class Teacher Approval',effect:['A Pending Student Portal signup request is created.','Student name/class details come from existing Student Master.','Class Teacher receives the approval request.']},
      {id:'teacher-signup-approval',role:'teacher',moduleKeyword:'Student Signup Approvals',screen:'My Students · Student Signup Approvals',title:'Class Teacher approves Student Portal access',task:'Pending request already exists; Teacher sirf identity/class scope verify karke decision leta hai.',interaction:'review',autoFields:[F('Student','{applicant}','read'),F('GR / Login ID','{grNo}','read'),F('Class / Division','{class}','read'),F('Signup Status','Pending','status')],actionLabel:'Approve Student Account',effect:['Student Portal account becomes Active immediately.','Existing Student Master identity is linked; no duplicate student is created.']},
      {id:'student-view',role:'student',moduleKeyword:'My Home',screen:'Student Portal · My Home',title:'Open active Student account',task:'Read-only connected role view after Class Teacher approval.',interaction:'view',autoFields:[F('Student','{applicant}','read'),F('Login ID','{grNo}','read'),F('Class','{class}','read'),F('Account Status','Active','status'),F('Available','Timetable · Homework · Attendance · Results','read')],actionLabel:'Open My Dashboard',effect:['Student can now use role-scoped academic modules.']},
      {id:'parent-signup',role:'parent',moduleKeyword:'Parent Home',screen:'School Login · Parent Portal Signup',title:'Parent requests child link',task:'Actual Parent signup uses ward GR/PEN + registered parent mobile + password; final approval Headmaster ka hai.',interaction:'form',autoFields:[F("Ward's G.R. Number or PEN",'{grNo}','text'),F('Registered Parent Mobile','{mobile}','text'),F("Ward's Date of Birth",'2014-06-18','date'),F('Set Password','••••••••','password'),F('Confirm Password','••••••••','password')],actionLabel:'Sign Up and Await Headmaster Approval',effect:['Parent account/child-link request is created in Pending state.','Headmaster receives the Parent Accounts & Child Links approval request.']},
      {id:'hm-parent-approval',role:'headmaster',moduleKeyword:'Parent Accounts & Child Links',screen:'Parent Accounts & Child Links · Pending Approval',title:'Approve Parent account and child link',task:'Verified Student Master/GR relationship already shown; Headmaster final access decision karega.',interaction:'review',autoFields:[F('Parent / Guardian','{applicantParent}','read'),F('Linked Student','{applicant}','read'),F('GR Number','{grNo}','read'),F('Registered Mobile','{mobile}','read'),F('Request Status','Pending','status')],actionLabel:'Approve Parent Account',effect:['Parent account is approved.','Verified child link becomes active for the same Student Master identity.']},
      {id:'parent-view',role:'parent',moduleKeyword:'Parent Home',screen:'Parent Portal · Linked Child',title:'Parent sees the admitted student',task:'Admission process ka final connected result: approved Parent account me wahi child securely linked hai.',interaction:'view',autoFields:[F('Parent','{applicantParent}','read'),F('Linked Child','{applicant}','read'),F('Class','{class}','read'),F('School','{school}','read'),F('Link Status','Active','status')],actionLabel:'Open Child Overview',effect:['Parent can see authorized attendance, homework, notices and published results for the linked child.']}
    ]
  },
  {
    id:'academic-setup',number:2,title:'Academic Year → Class → Division → Curriculum',short:'Academic Setup',category:'Academic Setup & Staffing',tier:'guided',importance:'high',
    description:'Production owner modules: Academic Year & Class Setup + Subjects & Curriculum. Board/State context stays governed while the school configures its own year, classes, divisions and curriculum mapping.',
    steps:[
      {id:'year',role:'headmaster',moduleKeyword:'Academic Year & Class Setup',screen:'Academic Year & Class Setup · Academic Years',title:'Create or open the academic year',task:'Only actual editable year controls are entered; board/state context is already locked by the selected school profile.',interaction:'form',autoFields:[F('Academic Year','2026-27','text'),F('Board / Curriculum','{board}','read'),F('Jurisdiction','{jurisdiction}','read'),F('Primary Medium','{medium}','select'),F('Start Date','2026-06-15','date'),F('End Date','2027-04-30','date')],actionLabel:'Save Academic Year',effect:['Academic year becomes available to class, assignment, timetable and result workflows.','Board/State rules are not replaced by this school-level setup.']},
      {id:'class',role:'headmaster',moduleKeyword:'Academic Year & Class Setup',screen:'Academic Year & Class Setup · Classes & Divisions',title:'Create class and division structure',task:'Class/division setup uses the same form-style controls as the production academic setup.',interaction:'form',autoFields:[F('Class Name','VIII','text'),F('Division','A','text'),F('Capacity','40','number'),F('Academic Year','2026-27','select')],actionLabel:'Save Class & Division',effect:['The class/division becomes available to admissions, teacher assignments and timetable generation.']},
      {id:'subjects',role:'headmaster',moduleKeyword:'Subjects & Curriculum',screen:'Subjects & Curriculum · Class ↔ Subject Mapping',title:'Map subjects to the class',task:'Subject and class mappings are choices, not fake typing.',interaction:'selection',autoFields:[F('Class','{class}','select'),F('Subjects','{subject} · {secondarySubject}','multiselect'),F('Medium','{medium}','read'),F('Assessment Context','Selected Board Rules','status')],actionLabel:'Save Curriculum Mapping',effect:['Only mapped subjects become available to teacher assignment and result ownership.']},
      {id:'term',role:'headmaster',moduleKeyword:'Academic Year & Class Setup',screen:'Academic Year & Class Setup · Academic Term Calendar',title:'Set the academic term calendar',task:'Term dates are selected through calendar controls.',interaction:'form',autoFields:[F('Term','First Term','select'),F('Starts','2026-06-15','date'),F('Ends','2026-10-31','date'),F('Status','Ready','status')],actionLabel:'Save Term Calendar',effect:['Exam scheduling and academic planning can now use the same academic-year calendar.']}
    ]
  },
  {
    id:'teacher-assignment',number:3,title:'Class Teacher & Subject Teacher Assignment',short:'Teacher Assignment',category:'Academic Setup & Staffing',tier:'live',importance:'hero',
    description:'Headmaster assigns canonical Class Teacher and Subject Teacher duties; Teacher permissions update from the same cloud assignments.',
    steps:[
      {id:'class-teacher',role:'headmaster',moduleKeyword:'Teacher & Academic Assignments',screen:'Teacher & Academic Assignments · Class Teacher Assignment',title:'Assign Class Teacher duty',task:'Production assignment uses dropdown choices for year, class/division and teacher.',interaction:'selection',autoFields:[F('Academic Year','2026-27','select'),F('Class','8','select'),F('Division','A','select'),F('Teacher','{teacher}','select'),F('Duty','Class Teacher','read')],actionLabel:'Assign Class Teacher',effect:['Class Teacher duty is attached to the same Teacher account.','Class Teacher-only review and student permissions become available.']},
      {id:'subject-teacher',role:'headmaster',moduleKeyword:'Teacher & Academic Assignments',screen:'Teacher & Academic Assignments · Teaching Assignment',title:'Assign subject teaching scope',task:'Class, division, subject and teacher are selected from canonical masters.',interaction:'selection',autoFields:[F('Academic Year','2026-27','select'),F('Class','8','select'),F('Division','A','select'),F('Subject','{subject}','select'),F('Teacher','{teacher}','select')],actionLabel:'Save Subject Assignment',effect:['Teacher subject scope and Result ownership update.','Timetable workload can consume the same assignment without replacing it.']},
      {id:'teacher-dashboard',role:'teacher',moduleKeyword:'dashboard',screen:'Teacher Dashboard',title:'See the assignment effect',task:'Read-only Teacher view after Headmaster assignment.',interaction:'view',autoFields:[F('Teacher','{teacher}','read'),F('My Class','{class}','read'),F('My Subject','{subject}','read'),F('Additional Duty','Class Teacher','status')],actionLabel:'Open My Academic Work',effect:['Attendance, academic work, My Students and Result access now follow the assigned scope.']}
    ]
  },
  {
    id:'timetable',number:4,title:'Smart Timetable → Validate → Publish → Teacher View',short:'Timetable',category:'Daily School Operations',tier:'live',importance:'hero',
    description:'Headmaster Smart AI Timetable consumes canonical assignments/workload, validates conflicts and publishes one active timetable version.',
    steps:[
      {id:'generate',role:'headmaster',moduleKeyword:'Smart AI Timetable',screen:'Smart AI Timetable · Generation Setup',title:'Prepare timetable constraints',task:'Real configuration mixes dropdowns and numeric settings; generation remains the user action.',interaction:'form',autoFields:[F('Academic Year','2026-27','select'),F('Periods per Day','8','number'),F('Break After','Period 3','select'),F('Working Days','Mon · Tue · Wed · Thu · Fri · Sat','multiselect'),F('Scope','Whole School','select'),F('Assignment Source','Canonical Teacher Assignments','status')],actionLabel:'Generate Timetable',effect:['A conflict-aware draft is generated from the school academic structure and teacher assignments.']},
      {id:'publish',role:'headmaster',moduleKeyword:'Smart AI Timetable',screen:'Smart AI Timetable · Conflict Review',title:'Review and publish the timetable',task:'Generated rows already exist; this screen is review-only before publication.',interaction:'review',autoFields:[F('Hard Conflicts','0','status'),F('Teacher Workload','Balanced','status'),F('Unassigned Periods','0','status'),F('Draft Version','v4','read')],actionLabel:'Publish & Lock Timetable',effect:['The timetable version becomes active.','Teacher and class timetable views update from the same published feed.']},
      {id:'teacher-view',role:'teacher',moduleKeyword:'My Timetable',screen:'Timetable & Workload · My Timetable',title:'Teacher receives the published schedule',task:'Teacher does not re-enter the timetable.',interaction:'view',autoFields:[F('Teacher','{teacher}','read'),F('Period 2','{subject} · {class}','read'),F('Period 5','{secondarySubject} · {class}','read'),F('Weekly Workload','28 periods','status')],actionLabel:'Open Today Schedule',effect:['Teacher sees the same published timetable and calculated workload.']}
    ]
  },
  {
    id:'substitute',number:5,title:'Approved Absence → Substitute Allocation → Teacher Duty',short:'Substitute',category:'Daily School Operations',tier:'live',importance:'hero',
    description:'Approved staff absence identifies affected periods; Headmaster Substitute Management assigns a conflict-free temporary duty without changing the permanent timetable.',
    steps:[
      {id:'absence',role:'headmaster',moduleKeyword:'Leave Management',screen:'Leave Management · Approved Staff Absence',title:'Review affected periods',task:'Absence and affected periods are already known from the approved leave record.',interaction:'review',autoFields:[F('Absent Teacher','{teacher2}','read'),F('Leave Status','Approved','status'),F('Date','Tomorrow','read'),F('Affected Periods','3','status')],actionLabel:'Open Substitute Management',effect:['Only affected timetable slots are sent to the substitution workflow.']},
      {id:'allocation',role:'headmaster',moduleKeyword:'Smart AI Timetable',screen:'Smart AI Timetable · Substitute Management',title:'Assign a substitute teacher',task:'Period and substitute are selected; no teacher name is fake-typed.',interaction:'selection',autoFields:[F('Affected Period','Period 3','select'),F('Class','{class}','read'),F('Subject','{secondarySubject}','read'),F('Suggested Substitute','{teacher}','select'),F('Conflict Check','Available','status'),F('Workload Check','Within limit','status')],actionLabel:'Assign Substitute',effect:['Temporary substitute duty is attached to the selected period.','The permanent timetable template remains unchanged.']},
      {id:'teacher',role:'teacher',moduleKeyword:'Substitute / Adjustment Duties',screen:'Timetable & Workload · Substitute / Adjustment Duties',title:'Teacher sees the new temporary duty',task:'Read-only role view of the approved duty.',interaction:'view',autoFields:[F('Teacher','{teacher}','read'),F('New Duty','Period 3 · {class}','read'),F('Reason','Substitute for {teacher2}','read'),F('Status','Assigned','status')],actionLabel:'Acknowledge Duty',effect:['Teacher has a clear daily adjustment while the original timetable stays intact.']}
    ]
  },
  {
    id:'attendance',number:6,title:'Daily Attendance → Monthly Register → Student & Parent',short:'Attendance',category:'Daily School Operations',tier:'live',importance:'hero',
    description:'Teacher marks the authorized class roster with real attendance controls; the same cloud status drives monthly register, Student and Parent views.',
    steps:[
      {id:'mark',role:'teacher',moduleKeyword:'Attendance',screen:'Attendance · Daily Roll Call',title:'Mark daily attendance',task:'Class/date are selected and attendance uses P/A-style action controls, not text typing.',interaction:'selection',autoFields:[F('Class / Division','{class}','select'),F('Date','2026-09-04','date'),F('Student','{student}','read'),F('Attendance Status','Absent','choice')],actionLabel:'Save Attendance',effect:['Daily attendance is saved for the permitted roster.','Monthly attendance calculations update from the same record.']},
      {id:'catalogue',role:'teacher',moduleKeyword:'Attendance',screen:'Attendance · Monthly Catalogue / Register',title:'See the monthly effect',task:'Monthly catalogue is calculated; Teacher reviews rather than retyping totals.',interaction:'view',autoFields:[F('Month','September 2026','read'),F('Student','{student}','read'),F('Present Days','18','status'),F('Absent Days','1','status'),F('Attendance %','94.7%','status')],actionLabel:'Open Monthly Register',effect:['The monthly register reflects the saved daily attendance automatically.']},
      {id:'student',role:'student',moduleKeyword:'Attendance',screen:'Student · My Attendance',title:'Student sees own attendance',task:'Read-only Student view.',interaction:'view',autoFields:[F('Student','{student}','read'),F('Today','Absent','status'),F('Month','94.7%','status'),F('History','Available','read')],actionLabel:'Open Attendance History',effect:['Student can review attendance but cannot overwrite Teacher records.']},
      {id:'parent',role:'parent',moduleKeyword:'Attendance',screen:'Parent · Child Attendance',title:'Parent sees the same attendance source',task:'Linked-child read-only view.',interaction:'view',autoFields:[F('Child','{student}','read'),F('Today','Absent','status'),F('Month','94.7%','status'),F('Source','Canonical attendance record','read')],actionLabel:'View Monthly Summary',effect:['Parent and Student views reuse the same attendance record.']}
    ]
  },
  {
    id:'study-material',number:7,title:'Study Material → Textbook Source → AI Context',short:'Study Material',category:'Teaching & AI',tier:'guided',importance:'high',
    description:'Teacher enters the assigned class/subject library, uses the Textbook category and makes a source available to AI academic tools.',
    steps:[
      {id:'material',role:'teacher',moduleKeyword:'Study Material',screen:'Teaching & Academic Work · Study Material',title:'Choose class, subject and Textbook category',task:'Class/subject/category use card/choice behavior; upload uses the actual file selector.',interaction:'form',autoFields:[F('Class','8','choice'),F('Subject','{subject}','choice'),F('Category','Textbook','choice'),F('Textbook Name','Demo {subject} Textbook','text'),F('Source','demo_textbook.pdf','file')],actionLabel:'Upload Textbook',effect:['The temporary textbook appears in the Teacher Study Material library.','Production uses private storage/indexing; public demo does not upload to the real school bucket.']},
      {id:'ai-ready',role:'teacher',moduleKeyword:'AI Lesson Plan',screen:'Teaching & Academic Work · AI Tools',title:'Use the approved textbook source',task:'Source context is already available; this is a selection/view step.',interaction:'selection',autoFields:[F('Class','{class}','select'),F('Subject','{subject}','select'),F('Source','Demo {subject} Textbook','select'),F('Chapter','Chapter 4 · Energy & Motion','select'),F('Language','{medium}','select')],actionLabel:'Open AI Teaching Tools',effect:['Supported AI Year Plan, Daily Plan, Lesson Plan, Homework and Question Paper can reuse the selected source.']}
    ]
  },
  {
    id:'ai-teaching',number:8,title:'AI Year Plan → Daily Plan → Lesson Plan → Teaching Diary',short:'AI Teaching',category:'Teaching & AI',tier:'live',importance:'hero',
    description:'Teacher experiences the real planning chain instead of four disconnected AI buttons.',
    steps:[
      {id:'year-plan',role:'teacher',moduleKeyword:'AI Year Plan',screen:'Teaching & Academic Work · AI Year Plan',title:'Generate the annual plan',task:'Scope and source are selected; generation remains the user decision.',interaction:'selection',autoFields:[F('Class','{class}','select'),F('Subject','{subject}','select'),F('Academic Year','2026-27','select'),F('Textbook Source','Demo {subject} Textbook','select'),F('Output Language','{medium}','select')],actionLabel:'Generate Year Plan',effect:['An editable annual/month-wise plan draft is prepared.']},
      {id:'daily-plan',role:'teacher',moduleKeyword:'AI Daily Teaching Plan',screen:'Teaching & Academic Work · AI Daily Teaching Plan',title:'Prepare today’s teaching sequence',task:'Date/topic/source selections reuse the same academic context.',interaction:'selection',autoFields:[F('Class','{class}','select'),F('Subject','{subject}','select'),F('Date','2026-09-04','date'),F('Chapter','Chapter 4','select'),F('Source','Demo {subject} Textbook','select')],actionLabel:'Generate Daily Teaching Plan',effect:['Objectives, sequence, activities and resources are prepared for review.']},
      {id:'lesson',role:'teacher',moduleKeyword:'AI Lesson Plan',screen:'Teaching & Academic Work · AI Lesson Plan',title:'Generate a lesson plan',task:'Dropdown selections remain selections; only actual free-text Teacher note is typed.',interaction:'form',autoFields:[F('Topic','Energy & Motion','select'),F('Duration (minutes)','40','number'),F('Teaching Approach','Activity Based','select'),F('Teacher Note','Include one local classroom example.','textarea')],actionLabel:'Generate Lesson Plan',effect:['Editable lesson plan is generated and linked to the selected topic/source.']},
      {id:'diary',role:'teacher',moduleKeyword:'AI Teaching Diary',screen:'Teaching & Academic Work · AI Teaching Diary',title:'Record what was actually taught',task:'Completed plan context is reused; Teacher records actual status/remarks.',interaction:'form',autoFields:[F('Date','2026-09-04','date'),F('Lesson Plan','Energy & Motion · LP-104','select'),F('Completion Status','Completed','select'),F('Actual Teaching Note','Lesson completed with activity and recap.','textarea')],actionLabel:'Save Teaching Diary',effect:['Planned work and completed classroom work remain connected in the Teacher record.']}
    ]
  },
  {
    id:'homework',number:9,title:'AI Homework → Review → Publish → Student & Parent',short:'AI Homework',category:'Teaching & AI',tier:'live',importance:'hero',
    description:'Teacher generates source-scoped homework with the same types of controls used by Homework Builder, then publishes once for Student and Parent views.',
    steps:[
      {id:'generate',role:'teacher',moduleKeyword:'AI Homework',screen:'Teaching & Academic Work · AI Homework',title:'Configure homework',task:'Chapter/pattern/difficulty/language are selections; homework types use checks; only title/instruction are typed.',interaction:'form',autoFields:[F('Class','{class}','select'),F('Subject','{subject}','select'),F('Chapter','Chapter 4 · Energy & Motion','select'),F('Pattern','Practice Homework','select'),F('Question Types','Short Answer · MCQ','multiselect'),F('Difficulty','Balanced','select'),F('Due Date','2026-09-05','date'),F('Output Language','{medium}','select'),F('Homework Title','{subject} · Chapter 4 Practice','text')],actionLabel:'Generate Homework',effect:['An editable homework draft is generated from the selected textbook context.']},
      {id:'publish',role:'teacher',moduleKeyword:'AI Homework',screen:'AI Homework · Preview & Publish',title:'Review and publish homework',task:'Generated content already exists; Teacher reviews before publication.',interaction:'review',autoFields:[F('Title','{subject} · Chapter 4 Practice','read'),F('Questions','8','status'),F('Due','05 Sep 2026','read'),F('Status','Draft','status')],actionLabel:'Publish Homework',effect:['One published homework record becomes available to the assigned Students.','Linked Parents can see the same homework summary.']},
      {id:'student',role:'student',moduleKeyword:'Homework & Assignments',screen:'Student · Homework & Assignments',title:'Student receives the homework',task:'Read-only Student view.',interaction:'view',autoFields:[F('Student','{student}','read'),F('Homework','{subject} · Chapter 4 Practice','read'),F('Due','05 Sep 2026','read'),F('Status','New','status')],actionLabel:'Open Homework',effect:['Student sees the Teacher-published assignment.']},
      {id:'parent',role:'parent',moduleKeyword:'Homework',screen:'Parent · Child Homework',title:'Parent sees the same homework',task:'Read-only linked-child view.',interaction:'view',autoFields:[F('Child','{student}','read'),F('Homework','{subject} · Chapter 4 Practice','read'),F('Due','05 Sep 2026','read')],actionLabel:'View Child Homework',effect:['Teacher publishes once; Student and Parent consume the same assignment record.']}
    ]
  },
  {
    id:'question-paper',number:10,title:'Question Paper → Teacher Review → Headmaster Finalization → Print',short:'Question Paper',category:'Teaching & AI',tier:'live',importance:'hero',
    description:'Real generator controls are respected: class/division/subject dropdowns, chapter/source checks, marks/duration numbers, Teacher review and Headmaster finalization.',
    steps:[
      {id:'scope',role:'teacher',moduleKeyword:'Question Paper',screen:'Question Paper Generator',title:'Configure the paper scope',task:'The demo mirrors the actual control types rather than typing every value.',interaction:'form',autoFields:[F('Exam','Unit Test 1','choice'),F('Paper Mode','Single Subject','choice'),F('Class','8','select'),F('Division','A','select'),F('Subject','{subject}','select'),F('Chapters','Chapter 3 · Chapter 4','multiselect'),F('Whole Chapter Source','Yes','checkbox'),F('Exercise Source','Yes','checkbox'),F('Total Marks','20','number'),F('Duration (minutes)','45','number'),F('Language','{medium}','select')],actionLabel:'Generate Question Paper',effect:['A question-paper draft is generated for Teacher review.']},
      {id:'teacher-review',role:'teacher',moduleKeyword:'Question Paper',screen:'Question Paper · Teacher Review',title:'Edit and mark the paper reviewed',task:'Generated questions exist; only a genuine question edit types text and the review flag uses a checkbox.',interaction:'form',autoFields:[F('Question 1','Explain the main idea in your own words.','textarea'),F('Teacher Reviewed','Yes','checkbox'),F('Marks Validation','20 / 20','status')],actionLabel:'Save Reviewed Paper',effect:['Teacher-reviewed paper is saved to the shared Question Paper workflow.']},
      {id:'hm-review',role:'headmaster',moduleKeyword:'Exams & Question Papers',screen:'Exams & Question Papers · Question Paper Review & Finalization',title:'Headmaster finalizes the reviewed paper',task:'No fake data entry on approval/finalization.',interaction:'review',autoFields:[F('Teacher','{teacher}','read'),F('Class / Subject','{class} · {subject}','read'),F('Total Marks','20','status'),F('Teacher Review','Complete','status')],actionLabel:'Finalize Question Paper',effect:['Paper becomes finalized for the controlled exam/print workflow.']},
      {id:'print',role:'teacher',moduleKeyword:'Question Paper',screen:'Classtago Smart Print · Question Paper',title:'Choose print settings',task:'Paper size/orientation are dropdown selections; page/header options are checks.',interaction:'selection',autoFields:[F('Paper Size','A4','select'),F('Orientation','Portrait','select'),F('School Header','On','checkbox'),F('Page Numbers','On','checkbox')],actionLabel:'Preview PDF / Print',effect:['Demo shows print/PDF preparation without issuing a real production examination paper.']}
    ]
  },
  {
    id:'exam-setup',number:11,title:'Exam Setup → Official Schedule → Teacher Context',short:'Exam Setup',category:'Exams & Results',tier:'guided',importance:'high',
    description:'Term/exam configuration stays governed by Academic Setup; Headmaster Exam Control owns official schedule rows and publication.',
    steps:[
      {id:'exam',role:'headmaster',moduleKeyword:'Academic Year & Class Setup',screen:'Academic Setup · Term / Exam Configuration',title:'Define the exam context',task:'Actual setup combines choices, dates and numeric marks.',interaction:'form',autoFields:[F('Academic Year','2026-27','select'),F('Term','First Term','select'),F('Exam Name','Unit Test 1','text'),F('Class','{class}','select'),F('Total Marks','20','number')],actionLabel:'Save Exam Context',effect:['The exam identity becomes available to schedule and result workflows.']},
      {id:'schedule',role:'headmaster',moduleKeyword:'Exams & Question Papers',screen:'Exams & Question Papers · Official Exam Schedule',title:'Create schedule rows',task:'Date/time/room are entered with their real control types.',interaction:'form',autoFields:[F('Subject','{subject}','select'),F('Exam Date','2026-09-15','date'),F('Start Time','10:00','time'),F('End Time','10:45','time'),F('Room','Room 8-A','text'),F('Instructions','Bring required stationery.','textarea')],actionLabel:'Save Schedule Row',effect:['A draft official exam schedule row is created.']},
      {id:'publish',role:'headmaster',moduleKeyword:'Exams & Question Papers',screen:'Exam Schedule · Review & Publish',title:'Publish the official schedule',task:'Schedule rows are already filled; this is review-only.',interaction:'review',autoFields:[F('Schedule Rows','6','status'),F('Clash Check','No clash','status'),F('Status','Draft','status')],actionLabel:'Publish Exam Schedule',effect:['Published schedule becomes the school exam source-of-truth.']},
      {id:'teacher-ready',role:'teacher',moduleKeyword:'Subject Marks List',screen:'Result Management · Subject Marks List',title:'Teacher receives the exam context',task:'Teacher does not recreate the exam.',interaction:'view',autoFields:[F('Exam','Unit Test 1','read'),F('Class','{class}','read'),F('Subject','{subject}','read'),F('Maximum Marks','20','status')],actionLabel:'Open Marks Entry',effect:['Assigned Subject Teacher can now enter marks against the configured exam.']}
    ]
  },
  {
    id:'result-management',number:12,title:'Subject Marks → Class Review → Result Book → Clerk Queue → Headmaster Publish → Parent',short:'Result Management',category:'Exams & Results',tier:'live',importance:'hero',
    description:'Audited against the current Teacher/Class Teacher/Clerk/Headmaster result chain instead of a shortened generic approval flow.',
    steps:[
      {id:'teacher-marks',role:'teacher',moduleKeyword:'Subject Marks List',screen:'Result Management · Subject Marks List',title:'Enter subject marks',task:'Scope/term use dropdowns and actual marks use numeric entry.',interaction:'form',autoFields:[F('Class / Division','{class}','select'),F('Term','First Term','select'),F('Subject','{subject}','read'),F('{student}','18','number'),F('{student2}','17','number'),F('{student3}','15','number'),F('Maximum','20','status')],actionLabel:'Submit Marks to Class Teacher',effect:['Subject Marks List enters Submitted state.','Subject Teacher cannot directly publish the class result.']},
      {id:'class-review',role:'teacher',moduleKeyword:'Class Mark List',screen:'Result Management · Class Mark List',title:'Class Teacher reviews submitted subject lists',task:'Submitted lists already exist; Class Teacher reviews them without retyping marks.',interaction:'review',autoFields:[F('Class','{class}','read'),F('Submitted Subjects','6 / 6','status'),F('Missing Marks','0','status'),F('Review Status','Ready','status')],actionLabel:'Send Accepted Lists to Result Book',effect:['Accepted Subject Mark Lists become eligible for Result Book consolidation.','A correction path remains available in production if a list is wrong.']},
      {id:'result-book',role:'teacher',moduleKeyword:'Result Book',screen:'Result Management · Result Book',title:'Build the class Result Book',task:'Result Book is consolidated from accepted lists; totals are not re-entered manually.',interaction:'review',autoFields:[F('Class','{class}','read'),F('Accepted Lists','6','status'),F('Students','32','status'),F('Consolidation','Complete','status')],actionLabel:'Send to Progress Card & Clerk',effect:['Progress Card data is prepared.','Clerk Result Print Center receives the print workflow item.']},
      {id:'clerk-queue',role:'clerk',moduleKeyword:'Result Printing & Master Result Book',screen:'Result Print Center',title:'Clerk receives the print item',task:'Clerk sees the same completed result item; no academic marks are edited here.',interaction:'view',autoFields:[F('Class','{class}','read'),F('Item','Progress Card Batch','read'),F('Students','32','status'),F('Print Status','Pending','status')],actionLabel:'Open Smart Print Queue',effect:['Office printing is separated from academic marks ownership.']},
      {id:'hm-review',role:'headmaster',moduleKeyword:'Result Management',screen:'Result Management · Publication Queue',title:'Headmaster reviews publication readiness',task:'Final authority reviews the completed result; no mark typing occurs.',interaction:'review',autoFields:[F('Class','{class}','read'),F('Result Book','Complete','status'),F('Progress Cards','Ready','status'),F('Validation','Passed','status')],actionLabel:'Mark Result Reviewed',effect:['Publication gate is unlocked only after Headmaster review.']},
      {id:'hm-publish',role:'headmaster',moduleKeyword:'Result Management',screen:'Result Management · Publication & Final Lock',title:'Publish and lock the result',task:'This is an approval/publication action only.',interaction:'review',autoFields:[F('Review','Complete','status'),F('Publish Readiness','Ready','status'),F('Lock After Publish','Yes','status')],actionLabel:'Publish & Lock',effect:['Published result becomes read-only for Student/Parent presentation.','Final lock prevents silent post-publication edits.']},
      {id:'parent-card',role:'parent',moduleKeyword:'Results & Progress',screen:'Parent · Results & Progress',title:'Parent opens the final Progress Card',task:'Read-only linked-child document view.',interaction:'view',autoFields:[F('Child','{student}','read'),F('Exam','Unit Test 1','read'),F('{subject}','18 / 20','read'),F('Result Status','Published','status'),F('Template','Active School Progress Card','read')],actionLabel:'Open Progress Card',effect:['The same published result reaches the linked Parent without duplicating academic data.']}
    ]
  },
  {
    id:'templates',number:13,title:'Result Template Routing → School Format Import → Render',short:'Result Templates',category:'Exams & Results',tier:'guided',importance:'high',
    description:'Clerk can route canonical result templates; a new school can also import existing Mark List/Result Book/Progress Card evidence for governed onboarding.',
    steps:[
      {id:'mapping',role:'clerk',moduleKeyword:'Result Printing & Master Result Book',screen:'Teacher Mark List Template Routing',title:'Map a Master template to Class + Subject',task:'Production mapping uses three dropdowns and Save Mapping.',interaction:'selection',autoFields:[F('Class','{class}','select'),F('Subject','{subject}','select'),F('Master Template','Class 1–8 Regular','select')],actionLabel:'Save Template Mapping',effect:['Teachers receive the mapped Master Mark List automatically; they do not choose templates themselves.']},
      {id:'import',role:'clerk',moduleKeyword:'Result Printing & Master Result Book',screen:'Dynamic Result Engine · New School Onboarding',title:'Import an existing school result format',task:'For onboarding only: source document role is chosen and files use file-selection controls.',interaction:'form',autoFields:[F('Document Role','Progress Card / Report Card','choice'),F('Existing School Format','school_progress_card.pdf','file'),F('Clerk Verification Note','Existing school layout provided for mapping review.','textarea')],actionLabel:'Analyze School Format',effect:['Demo prepares a proposed mapping without replacing active academic truth.','In production, Headmaster verification is required before a new Result System becomes active.']},
      {id:'preview',role:'clerk',moduleKeyword:'Result Printing & Master Result Book',screen:'Result Template Preview',title:'Review mapped fields',task:'Detected fields and compatibility are reviewed, not retyped.',interaction:'review',autoFields:[F('Student Fields','Mapped','status'),F('Subject / Marks Fields','Mapped','status'),F('Attendance / Remarks','Mapped','status'),F('Board Compatibility','Needs/Passed verification','status')],actionLabel:'Use Approved Mapping in Demo',effect:['A structured template can render canonical result data while marks/calculations remain governed separately.']},
      {id:'render',role:'parent',moduleKeyword:'Results & Progress',screen:'Parent · Progress Card Template Preview',title:'See the same result in the selected layout',task:'Read-only presentation view.',interaction:'view',autoFields:[F('Student','{student}','read'),F('Template','Selected School Format','read'),F('Language','{medium}','read'),F('Data Source','Published Result','status')],actionLabel:'Preview Progress Card',effect:['Layout changes; the underlying published marks do not.']}
    ]
  },
  {
    id:'student-lifecycle',number:14,title:'Student Lifecycle Request → Headmaster Decision → Updated Placement',short:'Student Lifecycle',category:'Admissions & Student Journey',tier:'guided',importance:'standard',
    description:'Uses a Class/Division Transfer example because annual Promotion is owned by the Result Promotion Engine, not a generic Clerk lifecycle approval.',
    steps:[
      {id:'request',role:'clerk',moduleKeyword:'Student Lifecycle Support',screen:'Student Lifecycle Support · Class / Division Transfer Request',title:'Prepare a controlled placement request',task:'Student/action/target use selections; only reason is free text.',interaction:'form',autoFields:[F('Student','{student}','select'),F('Current Placement','{class}','read'),F('Action','Class / Division Transfer','select'),F('Target Class','8','select'),F('Target Division','B','select'),F('Reason','Administrative division balancing.','textarea')],actionLabel:'Send Request to Headmaster',effect:['Request enters the Headmaster Student Lifecycle queue.','Clerk cannot silently change class/division outside the lifecycle workflow.']},
      {id:'approve',role:'headmaster',moduleKeyword:'Student Lifecycle',screen:'Student Lifecycle · Pending Clerk Request',title:'Review and approve the transfer',task:'Submitted placement request is review-only.',interaction:'review',autoFields:[F('Student','{student}','read'),F('Current','{class}','read'),F('Target','8-B','read'),F('Request Status','Pending','status')],actionLabel:'Approve Transfer',effect:['Student placement updates while permanent identity/history is preserved.']},
      {id:'student-view',role:'student',moduleKeyword:'My Home',screen:'Student · My Home',title:'Student sees the updated placement',task:'Read-only Student view after approved lifecycle change.',interaction:'view',autoFields:[F('Student','{student}','read'),F('Current Class','8-B','status'),F('GR Number','{grNo}','read'),F('History','Previous placement retained','read')],actionLabel:'Open Updated Profile',effect:['Placement changes without creating a new Student identity.']}
    ]
  },
  {
    id:'leave',number:15,title:'Teacher Leave → Headmaster Approval → Substitute Handoff',short:'Leave Management',category:'Daily School Operations',tier:'live',importance:'high',
    description:'Teacher uses the real leave form control pattern; Headmaster review has no fake typing and approved leave can hand off to Substitute Management.',
    steps:[
      {id:'apply',role:'teacher',moduleKeyword:'Leave & Personal HR',screen:'Leave & Personal HR · New Leave Request',title:'Submit a leave request',task:'Leave type/dates/half-day use actual selectors; reason is the free-text field.',interaction:'form',autoFields:[F('Leave Type','Casual Leave','select'),F('Start Date','2026-09-05','date'),F('End Date','2026-09-05','date'),F('Half Day','No','checkbox'),F('Reason','Personal work','textarea')],actionLabel:'Submit to Headmaster',effect:['A pending staff leave request is created.']},
      {id:'approve',role:'headmaster',moduleKeyword:'Leave Management',screen:'Leave Management · Staff Leave Review',title:'Review and approve Teacher leave',task:'Teacher submission is already visible; Headmaster only decides.',interaction:'review',autoFields:[F('Teacher','{teacher2}','read'),F('Leave Type','Casual Leave','read'),F('Date','05 Sep 2026','read'),F('Affected Periods','3','status'),F('Status','Pending','status')],actionLabel:'Approve & Open Substitute Plan',effect:['Leave becomes Approved.','Affected periods are made available to Substitute Management.']},
      {id:'teacher-status',role:'teacher',moduleKeyword:'Leave & Personal HR',screen:'Leave & Personal HR · Request History',title:'Teacher sees the final status',task:'Read-only history view.',interaction:'view',autoFields:[F('Request','Casual Leave · 05 Sep','read'),F('Status','Approved','status'),F('Decision','Headmaster approved','read')],actionLabel:'Open Leave History',effect:['Teacher and Headmaster share one audited leave workflow.']}
    ]
  },
  {
    id:'communication',number:16,title:'Clerk Notice Draft → Headmaster Publish → Parent Receive',short:'Communication',category:'Communication & School Services',tier:'guided',importance:'high',
    description:'Actual office governance: Clerk prepares notice/circular drafts; official publishing remains Headmaster-controlled; public demo simulates external delivery.',
    steps:[
      {id:'draft',role:'clerk',moduleKeyword:'Communication Drafts & Office Dispatch',screen:'Communication · Notice / Circular Drafts',title:'Prepare a school notice draft',task:'Title/body are typed, category is a dropdown and audience uses role buttons/multi-select.',interaction:'form',autoFields:[F('Notice Title','Parent-Teacher Meeting','text'),F('Category','General','select'),F('Notice Body','Parent-Teacher meeting will be held on Saturday at 10:00 AM.','textarea'),F('Target Roles','Parent · Student','multiselect')],actionLabel:'Send for Headmaster Approval',effect:['Notice enters the Headmaster approval queue; it is not publicly delivered yet.']},
      {id:'publish',role:'headmaster',moduleKeyword:'Communication Hub',screen:'Communication Hub · Clerk Notice Approval Queue',title:'Approve and publish the notice',task:'Draft content is already visible; Headmaster chooses Publish or Reject.',interaction:'review',autoFields:[F('Prepared By','{clerk}','read'),F('Notice','Parent-Teacher Meeting','read'),F('Audience','Parent · Student','read'),F('Status','Pending','status')],actionLabel:'Approve & Publish',effect:['In-app notification is published to the selected school roles.','WhatsApp/SMS/Email are simulated only in public demo.']},
      {id:'parent',role:'parent',moduleKeyword:'Messages & Notices',screen:'Parent · Messages & Notices',title:'Parent receives the school notice',task:'Read-only Parent view.',interaction:'view',autoFields:[F('Notice','Parent-Teacher Meeting','read'),F('Child','{student}','read'),F('Status','New','status'),F('Source','School Communication Hub','read')],actionLabel:'Open Notice',effect:['The same published communication appears in the linked Parent account.']}
    ]
  },
  {
    id:'website-campaign',number:17,title:'Website Design → Publish + Admission Campaign → Public View',short:'Website & Campaign',category:'Communication & School Services',tier:'guided',importance:'standard',
    description:'Clerk owns Website Design & Content and Admission Campaign Setup. Website changes are drafted/previewed before publish; campaign setup remains separate from Headmaster admission confirmation.',
    steps:[
      {id:'edit',role:'clerk',moduleKeyword:'Website Design & Content',screen:'Website Design & Content · Home Page',title:'Edit the school website',task:'Text areas remain text; media uses a file selector; section choice uses buttons/dropdown behavior.',interaction:'form',autoFields:[F('Section','Home Banner','choice'),F('Eyebrow','Admissions 2026-27','text'),F('Main Title','Learn. Grow. Lead.','text'),F('Description','Admissions are now open for the new academic session.','textarea'),F('Hero Image','school_banner.webp','file')],actionLabel:'Save Draft',effect:['Website draft is saved privately and can be previewed before going live.']},
      {id:'publish',role:'clerk',moduleKeyword:'Website Design & Content',screen:'Website Design & Content · Private Preview',title:'Publish the saved website draft',task:'No re-entry on publish confirmation.',interaction:'review',autoFields:[F('Draft Status','Saved','status'),F('Unpublished Changes','Yes','status'),F('Preview','Ready','status')],actionLabel:'Publish Website',effect:['Demo public school website receives the temporary published version.']},
      {id:'campaign',role:'clerk',moduleKeyword:'Admission Campaign Setup',screen:'Admission Campaign Setup',title:'Configure the admission campaign',task:'Dates/numbers use actual controls; title/description are free text.',interaction:'form',autoFields:[F('Admission Session','2026-27 Admissions','text'),F('Maximum Applications','500','number'),F('Start','2026-09-10T09:00','datetime'),F('End','2026-10-10T18:00','datetime'),F('Eligible Classes','Class 1 · Class 5 · Class 8','multiselect'),F('Public Title','Admissions Open 2026-27','text')],actionLabel:'Save Campaign',effect:['Campaign remains in Clerk-owned setup; Headmaster admission review/confirmation stays separate.']},
      {id:'public',role:'parent',moduleKeyword:'Parent Home',screen:'Demo School Public Website',title:'See the public-facing result',task:'Read-only visitor-style view.',interaction:'view',autoFields:[F('Website Banner','Admissions 2026-27','read'),F('Campaign CTA','Apply Online','status'),F('School','{school}','read')],actionLabel:'Open Public Admission Page',effect:['The demo shows how Clerk-managed public content connects to the admission journey.']}
    ]
  },
  {
    id:'certificate-print',number:18,title:'Clerk Certificate → Headmaster Issue → Multilingual Smart Print',short:'Certificates & Print',category:'Communication & School Services',tier:'guided',importance:'standard',
    description:'Clerk prepares certificates; Headmaster is the official approval/issue authority; only issued records are printable from the official vault.',
    steps:[
      {id:'certificate',role:'clerk',moduleKeyword:'Certificate Studio & Management',screen:'Certificates & Documents · Certificate Studio',title:'Prepare a certificate request',task:'Student/year/class/language/template are selections.',interaction:'selection',autoFields:[F('Academic Year','2026-27','select'),F('Class','{class}','select'),F('Student','{student}','select'),F('Certificate Type','Bonafide Certificate','select'),F('Language','{medium}','select'),F('Template','School Standard','choice')],actionLabel:'Send to Headmaster',effect:['Prepared certificate enters the Headmaster Certificate Approval Queue.']},
      {id:'approve',role:'headmaster',moduleKeyword:'Certificates & Documents',screen:'Certificates & Documents · Certificate Approval Queue',title:'Approve and officially issue the certificate',task:'Request data is already visible; Headmaster only decides.',interaction:'review',autoFields:[F('Student','{student}','read'),F('GR Number','{grNo}','read'),F('Certificate','Bonafide Certificate','read'),F('Status','Pending Headmaster','status')],actionLabel:'Approve & Issue',effect:['An official certificate number and audit decision are created.']},
      {id:'print',role:'headmaster',moduleKeyword:'Certificates & Documents',screen:'Certificates & Documents · Multilingual Official Print',title:'Choose print language and prepare PDF',task:'Only issued certificates can be selected for official print.',interaction:'selection',autoFields:[F('Issued Certificate','Bonafide · {student}','select'),F('Print Language','{medium}','select'),F('Paper','A4','select')],actionLabel:'Smart Print / PDF',effect:['Demo prepares the issued certificate for print/PDF without affecting production records.']}
    ]
  },
  {
    id:'multilingual',number:19,title:'One Record → Feature Language → Localized Output',short:'Multilingual Documents',category:'Platform & Documents',tier:'live',importance:'high',
    description:'Feature/document language changes presentation only; it does not change Board Rules or the app-wide UI language.',
    steps:[
      {id:'select',role:'teacher',moduleKeyword:'AI Homework',screen:'AI Homework · Output Language',title:'Choose the document output language',task:'Language is a dropdown choice, independent from the instruction/UI language.',interaction:'selection',autoFields:[F('App / Demo UI','English','read'),F('Feature','Homework','read'),F('Output Language','{medium}','select'),F('Academic Rules','Unchanged','status')],actionLabel:'Apply Output Language',effect:['The homework/document presentation switches language while the canonical record and calculations stay the same.']},
      {id:'preview',role:'parent',moduleKeyword:'Homework',screen:'Parent · Localized Homework',title:'Parent sees the localized presentation',task:'Read-only view of the same homework.',interaction:'view',autoFields:[F('Child','{student}','read'),F('Document','Homework','read'),F('Language','{medium}','status'),F('Data Source','Same published homework','read')],actionLabel:'Open Localized View',effect:['One canonical record can have a permitted localized presentation.']}
    ]
  },
  {
    id:'connected-family',number:20,title:'Student & Parent Connected Daily Experience',short:'Student / Parent',category:'Platform & Documents',tier:'live',importance:'high',
    description:'A read-only connected-role tour showing that Timetable, Attendance, Homework, Notices and published Results are not duplicate records.',
    steps:[
      {id:'student',role:'student',moduleKeyword:'My Home',screen:'Student Portal · My Home',title:'Open the Student daily view',task:'Student sees only own authorized records.',interaction:'view',autoFields:[F('Student','{student}','read'),F('Class','{class}','read'),F('Today','Timetable · Attendance · Homework','read'),F('Published Results','Available','status')],actionLabel:'Open My Day',effect:['Student dashboard consolidates authorized school records.']},
      {id:'parent',role:'parent',moduleKeyword:'Parent Home',screen:'Parent Portal · Parent Home',title:'Open the linked Parent view',task:'Parent sees the same child records through the approved relationship.',interaction:'view',autoFields:[F('Parent','{parent}','read'),F('Linked Child','{student}','read'),F('Attendance','Current month','read'),F('Homework','Latest published','read'),F('Results','Published only','status')],actionLabel:'Open Child Overview',effect:['Parent visibility reuses the Student identity and published school records.']}
    ]
  },
  {
    id:'fees-receipts',number:21,title:'Fee Collection → Permanent Receipt → Parent View',short:'Fees & Receipts',category:'Communication & School Services',tier:'guided',importance:'standard',
    description:'Clerk owns canonical fee collection/receipts. Concession and cancellation approvals remain separate Headmaster authorities.',
    steps:[
      {id:'fee-desk',role:'clerk',moduleKeyword:'Fees',screen:'Fees · Fee Collection',title:'Record a student payment',task:'Student/payment mode are selections; amount is numeric; reference/notes are text; advance permission is a checkbox.',interaction:'form',autoFields:[F('Student','{student}','select'),F('Current Balance','₹2,500','read'),F('Payment Amount','2500','number'),F('Payment Mode','UPI','select'),F('Reference','DEMO-UPI-4821','text'),F('Allow Advance Payment','No','checkbox')],actionLabel:'Record Payment & Issue Receipt',effect:['A temporary demo receipt is produced.','No real payment is collected in the public demo.']},
      {id:'receipt',role:'clerk',moduleKeyword:'Fees',screen:'Fees · Receipts & Student Ledger',title:'Open the issued receipt',task:'Receipt is already created and read-only.',interaction:'view',autoFields:[F('Receipt No.','DEMO-RCPT-2418','read'),F('Student','{student}','read'),F('Paid','₹2,500','status'),F('Balance','₹0','status')],actionLabel:'Print / PDF Receipt',effect:['Receipt and Student ledger share the same fee transaction.']},
      {id:'parent-receipt',role:'parent',moduleKeyword:'Fees & Receipts',screen:'Parent · Fees & Receipts',title:'Parent sees the same receipt',task:'Read-only linked-child fee view.',interaction:'view',autoFields:[F('Child','{student}','read'),F('Receipt','DEMO-RCPT-2418','read'),F('Paid','₹2,500','status'),F('Balance','₹0','status')],actionLabel:'Open Receipt',effect:['Parent sees the same canonical fee position and receipt history.']}
    ]
  },
  {
    id:'library',number:22,title:'Student Book Request → Headmaster Library Issue → Parent View',short:'Library',category:'Communication & School Services',tier:'guided',importance:'standard',
    description:'Corrects the old Clerk-register shortcut: the Statutory Library Register is generated support, while operational library work is in Digital Library and Student service requests.',
    steps:[
      {id:'request',role:'student',moduleKeyword:'My Library',screen:'Student · My Library',title:'Request a library book',task:'Book selection is a choice; request is the Student action.',interaction:'selection',autoFields:[F('Book','Young Scientist · Vol. 2','select'),F('Availability','Available','status'),F('Student','{student}','read')],actionLabel:'Request Book',effect:['A Student library request becomes available to the school service workflow.']},
      {id:'issue',role:'headmaster',moduleKeyword:'Digital Library',screen:'Digital Library · Issue / Return Monitoring',title:'Issue the requested book',task:'Book and borrower type are dropdowns, borrower ID/name are form fields, due date uses the date picker.',interaction:'form',autoFields:[F('Book','LIB-0842 · Young Scientist · Vol. 2','select'),F('Borrower Type','Student','select'),F('Borrower Name','{student}','text'),F('Borrower ID','{grNo}','text'),F('Due Date','2026-09-18','date')],actionLabel:'Issue Book',effect:['A temporary library loan is created for the Student.']},
      {id:'student-loan',role:'student',moduleKeyword:'My Library',screen:'Student · My Library',title:'Student sees the active loan',task:'Read-only loan view.',interaction:'view',autoFields:[F('Book','Young Scientist · Vol. 2','read'),F('Status','Issued','status'),F('Due','18 Sep 2026','read'),F('Fine','₹0','status')],actionLabel:'Open My Library',effect:['Student sees the same issued-loan record.']},
      {id:'parent-loan',role:'parent',moduleKeyword:'Library Information',screen:'Parent · Library Information',title:'Parent sees the child library status',task:'Read-only linked-child view.',interaction:'view',autoFields:[F('Child','{student}','read'),F('Book','Young Scientist · Vol. 2','read'),F('Due','18 Sep 2026','read'),F('Fine','₹0','status')],actionLabel:'View Library Status',effect:['Parent visibility reuses the same Student loan record.']}
    ]
  },
  {
    id:'staff-master',number:23,title:'Staff Master → Staff Login → Academic Duty Scope',short:'Staff & Accounts',category:'Academic Setup & Staffing',tier:'guided',importance:'standard',
    description:'Staff identity, login account and academic assignment remain separate governed records; deleting a login never deletes Staff Master.',
    steps:[
      {id:'staff',role:'headmaster',moduleKeyword:'Staff Master',screen:'Staff Master · Add Staff',title:'Create the Staff Master identity',task:'Actual Staff Master uses text, dropdown and date controls.',interaction:'form',autoFields:[F('Full Name','{teacher2}','text'),F('Designation','Teacher','select'),F('Employee ID','EMP-2048','text'),F('Mobile','{mobile}','text'),F('Qualification','B.Ed.','select'),F('Joining Date','2026-06-15','date')],actionLabel:'Save to Cloud',effect:['Permanent Staff Master identity becomes available to account and duty workflows.']},
      {id:'account',role:'headmaster',moduleKeyword:'Staff Accounts & Access',screen:'Staff Accounts & Access · Create New Staff Login',title:'Create the staff login',task:'Role is a dropdown; credentials use real text/password fields.',interaction:'form',autoFields:[F('Staff Name','{teacher2}','text'),F('Username','teacher.demo','text'),F('Role','Teacher','select'),F('Designation','Teacher','text'),F('Phone','{mobile}','text'),F('Password','••••••••','password'),F('Confirm Password','••••••••','password')],actionLabel:'Create Staff Login',effect:['Login account links to the existing Staff Master identity.','Academic duty permissions are still separate.']},
      {id:'assignment',role:'headmaster',moduleKeyword:'Teacher & Academic Assignments',screen:'Teacher & Academic Assignments',title:'Assign the Teacher academic scope',task:'Canonical dropdown assignment step.',interaction:'selection',autoFields:[F('Teacher','{teacher2}','select'),F('Class','8','select'),F('Division','A','select'),F('Subject','{secondarySubject}','select')],actionLabel:'Save Teaching Assignment',effect:['Teacher account receives only the assigned academic scope.']},
      {id:'teacher-view',role:'teacher',moduleKeyword:'Dashboard',screen:'Teacher Dashboard',title:'See the governed access result',task:'Read-only Teacher view.',interaction:'view',autoFields:[F('Teacher','{teacher2}','read'),F('Assigned Class','{class}','read'),F('Assigned Subject','{secondarySubject}','read'),F('Account','Active','status')],actionLabel:'Open Teacher Dashboard',effect:['One person has one Staff identity, linked login and separately governed academic duties.']}
    ]
  },
  {
    id:'payroll-hr',number:24,title:'Payroll Run → Review → Approve → Mark Paid',short:'Payroll & HR',category:'Platform & Documents',tier:'guided',importance:'standard',
    description:'Headmaster Payroll & HRMS workflow is represented as a safe back-office process; public demo never creates a bank transaction.',
    steps:[
      {id:'create',role:'headmaster',moduleKeyword:'Payroll & HRMS',screen:'Payroll & HRMS · Payroll Processing',title:'Create the monthly payroll run',task:'Month uses the production month control; run creation is the user action.',interaction:'selection',autoFields:[F('Payroll Month','2026-09','select'),F('Active Staff','42','status'),F('Salary Profiles','Configured','status')],actionLabel:'Create Payroll Run',effect:['A demo payroll run is calculated from Staff salary profiles and available attendance/HR inputs.']},
      {id:'review',role:'headmaster',moduleKeyword:'Payroll & HRMS',screen:'Payroll & HRMS · Payroll Run Review',title:'Review the calculated payroll',task:'Computed amounts are review-only.',interaction:'review',autoFields:[F('Staff','{teacher}','read'),F('Attendance Days','24','status'),F('Gross','₹42,000','read'),F('Deductions','₹2,400','read'),F('Net','₹39,600','status')],actionLabel:'Approve Payroll Run',effect:['Payroll moves to Approved state in the demo.']},
      {id:'paid',role:'headmaster',moduleKeyword:'Payroll & HRMS',screen:'Payroll & HRMS · Approved Run',title:'Mark the approved run paid',task:'No bank details are entered in public demo; this is a status action only.',interaction:'review',autoFields:[F('Run Status','Approved','status'),F('Net Payroll','₹16,24,500','read'),F('Bank Instruction','Not created in demo','status')],actionLabel:'Mark Paid',effect:['Demo payroll enters Paid status.','No financial transaction or bank instruction is created.']}
    ]
  },
  {
    id:'inventory-registers',number:25,title:'Asset Entry → Generated Register → Write-off Approval → Audit Trail',short:'Office Operations',category:'Platform & Documents',tier:'guided',importance:'standard',
    description:'Corrects the old Clerk asset-entry shortcut: Inventory & Assets is the operational owner; Clerk Statutory Register is generated support, not duplicate inventory entry.',
    steps:[
      {id:'asset',role:'headmaster',moduleKeyword:'Inventory & Assets',screen:'Inventory & Assets · Add Asset',title:'Create an asset in the owner module',task:'Actual owner form uses text, number and condition dropdown controls.',interaction:'form',autoFields:[F('Asset Code','AST-2026-044','text'),F('Asset Name','Science Lab Microscope','text'),F('Category','Science Lab','text'),F('Location','Science Lab','text'),F('Quantity','4','number'),F('Condition','Good','select'),F('Supplier','Demo Scientific Stores','text')],actionLabel:'Add Asset',effect:['Asset is created in the operational Inventory & Assets workspace.']},
      {id:'register',role:'clerk',moduleKeyword:'Statutory Registers',screen:'Statutory Registers · Inventory Register',title:'See the generated office register',task:'Clerk register is read-only support generated from the owner record.',interaction:'view',autoFields:[F('Asset Code','AST-2026-044','read'),F('Item','Science Lab Microscope','read'),F('Quantity','4','status'),F('Condition','Good','status'),F('Source','Inventory & Assets','read')],actionLabel:'Open Inventory Register',effect:['No duplicate asset is created in the register.']},
      {id:'writeoff',role:'headmaster',moduleKeyword:'Inventory & Assets',screen:'Inventory & Assets · Write-off / Disposal',title:'Create a controlled write-off request',task:'Asset is selected; quantity is numeric; reason is typed.',interaction:'form',autoFields:[F('Asset','AST-2026-044 · Science Lab Microscope','select'),F('Quantity','1','number'),F('Reason','Damaged beyond economical repair.','textarea')],actionLabel:'Create Write-off Request',effect:['A controlled request is created; asset quantity is not silently removed.']},
      {id:'approval',role:'headmaster',moduleKeyword:'Inventory & Assets',screen:'Inventory & Assets · Write-off Approval',title:'Review the controlled disposal action',task:'Approval screen contains no fake data entry.',interaction:'review',autoFields:[F('Asset','AST-2026-044','read'),F('Requested Quantity','1','read'),F('Reason','Damaged beyond economical repair.','read'),F('Audit Trail','Enabled','status')],actionLabel:'Approve Demo Write-off',effect:['Demo records the approval and preserves an audit trail.','Academic records are unaffected.']}
    ]
  }

];

export const PROCESS_CATEGORIES:Array<ProcessCategory>=['Admissions & Student Journey','Academic Setup & Staffing','Daily School Operations','Teaching & AI','Exams & Results','Communication & School Services','Platform & Documents'];
