export type DemoGuidanceMode='form'|'selection'|'review'|'view';

type Copy={
  readyBadge:string;
  readyTitle:string;
  startProcess:string;
  waiting:string;
  readyDecision:string;
  paused:string;
  pause:string;
  resume:string;
  yourAction:string;
  actionHelp:string;
  whatHappened:string;
  fieldPending:string;
  selectPending:string;
  checkPending:string;
  formInstruction:string;
  selectionInstruction:string;
  reviewInstruction:string;
  viewInstruction:string;
  formProgress:string;
  selectionProgress:string;
  reviewProgress:string;
  viewProgress:string;
  formPanel:string;
  selectionPanel:string;
  reviewPanel:string;
  viewPanel:string;
  automatedForm:string;
  automatedSelection:string;
  automatedReview:string;
  automatedView:string;
};

const EN:Copy={
  readyBadge:'Ready when you are',
  readyTitle:'Review this page first, then start the process.',
  startProcess:'Start Process',
  waiting:'Waiting for Start Process',
  readyDecision:'Ready for your decision',
  paused:'Paused', pause:'Pause', resume:'Resume',
  yourAction:'Your action',
  actionHelp:'The demo prepares repetitive work. You make the important workflow decision.',
  whatHappened:'What just happened',
  fieldPending:'Will be entered after Start Process',
  selectPending:'Will be selected after Start Process',
  checkPending:'Will be checked after Start Process',
  formInstruction:'This screen contains real data entry. Text fields will be typed naturally; dropdowns and checkboxes will be selected the way they are in the actual workflow.',
  selectionInstruction:'This screen uses selections rather than typing. The demo will choose dropdowns, options and toggles one by one; it will not simulate text entry where none exists.',
  reviewInstruction:'This record has already been submitted. Nothing will be typed. Start the process to review the important information, then make the approval or publication decision yourself.',
  viewInstruction:'This is a read-only role view. Nothing will be entered. Start the process to highlight the information already available to this user.',
  formProgress:'Entering sample data', selectionProgress:'Applying selections', reviewProgress:'Reviewing submitted record', viewProgress:'Walking through this view',
  formPanel:'Guided data entry', selectionPanel:'Guided selections', reviewPanel:'Review checklist', viewPanel:'Read-only walkthrough',
  automatedForm:'Natural typing only in text inputs; dropdowns and checks use their real control behavior.',
  automatedSelection:'Dropdowns, choices and toggles are applied without fake typing.',
  automatedReview:'Submitted data stays visible; the demo only guides the review sequence.',
  automatedView:'Existing role data stays read-only and is highlighted for explanation.'
};

const copies:Record<string,Partial<Copy>>={
  hi:{readyBadge:'जब आप तैयार हों',readyTitle:'पहले इस पेज को देखें, फिर प्रक्रिया शुरू करें।',startProcess:'प्रक्रिया शुरू करें',waiting:'प्रक्रिया शुरू होने की प्रतीक्षा',readyDecision:'आपके निर्णय के लिए तैयार',paused:'रुका हुआ',pause:'रोकें',resume:'जारी रखें',yourAction:'आपकी कार्रवाई',actionHelp:'दोहराव वाला काम डेमो तैयार करेगा। महत्वपूर्ण निर्णय आप स्वयं करेंगे।',whatHappened:'अभी क्या हुआ',fieldPending:'प्रक्रिया शुरू होने के बाद दर्ज होगा',selectPending:'प्रक्रिया शुरू होने के बाद चुना जाएगा',checkPending:'प्रक्रिया शुरू होने के बाद टिक होगा',formInstruction:'इस स्क्रीन पर वास्तविक डेटा एंट्री है। केवल टेक्स्ट फ़ील्ड स्वाभाविक गति से टाइप होंगे; ड्रॉपडाउन और चेकबॉक्स वास्तविक तरीके से चुने जाएंगे।',selectionInstruction:'इस स्क्रीन पर टाइपिंग के बजाय चयन होते हैं। डेमो ड्रॉपडाउन, विकल्प और टॉगल एक-एक करके चुनेगा; जहाँ टाइपिंग नहीं है वहाँ नकली टाइपिंग नहीं होगी।',reviewInstruction:'यह रिकॉर्ड पहले ही जमा हो चुका है। यहाँ कुछ टाइप नहीं होगा। प्रक्रिया शुरू करके महत्वपूर्ण जानकारी की समीक्षा करें और मंजूरी/प्रकाशन का निर्णय स्वयं लें।',viewInstruction:'यह केवल देखने वाला रोल व्यू है। यहाँ कोई डेटा दर्ज नहीं होगा। प्रक्रिया शुरू करने पर उपलब्ध जानकारी क्रम से हाइलाइट होगी।',formProgress:'नमूना डेटा दर्ज हो रहा है',selectionProgress:'चयन लागू हो रहे हैं',reviewProgress:'जमा रिकॉर्ड की समीक्षा',viewProgress:'व्यू का मार्गदर्शित अवलोकन',formPanel:'मार्गदर्शित डेटा एंट्री',selectionPanel:'मार्गदर्शित चयन',reviewPanel:'समीक्षा सूची',viewPanel:'रीड-ओनली अवलोकन',automatedForm:'सिर्फ टेक्स्ट इनपुट में स्वाभाविक टाइपिंग; ड्रॉपडाउन और चेक वास्तविक कंट्रोल की तरह काम करेंगे।',automatedSelection:'ड्रॉपडाउन, विकल्प और टॉगल बिना नकली टाइपिंग के चुने जाएंगे।',automatedReview:'जमा डेटा पहले से दिखाई देगा; डेमो केवल समीक्षा क्रम दिखाएगा।',automatedView:'मौजूदा रोल डेटा रीड-ओनली रहेगा और समझाने के लिए हाइलाइट होगा।'},
  mr:{readyBadge:'तुम्ही तयार असाल तेव्हा',readyTitle:'आधी हे पान नीट पाहा, नंतर प्रक्रिया सुरू करा.',startProcess:'प्रक्रिया सुरू करा',waiting:'प्रक्रिया सुरू होण्याची प्रतीक्षा',readyDecision:'तुमच्या निर्णयासाठी तयार',paused:'थांबवले',pause:'थांबवा',resume:'पुढे सुरू करा',yourAction:'तुमची कृती',actionHelp:'पुनरावृत्तीचे काम डेमो तयार करेल. महत्त्वाचा निर्णय तुम्ही स्वतः घ्याल.',whatHappened:'आत्ताच काय झाले',fieldPending:'प्रक्रिया सुरू केल्यानंतर भरले जाईल',selectPending:'प्रक्रिया सुरू केल्यानंतर निवडले जाईल',checkPending:'प्रक्रिया सुरू केल्यानंतर टिक केले जाईल',formInstruction:'या स्क्रीनवर प्रत्यक्ष डेटा एंट्री आहे. फक्त मजकूर फील्ड नैसर्गिक गतीने टाइप होतील; ड्रॉपडाउन आणि चेकबॉक्स प्रत्यक्ष कार्यपद्धतीप्रमाणे निवडले जातील.',selectionInstruction:'या स्क्रीनवर टाइपिंगपेक्षा निवडी आहेत. डेमो ड्रॉपडाउन, पर्याय आणि टॉगल एक-एक करून निवडेल; जिथे टाइपिंग नाही तिथे बनावट टाइपिंग होणार नाही.',reviewInstruction:'हा रेकॉर्ड आधीच सबमिट झाला आहे. येथे काहीही टाइप होणार नाही. प्रक्रिया सुरू करून महत्त्वाची माहिती तपासा आणि मंजुरी/प्रकाशनाचा निर्णय स्वतः घ्या.',viewInstruction:'हा फक्त पाहण्यासाठी असलेला रोल व्ह्यू आहे. येथे डेटा एंट्री होणार नाही. प्रक्रिया सुरू केल्यावर उपलब्ध माहिती क्रमाने हायलाइट होईल.',formProgress:'नमुना डेटा भरला जात आहे',selectionProgress:'निवडी लागू होत आहेत',reviewProgress:'सबमिट रेकॉर्ड तपासला जात आहे',viewProgress:'व्ह्यूचे मार्गदर्शित अवलोकन',formPanel:'मार्गदर्शित डेटा एंट्री',selectionPanel:'मार्गदर्शित निवडी',reviewPanel:'तपासणी सूची',viewPanel:'रीड-ओनली अवलोकन',automatedForm:'फक्त टेक्स्ट इनपुटमध्ये नैसर्गिक टाइपिंग; ड्रॉपडाउन आणि चेक प्रत्यक्ष कंट्रोलप्रमाणे चालतील.',automatedSelection:'ड्रॉपडाउन, पर्याय आणि टॉगल बनावट टाइपिंगशिवाय निवडले जातील.',automatedReview:'सबमिट डेटा आधीपासून दिसेल; डेमो फक्त तपासणी क्रम दाखवेल.',automatedView:'विद्यमान रोल डेटा रीड-ओनली राहील आणि समजावण्यासाठी हायलाइट केला जाईल.'},
  ur:{readyBadge:'جب آپ تیار ہوں',readyTitle:'پہلے اس صفحے کو اچھی طرح دیکھیں، پھر عمل شروع کریں۔',startProcess:'عمل شروع کریں',waiting:'عمل شروع ہونے کا انتظار',readyDecision:'آپ کے فیصلے کے لیے تیار',paused:'روکا گیا',pause:'روکیں',resume:'جاری رکھیں',yourAction:'آپ کی کارروائی',actionHelp:'بار بار ہونے والا کام ڈیمو تیار کرے گا۔ اہم فیصلہ آپ خود کریں گے۔',whatHappened:'ابھی کیا ہوا',fieldPending:'عمل شروع ہونے کے بعد درج ہوگا',selectPending:'عمل شروع ہونے کے بعد منتخب ہوگا',checkPending:'عمل شروع ہونے کے بعد نشان لگے گا',formInstruction:'اس اسکرین پر حقیقی ڈیٹا انٹری ہے۔ صرف ٹیکسٹ فیلڈ قدرتی رفتار سے ٹائپ ہوں گے؛ ڈراپ ڈاؤن اور چیک باکس اصل طریقۂ کار کے مطابق منتخب ہوں گے۔',selectionInstruction:'اس اسکرین پر ٹائپنگ کے بجائے انتخاب ہوتے ہیں۔ ڈیمو ڈراپ ڈاؤن، آپشن اور ٹوگل ایک ایک کرکے منتخب کرے گا؛ جہاں ٹائپنگ نہیں ہے وہاں فرضی ٹائپنگ نہیں ہوگی۔',reviewInstruction:'یہ ریکارڈ پہلے ہی جمع ہو چکا ہے۔ یہاں کچھ ٹائپ نہیں ہوگا۔ عمل شروع کرکے اہم معلومات کا جائزہ لیں اور منظوری یا اشاعت کا فیصلہ خود کریں۔',viewInstruction:'یہ صرف دیکھنے والا رول ویو ہے۔ یہاں کوئی ڈیٹا درج نہیں ہوگا۔ عمل شروع کرنے پر موجود معلومات ترتیب سے نمایاں ہوں گی۔',formProgress:'نمونہ ڈیٹا درج ہو رہا ہے',selectionProgress:'انتخاب نافذ ہو رہے ہیں',reviewProgress:'جمع شدہ ریکارڈ کا جائزہ',viewProgress:'ویو کا رہنمائی والا جائزہ',formPanel:'رہنمائی والی ڈیٹا انٹری',selectionPanel:'رہنمائی والے انتخاب',reviewPanel:'جائزہ فہرست',viewPanel:'صرف دیکھنے کا جائزہ',automatedForm:'صرف ٹیکسٹ ان پٹ میں قدرتی ٹائپنگ؛ ڈراپ ڈاؤن اور چیک اصل کنٹرول کی طرح کام کریں گے۔',automatedSelection:'ڈراپ ڈاؤن، آپشن اور ٹوگل فرضی ٹائپنگ کے بغیر منتخب ہوں گے۔',automatedReview:'جمع شدہ ڈیٹا پہلے سے نظر آئے گا؛ ڈیمو صرف جائزے کی ترتیب دکھائے گا۔',automatedView:'موجودہ رول ڈیٹا صرف دیکھنے کے لیے رہے گا اور وضاحت کے لیے نمایاں ہوگا۔'},
  gu:{readyBadge:'તમે તૈયાર હો ત્યારે',readyTitle:'પહેલા આ પેજ સારી રીતે જુઓ, પછી પ્રક્રિયા શરૂ કરો.',startProcess:'પ્રક્રિયા શરૂ કરો',waiting:'પ્રક્રિયા શરૂ થવાની રાહ',readyDecision:'તમારા નિર્ણય માટે તૈયાર',paused:'થોભાવેલ',pause:'થોભાવો',resume:'ફરી શરૂ કરો',yourAction:'તમારી કાર્યવાહી',actionHelp:'પુનરાવર્તિત કામ ડેમો તૈયાર કરશે. મહત્વપૂર્ણ નિર્ણય તમે કરશો.',whatHappened:'હમણાં શું થયું',fieldPending:'પ્રક્રિયા શરૂ થયા પછી દાખલ થશે',selectPending:'પ્રક્રિયા શરૂ થયા પછી પસંદ થશે',checkPending:'પ્રક્રિયા શરૂ થયા પછી ચેક થશે',formInstruction:'આ સ્ક્રીન પર વાસ્તવિક ડેટા એન્ટ્રી છે. માત્ર ટેક્સ્ટ ફીલ્ડ સ્વાભાવિક ગતિએ ટાઇપ થશે; ડ્રોપડાઉન અને ચેકબોક્સ વાસ્તવિક વર્કફ્લો પ્રમાણે પસંદ થશે.',selectionInstruction:'આ સ્ક્રીન પર ટાઇપિંગ કરતાં પસંદગીઓ છે. ડેમો ડ્રોપડાઉન, વિકલ્પો અને ટૉગલ એક પછી એક પસંદ કરશે; જ્યાં ટાઇપિંગ નથી ત્યાં નકલી ટાઇપિંગ નહીં થાય.',reviewInstruction:'આ રેકોર્ડ પહેલેથી સબમિટ થયો છે. અહીં કંઈ ટાઇપ નહીં થાય. પ્રક્રિયા શરૂ કરીને માહિતીની સમીક્ષા કરો અને મંજૂરી/પ્રકાશનનો નિર્ણય જાતે લો.',viewInstruction:'આ માત્ર વાંચવા માટેનો રોલ વ્યૂ છે. અહીં ડેટા દાખલ નહીં થાય. પ્રક્રિયા શરૂ કર્યા પછી ઉપલબ્ધ માહિતી હાઇલાઇટ થશે.',formProgress:'નમૂના ડેટા દાખલ થઈ રહ્યા છે',selectionProgress:'પસંદગીઓ લાગુ થઈ રહી છે',reviewProgress:'સબમિટ રેકોર્ડની સમીક્ષા',viewProgress:'વ્યૂનું માર્ગદર્શિત અવલોકન',formPanel:'માર્ગદર્શિત ડેટા એન્ટ્રી',selectionPanel:'માર્ગદર્શિત પસંદગીઓ',reviewPanel:'સમીક્ષા યાદી',viewPanel:'રીડ-ઓનલિ અવલોકન',automatedForm:'માત્ર ટેક્સ્ટ ઇનપુટમાં સ્વાભાવિક ટાઇપિંગ; ડ્રોપડાઉન અને ચેક વાસ્તવિક કન્ટ્રોલની જેમ ચાલશે.',automatedSelection:'ડ્રોપડાઉન, વિકલ્પો અને ટૉગલ નકલી ટાઇપિંગ વિના લાગુ થશે.',automatedReview:'સબમિટ ડેટા પહેલેથી દેખાશે; ડેમો માત્ર સમીક્ષા ક્રમ બતાવશે.',automatedView:'હાલનું રોલ ડેટા રીડ-ઓનલિ રહેશે અને સમજાવવા માટે હાઇલાઇટ થશે.'},
  bn:{readyBadge:'আপনি প্রস্তুত হলে',readyTitle:'আগে এই পৃষ্ঠাটি ভালোভাবে দেখুন, তারপর প্রক্রিয়া শুরু করুন।',startProcess:'প্রক্রিয়া শুরু করুন',waiting:'প্রক্রিয়া শুরুর অপেক্ষায়',readyDecision:'আপনার সিদ্ধান্তের জন্য প্রস্তুত',paused:'বিরতি',pause:'বিরতি দিন',resume:'চালিয়ে যান',yourAction:'আপনার কাজ',actionHelp:'পুনরাবৃত্ত কাজ ডেমো প্রস্তুত করবে। গুরুত্বপূর্ণ সিদ্ধান্ত আপনি নেবেন।',whatHappened:'এইমাত্র কী হলো',fieldPending:'প্রক্রিয়া শুরু হলে লেখা হবে',selectPending:'প্রক্রিয়া শুরু হলে নির্বাচন হবে',checkPending:'প্রক্রিয়া শুরু হলে চেক হবে',formInstruction:'এই স্ক্রিনে বাস্তব ডেটা এন্ট্রি আছে। শুধু টেক্সট ফিল্ড স্বাভাবিক গতিতে টাইপ হবে; ড্রপডাউন ও চেকবক্স বাস্তব ওয়ার্কফ্লোর মতো নির্বাচন হবে।',selectionInstruction:'এই স্ক্রিনে টাইপিংয়ের বদলে নির্বাচন আছে। ডেমো ড্রপডাউন, অপশন ও টগল একে একে বেছে নেবে; যেখানে টাইপিং নেই সেখানে নকল টাইপিং হবে না।',reviewInstruction:'এই রেকর্ড ইতিমধ্যে জমা হয়েছে। এখানে কিছু টাইপ হবে না। প্রক্রিয়া শুরু করে তথ্য পর্যালোচনা করুন এবং অনুমোদন/প্রকাশের সিদ্ধান্ত নিজে নিন।',viewInstruction:'এটি শুধু দেখার রোল ভিউ। এখানে ডেটা এন্ট্রি হবে না। প্রক্রিয়া শুরু করলে বিদ্যমান তথ্য হাইলাইট হবে।',formProgress:'নমুনা ডেটা লেখা হচ্ছে',selectionProgress:'নির্বাচন প্রয়োগ হচ্ছে',reviewProgress:'জমা রেকর্ড পর্যালোচনা',viewProgress:'ভিউয়ের নির্দেশিত পর্যালোচনা',formPanel:'নির্দেশিত ডেটা এন্ট্রি',selectionPanel:'নির্দেশিত নির্বাচন',reviewPanel:'পর্যালোচনা তালিকা',viewPanel:'রিড-অনলি ভিউ',automatedForm:'শুধু টেক্সট ইনপুটে স্বাভাবিক টাইপিং; ড্রপডাউন ও চেক বাস্তব কন্ট্রোলের মতো কাজ করবে।',automatedSelection:'ড্রপডাউন, অপশন ও টগল নকল টাইপিং ছাড়া প্রয়োগ হবে।',automatedReview:'জমা ডেটা আগে থেকেই দেখা যাবে; ডেমো শুধু পর্যালোচনার ক্রম দেখাবে।',automatedView:'রোল ডেটা রিড-অনলি থাকবে এবং ব্যাখ্যার জন্য হাইলাইট হবে।'},
  ta:{readyBadge:'நீங்கள் தயாரானதும்',readyTitle:'முதலில் இந்தப் பக்கத்தைப் பாருங்கள்; பிறகு செயல்முறையைத் தொடங்குங்கள்.',startProcess:'செயல்முறையை தொடங்கு',waiting:'செயல்முறை தொடங்க காத்திருக்கிறது',readyDecision:'உங்கள் முடிவுக்கு தயாராக உள்ளது',paused:'இடைநிறுத்தப்பட்டது',pause:'இடைநிறுத்து',resume:'தொடரவும்',yourAction:'உங்கள் செயல்',actionHelp:'மீண்டும் மீண்டும் செய்யும் பணியை டெமோ தயாரிக்கும். முக்கிய முடிவை நீங்கள் எடுப்பீர்கள்.',whatHappened:'இப்போது என்ன நடந்தது',fieldPending:'செயல்முறை தொடங்கிய பின் உள்ளிடப்படும்',selectPending:'செயல்முறை தொடங்கிய பின் தேர்வு செய்யப்படும்',checkPending:'செயல்முறை தொடங்கிய பின் குறிக்கப்படும்',formInstruction:'இந்த திரையில் உண்மையான தரவு உள்ளீடு உள்ளது. உரை புலங்கள் மட்டும் இயல்பான வேகத்தில் தட்டச்சாகும்; dropdown மற்றும் checkbox-கள் உண்மையான workflow போல தேர்வு செய்யப்படும்.',selectionInstruction:'இந்த திரையில் தட்டச்சை விட தேர்வுகள் உள்ளன. டெமோ dropdown, option, toggle-களை ஒன்றன்பின் ஒன்றாக தேர்வு செய்யும்; தேவையில்லாத இடத்தில் போலி தட்டச்சு இருக்காது.',reviewInstruction:'இந்த பதிவு ஏற்கனவே சமர்ப்பிக்கப்பட்டது. இங்கு எதுவும் தட்டச்சாகாது. செயல்முறையை தொடங்கி தகவலை ஆய்வு செய்து, அங்கீகாரம்/வெளியீட்டு முடிவை நீங்கள் எடுக்கவும்.',viewInstruction:'இது read-only role view. தரவு உள்ளீடு இருக்காது. செயல்முறை தொடங்கியதும் கிடைக்கும் தகவல்கள் வரிசையாக highlight செய்யப்படும்.',formProgress:'மாதிரி தரவு உள்ளிடப்படுகிறது',selectionProgress:'தேர்வுகள் பயன்படுத்தப்படுகின்றன',reviewProgress:'சமர்ப்பித்த பதிவை ஆய்வு செய்கிறது',viewProgress:'வழிகாட்டப்பட்ட பார்வை',formPanel:'வழிகாட்டப்பட்ட தரவு உள்ளீடு',selectionPanel:'வழிகாட்டப்பட்ட தேர்வுகள்',reviewPanel:'ஆய்வு பட்டியல்',viewPanel:'Read-only பார்வை',automatedForm:'உரை input-களில் மட்டும் இயல்பான தட்டச்சு; dropdown/check உண்மையான control போல செயல்படும்.',automatedSelection:'dropdown, option, toggle போலி தட்டச்சில்லாமல் தேர்வு செய்யப்படும்.',automatedReview:'சமர்ப்பித்த தரவு முன்பே தெரியும்; டெமோ ஆய்வு வரிசையை மட்டும் காட்டும்.',automatedView:'தற்போதைய role data read-only ஆக இருந்து விளக்கத்திற்காக highlight செய்யப்படும்.'},
  te:{readyBadge:'మీరు సిద్ధంగా ఉన్నప్పుడు',readyTitle:'ముందుగా ఈ పేజీని చూడండి, తరువాత ప్రక్రియను ప్రారంభించండి.',startProcess:'ప్రక్రియ ప్రారంభించండి',waiting:'ప్రక్రియ ప్రారంభానికి వేచి ఉంది',readyDecision:'మీ నిర్ణయానికి సిద్ధంగా ఉంది',paused:'నిలిపివేశారు',pause:'నిలిపివేయి',resume:'కొనసాగించు',yourAction:'మీ చర్య',actionHelp:'పునరావృత పనిని డెమో సిద్ధం చేస్తుంది. ముఖ్య నిర్ణయం మీరు తీసుకుంటారు.',whatHappened:'ఇప్పుడే ఏమైంది',fieldPending:'ప్రక్రియ ప్రారంభమైన తర్వాత నమోదు అవుతుంది',selectPending:'ప్రక్రియ ప్రారంభమైన తర్వాత ఎంపిక అవుతుంది',checkPending:'ప్రక్రియ ప్రారంభమైన తర్వాత చెక్ అవుతుంది',formInstruction:'ఈ స్క్రీన్‌లో నిజమైన డేటా ఎంట్రీ ఉంది. టెక్స్ట్ ఫీల్డ్‌లు మాత్రమే సహజ వేగంతో టైప్ అవుతాయి; dropdownలు మరియు checkboxలు నిజమైన workflow ప్రకారం ఎంపిక అవుతాయి.',selectionInstruction:'ఈ స్క్రీన్‌లో టైపింగ్ కంటే ఎంపికలు ఉంటాయి. డెమో dropdownలు, options, toggles ను ఒక్కొక్కటిగా ఎంచుతుంది; అవసరం లేని చోట నకిలీ టైపింగ్ ఉండదు.',reviewInstruction:'ఈ రికార్డు ఇప్పటికే సమర్పించబడింది. ఇక్కడ ఏమీ టైప్ కాదు. ప్రక్రియ ప్రారంభించి సమాచారాన్ని సమీక్షించి, ఆమోదం/ప్రచురణ నిర్ణయం మీరు తీసుకోండి.',viewInstruction:'ఇది read-only role view. డేటా ఎంట్రీ ఉండదు. ప్రక్రియ ప్రారంభించిన తర్వాత ఇప్పటికే ఉన్న సమాచారం highlight అవుతుంది.',formProgress:'నమూనా డేటా నమోదు అవుతోంది',selectionProgress:'ఎంపికలు అమలవుతున్నాయి',reviewProgress:'సమర్పించిన రికార్డు సమీక్ష',viewProgress:'మార్గదర్శిత వీక్షణ',formPanel:'మార్గదర్శిత డేటా ఎంట్రీ',selectionPanel:'మార్గదర్శిత ఎంపికలు',reviewPanel:'సమీక్ష జాబితా',viewPanel:'Read-only వీక్షణ',automatedForm:'టెక్స్ట్ inputల్లో మాత్రమే సహజ టైపింగ్; dropdown/check నిజమైన controlలా పనిచేస్తాయి.',automatedSelection:'dropdownలు, options, toggles నకిలీ టైపింగ్ లేకుండా ఎంపిక అవుతాయి.',automatedReview:'సమర్పించిన డేటా ముందే కనిపిస్తుంది; డెమో సమీక్ష క్రమాన్ని మాత్రమే చూపుతుంది.',automatedView:'ప్రస్తుత role data read-onlyగా ఉండి వివరణ కోసం highlight అవుతుంది.'},
  kn:{readyBadge:'ನೀವು ಸಿದ್ಧರಾದಾಗ',readyTitle:'ಮೊದಲು ಈ ಪುಟವನ್ನು ನೋಡಿ, ನಂತರ ಪ್ರಕ್ರಿಯೆಯನ್ನು ಪ್ರಾರಂಭಿಸಿ.',startProcess:'ಪ್ರಕ್ರಿಯೆ ಪ್ರಾರಂಭಿಸಿ',waiting:'ಪ್ರಕ್ರಿಯೆ ಪ್ರಾರಂಭಕ್ಕಾಗಿ ಕಾಯುತ್ತಿದೆ',readyDecision:'ನಿಮ್ಮ ನಿರ್ಧಾರಕ್ಕೆ ಸಿದ್ಧ',paused:'ವಿರಾಮ',pause:'ವಿರಾಮ',resume:'ಮುಂದುವರಿಸಿ',yourAction:'ನಿಮ್ಮ ಕ್ರಮ',actionHelp:'ಪುನರಾವರ್ತಿತ ಕೆಲಸವನ್ನು ಡೆಮೋ ಸಿದ್ಧಪಡಿಸುತ್ತದೆ. ಮುಖ್ಯ ನಿರ್ಧಾರವನ್ನು ನೀವು ತೆಗೆದುಕೊಳ್ಳುತ್ತೀರಿ.',whatHappened:'ಈಗ ಏನಾಯಿತು',fieldPending:'ಪ್ರಕ್ರಿಯೆ ಆರಂಭವಾದ ನಂತರ ನಮೂದಿಸಲಾಗುತ್ತದೆ',selectPending:'ಪ್ರಕ್ರಿಯೆ ಆರಂಭವಾದ ನಂತರ ಆಯ್ಕೆ ಮಾಡಲಾಗುತ್ತದೆ',checkPending:'ಪ್ರಕ್ರಿಯೆ ಆರಂಭವಾದ ನಂತರ ಚೆಕ್ ಆಗುತ್ತದೆ',formInstruction:'ಈ ಪರದೆಯಲ್ಲಿ ನೈಜ ಡೇಟಾ ಎಂಟ್ರಿ ಇದೆ. ಪಠ್ಯ ಕ್ಷೇತ್ರಗಳು ಮಾತ್ರ ಸಹಜ ವೇಗದಲ್ಲಿ ಟೈಪ್ ಆಗುತ್ತವೆ; dropdown ಮತ್ತು checkbox ಗಳು ನೈಜ workflow ಪ್ರಕಾರ ಆಯ್ಕೆಯಾಗುತ್ತವೆ.',selectionInstruction:'ಈ ಪರದೆಯಲ್ಲಿ ಟೈಪಿಂಗ್‌ಗಿಂತ ಆಯ್ಕೆಗಳು ಇವೆ. ಡೆಮೋ dropdown, option ಮತ್ತು toggle ಗಳನ್ನು ಒಂದೊಂದಾಗಿ ಆಯ್ಕೆ ಮಾಡುತ್ತದೆ; ಅಗತ್ಯವಿಲ್ಲದ ಕಡೆ ನಕಲಿ ಟೈಪಿಂಗ್ ಇರುವುದಿಲ್ಲ.',reviewInstruction:'ಈ ದಾಖಲೆ ಈಗಾಗಲೇ ಸಲ್ಲಿಸಲಾಗಿದೆ. ಇಲ್ಲಿ ಏನೂ ಟೈಪ್ ಆಗುವುದಿಲ್ಲ. ಪ್ರಕ್ರಿಯೆ ಆರಂಭಿಸಿ ಮಾಹಿತಿಯನ್ನು ಪರಿಶೀಲಿಸಿ, ಅನುಮೋದನೆ/ಪ್ರಕಟಣೆ ನಿರ್ಧಾರವನ್ನು ನೀವು ತೆಗೆದುಕೊಳ್ಳಿ.',viewInstruction:'ಇದು read-only role view. ಡೇಟಾ ಎಂಟ್ರಿ ಇರುವುದಿಲ್ಲ. ಪ್ರಕ್ರಿಯೆ ಆರಂಭಿಸಿದ ನಂತರ ಇರುವ ಮಾಹಿತಿಯನ್ನು highlight ಮಾಡಲಾಗುತ್ತದೆ.',formProgress:'ಮಾದರಿ ಡೇಟಾ ನಮೂದಿಸಲಾಗುತ್ತಿದೆ',selectionProgress:'ಆಯ್ಕೆಗಳು ಅನ್ವಯವಾಗುತ್ತಿವೆ',reviewProgress:'ಸಲ್ಲಿಸಿದ ದಾಖಲೆಯ ಪರಿಶೀಲನೆ',viewProgress:'ಮಾರ್ಗದರ್ಶಿತ ವೀಕ್ಷಣೆ',formPanel:'ಮಾರ್ಗದರ್ಶಿತ ಡೇಟಾ ಎಂಟ್ರಿ',selectionPanel:'ಮಾರ್ಗದರ್ಶಿತ ಆಯ್ಕೆಗಳು',reviewPanel:'ಪರಿಶೀಲನಾ ಪಟ್ಟಿ',viewPanel:'Read-only ವೀಕ್ಷಣೆ',automatedForm:'ಪಠ್ಯ inputಗಳಲ್ಲಿ ಮಾತ್ರ ಸಹಜ ಟೈಪಿಂಗ್; dropdown/check ನೈಜ control ರೀತಿ ಕೆಲಸ ಮಾಡುತ್ತವೆ.',automatedSelection:'dropdown, option ಮತ್ತು toggle ನಕಲಿ ಟೈಪಿಂಗ್ ಇಲ್ಲದೆ ಆಯ್ಕೆಯಾಗುತ್ತವೆ.',automatedReview:'ಸಲ್ಲಿಸಿದ ಡೇಟಾ ಮೊದಲೇ ಗೋಚರಿಸುತ್ತದೆ; ಡೆಮೋ ಪರಿಶೀಲನಾ ಕ್ರಮವನ್ನಷ್ಟೇ ತೋರಿಸುತ್ತದೆ.',automatedView:'ಇರುವ role data read-only ಆಗಿದ್ದು ವಿವರಣೆಗೆ highlight ಆಗುತ್ತದೆ.'},
  ml:{readyBadge:'നിങ്ങൾ തയ്യാറാകുമ്പോൾ',readyTitle:'ആദ്യം ഈ പേജ് നോക്കുക, ശേഷം പ്രക്രിയ ആരംഭിക്കുക.',startProcess:'പ്രക്രിയ ആരംഭിക്കുക',waiting:'പ്രക്രിയ ആരംഭിക്കാൻ കാത്തിരിക്കുന്നു',readyDecision:'നിങ്ങളുടെ തീരുമാനത്തിന് തയ്യാറാണ്',paused:'താൽക്കാലികമായി നിർത്തി',pause:'നിർത്തുക',resume:'തുടരുക',yourAction:'നിങ്ങളുടെ നടപടി',actionHelp:'ആവർത്തിക്കുന്ന ജോലി ഡെമോ തയ്യാറാക്കും. പ്രധാന തീരുമാനം നിങ്ങൾ എടുക്കും.',whatHappened:'ഇപ്പോൾ എന്ത് സംഭവിച്ചു',fieldPending:'പ്രക്രിയ ആരംഭിച്ച ശേഷം നൽകും',selectPending:'പ്രക്രിയ ആരംഭിച്ച ശേഷം തിരഞ്ഞെടുക്കും',checkPending:'പ്രക്രിയ ആരംഭിച്ച ശേഷം ചെക്ക് ചെയ്യും',formInstruction:'ഈ സ്ക്രീനിൽ യഥാർത്ഥ ഡാറ്റ എൻട്രിയുണ്ട്. ടെക്സ്റ്റ് ഫീൽഡുകൾ മാത്രം സ്വാഭാവിക വേഗത്തിൽ ടൈപ്പ് ചെയ്യും; dropdown-കളും checkbox-കളും യഥാർത്ഥ workflow പോലെ തിരഞ്ഞെടുക്കും.',selectionInstruction:'ഈ സ്ക്രീനിൽ ടൈപ്പിംഗിനേക്കാൾ തിരഞ്ഞെടുപ്പുകളാണ്. ഡെമോ dropdown, option, toggle എന്നിവ ഒന്നൊന്നായി തിരഞ്ഞെടുക്കും; ആവശ്യമില്ലാത്തിടത്ത് വ്യാജ ടൈപ്പിംഗ് ഉണ്ടാകില്ല.',reviewInstruction:'ഈ റെക്കോർഡ് ഇതിനകം സമർപ്പിച്ചിട്ടുണ്ട്. ഇവിടെ ഒന്നും ടൈപ്പ് ചെയ്യില്ല. പ്രക്രിയ ആരംഭിച്ച് വിവരങ്ങൾ പരിശോധിച്ച് അംഗീകാരം/പ്രസിദ്ധീകരണം നിങ്ങൾ തീരുമാനിക്കുക.',viewInstruction:'ഇത് read-only role view ആണ്. ഡാറ്റ എൻട്രിയില്ല. പ്രക്രിയ ആരംഭിച്ചാൽ നിലവിലുള്ള വിവരങ്ങൾ highlight ചെയ്യും.',formProgress:'സാമ്പിൾ ഡാറ്റ നൽകുന്നു',selectionProgress:'തിരഞ്ഞെടുപ്പുകൾ പ്രയോഗിക്കുന്നു',reviewProgress:'സമർപ്പിച്ച റെക്കോർഡ് പരിശോധിക്കുന്നു',viewProgress:'മാർഗനിർദ്ദേശത്തോടെ കാണുന്നു',formPanel:'മാർഗനിർദ്ദേശ ഡാറ്റ എൻട്രി',selectionPanel:'മാർഗനിർദ്ദേശ തിരഞ്ഞെടുപ്പുകൾ',reviewPanel:'പരിശോധന പട്ടിക',viewPanel:'Read-only കാഴ്ച',automatedForm:'ടെക്സ്റ്റ് input-കളിൽ മാത്രം സ്വാഭാവിക ടൈപ്പിംഗ്; dropdown/check യഥാർത്ഥ control പോലെ പ്രവർത്തിക്കും.',automatedSelection:'dropdown, option, toggle വ്യാജ ടൈപ്പിംഗ് ഇല്ലാതെ തിരഞ്ഞെടുക്കും.',automatedReview:'സമർപ്പിച്ച ഡാറ്റ മുൻകൂട്ടി കാണും; ഡെമോ പരിശോധിക്കൽ ക്രമം മാത്രം കാണിക്കും.',automatedView:'നിലവിലെ role data read-only ആയി തുടരും, വിശദീകരണത്തിന് highlight ചെയ്യും.'},
  pa:{readyBadge:'ਜਦੋਂ ਤੁਸੀਂ ਤਿਆਰ ਹੋ',readyTitle:'ਪਹਿਲਾਂ ਇਹ ਪੇਜ ਵੇਖੋ, ਫਿਰ ਪ੍ਰਕਿਰਿਆ ਸ਼ੁਰੂ ਕਰੋ।',startProcess:'ਪ੍ਰਕਿਰਿਆ ਸ਼ੁਰੂ ਕਰੋ',waiting:'ਪ੍ਰਕਿਰਿਆ ਸ਼ੁਰੂ ਹੋਣ ਦੀ ਉਡੀਕ',readyDecision:'ਤੁਹਾਡੇ ਫੈਸਲੇ ਲਈ ਤਿਆਰ',paused:'ਰੋਕਿਆ ਗਿਆ',pause:'ਰੋਕੋ',resume:'ਜਾਰੀ ਰੱਖੋ',yourAction:'ਤੁਹਾਡੀ ਕਾਰਵਾਈ',actionHelp:'ਦੁਹਰਾਇਆ ਜਾਣ ਵਾਲਾ ਕੰਮ ਡੈਮੋ ਤਿਆਰ ਕਰੇਗਾ। ਮਹੱਤਵਪੂਰਨ ਫੈਸਲਾ ਤੁਸੀਂ ਕਰੋਗੇ।',whatHappened:'ਹੁਣ ਕੀ ਹੋਇਆ',fieldPending:'ਪ੍ਰਕਿਰਿਆ ਸ਼ੁਰੂ ਹੋਣ ਤੋਂ ਬਾਅਦ ਭਰਿਆ ਜਾਵੇਗਾ',selectPending:'ਪ੍ਰਕਿਰਿਆ ਸ਼ੁਰੂ ਹੋਣ ਤੋਂ ਬਾਅਦ ਚੁਣਿਆ ਜਾਵੇਗਾ',checkPending:'ਪ੍ਰਕਿਰਿਆ ਸ਼ੁਰੂ ਹੋਣ ਤੋਂ ਬਾਅਦ ਚੈਕ ਹੋਵੇਗਾ',formInstruction:'ਇਸ ਸਕ੍ਰੀਨ ਉੱਤੇ ਅਸਲੀ ਡਾਟਾ ਐਂਟਰੀ ਹੈ। ਸਿਰਫ਼ ਟੈਕਸਟ ਫੀਲਡ ਕੁਦਰਤੀ ਗਤੀ ਨਾਲ ਟਾਈਪ ਹੋਣਗੇ; dropdown ਅਤੇ checkbox ਅਸਲੀ workflow ਵਾਂਗ ਚੁਣੇ ਜਾਣਗੇ।',selectionInstruction:'ਇਸ ਸਕ੍ਰੀਨ ਉੱਤੇ ਟਾਈਪਿੰਗ ਦੀ ਬਜਾਏ ਚੋਣਾਂ ਹਨ। ਡੈਮੋ dropdown, option ਅਤੇ toggle ਇੱਕ-ਇੱਕ ਕਰਕੇ ਚੁਣੇਗਾ; ਜਿੱਥੇ ਟਾਈਪਿੰਗ ਨਹੀਂ ਹੈ ਉੱਥੇ ਨਕਲੀ ਟਾਈਪਿੰਗ ਨਹੀਂ ਹੋਵੇਗੀ।',reviewInstruction:'ਇਹ ਰਿਕਾਰਡ ਪਹਿਲਾਂ ਹੀ ਜਮ੍ਹਾਂ ਹੋ ਚੁੱਕਾ ਹੈ। ਇੱਥੇ ਕੁਝ ਟਾਈਪ ਨਹੀਂ ਹੋਵੇਗਾ। ਪ੍ਰਕਿਰਿਆ ਸ਼ੁਰੂ ਕਰਕੇ ਜਾਣਕਾਰੀ ਦੀ ਸਮੀਖਿਆ ਕਰੋ ਅਤੇ ਮਨਜ਼ੂਰੀ/ਪ੍ਰਕਾਸ਼ਨ ਦਾ ਫੈਸਲਾ ਤੁਸੀਂ ਕਰੋ।',viewInstruction:'ਇਹ read-only role view ਹੈ। ਡਾਟਾ ਐਂਟਰੀ ਨਹੀਂ ਹੋਵੇਗੀ। ਪ੍ਰਕਿਰਿਆ ਸ਼ੁਰੂ ਕਰਨ ਤੋਂ ਬਾਅਦ ਮੌਜੂਦਾ ਜਾਣਕਾਰੀ highlight ਹੋਵੇਗੀ।',formProgress:'ਨਮੂਨਾ ਡਾਟਾ ਭਰਿਆ ਜਾ ਰਿਹਾ ਹੈ',selectionProgress:'ਚੋਣਾਂ ਲਾਗੂ ਹੋ ਰਹੀਆਂ ਹਨ',reviewProgress:'ਜਮ੍ਹਾਂ ਰਿਕਾਰਡ ਦੀ ਸਮੀਖਿਆ',viewProgress:'ਮਾਰਗਦਰਸ਼ਿਤ ਦ੍ਰਿਸ਼',formPanel:'ਮਾਰਗਦਰਸ਼ਿਤ ਡਾਟਾ ਐਂਟਰੀ',selectionPanel:'ਮਾਰਗਦਰਸ਼ਿਤ ਚੋਣਾਂ',reviewPanel:'ਸਮੀਖਿਆ ਸੂਚੀ',viewPanel:'Read-only ਦ੍ਰਿਸ਼',automatedForm:'ਸਿਰਫ਼ ਟੈਕਸਟ input ਵਿੱਚ ਕੁਦਰਤੀ ਟਾਈਪਿੰਗ; dropdown/check ਅਸਲੀ control ਵਾਂਗ ਚੱਲਣਗੇ।',automatedSelection:'dropdown, option ਅਤੇ toggle ਨਕਲੀ ਟਾਈਪਿੰਗ ਤੋਂ ਬਿਨਾਂ ਚੁਣੇ ਜਾਣਗੇ।',automatedReview:'ਜਮ੍ਹਾਂ ਡਾਟਾ ਪਹਿਲਾਂ ਹੀ ਦਿਖੇਗਾ; ਡੈਮੋ ਸਿਰਫ਼ ਸਮੀਖਿਆ ਕ੍ਰਮ ਦਿਖਾਵੇਗਾ।',automatedView:'ਮੌਜੂਦਾ role data read-only ਰਹੇਗਾ ਅਤੇ ਸਮਝਾਉਣ ਲਈ highlight ਹੋਵੇਗਾ.'},
  or:{readyBadge:'ଆପଣ ପ୍ରସ୍ତୁତ ହେଲେ',readyTitle:'ପ୍ରଥମେ ଏହି ପୃଷ୍ଠାକୁ ଦେଖନ୍ତୁ, ପରେ ପ୍ରକ୍ରିୟା ଆରମ୍ଭ କରନ୍ତୁ।',startProcess:'ପ୍ରକ୍ରିୟା ଆରମ୍ଭ କରନ୍ତୁ',waiting:'ପ୍ରକ୍ରିୟା ଆରମ୍ଭ ପାଇଁ ଅପେକ୍ଷା',readyDecision:'ଆପଣଙ୍କ ନିଷ୍ପତ୍ତି ପାଇଁ ପ୍ରସ୍ତୁତ',paused:'ବିରତ',pause:'ବିରତ କରନ୍ତୁ',resume:'ଜାରି ରଖନ୍ତୁ',yourAction:'ଆପଣଙ୍କ କାର୍ଯ୍ୟ',actionHelp:'ପୁନରାବୃତ୍ତ କାମ ଡେମୋ ପ୍ରସ୍ତୁତ କରିବ। ମୁଖ୍ୟ ନିଷ୍ପତ୍ତି ଆପଣ ନେବେ।',whatHappened:'ଏମାତ୍ର କଣ ହେଲା',fieldPending:'ପ୍ରକ୍ରିୟା ଆରମ୍ଭ ପରେ ଲେଖାଯିବ',selectPending:'ପ୍ରକ୍ରିୟା ଆରମ୍ଭ ପରେ ଚୟନ ହେବ',checkPending:'ପ୍ରକ୍ରିୟା ଆରମ୍ଭ ପରେ ଚେକ୍ ହେବ',formInstruction:'ଏହି ସ୍କ୍ରିନରେ ପ୍ରକୃତ ଡାଟା ଏଣ୍ଟ୍ରି ଅଛି। କେବଳ ଟେକ୍ସ୍ଟ ଫିଲ୍ଡ ସ୍ୱାଭାବିକ ଗତିରେ ଟାଇପ ହେବ; dropdown ଓ checkbox ପ୍ରକୃତ workflow ଅନୁଯାୟୀ ଚୟନ ହେବ।',selectionInstruction:'ଏହି ସ୍କ୍ରିନରେ ଟାଇପିଂ ଠାରୁ ଚୟନ ଅଧିକ। ଡେମୋ dropdown, option ଓ toggle କୁ ଏକେକରେ ବାଛିବ; ଯେଉଁଠି ଟାଇପିଂ ନାହିଁ ସେଠି ନକଲି ଟାଇପିଂ ହେବ ନାହିଁ।',reviewInstruction:'ଏହି ରେକର୍ଡ ପୂର୍ବରୁ ଦାଖଲ ହୋଇଛି। ଏଠାରେ କିଛି ଟାଇପ ହେବ ନାହିଁ। ପ୍ରକ୍ରିୟା ଆରମ୍ଭ କରି ସୂଚନା ସମୀକ୍ଷା କରନ୍ତୁ ଏବଂ ଅନୁମୋଦନ/ପ୍ରକାଶନ ନିଷ୍ପତ୍ତି ନିଜେ ନିଅନ୍ତୁ।',viewInstruction:'ଏହା read-only role view। ଡାଟା ଏଣ୍ଟ୍ରି ନାହିଁ। ପ୍ରକ୍ରିୟା ଆରମ୍ଭ ପରେ ଥିବା ସୂଚନା highlight ହେବ।',formProgress:'ନମୁନା ଡାଟା ଭରାଯାଉଛି',selectionProgress:'ଚୟନ ଲାଗୁ ହେଉଛି',reviewProgress:'ଦାଖଲ ରେକର୍ଡ ସମୀକ୍ଷା',viewProgress:'ମାର୍ଗଦର୍ଶିତ ଦୃଶ୍ୟ',formPanel:'ମାର୍ଗଦର୍ଶିତ ଡାଟା ଏଣ୍ଟ୍ରି',selectionPanel:'ମାର୍ଗଦର୍ଶିତ ଚୟନ',reviewPanel:'ସମୀକ୍ଷା ତାଲିକା',viewPanel:'Read-only ଦୃଶ୍ୟ',automatedForm:'କେବଳ text inputରେ ସ୍ୱାଭାବିକ typing; dropdown/check ପ୍ରକୃତ control ପରି କାମ କରିବ।',automatedSelection:'dropdown, option ଓ toggle ନକଲି typing ବିନା ବାଛାଯିବ।',automatedReview:'ଦାଖଲ ଡାଟା ପୂର୍ବରୁ ଦେଖାଯିବ; ଡେମୋ କେବଳ ସମୀକ୍ଷା କ୍ରମ ଦେଖାଇବ।',automatedView:'ବର୍ତ୍ତମାନ role data read-only ରହିବ ଏବଂ ବ୍ୟାଖ୍ୟା ପାଇଁ highlight ହେବ।'},
  as:{readyBadge:'আপুনি সাজু হ’লে',readyTitle:'আগতে এই পৃষ্ঠাটো ভালদৰে চাওক, তাৰ পিছত প্ৰক্ৰিয়া আৰম্ভ কৰক।',startProcess:'প্ৰক্ৰিয়া আৰম্ভ কৰক',waiting:'প্ৰক্ৰিয়া আৰম্ভ হোৱাৰ অপেক্ষা',readyDecision:'আপোনাৰ সিদ্ধান্তৰ বাবে সাজু',paused:'বিৰতি',pause:'বিৰতি দিয়ক',resume:'অব্যাহত ৰাখক',yourAction:'আপোনাৰ কাৰ্য',actionHelp:'পুনৰাবৃত্ত কাম ডেমোৱে সাজু কৰিব। গুৰুত্বপূর্ণ সিদ্ধান্ত আপুনি ল’ব।',whatHappened:'এতিয়া কি হ’ল',fieldPending:'প্ৰক্ৰিয়া আৰম্ভ হোৱাৰ পিছত লিখা হ’ব',selectPending:'প্ৰক্ৰিয়া আৰম্ভ হোৱাৰ পিছত বাছনি হ’ব',checkPending:'প্ৰক্ৰিয়া আৰম্ভ হোৱাৰ পিছত চেক হ’ব',formInstruction:'এই স্ক্ৰিনত বাস্তৱ ডাটা এণ্ট্ৰী আছে। কেৱল টেক্সট ফিল্ড স্বাভাৱিক গতিৰে টাইপ হ’ব; dropdown আৰু checkbox বাস্তৱ workflow অনুসৰি বাছনি হ’ব।',selectionInstruction:'এই স্ক্ৰিনত টাইপিংতকৈ বাছনি আছে। ডেমোৱে dropdown, option আৰু toggle এটাৰ পিছত এটা বাছি ল’ব; য’ত টাইপিং নাই তাত নকল টাইপিং নাথাকিব।',reviewInstruction:'এই ৰেকৰ্ড ইতিমধ্যে জমা হৈছে। ইয়াত একো টাইপ নহ’ব। প্ৰক্ৰিয়া আৰম্ভ কৰি তথ্যসমূহ পৰ্যালোচনা কৰক আৰু অনুমোদন/প্ৰকাশৰ সিদ্ধান্ত নিজে লওক।',viewInstruction:'এইটো read-only role view। ডাটা এণ্ট্ৰী নাথাকিব। প্ৰক্ৰিয়া আৰম্ভ হোৱাৰ পিছত থকা তথ্য highlight হ’ব।',formProgress:'নমুনা ডাটা ভৰোৱা হৈছে',selectionProgress:'বাছনি প্ৰয়োগ কৰা হৈছে',reviewProgress:'জমা ৰেকৰ্ড পৰ্যালোচনা',viewProgress:'মাৰ্গদৰ্শিত দৃশ্য',formPanel:'মাৰ্গদৰ্শিত ডাটা এণ্ট্ৰী',selectionPanel:'মাৰ্গদৰ্শিত বাছনি',reviewPanel:'পৰ্যালোচনা তালিকা',viewPanel:'Read-only দৃশ্য',automatedForm:'কেৱল text inputত স্বাভাৱিক typing; dropdown/check বাস্তৱ controlৰ দৰে কাম কৰিব।',automatedSelection:'dropdown, option আৰু toggle নকল typing নকৰাকৈ বাছনি হ’ব।',automatedReview:'জমা ডাটা আগতেই দেখা যাব; ডেমোৱে কেৱল পৰ্যালোচনাৰ ক্ৰম দেখুৱাব।',automatedView:'বৰ্তমান role data read-only থাকিব আৰু বুজাবলৈ highlight হ’ব.'}
};


// R2.5.61: complete Scheduled-language picker coverage. These core guidance strings
// keep Start/Review/Decision instructions in the selected language; unspecified micro-copy
// still inherits the English master wording safely.
Object.assign(copies,{
  brx:{readyBadge:'नोंथाङा थियार जानाय समाव',readyTitle:'गिबियाव बे बिलाइखौ नाय, बेनि उनाव प्रक्रियाखौ जागाय।',startProcess:'प्रक्रिया जागाय',waiting:'प्रक्रिया जागायनायखौ नेगासिनो दं',readyDecision:'नोंथांनि थिरांथानि थाखाय थियार',pause:'थांनाय',resume:'फिन जागाय',yourAction:'नोंथांनि हाबा',actionHelp:'फिन फिन खालामनाय हाबाखौ डेमो थियार खालामगोन। गोनांथार थिरांथाखौ नोंथाङा खालामगोन।',whatHappened:'दा मा जाबाय',formInstruction:'बे स्क्रिनाव थार डाटा एन्ट्रि दं। टेक्स्ट फील्डफोरखौल’ सोभाविक स्पिडआव टाइप खालामगोन; ड्रपडाउन आरो चेकबक्सखौ थार वर्कफ्लो बादियै सायखगोन।',selectionInstruction:'बे स्क्रिनाव टाइपिंनि सोलाय सायखनायफोर दं। ड्रपडाउन, अप्सन आरो टगलखौ एखेबारे सायखगोन।',reviewInstruction:'बे रेकर्डखौ सिगाङावनो सबमिट खालामबाय। बेयाव जेबो टाइप नङा; नायबिजिरनायनि उनाव थिरांथा खालाम।',viewInstruction:'बेयो read-only role view। डाटा एन्ट्रि गैया; थानाय फोरमायथिहोग्राखौ हाइलाइट खालामगोन।'},
  doi:{readyBadge:'जदूं तुस तैयार ओ',readyTitle:'पैह्लें एह पन्ना दिक्खो, फेर प्रक्रिया शुरू करो।',startProcess:'प्रक्रिया शुरू करो',waiting:'प्रक्रिया शुरू होने दी उडीक',readyDecision:'तुंदे फैसले आस्तै तैयार',pause:'रोक्को',resume:'जारी रक्खो',yourAction:'तुंदी कार्रवाई',actionHelp:'बार-बार होने आह्ला कम्म डेमो तैयार करग। जरूरी फैसला तुस खुद करोगे।',whatHappened:'हुन केह् होआ',formInstruction:'इस स्क्रीन पर असली डेटा एंट्री ऐ। सिर्फ टेक्स्ट फील्ड स्वाभाविक रफ्तार नाल टाइप होङन; ड्रॉपडाउन ते चेकबॉक्स असली तरीके नाल चुने जाङन।',selectionInstruction:'इस स्क्रीन पर टाइपिंग दी बजाय चयन ने। ड्रॉपडाउन, विकल्प ते टॉगल इक-इक करके चुने जाङन।',reviewInstruction:'एह रिकॉर्ड पैह्लें गै जमा होई चुके दा ऐ। इत्थे किश टाइप नेईं होग; समीक्षा करो ते मंजूरी/प्रकाशन दा फैसला तुस करो।',viewInstruction:'एह read-only रोल व्यू ऐ। डेटा एंट्री नेईं होग; मौजूद जानकारी हाइलाइट होग।'},
  ks:{readyBadge:'تُہۍ ییلہ تیار چھو',readyTitle:'پہلے یہ صفحہ وُچھِو، پتہ عمل شروع کٔرِو۔',startProcess:'عمل شروع کٔرِو',waiting:'عمل شروع گژھنُک انتظار',readyDecision:'تُہندِس فیصلس خٲطرٕ تیار',pause:'رُکٲو',resume:'جاری تھٲو',yourAction:'تُہنز کارروائی',actionHelp:'بار بار کرنہٕ وول کٲم ڈیمو تیار کرِ؛ اہم فیصلہ تُہۍ کٔرِو۔',whatHappened:'وۄنۍ کیاہ گوٚو',formInstruction:'یَتھ سکرینس پیٹھ حقیقی ڈیٹا انٹری چھِ۔ صرف ٹیکسٹ فیلڈ قدرتی رفتارَس سۭتۍ ٹائپ گژھن؛ ڈراپ ڈاؤن تہٕ چیک باکس اصل ورک فلو مطابق منتخب گژھن۔',selectionInstruction:'یَتھ سکرینس پیٹھ ٹائپنگ بدلہٕ انتخاب چھِ۔ ڈراپ ڈاؤن، آپشن تہٕ ٹوگل یکہٕ بعد دیگرے منتخب گژھن۔',reviewInstruction:'یہ ریکارڈ گوڈٕے جمع چھُ۔ یَتھ جاے کینہہ ٹائپ نہٕ گژھِ؛ جائزہ کٔرِتھ منظوری یا اشاعتُک فیصلہ کٔرِو۔',viewInstruction:'یہ read-only رول ویو چھُ۔ کینہہ درج نہٕ گژھِ؛ موجود معلومات نمایاں گژھن۔'},
  kok:{readyBadge:'तुमी तयार आसात तेन्ना',readyTitle:'पयलीं हें पान पळयात, मागीर प्रक्रिया सुरू करात.',startProcess:'प्रक्रिया सुरू करात',waiting:'प्रक्रिया सुरू जावपाची वाट पळयता',readyDecision:'तुमच्या निर्णयाखातीर तयार',pause:'थांबयात',resume:'फुडें चालू दवरात',yourAction:'तुमची कृती',actionHelp:'पुनरावृत्तीचें काम डेमो तयार करतलो. महत्त्वाचो निर्णय तुमी घेवचो.',whatHappened:'आतां कितें जालें',formInstruction:'ह्या स्क्रीनार खरी डेटा एंट्री आसा. फकत टेक्स्ट फील्ड नैसर्गिक गतीन टाइप जातली; ड्रॉपडाउन आनी चेकबॉक्स खऱ्या वर्कफ्लो प्रमाणें निवडले जातले.',selectionInstruction:'ह्या स्क्रीनार टाइपिंग परस निवड आसा. ड्रॉपडाउन, पर्याय आनी टॉगल एक-एक करून निवडले जातले.',reviewInstruction:'हो रेकॉर्ड आदींच सबमिट जाला. हांगा कितेंच टाइप जावचें ना; तपासून मंजुरी/प्रकाशनाचो निर्णय तुमी घेवचो.',viewInstruction:'हो read-only रोल व्यू आसा. डेटा एंट्री ना; उपलब्ध माहिती हायलाइट जातली.'},
  mai:{readyBadge:'जखन अहाँ तैयार छी',readyTitle:'पहिने ई पृष्ठ नीक सँ देखू, तकर बाद प्रक्रिया शुरू करू।',startProcess:'प्रक्रिया शुरू करू',waiting:'प्रक्रिया शुरू होएबाक प्रतीक्षा',readyDecision:'अहाँक निर्णय लेल तैयार',pause:'रोकू',resume:'जारी राखू',yourAction:'अहाँक कार्रवाई',actionHelp:'दोहराव वाला काज डेमो तैयार करत। महत्वपूर्ण निर्णय अहाँ स्वयं लेब।',whatHappened:'एखन की भेल',formInstruction:'एहि स्क्रीन पर वास्तविक डेटा एंट्री अछि। केवल टेक्स्ट फील्ड स्वाभाविक गति सँ टाइप होएत; ड्रॉपडाउन आ चेकबॉक्स वास्तविक वर्कफ्लो अनुसार चुनल जाएत।',selectionInstruction:'एहि स्क्रीन पर टाइपिंगक बदला चयन अछि। ड्रॉपडाउन, विकल्प आ टॉगल एक-एक कए चुनल जाएत।',reviewInstruction:'ई रिकॉर्ड पहिने सँ जमा अछि। एतय किछु टाइप नहि होएत; समीक्षा कए मंजूरी/प्रकाशनक निर्णय अहाँ लिअ।',viewInstruction:'ई read-only रोल व्यू अछि। डेटा एंट्री नहि होएत; उपलब्ध जानकारी हाइलाइट होएत।'},
  mni:{readyBadge:'ꯅꯍꯥꯛ ꯁꯦꯝ ꯁꯥꯕꯥ ꯃꯇꯝꯗꯥ',readyTitle:'ꯍꯥꯟꯅꯥ ꯃꯁꯤꯒꯤ ꯂꯥꯃꯥꯏ ꯌꯦꯡꯉꯨ, ꯃꯇꯨꯡꯗꯥ ꯄ꯭ꯔꯣꯁꯦꯁ ꯍꯧꯗꯣꯛꯎ.',startProcess:'ꯄ꯭ꯔꯣꯁꯦꯁ ꯍꯧꯗꯣꯛꯎ',waiting:'ꯄ꯭ꯔꯣꯁꯦꯁ ꯍꯧꯗꯣꯛꯄꯥ ꯉꯥꯏꯔꯤ',readyDecision:'ꯅꯍꯥꯛꯀꯤ ꯋꯥꯔꯦꯞꯀꯤꯗꯃꯛ ꯁꯦꯝ ꯁꯥꯔꯦ',pause:'ꯂꯦꯞꯄꯤ',resume:'ꯃꯈꯥ ꯆꯠꯊꯕꯤ',yourAction:'ꯅꯍꯥꯛꯀꯤ ꯊꯕꯛ',actionHelp:'ꯍꯟꯅꯥ-ꯍꯟꯅꯥ ꯇꯧꯕꯥ ꯊꯕꯛ ꯗꯦꯃꯣꯅꯥ ꯁꯦꯝ ꯁꯥꯒꯅꯤ; ꯃꯔꯨꯑꯣꯏꯕꯥ ꯋꯥꯔꯦꯞ ꯅꯍꯥꯛꯅꯥ ꯂꯧꯒꯅꯤ.',whatHappened:'ꯍꯧꯖꯤꯛ ꯀꯔꯤ ꯊꯣꯛꯂꯦ',formInstruction:'ꯃꯁꯤꯗꯥ ꯑꯁꯦꯡꯕꯥ ꯗꯥꯇꯥ ꯑꯦꯟꯇ꯭ꯔꯤ ꯌꯥꯎꯏ। ꯇꯦꯛꯁꯠ ꯐꯤꯜꯗ ꯈꯛ ꯅꯦꯆꯨꯔꯦꯜ ꯁ꯭ꯄꯤꯗꯇꯥ ꯇꯥꯏꯞ ꯇꯧꯒꯅꯤ; dropdown/check box ꯑꯁꯦꯡꯕꯥ workflow ꯃꯇꯨꯡ ꯏꯟꯅꯥ ꯈꯟꯒꯅꯤ.',selectionInstruction:'ꯃꯁꯤꯗꯥ typing ꯅꯠꯇꯅꯥ selection ꯑꯃꯥꯡ ꯌꯥꯎꯏ; dropdown, option, toggle ꯑꯃꯃꯃ ꯈꯟꯒꯅꯤ.',reviewInstruction:'ꯔꯦꯀꯣꯔꯗ ꯑꯁꯤ ꯍꯥꯟꯅꯥ submit ꯇꯧꯔꯦ। ꯃꯁꯤꯗꯥ typing ꯂꯩꯇꯦ; review ꯇꯧꯗꯨꯅꯥ approval/publication ꯋꯥꯔꯦꯞ ꯂꯧꯕꯤ.',viewInstruction:'ꯃꯁꯤ read-only role view ꯅꯤ। ꯗꯥꯇꯥ ꯑꯦꯟꯇ꯭ꯔꯤ ꯂꯩꯇꯦ; ꯂꯩꯔꯤꯕꯥ ꯏꯅꯐꯣꯔꯃꯦꯁꯟ ꯍꯥꯏꯂꯥꯏꯠ ꯇꯧꯒꯅꯤ.'},
  ne:{readyBadge:'तपाईं तयार हुँदा',readyTitle:'पहिले यो पृष्ठ हेर्नुहोस्, त्यसपछि प्रक्रिया सुरु गर्नुहोस्।',startProcess:'प्रक्रिया सुरु गर्नुहोस्',waiting:'प्रक्रिया सुरु हुने प्रतीक्षा',readyDecision:'तपाईंको निर्णयका लागि तयार',pause:'रोक्नुहोस्',resume:'जारी राख्नुहोस्',yourAction:'तपाईंको कार्य',actionHelp:'दोहोरिने काम डेमोले तयार गर्छ। महत्वपूर्ण निर्णय तपाईं आफैं गर्नुहुन्छ।',whatHappened:'अहिले के भयो',formInstruction:'यस स्क्रिनमा वास्तविक डेटा इन्ट्री छ। टेक्स्ट फिल्ड मात्र प्राकृतिक गतिमा टाइप हुन्छन्; ड्रपडाउन र चेकबक्स वास्तविक वर्कफ्लोअनुसार चयन हुन्छन्।',selectionInstruction:'यस स्क्रिनमा टाइपिङभन्दा चयन हुन्छ। ड्रपडाउन, विकल्प र टगल एक-एक गरी चयन हुन्छन्।',reviewInstruction:'यो रेकर्ड पहिले नै सबमिट भइसकेको छ। यहाँ केही टाइप हुँदैन; समीक्षा गरेर स्वीकृति/प्रकाशनको निर्णय तपाईं लिनुहोस्।',viewInstruction:'यो read-only रोल भ्यू हो। डेटा इन्ट्री हुँदैन; उपलब्ध जानकारी हाइलाइट हुन्छ।'},
  sa:{readyBadge:'यदा भवान्/भवती सज्जः',readyTitle:'प्रथमम् एतत् पृष्ठं पश्यतु, ततः प्रक्रियां आरभताम्।',startProcess:'प्रक्रियां आरभताम्',waiting:'प्रक्रियारम्भस्य प्रतीक्षा',readyDecision:'निर्णयाय सज्जम्',pause:'विरामः',resume:'पुनरारम्भः',yourAction:'भवतः/भवत्याः क्रिया',actionHelp:'पुनरावृत्तिकार्यं प्रदर्शनं सज्जीकरोति; महत्त्वपूर्णं निर्णयं भवान्/भवती करोति।',whatHappened:'अधुना किं जातम्',formInstruction:'अस्मिन् पटलस्य वास्तविकं दत्तांश-प्रवेशनम् अस्ति। केवलं पाठ-क्षेत्राणि स्वाभाविकगत्या लिख्यन्ते; विकल्प-सूची तथा चिह्न-पेटिकाः वास्तविक-प्रवाहानुसारं चयन्यन्ते।',selectionInstruction:'अस्मिन् पटलस्य लेखनस्य स्थाने चयनानि सन्ति; विकल्पाः क्रमशः चयन्यन्ते।',reviewInstruction:'एषः अभिलेखः पूर्वमेव समर्पितः। अत्र लेखनं न भवति; समीक्षां कृत्वा अनुमोदन/प्रकाशननिर्णयं कुरुत।',viewInstruction:'एषः केवलं-दर्शन role view अस्ति; दत्तांश-प्रवेशनं न भवति, उपलब्धसूचना प्रकाश्यते।'},
  sat:{readyBadge:'ᱟᱢ ᱥᱟᱯᱲᱟᱣ ᱡᱚᱠᱷᱚᱱ',readyTitle:'ᱯᱟᱹᱦᱤᱞ ᱱᱚᱣᱟ ᱥᱟᱦᱴᱟ ᱧᱮᱞ ᱢᱮ, ᱛᱟᱭᱚᱢ ᱯᱨᱚᱥᱮᱥ ᱮᱛᱚᱦᱚᱵ ᱢᱮ.',startProcess:'ᱯᱨᱚᱥᱮᱥ ᱮᱛᱚᱦᱚᱵ ᱢᱮ',waiting:'ᱯᱨᱚᱥᱮᱥ ᱮᱛᱚᱦᱚᱵ ᱨᱮᱭᱟᱜ ᱛᱟᱺᱜᱤ',readyDecision:'ᱟᱢᱟᱜ ᱱᱤᱨᱱᱚᱭ ᱞᱟᱹᱜᱤᱫ ᱥᱟᱯᱲᱟᱣ',pause:'ᱛᱤᱸᱜᱩ',resume:'ᱞᱟᱦᱟ ᱥᱮᱫ',yourAction:'ᱟᱢᱟᱜ ᱠᱟᱹᱢᱤ',actionHelp:'ᱵᱟᱨ ᱵᱟᱨ ᱠᱟᱹᱢᱤ ᱫᱮᱢᱚ ᱥᱟᱯᱲᱟᱣᱟ; ᱢᱩᱬᱩᱛ ᱱᱤᱨᱱᱚᱭ ᱟᱢ ᱮᱢ ᱦᱟᱛᱟᱣᱟ.',whatHappened:'ᱱᱤᱛᱚᱜ ᱪᱮᱫ ᱦᱩᱭᱮᱱᱟ',formInstruction:'ᱱᱚᱣᱟ ᱥᱠᱨᱤᱱ ᱨᱮ ᱥᱟᱹᱨᱤ ᱰᱟᱴᱟ ᱮᱱᱴᱨᱤ ᱢᱮᱱᱟᱜᱼᱟ। text field ᱫᱚ ᱥᱟᱵᱷᱟᱵᱤᱠ ᱥᱯᱤᱰ ᱛᱮ ᱴᱟᱭᱤᱯ ᱟ; dropdown/check ᱫᱚ ᱥᱟᱹᱨᱤ workflow ᱞᱮᱠᱟ ᱵᱟᱪᱷᱟᱣ ᱟ.',selectionInstruction:'ᱱᱚᱣᱟ ᱥᱠᱨᱤᱱ ᱨᱮ typing ᱵᱟᱝ, selection ᱢᱮᱱᱟᱜᱼᱟ; dropdown/option/toggle ᱠᱨᱚᱢ ᱛᱮ ᱵᱟᱪᱷᱟᱣ ᱟ.',reviewInstruction:'ᱱᱚᱣᱟ record ᱫᱚ ᱢᱟᱲᱟᱝ submit ᱦᱩᱭ ᱟᱠᱟᱱᱟ। typing ᱵᱟᱝ; review ᱠᱟᱛᱮ approval/publication ᱱᱤᱨᱱᱚᱭ ᱦᱟᱛᱟᱣ ᱢᱮ.',viewInstruction:'ᱱᱚᱣᱟ read-only role view ᱠᱟᱱᱟ; data entry ᱵᱟᱝ, ᱢᱮᱱᱟᱜ ᱠᱚ ᱦᱟᱭᱞᱟᱭᱤᱴ ᱟ.'},
  sd:{readyBadge:'جڏهن توهان تيار آهيو',readyTitle:'پهريان هي صفحو ڏسو، پوءِ عمل شروع ڪريو.',startProcess:'عمل شروع ڪريو',waiting:'عمل شروع ٿيڻ جو انتظار',readyDecision:'توهان جي فيصلي لاءِ تيار',pause:'روڪيو',resume:'جاري رکو',yourAction:'توهان جي ڪارروائي',actionHelp:'بار بار ٿيندڙ ڪم ڊيمو تيار ڪندو؛ اهم فيصلو توهان پاڻ ڪندا.',whatHappened:'هاڻي ڇا ٿيو',formInstruction:'هن اسڪرين تي حقيقي ڊيٽا انٽري آهي. صرف ٽيڪسٽ فيلڊ قدرتي رفتار سان ٽائپ ٿيندا؛ ڊراپ ڊائون ۽ چيڪ باڪس اصل ورڪ فلو مطابق چونڊيا ويندا.',selectionInstruction:'هن اسڪرين تي ٽائپنگ بدران چونڊون آهن. ڊراپ ڊائون، آپشن ۽ ٽوگل هڪ هڪ ڪري چونڊيا ويندا.',reviewInstruction:'هي رڪارڊ اڳ ئي جمع ٿيل آهي. هتي ڪجھ به ٽائپ نه ٿيندو؛ جائزو وٺي منظوري يا اشاعت جو فيصلو توهان ڪريو.',viewInstruction:'هي read-only رول ويو آهي. ڊيٽا انٽري نه ٿيندي؛ موجود معلومات نمايان ٿيندي.'}
});

export function getProcessDemoCopy(languageCode:string):Copy{
  const code=String(languageCode||'en').toLowerCase().split('-')[0];
  return {...EN,...(copies[code]||{})};
}

export function instructionDirection(languageCode:string):'ltr'|'rtl'{
  const code=String(languageCode||'en').toLowerCase().split('-')[0];
  return ['ur','ks','sd'].includes(code)?'rtl':'ltr';
}

export function guidanceInstruction(copy:Copy,mode:DemoGuidanceMode){
  return mode==='form'?copy.formInstruction:mode==='selection'?copy.selectionInstruction:mode==='review'?copy.reviewInstruction:copy.viewInstruction;
}
export function guidanceProgress(copy:Copy,mode:DemoGuidanceMode){
  return mode==='form'?copy.formProgress:mode==='selection'?copy.selectionProgress:mode==='review'?copy.reviewProgress:copy.viewProgress;
}
export function guidancePanelTitle(copy:Copy,mode:DemoGuidanceMode){
  return mode==='form'?copy.formPanel:mode==='selection'?copy.selectionPanel:mode==='review'?copy.reviewPanel:copy.viewPanel;
}
export function guidanceAutomationText(copy:Copy,mode:DemoGuidanceMode){
  return mode==='form'?copy.automatedForm:mode==='selection'?copy.automatedSelection:mode==='review'?copy.automatedReview:copy.automatedView;
}
