import React, { useEffect, useMemo, useState } from 'react';
import { BookOpenCheck, CheckCircle2, Languages, Loader2, Mic, Navigation, Save, Search, ShieldCheck, Sparkles, WandSparkles } from 'lucide-react';
import type { Phase1Scope } from '../lib/phase1Offline';
import { getPhase1Cache, putPhase1Cache } from '../lib/phase1Offline';
import { getPhase2MlCapabilities, translateOnDevice, transcribeOnDevice, type Phase2MlCapabilities } from '../lib/phase2NativeMl';
import { searchRoleTools } from '../lib/phase2SmartSearch';
import { FALLBACK_LANGUAGE_CATALOGUE, languageDisplayName } from '../lib/languageCatalog';

interface Props { scope: Phase1Scope; role: string; }

type LectureNote = { id:string; createdAt:string; transcript:string; recap:string; keywords:string[]; languageTag:string };

// Keep every Constitution-scheduled Indian language visible. ML Kit Translate
// currently has on-device models for only a subset; unsupported entries remain
// visible but disabled in the Translator instead of pretending they work.
const mlKitIndianTranslationCodes = new Set(['en','bn','gu','hi','kn','mr','ta','te','ur']);
const languages = FALLBACK_LANGUAGE_CATALOGUE.map(option => ({
  code: String(option.code),
  label: languageDisplayName(option),
  localeCode: option.localeCode || `${String(option.code)}-IN`,
  translationSupported: mlKitIndianTranslationCodes.has(String(option.code))
}));
const localeMap: Record<string,string> = Object.fromEntries(languages.map(option => [option.code, String(option.localeCode || `${option.code}-IN`)]));
const stop = new Set('the a an and or but if then is are was were be been being to of in on for with from by at as this that these those it its into about your you our we they them he she i student teacher class school today lesson period work will has have had do did done'.split(' '));

function localRecap(text:string){
  const clean=String(text||'').replace(/\s+/g,' ').trim();
  if(!clean)return {recap:'',keywords:[] as string[]};
  const sentences=clean.split(/(?<=[.!?।])\s+/).filter(Boolean);
  const words=(clean.toLowerCase().match(/[\p{L}\p{N}]{3,}/gu)||[]).filter(w=>!stop.has(w));
  const counts=new Map<string,number>();words.forEach(w=>counts.set(w,(counts.get(w)||0)+1));
  const keywords=[...counts.entries()].sort((a,b)=>b[1]-a[1]).slice(0,8).map(([w])=>w);
  const recap=sentences.length<=3?sentences.join(' '):[sentences[0],sentences[Math.floor(sentences.length/2)],sentences[sentences.length-1]].join(' ');
  return {recap,keywords};
}

export default function Phase2FreeTools({scope,role}:Props){
  const[cap,setCap]=useState<Phase2MlCapabilities|null>(null);const[error,setError]=useState('');const[message,setMessage]=useState('');
  const[query,setQuery]=useState('');const[commandListening,setCommandListening]=useState(false);
  const[src,setSrc]=useState('en');const[dst,setDst]=useState('ur');const[input,setInput]=useState('');const[translated,setTranslated]=useState('');const[translating,setTranslating]=useState(false);
  const[lectureLang,setLectureLang]=useState('en');const[transcript,setTranscript]=useState('');const[recap,setRecap]=useState('');const[keywords,setKeywords]=useState<string[]>([]);const[listening,setListening]=useState(false);const[notes,setNotes]=useState<LectureNote[]>([]);
  const teacherLike=['teacher','class_teacher','headmaster'].includes(role);
  const results=useMemo(()=>query.trim()?searchRoleTools(role,query,8):[],[role,query]);

  useEffect(()=>{void getPhase2MlCapabilities().then(setCap).catch(()=>setCap(null));void getPhase1Cache<{notes:LectureNote[]}>(scope,'phase2_lecture_notes','history').then(v=>setNotes(v?.notes||[])).catch(()=>{})},[scope.schoolId,scope.userId]);
  const navigate=(moduleId:string,featureId?:string)=>window.dispatchEvent(new CustomEvent('edunixo_smart_navigate',{detail:{moduleId,featureId}}));
  const listenCommand=async()=>{setCommandListening(true);setError('');setMessage('');try{const r=await transcribeOnDevice('en-IN',true);setQuery(String(r.text||'').trim());if(r.text)setMessage('Voice command captured on device. Review the role-safe result and tap to open.')}catch(e:any){setError(e?.message||'Voice command capture failed.')}finally{setCommandListening(false)}};
  const translate=async()=>{setTranslating(true);setError('');setMessage('');try{const r=await translateOnDevice(input,src,dst);setTranslated(r.text);setMessage('Translation completed on this device. Downloaded language models can work offline after first setup.')}catch(e:any){setError(e?.message||'Translation failed.')}finally{setTranslating(false)}};
  const listen=async()=>{setListening(true);setError('');setMessage('');try{const r=await transcribeOnDevice(localeMap[lectureLang]||'en-IN',true);const next=[transcript,r.text].filter(Boolean).join(transcript?' ':'');setTranscript(next);const quick=localRecap(next);setRecap(quick.recap);setKeywords(quick.keywords)}catch(e:any){setError(e?.message||'Voice transcription failed.')}finally{setListening(false)}};
  const makeRecap=()=>{const quick=localRecap(transcript);setRecap(quick.recap);setKeywords(quick.keywords)};
  const saveNote=async()=>{if(!transcript.trim())return;const note:LectureNote={id:crypto.randomUUID(),createdAt:new Date().toISOString(),transcript:transcript.trim(),recap,keywords,languageTag:localeMap[lectureLang]||'en-IN'};const next=[note,...notes].slice(0,20);await putPhase1Cache(scope,'phase2_lecture_notes','history',{notes:next});setNotes(next);setMessage('Lecture note saved in EDUNIXO encrypted local storage on this device.')};

  return <>
    <section className="rounded-2xl border border-cyan-200 bg-gradient-to-br from-cyan-50 to-white p-4 md:col-span-2"><div className="flex items-center gap-2"><Navigation className="h-5 w-5 text-cyan-700"/><div><b>Smart Command Search</b><p className="text-xs text-slate-500">Role-safe module finder · no AI/API call</p></div></div><div className="mt-3 flex gap-2"><div className="relative flex-1"><Search className="absolute left-3 top-3 h-4 w-4 text-slate-400"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Try: attendance correction, result book, leave, admission…" className="w-full rounded-xl border border-slate-200 bg-white py-2.5 pl-10 pr-3 text-sm outline-none focus:border-cyan-400"/></div><button disabled={commandListening||!cap?.speechRecognition} onClick={()=>void listenCommand()} className="inline-flex items-center gap-1 rounded-xl border border-cyan-200 bg-white px-3 text-[10px] font-black text-cyan-800 disabled:opacity-40">{commandListening?<Loader2 className="h-4 w-4 animate-spin"/>:<Mic className="h-4 w-4"/>}Speak</button></div>{results.length>0&&<div className="mt-3 grid gap-2 sm:grid-cols-2">{results.map((r,i)=><button key={`${r.moduleId}:${r.featureId||''}:${i}`} onClick={()=>navigate(r.moduleId,r.featureId)} className="rounded-xl border border-slate-200 bg-white p-3 text-left transition hover:border-cyan-300 hover:shadow-sm"><div className="text-xs font-black text-slate-950">{r.label}</div>{r.parentLabel&&<div className="mt-1 text-[9px] font-bold uppercase text-cyan-700">{r.parentLabel}</div>}<div className="mt-1 line-clamp-2 text-[10px] leading-4 text-slate-500">{r.description}</div></button>)}</div>}<div className="mt-3 text-[10px] text-slate-500"><ShieldCheck className="mr-1 inline h-3.5 w-3.5"/>Search indexes only the modules visible to this role; the normal permission/plan gate still decides navigation.</div></section>

    <section className="rounded-2xl border bg-white p-4 md:col-span-2"><div className="flex items-center gap-2"><Languages className="h-5 w-5 text-violet-700"/><div><b>On-device Translator</b><p className="text-xs text-slate-500">ML Kit Translation · no paid translation API</p></div></div><div className="mt-3 grid gap-2 sm:grid-cols-2"><select value={src} onChange={e=>setSrc(e.target.value)} className="rounded-xl border p-2.5 text-xs font-bold">{languages.map(option=><option key={option.code} value={option.code} disabled={!option.translationSupported}>{option.label}{option.translationSupported?'':' · UI only'}</option>)}</select><select value={dst} onChange={e=>setDst(e.target.value)} className="rounded-xl border p-2.5 text-xs font-bold">{languages.map(option=><option key={option.code} value={option.code} disabled={!option.translationSupported}>{option.label}{option.translationSupported?'':' · UI only'}</option>)}</select></div><textarea value={input} onChange={e=>setInput(e.target.value)} rows={4} placeholder="Type or paste school text…" className="mt-2 w-full rounded-xl border p-3 text-sm"/><button disabled={translating||!cap?.translation||!input.trim()} onClick={()=>void translate()} className="mt-2 inline-flex items-center gap-2 rounded-xl bg-violet-600 px-4 py-2 text-xs font-black text-white disabled:opacity-40">{translating?<Loader2 className="h-4 w-4 animate-spin"/>:<WandSparkles className="h-4 w-4"/>}Translate on device</button>{translated&&<div className="mt-3 rounded-xl border border-violet-100 bg-violet-50 p-3 text-sm whitespace-pre-wrap text-slate-800">{translated}<div className="mt-3 text-[9px] font-bold uppercase tracking-wider text-slate-500">Powered by Google Translate · on-device ML Kit</div></div>}<p className="mt-2 text-[10px] text-slate-500">All 22 Scheduled Indian Languages are listed. Languages marked <b>UI only</b> do not currently have a Google ML Kit on-device translation model, so they stay visible but cannot be selected for translation.</p>{!cap?.native&&<p className="mt-2 text-[10px] text-amber-700">This free translator appears in the Android app. Web preview keeps the normal multilingual UI but does not send text to a paid translation service.</p>}</section>

    {teacherLike&&<section className="rounded-2xl border bg-white p-4 md:col-span-2"><div className="flex items-center gap-2"><Mic className="h-5 w-5 text-emerald-700"/><div><b>Lecture Voice Notes</b><p className="text-xs text-slate-500">Device speech recognition · offline-preferred · encrypted local notes</p></div></div><div className="mt-3 flex flex-wrap gap-2"><select value={lectureLang} onChange={e=>setLectureLang(e.target.value)} className="rounded-xl border p-2 text-xs font-bold">{languages.map(option=><option key={option.code} value={option.code}>{option.label}</option>)}</select><button disabled={listening||!cap?.speechRecognition} onClick={()=>void listen()} className="inline-flex items-center gap-2 rounded-xl bg-emerald-700 px-4 py-2 text-xs font-black text-white disabled:opacity-40">{listening?<Loader2 className="h-4 w-4 animate-spin"/>:<Mic className="h-4 w-4"/>}Capture voice</button><button disabled={!transcript.trim()} onClick={makeRecap} className="inline-flex items-center gap-2 rounded-xl border px-4 py-2 text-xs font-black disabled:opacity-40"><Sparkles className="h-4 w-4"/>Build local recap</button><button disabled={!transcript.trim()} onClick={()=>void saveNote()} className="inline-flex items-center gap-2 rounded-xl border px-4 py-2 text-xs font-black disabled:opacity-40"><Save className="h-4 w-4"/>Save encrypted</button><button onClick={()=>navigate('tr-ai-teaching-diary')} className="inline-flex items-center gap-2 rounded-xl border px-4 py-2 text-xs font-black"><BookOpenCheck className="h-4 w-4"/>Open Teaching Diary</button></div><textarea value={transcript} onChange={e=>{setTranscript(e.target.value);const q=localRecap(e.target.value);setRecap(q.recap);setKeywords(q.keywords)}} rows={5} placeholder="Voice transcript / lecture notes…" className="mt-3 w-full rounded-xl border p-3 text-sm"/>{recap&&<div className="mt-3 rounded-xl bg-emerald-50 p-3"><div className="text-[9px] font-black uppercase tracking-wider text-emerald-700">Local quick recap — deterministic, not generative AI</div><p className="mt-2 text-xs leading-5 text-slate-700">{recap}</p>{keywords.length>0&&<div className="mt-2 flex flex-wrap gap-1">{keywords.map(k=><span key={k} className="rounded-full bg-white px-2 py-1 text-[9px] font-bold text-emerald-800">{k}</span>)}</div>}</div>}<div className="mt-3 text-[10px] text-slate-500">Android requests offline recognition first. Availability still depends on the device's installed speech engine/language pack. {notes.length} local note(s) saved.</div></section>}

    {message&&<div className="md:col-span-2 rounded-xl border border-emerald-200 bg-emerald-50 p-3 text-xs font-bold text-emerald-800"><CheckCircle2 className="mr-1 inline h-4 w-4"/>{message}</div>}{error&&<div className="md:col-span-2 rounded-xl border border-rose-200 bg-rose-50 p-3 text-xs font-bold text-rose-800">{error}</div>}
  </>;
}
